from pathlib import Path
import yaml
Q=[
('angle-chasing-ledger','foundational','Two lines intersect. One angle is 47 degrees. Find its vertical angle.','47 degrees','Vertical angles are equal.','133 degrees.'),
('linear-pairs','foundational','A linear pair has one angle 68 degrees. Find the other.','112 degrees','Linear pair sums to 180.','68 degrees.'),
('angles-around-point','foundational','Angles around point are 90,120,80,x. Find x.','70 degrees','They sum to 360.','110 degrees.'),
('triangle-angles','foundational','Triangle angles are 52,63,x. Find x.','65 degrees','Use triangle sum.','115 degrees.'),
('parallel-line-transfer','foundational','Parallel lines cut by transversal have corresponding angle 75. Find its mate.','75 degrees','Corresponding angles are equal.','105 degrees.'),
('parallel-line-transfer','foundational','Same-side interior angles: one is 118. Find other.','62 degrees','They are supplementary.','118 degrees.'),
('isosceles-triangle-angles','foundational','Isosceles triangle base angles 38 each. Find vertex angle.','104 degrees','Subtract 76 from 180.','142 degrees.'),
('cyclic-angle-relations','foundational','An inscribed angle intercepts arc 100 degrees. Find angle.','50 degrees','Inscribed angle is half arc.','100 degrees.'),
('cyclic-angle-relations','foundational','A central angle is 130 degrees. Find intercepted arc.','130 degrees','Central angle equals arc.','65 degrees.'),
('tangent-chord','foundational','A tangent-chord angle intercepts arc 80 degrees. Find angle.','40 degrees','It is half intercepted arc.','80 degrees.'),
('cyclic-quadrilateral','foundational','One angle of cyclic quadrilateral is 112. Find opposite angle.','68 degrees','Opposite angles supplement.','112 degrees.'),
('angle-chasing-ledger','foundational','What should accompany every derived angle in a chase?','A stated reason/theorem.','Maintain a reason ledger.','A measurement from drawing.'),
('parallel-line-transfer','intermediate','Parallel lines: alternate interior angle is 3x+5 and its mate 80. Find x.','25','Set equal and solve.','85.'),
('triangle-angles','intermediate','Exterior angle is 140, one remote interior is 65. Find other remote.','75 degrees','Exterior equals remote sum.','40 degrees.'),
('isosceles-triangle-angles','intermediate','AB=AC and exterior angle at B is 130. Find angle A.','80 degrees','Interior B is 50, so C=50.','130 degrees.'),
('parallel-line-transfer','intermediate','A transversal makes 35 degrees with one parallel line. Find acute angle it makes with other.','35 degrees','Corresponding acute angles equal.','145 degrees.'),
('cyclic-angle-relations','intermediate','Two chords intersect inside circle; intercepted arcs are 70 and 110. Find angle.','90 degrees','Inside chord angle is half sum.','20 degrees.'),
('cyclic-angle-relations','intermediate','Two secants meet outside circle; far arc 150, near arc 70. Find angle.','40 degrees','Outside angle is half difference.','110 degrees.'),
('cyclic-quadrilateral','intermediate','Cyclic quadrilateral angles are 2x and 4x opposite. Find x.','30 degrees','They sum 180.','45.'),
('regular-polygon-angles','intermediate','A regular hexagon has interior 120. An adjacent exterior turn is what?','60 degrees','Interior plus exterior is 180.','120 degrees.'),
('auxiliary-line-selection','intermediate','To use isosceles facts in a circle with center O and chord AB, what should you draw?','Radii OA and OB.','They create isosceles triangle OAB.','A random tangent.'),
('angle-chasing-ledger','intermediate','A chase gives x+20=3x-40. Find x.','30','Solve the equality of justified angles.','10.'),
('diagram-assumption-check','intermediate','Why can you not assume two unmarked lines are parallel?','Parallelism requires a marking or proof.','They look equally spaced.'),
('cyclic-angle-relations','intermediate','An angle subtending a diameter is what?','90 degrees','It intercepts a semicircle.','180 degrees.'),
('angle-chasing-ledger','advanced','Prove exterior angle theorem.','Compare triangle sum with adjacent linear-pair sum.','Use a diagram measurement.'),
('parallel-line-transfer','advanced','Prove equal alternate interior angles imply lines parallel.','Use the converse parallel-line theorem.','Assume parallelism as a given.'),
('cyclic-quadrilateral','advanced','Prove opposite angles of cyclic quadrilateral are supplementary.','Each is half a pair of arcs totaling 360.','Assume all quadrilaterals have this property.'),
('tangent-chord','advanced','Prove radius to tangent point is perpendicular.','A nonperpendicular line through contact would pass inside circle and meet it twice.','Use a visual right-angle guess.'),
('auxiliary-line-selection','advanced','Why draw a radius to a point of tangency?','It unlocks perpendicular tangent-radius theorem and isosceles triangles.','It always bisects the chord.'),
('angle-chasing-ledger','advanced','A proof has an angle equality with no cited reason. Is it complete?','No','Every inference needs a theorem or given.','Yes if diagram appears clear.'),
('diagram-assumption-check','advanced','Give counterexample to “equal-looking angles are equal.”','A distorted non-scale drawing with unequal measures.','Drawings do not determine metric facts.','A symmetric diagram.'),
('mixed-angle-chase','advanced','A triangle has angles 40,60,80. Extend side at 80-degree vertex. Find exterior angle.','100 degrees','Exterior equals remote 40+60.','80 degrees.'),
('mixed-angle-chase','advanced','An isosceles triangle has vertex angle 20. A line from vertex bisects it. Find each new vertex angle.','10 degrees','Angle bisector halves the angle.','80 degrees.'),
('circle-angle-theorem','advanced','An inscribed angle is 35. Find its intercepted arc.','70 degrees','Arc is twice inscribed angle.','35 degrees.'),
('circle-angle-theorem','advanced','Two tangent segments from one exterior point meet circle. What length relation holds?','They are equal.','Use tangent-segment theorem.','They are perpendicular.'),
('proof-obligation','advanced','Why is “the arc looks like a semicircle” insufficient?','A diameter or 180-degree arc must be given/proved.','Arcs are always halves.'),
('construction','advanced','What auxiliary line often helps prove a circle angle relation?','A radius to an endpoint or a chord/diameter creating isosceles triangles.','Any line through the picture.'),
('mixed-angle-chase','advanced','Parallel lines are cut by transversal; one interior angle is 72. Find all four acute angles.','72 degrees each','Vertical and corresponding angles propagate.','108 degrees each.'),
('mixed-angle-chase','advanced','Same setup: find all four obtuse angles.','108 degrees each','They supplement the acute 72.','72 degrees each.'),
('geometry-proof-strategy','advanced','What should be checked before applying an inscribed-angle theorem?','Vertex is on circle and angle sides are chords/secants intercepting the stated arc.','Only that a circle is drawn.'),
('vertical-angles','foundational','Two intersecting lines make angle 122. Find vertical angle.','122 degrees','Vertical angles equal.','58 degrees.'),
('linear-pairs','foundational','One angle on a straight line is 39. Find its supplement.','141 degrees','Subtract from 180.','39 degrees.'),
('angles-around-point','foundational','Three angles around point are 140,95,65. Find fourth.','60 degrees','Total is 360.','100 degrees.'),
('parallel-line-transfer','foundational','Corresponding angle is 118. Find corresponding mate.','118 degrees','Corresponding angles equal.','62 degrees.'),
('parallel-line-transfer','foundational','Alternate interior angle is 104. Find its mate.','104 degrees','Alternate interior angles equal.','76 degrees.'),
('triangle-angles','foundational','Triangle has angles 90 and 35. Find third.','55 degrees','Use sum 180.','145 degrees.'),
('isosceles-triangle-angles','foundational','An isosceles triangle vertex angle 70. Find base angle.','55 degrees','Remaining 110 split equally.','35 degrees.'),
('cyclic-quadrilateral','foundational','Cyclic quadrilateral opposite angle 97. Find other.','83 degrees','Opposite angles sum 180.','97 degrees.'),
('circle-angle-theorem','foundational','Inscribed angle is 42. Find arc.','84 degrees','Arc is double angle.','21 degrees.'),
('tangent-chord','foundational','Tangent is perpendicular to which circle segment at contact?','Radius','Use tangent-radius theorem.','Chord.'),
('angle-chasing-ledger','foundational','A justified angle is 180 minus 77. What is it?','103 degrees','Evaluate supplement.','77 degrees.'),
('parallel-line-transfer','intermediate','Corresponding angles are 5x-10 and 110. Find x.','24','Set equal.','20.'),
('triangle-angles','intermediate','Isosceles triangle has base angles x+10 and 2x-20. Find x.','30','Equal base angles.','10.'),
('exterior-angle','intermediate','Exterior angle 150; one remote 72. Find other.','78 degrees','Subtract 72.','30 degrees.'),
('cyclic-angle-relations','intermediate','Inside chord angle is 75; one arc is 90. Find other intercepted arc.','60 degrees','150=90+arc.','240 degrees.'),
('cyclic-angle-relations','intermediate','Exterior secant angle 20; far arc 130. Find near arc.','90 degrees','40=130-near.','170 degrees.'),
('tangent-chord','intermediate','A tangent-chord angle is 55. Find its intercepted arc.','110 degrees','Arc is twice tangent-chord angle.','55 degrees.'),
('cyclic-quadrilateral','intermediate','Cyclic quadrilateral has angles x+20 and 2x+10 opposite. Find x.','50','Their sum is 180.','75.'),
('regular-polygon-angles','intermediate','Exterior turn of regular octagon is 45. Find interior.','135 degrees','Supplement it.','45 degrees.'),
('auxiliary-line-selection','intermediate','A chord subtends an angle at circle center. What triangle is formed by radii to endpoints?','Isosceles triangle','Both sides are radii.','Equilateral always.'),
('angle-chasing-ledger','intermediate','A chase obtains 2x+15=75. Find x.','30','Subtract then divide.','45.'),
('diagram-assumption-check','intermediate','Can an unmarked angle be assumed 90 because a segment appears horizontal?','No','Perpendicularity needs proof/mark.','Yes.'),
('circle-angle-theorem','intermediate','An inscribed angle intercepts a semicircle. Find angle.','90 degrees','Half of 180.','180 degrees.'),
('parallel-line-converse','advanced','Prove equal corresponding angles imply two lines are parallel.','Apply corresponding-angle converse with common transversal.','Assume the desired parallelism.'),
('isosceles-proof','advanced','Prove equal base angles imply equal opposite sides.','Use the converse isosceles theorem or contradiction by side-angle order.','Use only forward theorem.'),
('circle-angle-theorem','advanced','Prove an angle in a semicircle is right.','It intercepts 180-degree arc, and inscribed angle is half arc.','Assume every chord is diameter.'),
('cyclic-quadrilateral','advanced','Prove a quadrilateral with supplementary opposite angles is cyclic.','Use the converse inscribed-angle relation to show one vertex lies on circle through other three.','Use forward cyclic theorem only.'),
('auxiliary-line-selection','advanced','A circle problem has a chord and center but no useful angles. What first construction is natural?','Connect center to chord endpoints.','It produces equal radii and isosceles triangle.','Draw a random parallel.'),
('angle-chasing-ledger','advanced','Why is substituting labels into a triangle sum safer than chasing by appearance?','The equation records a complete invariant and exposes arithmetic errors.','It makes the diagram to scale.'),
('mixed-angle-chase','advanced','Parallel lines transfer an acute angle 28 to a triangle. The triangle has another angle 67. Find third angle.','85 degrees','Subtract 28+67 from 180.','Using the obtuse supplement instead.'),
('corrected-chase','advanced','A triangle uses angles 28 and 67 transferred by parallel lines. Find third.','85 degrees','Subtract their sum from 180.','113 degrees.'),
('mixed-angle-chase','advanced','An isosceles triangle has base angles 40. A tangent at its circumcircle vertex forms what angle with each equal chord if it intercepts arc?','Use tangent-chord theorem; angle equals opposite inscribed angle, requiring the stated arc.','Assume it is 40 without establishing cyclic configuration.'),
('proof-obligation','advanced','Why must an outside-secant angle use arc difference, not sum?','Its rays intercept nested arcs and the external turning compares far minus near.','All circle angles average arcs the same way.'),
('diagram-assumption-check','advanced','Why does a point drawn on a circle require incidence marking?','A diagram alone cannot certify exact membership.','Circles contain every nearby point.'),
('construction','advanced','How can an auxiliary parallel line transfer an angle to a remote vertex?','Draw through target vertex a line parallel to the reference side and use corresponding angles.','Extend the angle arbitrarily.'),
('mixed-angle-chase','advanced','In cyclic quadrilateral, angle A=65 and angle B=80. Find C and D relation.','C=115; D is determined only with extra information.','Only opposite A+C are supplementary.','Assuming D=100.'),
('geometry-proof-strategy','advanced','What distinguishes a proof chase from a calculation chase?','A proof establishes a general relation from givens; a calculation finds a specified measure with reasons.','A proof uses no equations.'),
('circle-angle-theorem','advanced','An arc AB is 140. Any inscribed angles intercepting the same arc have what measure?','70 degrees','All are half the same arc.','They may differ by location.'),
('parallel-line-transfer','advanced','Why are same-side interior angles supplementary for parallel lines?','They combine with a corresponding/linear-pair relation under the parallel condition.','They are vertical angles.'),
('proof-obligation','advanced','A solution says “obvious by symmetry.” What must be supplied?','The actual symmetry transformation or congruence argument.','A cleaner picture.'),
('vertical-angles','foundational','Vertical angle to 135 degrees?','135 degrees','Vertical angles equal.','45 degrees.'),
('linear-pairs','foundational','Supplement of 101 degrees?','79 degrees','Subtract from 180.','101 degrees.'),
('angles-around-point','foundational','Angles 110,110,90,x around point. Find x.','50 degrees','Use total 360.','40 degrees.'),
('triangle-angles','foundational','Triangle angles 44,44,x. Find x.','92 degrees','Subtract 88 from 180.','136 degrees.'),
('parallel-line-transfer','foundational','Alternate interior mate of 63 degrees?','63 degrees','Parallel-line theorem.','117 degrees.'),
('parallel-line-transfer','foundational','Same-side interior mate of 63 degrees?','117 degrees','Supplementary pair.','63 degrees.'),
('isosceles-triangle-angles','foundational','Isosceles triangle base angle 72. Find vertex.','36 degrees','Two base angles total 144.','108 degrees.'),
('circle-angle-theorem','foundational','Central angle 72 intercepts what arc?','72 degrees','Central equals arc.','36 degrees.'),
('circle-angle-theorem','foundational','Inscribed angle intercepts 160-degree arc. Find angle.','80 degrees','Half arc.','160 degrees.'),
('cyclic-quadrilateral','foundational','Opposite angle to 75 in cyclic quadrilateral?','105 degrees','Supplement to 180.','75 degrees.'),
('tangent-chord','foundational','Tangent-chord angle intercepts 140-degree arc. Find angle.','70 degrees','Half arc.','140 degrees.'),
('angle-chasing-ledger','foundational','Name a valid reason for equal vertical angles.','Vertical-angle theorem','Cite the theorem.','They look opposite.'),
('parallel-line-transfer','intermediate','Alternate interior angles are 4x+8 and 100. Find x.','23','Set equal.','27.'),
('triangle-angles','intermediate','Triangle angles x,2x,3x. Find x.','30 degrees','Six x is 180.','60.'),
('exterior-angle','intermediate','Exterior angle 117 and remote interior 49. Find other remote.','68 degrees','Subtract.','166 degrees.'),
('isosceles-triangle-angles','intermediate','AB=AC; angle A=46. Find angle B.','67 degrees','Remaining 134 split equally.','44 degrees.'),
('cyclic-angle-relations','intermediate','Inside-chord angle is 65; one arc is 80. Find other arc.','50 degrees','Double angle equals arc sum.','210 degrees.'),
('cyclic-angle-relations','intermediate','Outside-secant angle 25, far arc 150. Find near arc.','100 degrees','Double angle is far minus near.','200 degrees.'),
('cyclic-quadrilateral','intermediate','Opposite cyclic angles are 3x and x+20. Find x.','40','Four x plus 20 is 180.','45.'),
('tangent-chord','intermediate','A radius meets tangent at T. What is angle between them?','90 degrees','Radius-tangent theorem.','180 degrees.'),
('parallel-line-transfer','intermediate','A transversal creates angle 115 with first parallel. Find acute angle at either intersection.','65 degrees','Supplement of 115.','115 degrees.'),
('auxiliary-line-selection','intermediate','To show two base angles equal in a circle-center chord setup, which fact helps?','Radii to chord endpoints are equal.','This makes an isosceles triangle.','Chord is a diameter.'),
('diagram-assumption-check','intermediate','A diagram lacks a parallel mark. What can be used to prove parallelism?','Equal alternate interior or corresponding angles.','Use a valid converse.','The apparent slope.'),
('circle-angle-theorem','intermediate','Two inscribed angles intercept same arc. Compare them.','They are equal.','Both are half same arc.','They supplement.'),
('mixed-angle-chase','intermediate','A triangle has angles 30 and 70. An exterior angle at third vertex is what?','100 degrees','It equals two remote angles.','80 degrees.'),
('mixed-angle-chase','intermediate','A square has diagonal. Find angle between diagonal and a side.','45 degrees','It forms isosceles right triangle.','90 degrees.'),
('angle-chasing-ledger','intermediate','If an angle is labeled x and its supplement 2x, find x.','60 degrees','3x=180.','90 degrees.'),
('parallel-line-converse','advanced','A transversal makes equal alternate interior angles. What conclusion is licensed?','The lines are parallel.','Use the converse theorem.','The transversal is perpendicular.'),
('cyclic-quadrilateral','advanced','A quadrilateral has opposite angles 88 and 92. What circle conclusion can be drawn?','It is cyclic, provided it is a simple quadrilateral.','Use supplementary-opposite-angle converse.','It is a rectangle.'),
('tangent-chord','advanced','Why does a tangent touch a circle once?','A line at distance exactly radius from center has one intersection; smaller distance gives two.','Tangency is visual.'),
('auxiliary-line-selection','advanced','What construction often proves two chord-related angles equal?','Connect endpoints to center and use equal radii/isosceles angles.','Draw an unrelated diameter.'),
('proof-obligation','advanced','Why must an angle chase state whether an arc is minor or major?','Different arcs with same endpoints can have different measures.','All arcs between endpoints are equal.'),
('mixed-angle-chase','advanced','An inscribed angle ACB is 48 and BOC is central angle 96. What extra information is needed to relate them?','Which arc each intercepts; their endpoints must match.','Nothing; all circle angles are equal.'),
('diagram-assumption-check','advanced','Why may an unlabeled point on a segment not be assumed midpoint?','Midpoint needs equal subsegment marks or proof.','It looks centered.'),
('geometry-proof-strategy','advanced','When should an angle label be replaced by an expression rather than a number?','When it participates in an equation with other unknown related angles.','Always; numbers are unhelpful.'),
('proof-obligation','advanced','What is wrong with using a theorem’s converse without checking hypotheses?','The conclusion may be false; converses require their own stated conditions.','Converse is automatically included.'),
('mixed-angle-chase','advanced','A regular pentagon has exterior turn 72. Two consecutive turns total what?','144 degrees','Add two equal exterior angles.','216 degrees.'),
('circle-angle-theorem','advanced','An angle between tangent and chord equals an inscribed angle in what segment?','The opposite segment intercepting the same chord arc.','Use alternate-segment theorem.','Any inscribed angle.'),
('vertical-angles','foundational','Vertical mate of 58 degrees?','58 degrees','Vertical angles equal.','122 degrees.'),
('linear-pairs','foundational','Supplement of 146 degrees?','34 degrees','Subtract from 180.','146 degrees.'),
('angles-around-point','foundational','Angles 75,85,100,x around point: x?','100 degrees','Their sum is 360.','90 degrees.'),
('triangle-angles','foundational','Triangle angles 70,55,x: x?','55 degrees','Subtract 125 from 180.','70 degrees.'),
('parallel-line-transfer','foundational','Corresponding mate of 42 degrees?','42 degrees','Corresponding angles equal.','138 degrees.'),
('parallel-line-transfer','foundational','Same-side interior mate of 142 degrees?','38 degrees','Supplementary.','142 degrees.'),
('isosceles-triangle-angles','foundational','Vertex angle 100 in isosceles triangle. Base angle?','40 degrees','Split remaining 80.','80 degrees.'),
('circle-angle-theorem','foundational','Arc 90 gives inscribed angle?','45 degrees','Half arc.','90 degrees.'),
('cyclic-quadrilateral','foundational','Cyclic opposite to 130 degrees?','50 degrees','Supplement.','130 degrees.'),
('tangent-chord','foundational','Arc 60 gives tangent-chord angle?','30 degrees','Half arc.','60 degrees.'),
('angle-chasing-ledger','foundational','What theorem justifies angles on a straight line summing 180?','Linear-pair theorem','Name the relation.','Vertical-angle theorem.'),
('parallel-line-transfer','intermediate','Corresponding angles 7x+1 and 99: find x.','14','Set equal.','15.'),
('triangle-angles','intermediate','Triangle angles x+5,x+15,2x. Find x.','40','Four x plus 20 is 180.','45.'),
('exterior-angle','intermediate','Exterior 132 and remote 57: other remote?','75 degrees','Subtract.','189 degrees.'),
('isosceles-triangle-angles','intermediate','Base angles x+8 and 3x-12. Find x.','10','Set equal.','5.'),
('cyclic-angle-relations','intermediate','Inside-chord angle 55 and one arc 70: other arc?','40 degrees','110=70+arc.','180 degrees.'),
('cyclic-angle-relations','intermediate','Outside angle 30, far arc 170: near arc?','110 degrees','60=170-near.','230 degrees.'),
('cyclic-quadrilateral','intermediate','Opposite angles 4x and 2x+30: x?','25','Six x plus 30 is 180.','30.'),
('regular-polygon-angles','intermediate','Regular decagon exterior angle?','36 degrees','360/10.','144 degrees.'),
('auxiliary-line-selection','intermediate','To find base angles of triangle made by two radii, which theorem applies?','Isosceles triangle theorem','The radii are equal.','Pythagorean theorem.'),
('diagram-assumption-check','intermediate','A vertex looks centered on a chord. What evidence is needed to call it midpoint?','Equal segment markings or proof.','Screen measurement.','A circle label.'),
('mixed-angle-chase','intermediate','A right triangle has acute angle 37. Find other acute angle.','53 degrees','Acute angles sum 90.','143 degrees.'),
('angle-chasing-ledger','intermediate','If vertical angle x+12 equals 74, find x.','62','Set equal and subtract.','86.'),
('circle-angle-theorem','intermediate','Two inscribed angles intercept arcs 120 and 80. Find their angle difference.','20 degrees','They are 60 and 40.','40 degrees.'),
('parallel-line-converse','advanced','Why do supplementary same-side interior angles prove lines parallel?','This is the same-side-interior converse for a common transversal.','Supplements are always parallel.'),
('cyclic-quadrilateral','advanced','Prove equal angles subtending same chord are equal.','Each equals half the same intercepted arc.','Use chord length alone.'),
('tangent-chord','advanced','Prove tangent segments from one external point are equal.','Join point to center and use congruent right triangles with common hypotenuse.','Assume tangents are symmetric.'),
('auxiliary-line-selection','advanced','Why can a diameter be a useful auxiliary line in an angle chase?','It creates a semicircle and right inscribed angles.','It bisects every angle.'),
('proof-obligation','advanced','Give a counterexample to “supplementary angles are always adjacent.”','Opposite angles of a cyclic quadrilateral are supplementary but nonadjacent.','A linear pair.'),
('geometry-proof-strategy','advanced','What final check catches an impossible chase result?','Verify local sums: triangle 180, straight line 180, point 360, and angle ranges.','Redraw it more neatly.'),
('parallel-line-transfer','intermediate','A corresponding angle is 127 degrees. Find the supplementary angle at the other intersection.','53 degrees','Supplement 127 after transferring it.','127 degrees.'),
('circle-angle-theorem','intermediate','An arc is 150 degrees. Find an inscribed angle intercepting it.','75 degrees','Take one half.','150 degrees.')]
items=[]
for i,item in enumerate(Q,1):
    c,d,p,a,o,*trap=item
    items.append({'id':f'aops-v1-ch14-q{i:03d}','concept':c,'difficulty':d,'source':'original-authoring','prompt':p,'answer':a,'solutionOutline':o,'commonTrap':trap[0] if trap else ''})
doc={'metadata':{'id':'aops-v1-ch14-angle-chasing-bank','chapter':14,'topicIds':['aops-angle-chasing'],'status':'in-progress','minimumRequiredItems':150,'sourcePageRange':'pdf 147-149; printed 133-135'},'items':items}
Path('docs/assessment-reference/aops-volume-1/chapter-14-angle-chasing-question-bank.yaml').write_text(yaml.safe_dump(doc,sort_keys=False,allow_unicode=True),encoding='utf8')
