from pathlib import Path
import yaml
Q=[
('polygon-classification','foundational','How many sides does a hexagon have?','6','Use the name prefix.','5.'),
('polygon-classification','foundational','What is a convex polygon?','One whose interior angles are all less than 180 degrees.','Use the convexity definition.','Any polygon with equal sides.'),
('interior-angle-sum','foundational','Find interior-angle sum of a pentagon.','540 degrees','Use (n-2) times 180 with n=5.','360 degrees.'),
('interior-angle-sum','foundational','Find interior-angle sum of an octagon.','1080 degrees','Use six triangles.','1440 degrees.'),
('exterior-angle-sum','foundational','What is sum of one exterior angle at each vertex of a convex polygon?','360 degrees','One circuit makes a full turn.','180 degrees.'),
('regular-polygon-angles','foundational','Find each exterior angle of regular hexagon.','60 degrees','Divide 360 by 6.','120 degrees.'),
('regular-polygon-angles','foundational','Find each interior angle of regular pentagon.','108 degrees','Use 540 divided by 5.','72 degrees.'),
('polygon-diagonals','foundational','How many diagonals does a quadrilateral have?','2','Use n(n-3)/2.','4.'),
('polygon-diagonals','foundational','How many diagonals does a pentagon have?','5','Use 5 times 2 divided by 2.','10.'),
('regular-polygon-area','foundational','A regular polygon has perimeter 24 and apothem 5. Find area.','60','Use one-half apothem times perimeter.','120.'),
('regular-polygon-angles','foundational','A regular polygon exterior angle is 45 degrees. How many sides?','8','Divide 360 by 45.','4.'),
('polygon-classification','foundational','Is a regular polygon necessarily equiangular?','Yes','Regular means equal sides and equal angles.','No.'),
('interior-angle-sum','intermediate','A polygon interior-angle sum is 1260 degrees. Find number of sides.','9','Solve (n-2)180=1260.','7.'),
('regular-polygon-angles','intermediate','Each interior angle of regular polygon is 150 degrees. Find n.','12','Exterior is 30; 360/30.','10.'),
('polygon-diagonals','intermediate','A polygon has 27 diagonals. Find n.','9','Solve n(n-3)/2=27.','8.'),
('exterior-angle-sum','intermediate','Exterior angles of a convex polygon are 70,80,90,120. Is this possible?','Yes','They sum to 360.','No because angles differ.'),
('interior-angle-sum','intermediate','Find one missing angle if hexagon interior angles total 720 and five sum 610.','110 degrees','Subtract known sum.','180 degrees.'),
('regular-polygon-area','intermediate','A regular hexagon side is 4. Find area.','$24\sqrt3$','It is six equilateral triangles of area $4\sqrt3$.','$16\sqrt3$.'),
('regular-polygon-area','intermediate','A regular octagon has perimeter 40 and apothem 6. Find area.','120','Use one-half 40 times 6.','240.'),
('polygon-symmetry','intermediate','How many lines of symmetry has regular decagon?','10','One for each vertex/side pattern.','5.'),
('polygon-symmetry','intermediate','What rotational symmetry angle maps a regular nonagon to itself first?','40 degrees','360/9.','45 degrees.'),
('polygon-triangulation','intermediate','How many triangles arise by drawing diagonals from one vertex of decagon?','8','An n-gon gives n-2 triangles.','7.'),
('polygon-diagonals','intermediate','How many diagonals start from one vertex of a heptagon?','4','Exclude itself and two adjacent vertices.','7.'),
('regular-polygon-angles','intermediate','Find central angle of regular 15-gon.','24 degrees','360/15.','12 degrees.'),
('polygon-classification','advanced','Prove interior-angle sum formula for convex n-gon.','Triangulate from one vertex into n-2 triangles.','Assuming formula by pattern.'),
('exterior-angle-sum','advanced','Prove exterior-angle sum is 360 degrees.','Track directed turning through one closed convex boundary.','Adding interior angles directly.'),
('polygon-diagonals','advanced','Derive n(n-3)/2 diagonal formula.','Each vertex joins n-3 nonneighbors; divide by two for double count.','Forgetting double counting.'),
('regular-polygon-area','advanced','Prove area equals one-half apothem times perimeter.','Decompose into n center triangles sharing apothem height.','Using circle area formula.'),
('polygon-converse','advanced','Give counterexample to “equiangular means regular.”','A non-square rectangle is equiangular but unequal-sided.','Using a regular square.'),
('polygon-symmetry','advanced','Why is every regular polygon cyclic?','All vertices are equally distant from its center.','Assuming all polygons are cyclic.'),
('mixed-polygon-circle','advanced','A regular hexagon is inscribed in circle radius 7. Find side.','7','Each central triangle is equilateral.','14.'),
('mixed-polygon-circle','advanced','A square is inscribed in circle radius 5. Find its side.','$5\sqrt2$','Diagonal is diameter 10.','10.'),
('construction','advanced','Describe construction of a regular hexagon in a given circle.','Step the radius around the circumference six times.','Divide diameter into six parts.'),
('polygon-proof-strategy','advanced','Why can concave polygons require care in triangulation?','Some vertex-to-vertex segments leave the interior.','Their angles merely look different.'),
('diagram-assumption-check','advanced','Why does a symmetric-looking polygon not prove regularity?','Equal sides/angles need marks or proof.','Symmetry in a drawing is a theorem.'),
('regular-polygon-angles','advanced','A regular polygon has an interior angle twice its exterior angle. Find n.','6','Let exterior x; 180-x=2x, then n=360/x.','3.'),
('polygon-optimization','advanced','Among n-gons with fixed perimeter, which has maximal area?','The regular n-gon.','Symmetry/optimization result; use as advanced principle.','A degenerate polygon.'),
('mixed-polygon-triangle','advanced','Connect alternate vertices of regular hexagon. What triangle forms?','Equilateral','The selected chords subtend equal 120-degree arcs and are equal.','Right triangle.'),
('classification','advanced','Can a concave polygon be regular under ordinary Euclidean definition?','No','Equal interior angles in a simple regular polygon are convex.','Yes if one vertex is reflex.'),
('proof-obligation','advanced','Why is an exterior angle not simply 180 minus any interior angle without orientation?','It must be the adjacent turn along a chosen traversal.','Every nonadjacent angle pairs with it.'),
('polygon-classification','foundational','How many sides has a nonagon?','9','Use the name prefix.','8.'),
('polygon-classification','foundational','What is a concave polygon?','One with an interior angle greater than 180 degrees.','Use the reflex-angle criterion.','One with unequal sides.'),
('interior-angle-sum','foundational','Find sum of interior angles of a heptagon.','900 degrees','Use five triangles.','1080 degrees.'),
('regular-polygon-angles','foundational','Each exterior angle of regular octagon is what?','45 degrees','Divide 360 by 8.','135 degrees.'),
('regular-polygon-angles','foundational','Each interior angle of regular hexagon is what?','120 degrees','Interior equals 180 minus exterior 60.','60 degrees.'),
('polygon-diagonals','foundational','How many diagonals does a hexagon have?','9','Use 6 times 3 divided by 2.','6.'),
('polygon-symmetry','foundational','How many rotational positions map regular square to itself?','4','Rotations by multiples of 90 work.','2.'),
('regular-polygon-area','foundational','Regular polygon perimeter 30, apothem 4: area?','60','One-half times perimeter times apothem.','120.'),
('exterior-angle-sum','foundational','A convex polygon has exterior angles 100,100,80,80. Is it possible?','Yes','They sum to 360.','No because it has four sides.'),
('interior-angle-sum','intermediate','A polygon has interior sum 1440. Find side count.','10','n-2=8.','12.'),
('regular-polygon-angles','intermediate','A regular polygon has exterior angle 20. Find interior angle.','160 degrees','Interior plus exterior is 180.','340 degrees.'),
('polygon-diagonals','intermediate','A polygon has 14 sides. How many diagonals?','77','Compute 14 times 11 divided by 2.','154.'),
('polygon-triangulation','intermediate','How many triangles from a vertex of a 20-gon?','18','Use n-2.','17.'),
('regular-polygon-area','intermediate','A regular hexagon side is 2. Find perimeter.','12','Six equal sides.','6.'),
('regular-polygon-area','intermediate','Regular decagon perimeter 50, apothem 7: area?','175','Use half Pa.','350.'),
('polygon-symmetry','intermediate','What is least rotation symmetry of regular 18-gon?','20 degrees','360 divided by 18.','18 degrees.'),
('mixed-polygon-circle','intermediate','A regular hexagon inscribed in circle radius 9 has perimeter?','54','Each side equals radius.','18 pi.'),
('mixed-polygon-triangle','intermediate','A regular pentagon has central angle?','72 degrees','Divide full turn by five.','108 degrees.'),
('polygon-converse','intermediate','Is an equilateral pentagon necessarily regular?','No','Its angles need not all be equal.','Yes.'),
('interior-angle-sum','intermediate','A convex polygon has five angles 100 each and one missing. Find missing.','220 degrees','Hexagon total is 720.','180 degrees.'),
('regular-polygon-angles','advanced','A regular polygon interior angle is 156 degrees. Find number of sides.','15','Exterior 24, then 360/24.','12.'),
('polygon-diagonals','advanced','A polygon has 35 diagonals. Find number of sides.','10','Solve n(n-3)=70.','8.'),
('polygon-proof-strategy','advanced','Prove that a regular polygon has a center equidistant from all vertices.','Use rotational symmetry: its fixed point is preserved and vertices form one orbit.','Assuming it from a drawing.'),
('polygon-symmetry','advanced','How many reflection axes does a regular odd n-gon have?','n','Each axis passes through a vertex and opposite side midpoint.','n/2.'),
('polygon-symmetry','advanced','How many reflection axes does a regular even n-gon have?','n','Half join opposite vertices and half opposite side midpoints.','n/2.'),
('regular-polygon-area','advanced','Derive regular polygon area using central triangles.','Sum n areas one-half side times apothem.','Using radius as altitude without proof.'),
('mixed-polygon-circle','advanced','A regular octagon is inscribed in circle radius R. What is its central triangle vertex angle?','45 degrees','Eight equal central sectors partition 360.','135 degrees.'),
('construction','advanced','How can a regular pentagon be checked after construction?','Verify equal central angles 72 degrees and equal chords.','Check only one side visually.'),
('polygon-optimization','advanced','Why does increased regularity tend to increase area for fixed perimeter?','Redistributing unequal adjacent lengths/angles toward equality reduces wasted boundary; formal proof uses isoperimetric principles.','Because regular shapes look round.'),
('diagram-assumption-check','advanced','Why may a polygon drawing not establish convexity?','A reflex angle must be marked, measured, or proved.','Concavity is always obvious in sketches.'),
('mixed-polygon-triangle','advanced','A regular hexagon has side 6. Find distance between opposite vertices.','12','Opposite vertices lie on a diameter of circumcircle radius 6.','$6\sqrt3$.'),
('mixed-polygon-triangle','advanced','A regular hexagon side 6: find long diagonal skipping one vertex.','$6\sqrt3$','It is chord subtending 120 degrees or 30-60-90 result.','12.'),
('proof-obligation','advanced','Why does n(n-3)/2 count diagonals but not sides?','The n-3 choices exclude self and two adjacent vertices.','Dividing side count by two.'),
('classification','advanced','Can a polygon with all interior angles under 180 be nonconvex?','No, for a simple polygon this is the convexity criterion.','Yes because side lengths can vary.'),
('exterior-angle-sum','advanced','Explain why exterior-turn sum remains 360 despite unequal side lengths.','Turning direction changes only with direction, and a closed simple convex path returns to original heading.','Side lengths enter the sum.'),
('regular-polygon-angles','advanced','Find n if regular polygon has one interior angle 11 times its exterior angle.','13','180-e=11e gives e=15.','12.'),
('polygon-diagonals','advanced','How many diagonals of regular 12-gon are not diameters?','48','There are 54 diagonals total and 6 diameters.','Counting each diameter twice.'),
('corrected-counting','advanced','Correct: How many non-diameter diagonals has regular 12-gon?','48','Subtract 6 diameters from 54 total diagonals.','54.'),
('area-decomposition','advanced','A regular hexagon is divided into six center triangles. What fraction is each?','1/6','Congruent triangles partition whole.','1/3.'),
('proof-obligation','advanced','Why must a regular-polygon apothem meet a side at its midpoint?','The center-to-chord perpendicular bisects that chord by circle symmetry.','Every radius bisects every segment.'),
('polygon-classification','foundational','How many sides does a dodecagon have?','12','Use the Greek prefix dodeca.','10.'),
('interior-angle-sum','foundational','Find interior sum of a quadrilateral.','360 degrees','Split it into two triangles.','180 degrees.'),
('exterior-angle-sum','foundational','Regular triangle exterior angle equals what?','120 degrees','360 divided by 3.','60 degrees.'),
('regular-polygon-angles','foundational','Regular octagon interior angle equals what?','135 degrees','180 minus 45.','45 degrees.'),
('polygon-diagonals','foundational','How many diagonals in a triangle?','0','Every pair of vertices is already a side.','3.'),
('polygon-symmetry','foundational','How many symmetry lines has regular triangle?','3','One through each vertex and opposite midpoint.','6.'),
('regular-polygon-area','foundational','Perimeter 18 and apothem 3: area?','27','Use Pa/2.','54.'),
('polygon-triangulation','foundational','A convex 9-gon can be split into how many triangles from a vertex?','7','Use n-2.','6.'),
('regular-polygon-angles','intermediate','A regular polygon has 24 sides. Find exterior angle.','15 degrees','360 divided by 24.','7.5 degrees.'),
('interior-angle-sum','intermediate','A polygon has angle sum 1980. Find n.','13','1980/180=11=n-2.','11.'),
('polygon-diagonals','intermediate','A 15-gon has how many diagonals?','90','15 times 12 divided by 2.','180.'),
('regular-polygon-area','intermediate','A regular polygon has area 144 and perimeter 48. Find apothem.','6','144=24a.','3.'),
('polygon-symmetry','intermediate','Which rotations map regular hexagon to itself?','Multiples of 60 degrees','Use its sixfold rotation group.','Only 360 degrees.'),
('mixed-polygon-circle','intermediate','A regular triangle inscribed in radius 4 circle has central angle?','120 degrees','Three equal arcs partition full circle.','60 degrees.'),
('mixed-polygon-circle','intermediate','A square circumscribed about a radius 3 circle has perimeter?','24','Side equals diameter 6.','12 pi.'),
('polygon-converse','intermediate','Can an equiangular hexagon have unequal sides?','Yes','Angle equality alone does not fix side lengths.','No.'),
('exterior-angle-sum','intermediate','A convex polygon has exterior angles 30,40,50,60,70,110. Is it possible?','Yes','Their total is 360.','No because not equal.'),
('regular-polygon-angles','intermediate','A regular polygon has each interior angle 135. Find side count.','8','Exterior is 45.','10.'),
('polygon-diagonals','intermediate','How many diagonals from one vertex of a 12-gon?','9','Exclude itself and two neighbors.','10.'),
('interior-angle-sum','advanced','Prove a convex n-gon has n-2 triangle decomposition.','A fan from one vertex reaches every nonadjacent vertex and yields n-2 regions.','Counting diagonals as triangles.'),
('polygon-symmetry','advanced','Prove regular n-gon rotation by 360/n maps it to itself.','It permutes equally spaced vertices cyclically and preserves connecting edges.','Using a reflection argument only.'),
('regular-polygon-area','advanced','Derive apothem of regular hexagon side s.','$s\sqrt3/2$','Split an equilateral center triangle along altitude.','Using s/2.'),
('mixed-polygon-circle','advanced','Regular hexagon inscribed in radius 10 circle: find area.','$150\sqrt3$','Six equilateral triangles of side 10.','$300\sqrt3$.'),
('mixed-polygon-circle','advanced','Regular triangle inscribed in radius R: find side.','$R\sqrt3$','Chord for central 120 degrees, or two 30-60-90 triangles.','2R.'),
('polygon-converse','advanced','Give counterexample to “equal exterior angles implies regular polygon.”','An equiangular rectangle that is not a square.','Equal turns do not force equal sides.','A square.'),
('polygon-diagonals','advanced','Prove a regular even n-gon has n/2 diameters.','Each vertex has one opposite vertex; pair endpoints to avoid double count.','Counting n diameters.'),
('polygon-optimization','advanced','Why is a regular hexagon more area-efficient than an irregular one with same side sum?','Equalizing local variations increases area; formal justification is a polygonal isoperimetric result.','Because it has more sides.'),
('construction','advanced','Describe a regular octagon construction from a square.','Cut congruent isosceles right corner triangles so eight new sides match.','Add arbitrary diagonals.'),
('coordinate-polygon','advanced','Use shoelace or decomposition to find area of square vertices (0,0),(4,0),(4,4),(0,4).','16','Apply base-height or coordinate sum.','8.'),
('coordinate-polygon','advanced','Regular polygon vertices lie on a circle. What coordinate transformation preserves it?','Rotation about the center.','Rotations preserve radius and equally spaced angles.','Translation from the center.'),
('proof-obligation','advanced','Why does a diagonal-count proof divide by two?','Each diagonal has two endpoints and is selected from both endpoint counts.','Because there are two polygon sides per vertex.'),
('diagram-assumption-check','advanced','Why should an interior-angle formula not be applied blindly to self-intersecting figures?','The simple-polygon triangulation proof no longer applies directly.','They still look like polygons.'),
('classification','advanced','Can a regular polygon have exactly two symmetry axes?','No; regular polygons have as many axes as sides, at least three.','A rectangle analogy.'),
('regular-polygon-angles','advanced','Find n if exterior angle is one fifth of interior angle.','12','Let e=(180-e)/5, giving e=30.','10.'),
('area-decomposition','advanced','A regular polygon is cut from center into n congruent triangles. If total area 210 and n=14, find each.','15','Equal partition gives 210/14.','30.'),
('mixed-polygon-triangle','advanced','A regular octagon has central angle 45. What angle at a base vertex of one central triangle?','67.5 degrees','Isosceles triangle angles are (180-45)/2.','45 degrees.'),
('proof-obligation','advanced','Why may a regular polygon be decomposed using its center?','The center lies equidistant from all vertices, creating congruent isosceles triangles.','Any interior point works identically.'),
('polygon-proof-strategy','advanced','For a missing regular-polygon angle, which representation should be chosen first?','Exterior/central angle if side count is known, because it comes directly from one full turn.','Heron formula.'),
('mixed-polygon-circle','advanced','A regular pentagon is inscribed in a circle. What is central angle between adjacent vertices?','72 degrees','Divide 360 by 5.','108 degrees.'),
('polygon-classification','foundational','How many sides has an octagon?','8','Use the name.','7.'),
('interior-angle-sum','foundational','Interior sum of a 10-gon?','1440 degrees','Use (10-2)180.','1800.'),
('exterior-angle-sum','foundational','Exterior angle of regular 10-gon?','36 degrees','Divide 360 by 10.','144 degrees.'),
('regular-polygon-angles','foundational','Interior angle of regular 10-gon?','144 degrees','Subtract exterior angle from 180.','36 degrees.'),
('polygon-diagonals','foundational','Diagonals of a heptagon?','14','7 times 4 divided by 2.','28.'),
('polygon-symmetry','foundational','Regular pentagon rotational order?','5','Five rotations including identity map it to itself.','10.'),
('regular-polygon-area','foundational','Perimeter 16, apothem 2: area?','16','Use Pa/2.','32.'),
('polygon-triangulation','foundational','Triangles in a convex 6-gon fan?','4','n-2.','3.'),
('interior-angle-sum','intermediate','Interior sum 2340: find n.','15','n-2=13.','13.'),
('regular-polygon-angles','intermediate','Regular polygon exterior 18: find n.','20','360/18.','10.'),
('polygon-diagonals','intermediate','A 9-gon has how many diagonals from one vertex?','6','n-3.','7.'),
('regular-polygon-area','intermediate','Area 200, perimeter 80: apothem?','5','200=40a.','2.5.'),
('polygon-symmetry','intermediate','Least rotation of regular 12-gon?','30 degrees','360/12.','12 degrees.'),
('mixed-polygon-circle','intermediate','Regular square in radius 6 circle: diagonal?','12','It is a diameter.','$6\sqrt2$.'),
('mixed-polygon-triangle','intermediate','Central triangle of regular 6-gon has what three angles?','60,60,60','Central angle is 60 and equal radii give equal base angles.','30,30,120.'),
('polygon-converse','intermediate','Can a polygon have equal sides but unequal angles?','Yes','A non-square rhombus is an example.','No.'),
('exterior-angle-sum','intermediate','Missing exterior angle when others total 285?','75 degrees','Subtract from 360.','105.'),
('interior-angle-sum','intermediate','A regular polygon has interior sum 2160. Find n.','14','(n-2)180=2160.','12.'),
('polygon-diagonals','intermediate','Total diagonals of 8-gon?','20','8 times 5 divided by 2.','40.'),
('regular-polygon-area','intermediate','Regular hexagon perimeter 36, apothem $3\sqrt3$: area?','$54\sqrt3$','Use Pa/2.','$108\sqrt3$.'),
('polygon-classification','foundational','How many sides has a pentagon?','5','Use the name.','6.'),
('interior-angle-sum','foundational','Interior sum of a 9-gon?','1260 degrees','Use seven triangles.','1080 degrees.'),
('exterior-angle-sum','foundational','Exterior angle of regular 9-gon?','40 degrees','360/9.','45 degrees.'),
('regular-polygon-angles','foundational','Interior angle of regular 9-gon?','140 degrees','180-40.','120 degrees.'),
('polygon-diagonals','foundational','Diagonals of a 10-gon?','35','10 times 7 divided by 2.','70.'),
('polygon-triangulation','foundational','Triangles in a convex 12-gon fan?','10','n-2.','9.'),
('regular-polygon-area','foundational','Perimeter 50, apothem 8: area?','200','Use Pa/2.','400.'),
('polygon-symmetry','foundational','Regular 7-gon has how many symmetry axes?','7','One for each vertex.','14.'),
('interior-angle-sum','intermediate','Interior sum 2520: find n.','16','n-2=14.','14.'),
('regular-polygon-angles','intermediate','Regular polygon has exterior 12 degrees. Find n.','30','360/12.','15.'),
('polygon-diagonals','intermediate','Diagonals from one vertex of 16-gon?','13','n-3.','14.'),
('regular-polygon-area','intermediate','Area 90, apothem 3: perimeter?','60','90=Pa/2.','30.'),
('polygon-symmetry','intermediate','Least rotation of regular 5-gon?','72 degrees','360/5.','60 degrees.'),
('mixed-polygon-circle','intermediate','Circle radius 8 contains regular hexagon. Find its side.','8','Hexagon chord equals radius.','16.'),
('exterior-angle-sum','intermediate','Other exterior angles total 250. Find missing exterior angle.','110 degrees','Subtract from 360.','70.'),
('polygon-converse','intermediate','Can an equiangular octagon be nonregular?','Yes','Equal angles do not force equal sides.','No.'),
('polygon-triangulation','intermediate','A convex 17-gon is triangulated from one vertex. How many triangles form?','15','Use n-2.','14.')]
items=[]
for i,item in enumerate(Q,1):
    c,d,p,a,o,*trap=item
    items.append({'id':f'aops-v1-ch13-q{i:03d}','concept':c,'difficulty':d,'source':'original-authoring','prompt':p,'answer':a,'solutionOutline':o,'commonTrap':trap[0] if trap else ''})
doc={'metadata':{'id':'aops-v1-ch13-polygons-bank','chapter':13,'topicIds':['aops-polygons'],'status':'in-progress','minimumRequiredItems':150,'sourcePageRange':'pdf 141-146; printed 127-132'},'items':items}
Path('docs/assessment-reference/aops-volume-1/chapter-13-polygons-question-bank.yaml').write_text(yaml.safe_dump(doc,sort_keys=False,allow_unicode=True),encoding='utf8')
