from pathlib import Path
import yaml

# Individually authored seed items. Continue this list to 150 before using it for assessments.
Q=[
('triangle-inequality','foundational','Do side lengths 4, 7, and 12 form a triangle?','No; 4+7 is less than 12.','Check the sum of the two shorter sides.'),
('triangle-inequality','foundational','Find the integer values of x if sides are 5, 8, and x.','$4\le x\le12$','Use $|8-5|<x<13$ and integrality.'),
('triangle-angle-sum','foundational','A triangle has angles 48 degrees and 71 degrees. Find the third angle.','61 degrees','Subtract their sum from 180 degrees.'),
('exterior-angle','foundational','An exterior angle is 125 degrees and one remote interior angle is 54 degrees. Find the other remote interior angle.','71 degrees','Use exterior angle equals remote interior sum.'),
('pythagorean-theorem','foundational','Find the hypotenuse of a right triangle with legs 9 and 12.','15','Compute the square root of 81+144.'),
('pythagorean-converse','foundational','Classify a triangle with sides 6, 8, 10.','Right','Compare 6 squared plus 8 squared with 10 squared.'),
('pythagorean-converse','foundational','Classify a triangle with sides 5, 6, 8.','Acute','Since 8 squared is less than 5 squared plus 6 squared, it is acute.'),
('pythagorean-converse','foundational','Classify a triangle with sides 3, 4, 6.','Obtuse','The longest side squared exceeds the sum of the other squares.'),
('isosceles-triangle','foundational','In isosceles triangle ABC, AB=AC and angle B=37 degrees. Find angle A.','106 degrees','The base angles B and C are equal.'),
('equilateral-triangle','foundational','Find each angle of an equilateral triangle.','60 degrees','All three angles are equal and total 180 degrees.'),
('congruence','foundational','Which criterion proves two triangles congruent from three matching side lengths?','SSS','Three corresponding side equalities determine the triangle.'),
('congruence','foundational','Why is SSA generally insufficient for triangle congruence?','It can yield two noncongruent triangles.','The given angle is not included between the known sides.'),
('similarity','foundational','Triangles have corresponding side ratios 2:3 and one matching included angle. Are they necessarily similar?','Not from this information alone.','A scale ratio and one angle do not supply a valid general similarity criterion.'),
('similarity','foundational','Two similar triangles have scale factor 3 from small to large. A small side is 7. Find its corresponding large side.','21','Multiply every length by the linear scale factor.'),
('similarity-and-area','foundational','Similar triangles have linear scale factor 4. What is their area ratio?','16:1','Area scales by the square of a length factor.'),
('triangle-area','foundational','Find area of a triangle with base 14 and altitude 5.','35','Use one half times base times altitude.'),
('triangle-area','foundational','A triangle has sides 8 and 10 enclosing a 30 degree angle. Find its area.','20','Use one half ab sine C.'),
('right-triangle-trigonometry','foundational','In a right triangle, opposite=3 and hypotenuse=5. Find sine theta.','3/5','Use opposite divided by hypotenuse.'),
('right-triangle-trigonometry','foundational','In a right triangle, adjacent=12 and opposite=5. Find tangent theta.','5/12','Use opposite divided by adjacent.'),
('special-right-triangles','foundational','A 45-45-90 triangle has leg 6. Find hypotenuse.','$6\sqrt2$','Hypotenuse is leg times square root of 2.'),
('special-right-triangles','foundational','A 30-60-90 triangle has short leg 4. Find long leg.','$4\sqrt3$','The long leg is short leg times square root of 3.'),
('triangle-centers','foundational','Which center is equidistant from all three sides of a triangle?','Incenter','It is the intersection of angle bisectors.'),
('triangle-centers','foundational','Which center divides each median in a 2:1 ratio from vertex to midpoint?','Centroid','It is the intersection of medians.'),
('triangle-centers','foundational','Where is the circumcenter of an acute triangle?','Inside the triangle','Perpendicular bisectors meet inside for acute triangles.'),
('triangle-centers','intermediate','A right triangle has legs 5 and 12. Find its circumradius.','13/2','The circumcenter is midpoint of hypotenuse 13.'),
('similarity','intermediate','A line parallel to BC cuts AB at D and AC at E. If AD=4, AB=10, and DE=6, find BC.','15','Triangles ADE and ABC are similar with scale 2:5.'),
('similarity','intermediate','A 10-foot pole casts 6-foot shadow. A tree casts 21-foot shadow. Find tree height.','35 feet','Use similar right triangles from the same sun angle.'),
('right-triangle-altitude','intermediate','An altitude to a right triangle hypotenuse splits it into 4 and 9. Find hypotenuse.','13','The two segments add to the hypotenuse.'),
('right-triangle-altitude','intermediate','An altitude to a right triangle hypotenuse splits it into 4 and 9. Find altitude.','6','Altitude squared is the product 4 times 9.'),
('right-triangle-altitude','intermediate','A right triangle hypotenuse is split into 5 and 20 by altitude. Find the leg adjacent to the 5 segment.','5 square root of 5','That leg squared is hypotenuse times adjacent segment: 25 times 5.'),
('inradius-area','intermediate','A triangle has semiperimeter 12 and inradius 3. Find its area.','36','Use area equals inradius times semiperimeter.'),
('heron','intermediate','Find area of a 3-4-5 triangle by Heron formula.','6','Semiperimeter is 6; compute square root of 6 times 3 times 2 times 1.'),
('median','intermediate','A median divides a triangle into two regions. What is their area ratio?','1:1','The two triangles share an altitude and have equal bases.'),
('angle-bisector','intermediate','An angle bisector meets opposite side in segments 6 and 9. If adjacent side near 6 is 8, find the other adjacent side.','12','Use side ratio equals split-segment ratio.'),
('triangle-inequality','intermediate','How many integer-sided triangles have perimeter 10?','2','Enumerate ordered side triples with a<=b<=c and apply inequality: 3,3,4 and 2,4,4.'),
('congruence-proof','intermediate','Two right triangles have equal hypotenuses and one matching leg. Name the congruence theorem.','HL','Hypotenuse-leg applies only to right triangles.'),
('similarity-proof','intermediate','Why do two triangles created by a line parallel to one side of a triangle become similar?','They have two equal corresponding angles.','Parallel-line angles give AA similarity.'),
('trigonometry','intermediate','A ladder makes 60 degrees with ground and reaches 8 square root of 3 feet high. Find ladder length.','16','Height is L sine 60 degrees.'),
('triangle-area','intermediate','A triangle has sides 13,14,15. Find its area.','84','Heron: semiperimeter 21 and square root of 21 times 8 times 7 times 6.'),
('triangle-proof-strategy','advanced','Prove that the medians of a triangle concur.','Use coordinates or area ratios; each median divides area equally and the shared ratio locates the common point.','A full proof must establish all three medians, not draw their apparent intersection.'),
('triangle-angle-sum','foundational','A triangle has one right angle and one 28 degree angle. Find the third angle.','62 degrees','Subtract 90 and 28 from 180.','Using 180-28 only.'),
('triangle-inequality','foundational','Find the largest integer side if the other sides are 9 and 14.','22','The third side is strictly less than 23.','Allowing 23, which is degenerate.'),
('isosceles-triangle','foundational','An isosceles triangle has vertex angle 44 degrees. Find a base angle.','68 degrees','Split the remaining 136 degrees equally.','Splitting 44 instead.'),
('pythagorean-theorem','foundational','A right triangle has hypotenuse 17 and one leg 8. Find the other leg.','15','Subtract 64 from 289 before square rooting.','Subtracting 8 from 17.'),
('congruence','foundational','Which information proves congruence: two angles and a nonincluded side?','AAS','Two angles determine the third and the side fixes scale.','Calling it AAA.'),
('similarity','foundational','Which criterion proves similarity from two equal angle pairs?','AA','Two equal angles force the third equal too.','Using SAS congruence.'),
('triangle-area','foundational','Find the altitude to base 16 of a triangle with area 56.','7','Solve 56=one-half times 16 times h.','Dividing 56 by 16.'),
('trigonometry','foundational','Find cosine theta if adjacent=8 and hypotenuse=17.','8/17','Cosine is adjacent over hypotenuse.','Using opposite over hypotenuse.'),
('special-right-triangles','foundational','A 30-60-90 triangle has hypotenuse 18. Find short leg.','9','Short leg is half hypotenuse.','Using 9 square root of 3.'),
('triangle-centers','foundational','Which center is equidistant from vertices?','Circumcenter','It lies on perpendicular bisectors.','Incenter.'),
('triangle-centers','foundational','Where is the orthocenter of an obtuse triangle?','Outside the triangle','Altitudes meet outside in an obtuse triangle.','At the midpoint of hypotenuse.'),
('triangle-area','foundational','A triangle has base 20 and area 90. Find altitude.','9','Rearrange A=bh/2.','Using 90/20.'),
('similarity-and-perimeter','intermediate','Similar triangles have perimeters 24 and 40. A small side is 9. Find corresponding large side.','15','Linear scale factor is 40/24=5/3.','Scaling by the area ratio.'),
('similarity-and-area','intermediate','Similar triangles have areas 25 and 121. Find positive linear scale factor.','11/5','Take square root of area ratio.','Using 121/25 as length factor.'),
('right-triangle-trigonometry','intermediate','From 40 meters away, angle of elevation to a tower top is 30 degrees. Find height.','$40\sqrt3/3$ meters','Use tangent equals height over 40.','Using sine without hypotenuse.'),
('right-triangle-trigonometry','intermediate','A 13-meter cable reaches a point 5 meters above ground. Find horizontal distance.','12 meters','Use Pythagoras with cable as hypotenuse.','Subtracting lengths.'),
('inradius-area','intermediate','A right triangle has legs 6 and 8. Find inradius.','2','Area is 24, semiperimeter is 12, so r=2.','Using half hypotenuse.'),
('circumcenter','intermediate','Find circumradius of an equilateral triangle of side 6.','$2\sqrt3$','Altitude is $3\sqrt3$ and centroid/circumcenter lies two thirds from vertex.','Using altitude itself.'),
('centroid','intermediate','A median has length 15. Find vertex-to-centroid distance.','10','Centroid divides median 2:1 from vertex.','Taking 5.'),
('angle-bisector','intermediate','In triangle ABC, AB=10, AC=15, and angle bisector from A meets BC at D. Find BD:DC.','2:3','Apply angle-bisector theorem.','Using 10:25.'),
('median','intermediate','In triangle ABC, M is midpoint of BC. If area ABC is 72, find area ABM.','36','Median creates equal-area triangles.','Using one third.'),
('triangle-inequality','intermediate','Find number of integer x such that 7, 11, x make a triangle.','13','Integers run from 5 through 17 inclusive.','Including 4 or 18.'),
('congruence','intermediate','Two triangles have sides 5,7,9 and 5,7,9. What corresponding angle fact follows?','All corresponding angles are equal.','Use SSS congruence then CPCTC.','Assuming angles before proving congruence.'),
('similarity','intermediate','Two triangles have angle pairs 40,70 and 40,70. If one has side opposite 40 equal 6 and other corresponding side 15, find scale factor.','5/2','AA establishes similarity; use 15/6.','Using 6/15 for large from small.'),
('triangle-area','intermediate','Find area of an equilateral triangle with side 10.','$25\sqrt3$','Use altitude $5\sqrt3$ then base-height formula.','Using 50 square root of 3.'),
('heron','intermediate','Find area of a triangle with sides 5,5,6.','12','Semiperimeter 8; square root of 8 times 3 times 3 times 2.','Using 15 as semiperimeter.'),
('right-triangle-altitude','intermediate','A right triangle has hypotenuse 25 and projection of a leg 9. Find that leg.','15','Leg squared equals hypotenuse times its projection.','Using 25-9 as leg length.'),
('triangle-proof-strategy','advanced','Prove the angle bisector theorem using areas.','Triangles ABD and ACD share altitude from A, so their area ratio is BD:DC; use sine-area expressions with equal half-angles to get AB:AC.','Claiming equal areas; their bases generally differ.'),
('triangle-proof-strategy','advanced','Prove that an angle bisector is the locus of points equidistant from the angle sides.','Drop perpendiculars to both sides and use congruent right triangles in both directions.','Showing only one direction of the locus statement.'),
('triangle-centers','advanced','Prove that perpendicular bisectors of a triangle concur.','Intersect two; equal-distance properties place that point on the third bisector.','Assuming the third line passes through the intersection.'),
('similarity-proof','advanced','Show that the altitude to hypotenuse of a right triangle forms two triangles similar to the original.','Each small triangle shares an acute angle with original and has a right angle, so use AA.','Using congruence despite different sizes.'),
('triangle-area','advanced','A triangle has sides 13,14,15. Find its inradius.','4','Heron gives area 84 and semiperimeter is 21.','Using 84/42.'),
('trigonometry','advanced','Prove sine squared theta plus cosine squared theta equals 1.','Divide the Pythagorean theorem by hypotenuse squared.','Adding ratios with mismatched denominators.'),
('triangle-inequality','advanced','Prove that the longest side is opposite the largest angle.','Drop an altitude or compare by the law-of-cosines-style construction; larger included angle increases opposite side.','Relying on a drawing without proof.'),
('construction','advanced','Describe how to construct the circumcenter with straightedge and compass.','Construct perpendicular bisectors of two sides; their intersection is equidistant from all vertices.','Constructing angle bisectors instead.'),
('construction','advanced','Describe how to construct the incenter.','Intersect two internal angle bisectors; it is equidistant from all sides.','Using perpendicular bisectors.'),
('proof-obligation','advanced','Why does equal area not imply congruent triangles?','Different base-height pairs can have same half-product, e.g. base 6 height 4 and base 8 height 3.','Treating area as a complete size-and-shape invariant.'),
('triangle-angle-sum','foundational','An equiangular triangle has one angle 60 degrees. What type is it?','Equilateral','Equal angles imply equal opposite sides.','Thinking equiangular only describes angles.'),
('triangle-inequality','foundational','Can lengths 2,3,5 form a nondegenerate triangle?','No','The sum of two sides equals the third, giving a degenerate segment.','Allowing equality in triangle inequality.'),
('pythagorean-theorem','foundational','A square has diagonal 10. Find its side.','$5\sqrt2$','Diagonal equals side times square root of 2.','Dividing by 2.'),
('isosceles-triangle','foundational','A triangle has angles 72,72,36. Which sides are equal?','The sides opposite the two 72 degree angles.','Equal angles have equal opposite sides.','Choosing the side opposite 36 degrees.'),
('congruence','foundational','Does AAA prove congruence?','No; it proves similarity only.','Angles fix shape but not scale.','Calling all similar triangles congruent.'),
('similarity','foundational','A triangle is enlarged by factor one half. What happens to an angle?','It is unchanged.','Similarity preserves angle measure.','Halving the angle.'),
('trigonometry','foundational','In a right triangle, sine theta=5/13. What is cosecant theta?','13/5','Use reciprocal functions.','Using 8/13.'),
('trigonometry','foundational','In a right triangle, tan theta=1. What acute angle is theta?','45 degrees','The legs are equal.','30 degrees.'),
('triangle-area','foundational','A triangle has area 24 and height 6. Find base.','8','Solve 24=bh/2.','Using base 4.'),
('triangle-centers','foundational','Which center is intersection of altitudes?','Orthocenter','This is its definition.','Centroid.'),
('similarity','intermediate','Corresponding sides are 9 and 15. If the small triangle has area 28, find large area.','700/9','Area factor is (15/9) squared=25/9.','Using 15/9 once.'),
('similarity','intermediate','A 6-8-10 triangle is similar to another with hypotenuse 25. Find its two legs.','15 and 20','Scale by 25/10=5/2.','Scaling by 25.'),
('right-triangle-trigonometry','intermediate','A kite string is 50 meters and makes 53.13 degrees with ground; use sin=4/5. Find height.','40 meters','Height is 50 times 4/5.','Using 30 meters.'),
('right-triangle-trigonometry','intermediate','A right triangle has hypotenuse 10 and angle 30 degrees. Find side opposite angle.','5','Use sine 30 degrees=1/2.','Using $5\sqrt3$.'),
('right-triangle-trigonometry','intermediate','A right triangle has adjacent leg 7 and angle 45 degrees. Find hypotenuse.','$7\sqrt2$','Cosine 45 degrees is square root of 2 over 2.','Using 14.'),
('triangle-area','intermediate','Two triangles share base 12. Their altitudes are 5 and 9. Find area ratio.','5:9','Same base makes area proportional to altitude.','Using 12:14.'),
('triangle-area','intermediate','A triangle has base 18. A line parallel to base cuts off a similar top triangle with scale 1/3. If original area is 90, find trapezoid area.','80','Small area is 1/9 of 90; subtract.','Using 90 times 2/3.'),
('triangle-centers','intermediate','In a right triangle with legs on coordinate axes and right vertex at origin, where is the orthocenter?','At the origin','The legs are altitudes.','At midpoint of hypotenuse.'),
('circumcenter','intermediate','An obtuse triangle has side lengths 4,5,8. Where is circumcenter?','Outside','Since 8 squared exceeds 4 squared+5 squared, triangle is obtuse.','Inside because all triangles have interior centers.'),
('median','intermediate','In triangle ABC, centroid G lies on median AM and AG=14. Find GM.','7','Vertex-to-centroid is twice centroid-to-midpoint.','Using 28.'),
('angle-bisector','intermediate','An angle bisector divides BC into 4 and 10. If AB=6, find AC.','15','Use AB/AC=4/10.','Using 6 times 10/4.'),
('heron','intermediate','Find area of triangle with sides 7,8,9.','$12\sqrt5$','Semiperimeter 12; root of 12 times 5 times 4 times 3.','Using 24 square root of 5.'),
('triangle-proof-strategy','advanced','Prove that the three interior angles of a triangle sum to 180 degrees.','Draw a line through one vertex parallel to opposite side and use alternate interior angles plus a straight angle.','Assuming the sum from a picture.'),
('triangle-proof-strategy','advanced','Prove the median from the right angle of a right triangle equals half the hypotenuse.','Use the circumcenter: hypotenuse midpoint is equidistant from all vertices.','Applying Pythagoras without locating the midpoint.'),
('similarity-proof','advanced','Prove that areas of similar triangles are in squared ratio of corresponding sides.','Use base and corresponding altitude, both scaled by k, in one-half bh.','Claiming it from examples.'),
('triangle-inequality','advanced','Prove that the sum of two sides of a triangle exceeds the third using a straightened broken path.','The direct segment between two points is shortest; the two sides form a longer broken path.','Treating the diagram as proof without the shortest-path fact.'),
('trigonometry','advanced','Derive the area formula one-half ab sine C.','Drop an altitude; its length is b sine C, then use base a.','Using cosine for the altitude.'),
('inradius-area','advanced','Prove area equals rs for any triangle.','Join incenter to vertices, creating three triangles of common height r and bases summing to 2s.','Using the circumradius instead.'),
('congruence-proof','advanced','Explain why SSA can be sufficient in a right triangle only under HL.','The right angle fixes the included structure; equal hypotenuse and one leg determine the other leg by Pythagoras.','Treating all SSA cases as valid.'),
('triangle-angle-sum','foundational','Find the third angle of a triangle with angles 33 degrees and 89 degrees.','58 degrees','Subtract 122 from 180.','Adding instead of subtracting.'),
('triangle-inequality','foundational','Which side can be opposite the largest angle?','The longest side.','Use side-angle ordering.','Choosing the shortest side.'),
('pythagorean-theorem','foundational','Find diagonal of a rectangle 7 by 24.','25','The diagonal is hypotenuse of a right triangle.','Adding 7 and 24.'),
('isosceles-triangle','foundational','Equal sides in a triangle are opposite what?','Equal angles.','Use the isosceles triangle theorem.','Supplementary angles.'),
('congruence','foundational','Which criterion uses two sides and included angle?','SAS','The angle lies between the two named sides.','SSA.'),
('similarity','foundational','If two triangles are similar, what is true of corresponding angles?','They are equal.','Similarity preserves shape.','They are proportional.'),
('triangle-area','foundational','Find area of triangle base 9 height 10.','45','Take half the base-height product.','Using 90.'),
('trigonometry','foundational','What is cosine 60 degrees?','1/2','Use the 30-60-90 triangle.','Square root of 3 over 2.'),
('trigonometry','foundational','What is sine 45 degrees?','square root of 2 over 2','Use an isosceles right triangle.','1/2.'),
('triangle-centers','foundational','A point equidistant from endpoints of a segment lies on what locus?','Its perpendicular bisector.','This is the perpendicular-bisector locus theorem.','The segment itself.'),
('triangle-inequality','intermediate','A triangle has sides x, x+2, and 15. Find smallest integer x.','7','Need 2x+2>15.','Using x+2>15.'),
('pythagorean-converse','intermediate','A triangle has sides 7,24,25. Find its area.','84','It is right; use half of 7 times 24.','Using Heron unnecessarily and incorrectly.'),
('similarity','intermediate','In similar triangles, a side 12 corresponds to 20. A second small side is 9. Find its large counterpart.','15','Scale by 20/12.','Scale by 12/20.'),
('triangle-area','intermediate','A triangle has area 48 and two sides 12 and 10. Find sine of included angle.','4/5','Solve 48=one-half(12)(10)sin C.','Using 48/120.'),
('trigonometry','intermediate','A 20-meter ramp rises 12 meters. Find sine of its angle with ground.','3/5','Rise is opposite and ramp is hypotenuse.','Using 4/5.'),
('trigonometry','intermediate','A right triangle has tan theta=3/4 and hypotenuse 20. Find opposite leg.','12','Recognize 3-4-5 ratio scaled by 4.','Using 15.'),
('triangle-centers','intermediate','The perpendicular bisectors of a triangle meet at a point 10 from one vertex. Find circumradius.','10','Circumcenter is equidistant from all vertices.','Using half 10.'),
('centroid','intermediate','Centroid G divides median AM with GM=6. Find AM.','18','AG=12 and GM=6.','Using 12.'),
('inradius-area','intermediate','A triangle has area 30 and semiperimeter 10. Find inradius.','3','Use A=rs.','Using radius 20.'),
('heron','intermediate','Find area of triangle 10,10,12.','48','Semiperimeter 16; root of 16 times 6 times 6 times 4.','Using base 12 height 10.'),
('right-triangle-altitude','intermediate','Hypotenuse segments are 1 and 16. Find the shorter leg.','square root of 17','Leg squared is whole hypotenuse 17 times adjacent segment 1.','Using altitude formula.'),
('angle-bisector','intermediate','AB:AC=5:7 and bisector meets BC at D. If BD=15, find DC.','21','Split segments have ratio 5:7.','Using 15 times 5/7.'),
('median','intermediate','A median is drawn to a side of length 18. What does the median do to that side?','Splits it into two segments of length 9.','A median ends at midpoint.','Makes two angles 9 degrees.'),
('construction','intermediate','How can you construct an altitude from vertex A to line BC?','Draw through A a perpendicular to BC.','Use perpendicular construction.','Bisect BC without ensuring perpendicularity.'),
('triangle-proof-strategy','advanced','Prove a triangle with two equal angles is isosceles.','Assume opposite sides unequal; the larger side would oppose larger angle, contradiction.','Using only the forward isosceles theorem without converse.'),
('triangle-proof-strategy','advanced','Prove the centroid area ratio statement for any median.','The two subtriangles have equal bases on the midpoint split and share altitude from opposite vertex.','Claiming equal sides.'),
('right-triangle-altitude','advanced','Prove altitude-to-hypotenuse geometric mean relation.','Use AA similarity of the three right triangles and write corresponding-side proportions.','Using Pythagoras alone without the required segments.'),
('similarity-proof','advanced','Prove that a line through one side of triangle parallel to another side cuts the remaining sides proportionally.','Use the similar small and original triangles, then translate side ratios into segment ratios.','Assuming ratios without proving similarity.'),
('trigonometry','advanced','Derive tan theta=sin theta/cos theta.','Divide opposite/hypotenuse by adjacent/hypotenuse.','Dividing angle measures.'),
('triangle-area','advanced','Prove that triangles on same base and between same parallels have equal area.','They share base and have equal perpendicular height between parallels.','Assuming their other sides equal.'),
('circumcenter','advanced','Prove circumcenter of a right triangle is hypotenuse midpoint.','That midpoint is equidistant from all three vertices by equal radii of the diameter circle.','Claiming every midpoint is a circumcenter.'),
('incenter','advanced','Why is an incenter inside every nondegenerate triangle?','Internal angle bisectors lie within the angle regions and their intersection is interior.','Extending external angle bisectors.'),
('triangle-inequality','advanced','Show no triangle has side lengths 2,3,6.','The two shorter sides total 5, less than 6.','Checking Pythagoras instead of inequality.'),
('congruence-proof','advanced','If two triangles have two sides and included angle equal, why is reflection not a counterexample to SAS?','A reflection is a rigid motion, so the reflected triangles are congruent.','Treating orientation as noncongruence.'),
('proof-obligation','advanced','Give a counterexample to “equal perimeters imply congruent triangles.”','A 3-4-5 triangle and equilateral triangle of side 4 both have perimeter 12 but differ.','Giving equal-area examples instead.'),
('triangle-centers','advanced','Explain why the orthocenter of a right triangle is the right-angle vertex.','Each leg is an altitude because it is perpendicular to the opposite leg.','Using the hypotenuse midpoint.'),
('similarity-and-area','advanced','Similar triangles have area ratio 49:64 and a small perimeter 42. Find large perimeter.','48','Linear ratio is 7:8.','Using 64/49 directly.'),
('triangle-area','advanced','A triangle has sides 6,8,10. Find its inradius using area and semiperimeter.','2','Area 24, semiperimeter 12.','Using circumradius 5.'),
('triangle-proof-strategy','advanced','Describe a reliable order for a triangle proof.','State givens, identify a theorem whose hypotheses are established, derive only licensed facts, and end at target.','Listing theorem names without logical connections.'),
('diagram-assumption-check','advanced','Why may a diagram not be used to infer a right angle?','A right angle requires a marking or proof; drawings can be distorted.','Saying diagrams are never useful.'),
('mixed-triangle-reasoning','advanced','A right triangle has legs 9 and 40. Find its inradius.','4','Hypotenuse 41, area 180, semiperimeter 45.','Using half the shorter leg.'),
('triangle-proof-strategy','advanced','Prove that an equilateral triangle is equiangular.','Use SSS congruence between appropriate triangles or the converse isosceles theorem repeatedly.','Claiming it from a standard drawing.'),
('similarity-and-area','advanced','Two similar triangles have corresponding altitudes 9 and 15. If small area is 54, find large area.','150','Area ratio is the square of 15/9=5/3.','Using 5/3 only once.'),
('triangle-center-locus','advanced','Why do internal angle bisectors meet at one point rather than form a triangle?','The intersection of two is equidistant from all three side lines, so it lies on the third angle bisector.','Assuming concurrency from symmetry.'),
('cevian-ratio','advanced','In triangle ABC, D is on BC with BD:DC=2:3. What is area ABD:ADC?','2:3','The triangles share the same altitude from A.','Using side lengths AB:AC.'),
('cevian-ratio','advanced','A median and an angle bisector from the same vertex coincide. What can be concluded?','The adjacent sides are equal, so the triangle is isosceles.','Equal split of the opposite side plus angle-bisector theorem gives side equality.','Concluding the triangle is equilateral.'),
('triangle-centers','advanced','Prove that the centroid is inside a nondegenerate triangle.','Each median segment lies inside the convex triangle; their intersection is interior.','Extending medians outside the figure.'),
('right-triangle-altitude','advanced','A right triangle has altitude to hypotenuse 12 and hypotenuse segments in ratio 4:9. Find hypotenuse.','25','Let segments be 4k and 9k; altitude squared is 36k squared=144.','Adding 4 and 9 before finding k.'),
('triangle-inequality','advanced','Find all integer triples with sides a<=b<=c and perimeter 12 that are right triangles.','3,4,5 only.','Test Pythagorean possibilities subject to sum 12.','Listing 5,5,2.'),
('similarity','advanced','A line parallel to base BC cuts AB and AC in ratio AD:DB=2:1. What is area ratio of top triangle to whole triangle?','4:9','Linear scale AD/AB=2/3, then square.','Using 2:3 for area.'),
('triangle-area','advanced','A triangle has fixed base 10 and fixed perimeter 30. Which shape maximizes area?','The isosceles triangle with the other two sides equal.','For fixed sum of the two sides, height is maximized symmetrically; this is an optimization fact.','Choosing a degenerate triangle.'),
('trigonometry','advanced','Derive the law of sines for a triangle from its circumcircle.','Each side equals 2R times sine of its opposite angle by the chord relation.','Using an inradius relation.'),
('trigonometry','advanced','A triangle has sides 5,7,8. Find cosine of angle opposite side 8.','1/7','Use cosine law: (25+49-64)/(2*5*7).','Using 8 as adjacent side.'),
('triangle-proof-strategy','advanced','Prove that a triangle cannot have two right angles.','Their sum is already 180 degrees, leaving no positive third interior angle.','Appealing to a flat drawing.'),
('reflection-symmetry','advanced','Why does the angle bisector in an isosceles triangle also bisect its base?','Reflection across the vertex angle bisector swaps equal sides and fixes the base midpoint.','Assuming every angle bisector is a median.'),
('mixed-triangle-reasoning','advanced','An equilateral triangle has inradius 6. Find its area.','$108\sqrt3$','Side is $2r\sqrt3=12\sqrt3$; use equilateral area.','Using area $\pi r^2$.')]
items=[]
for i,item in enumerate(Q,1):
    c,d,p,a,o,*trap=item
    items.append({'id':f'aops-v1-ch11-q{i:03d}','concept':c,'difficulty':d,'source':'original-authoring','prompt':p,'answer':a,'solutionOutline':o,'commonTrap':trap[0] if trap else ''})
doc={'metadata':{'id':'aops-v1-ch11-triangles-bank','chapter':11,'topicIds':['aops-triangles'],'status':'in-progress','minimumRequiredItems':150,'sourcePageRange':'pdf 107-131; printed 93-117'},'items':items}
Path('docs/assessment-reference/aops-volume-1/chapter-11-triangles-question-bank.yaml').write_text(yaml.safe_dump(doc,sort_keys=False,allow_unicode=True),encoding='utf8')
