from pathlib import Path
import yaml
Q=[
('quadrilateral-angle-sum','foundational','Find the fourth angle of a quadrilateral with angles 80,95,110 degrees.','75 degrees','Subtract 285 from 360.','Using triangle sum 180.'),
('parallelogram-properties','foundational','In parallelogram ABCD, AB=13. Find CD.','13','Opposite sides of a parallelogram are equal.','Using adjacent side.'),
('parallelogram-properties','foundational','One angle of a parallelogram is 68 degrees. Find an adjacent angle.','112 degrees','Consecutive angles are supplementary.','Using 68 degrees.'),
('rectangle-properties','foundational','A rectangle has sides 6 and 8. Find its diagonal.','10','Use Pythagoras.','Adding 6 and 8.'),
('rhombus-properties','foundational','A rhombus has diagonals 10 and 24. Find its area.','120','Use half product of perpendicular diagonals.','Using full product.'),
('square-properties','foundational','A square has side 7. Find its diagonal.','$7\sqrt2$','Use a 45-45-90 triangle.','Using 14.'),
('trapezoid-area','foundational','A trapezoid has bases 8 and 14 and height 5. Find area.','55','Use half sum of bases times height.','Using 110.'),
('kite-properties','foundational','A kite has perpendicular diagonals 12 and 9. Find area.','54','Use half the diagonal product.','Using 108.'),
('parallelogram-test','foundational','Which property proves a quadrilateral is a parallelogram: diagonals bisect each other?','Yes','This is a converse test.','Thinking equal diagonals alone is enough.'),
('rectangle-properties','foundational','What is every interior angle of a rectangle?','90 degrees','A rectangle is a parallelogram with a right angle.','360 degrees.'),
('rhombus-properties','foundational','What do rhombus diagonals do?','They bisect each other at right angles.','State both properties.','Saying they are always congruent.'),
('trapezoid-properties','foundational','What is the midsegment length of a trapezoid with bases 6 and 18?','12','Average the bases.','Taking difference 12.'),
('parallelogram-area','intermediate','A parallelogram has base 15 and height 7. Find area.','105','Use base times perpendicular height.','Using side length if not altitude.'),
('parallelogram-area','intermediate','Adjacent sides 8 and 10 enclose 30 degrees. Find parallelogram area.','40','Use ab sine theta.','Using half ab sine theta.'),
('rectangle-properties','intermediate','A rectangle has diagonal 13 and width 5. Find length.','12','Use Pythagoras.','Subtracting 5.'),
('rhombus-properties','intermediate','A rhombus side is 13 and one diagonal is 10. Find other diagonal.','24','Half diagonals and side form right triangle: 5,12,13.','Using 26.'),
('trapezoid-area','intermediate','An isosceles trapezoid has bases 10,18 and legs 5. Find height.','3','Each horizontal offset is 4; use 3-4-5 triangle.','Using height 5.'),
('trapezoid-area','intermediate','Using previous trapezoid, find area.','42','Average bases 14 times height 3.','Using 84.'),
('diagonal-reasoning','intermediate','Parallelogram diagonals intersect at O. If AO=9, find OC.','9','Diagonals bisect each other.','Using 18.'),
('rectangle-properties','intermediate','A rectangle has diagonal 10 and makes 30 degrees with its base. Find shorter side.','5','Opposite side is 10 sine 30.','Using $5\sqrt3$.'),
('square-properties','intermediate','A square has diagonal 12. Find area.','72','Side squared is diagonal squared divided by 2.','Using 144.'),
('kite-properties','intermediate','A kite has diagonals 14 and 20. Find area.','140','Use half product.','Using 280.'),
('parallelogram-test','intermediate','A quadrilateral has one pair of opposite sides both parallel and equal. Classify it.','Parallelogram','This is a sufficient test.','Trapezoid only.'),
('rhombus-test','intermediate','A parallelogram has perpendicular diagonals. Classify it.','Rhombus','Perpendicular diagonals in a parallelogram imply equal sides.','Rectangle.'),
('rectangle-test','intermediate','A parallelogram has congruent diagonals. Classify it.','Rectangle','Congruent diagonals in a parallelogram imply right angles.','Rhombus.'),
('isosceles-trapezoid','intermediate','An isosceles trapezoid has base angle 70 degrees. Find the other angle on same leg.','110 degrees','Angles along a leg are supplementary.','70 degrees.'),
('quadrilateral-angle-sum','intermediate','Three angles of a parallelogram are 2x,3x,2x. Find x.','36 degrees','Opposite angles equal, so the data require 2x+3x=180.','Using all three as independent.'),
('diagonal-reasoning','intermediate','A rectangle has sides 9 and 12. Find distance from diagonal intersection to a vertex.','15/2','It is half the diagonal 15.','Using 15.'),
('quadrilateral-converses','advanced','Give a counterexample to “a quadrilateral with equal diagonals is a rectangle.”','An isosceles trapezoid that is not a rectangle.','Equal diagonals alone do not ensure opposite sides parallel.','Giving a square, which is a rectangle.'),
('parallelogram-proof','advanced','Prove opposite sides of a parallelogram are equal.','Draw a diagonal; alternate interior angles and shared diagonal give congruent triangles.','Assuming equality from a sketch.'),
('trapezoid-proof','advanced','Prove the trapezoid midsegment has length average of bases.','Use similar triangles or coordinate heights to show its endpoints divide legs equally.','Averaging without proving midpoint relation.'),
('rhombus-proof','advanced','Prove diagonals of a rhombus are perpendicular.','Use congruent SSS triangles formed by a diagonal and show bisected angles create equal supplementary angles.','Claiming all parallelogram diagonals are perpendicular.'),
('quadrilateral-area','advanced','Prove area of a rhombus with perpendicular diagonals is half their product.','Split into four right triangles and add their areas.','Using formula without the perpendicular hypothesis.'),
('parallelogram-area','advanced','Prove area of a parallelogram is base times height.','Cut a corner triangle and translate it to form a rectangle.','Changing area during the move.'),
('rectangle-proof','advanced','Prove a parallelogram with one right angle is a rectangle.','Consecutive angles supplementary and opposite angles equal force all four right.','Assuming adjacent angles are equal.'),
('square-classification','advanced','What two properties prove a parallelogram is a square?','It is both a rectangle and a rhombus.','Combine right-angle and equal-side characterizations.','Equal diagonals and equal area.'),
('orthodiagonal','advanced','A quadrilateral has perpendicular diagonals 16 and 30. Find area.','240','Use half product, valid for orthodiagonal quadrilateral.','Using 480.'),
('diagonal-reasoning','advanced','A rhombus has diagonals 18 and 24. Find side length.','15','Half diagonals 9 and 12 make right triangle.','Using 21.'),
('trapezoid-area','advanced','A trapezoid has area 96, bases 10 and 14. Find height.','8','Area is 12h.','Using 4.'),
('quadrilateral-proof-strategy','advanced','Why is “opposite sides look equal” not a proof of parallelogram?','Diagrams are not necessarily to scale; use a converse test or marked relation.','Saying drawings are never useful.'),
('quadrilateral-angle-sum','foundational','A quadrilateral has three right angles. Find the fourth.','90 degrees','Four angles total 360 degrees.','Using 180 degrees.'),
('parallelogram-properties','foundational','Opposite angles in a parallelogram are what?','Equal','Use parallel sides and alternate interior angles.','Supplementary in every case.'),
('rectangle-properties','foundational','A rectangle has diagonals 18. What is each diagonal length?','18','Rectangle diagonals are congruent.','9.'),
('rhombus-properties','foundational','A rhombus has four sides of what relation?','Equal length','This is the defining side property.','Parallel only.'),
('square-properties','foundational','Is every square a rectangle?','Yes','It has four right angles.','No because it has equal sides.'),
('square-properties','foundational','Is every rectangle a square?','No','A rectangle need not have equal adjacent sides.','Yes because both have right angles.'),
('trapezoid-properties','foundational','What sides are called bases of a trapezoid?','The parallel sides','They define the height direction.','The equal sides.'),
('kite-properties','foundational','A kite has which adjacent side condition?','Two pairs of adjacent congruent sides','This distinguishes it from a general quadrilateral.','Opposite sides congruent.'),
('parallelogram-area','foundational','Find area of a parallelogram base 11 height 4.','44','Use bh.','Using 22.'),
('trapezoid-area','foundational','Find area of trapezoid bases 5,9 height 6.','42','Average bases 7, multiply by 6.','Using 84.'),
('quadrilateral-angle-sum','intermediate','A quadrilateral has angles x,2x,3x,4x. Find x.','36 degrees','Ten x equals 360.','Using 18.'),
('parallelogram-properties','intermediate','In parallelogram, AB=3x+1 and CD=19. Find x.','6','Set opposite sides equal.','Using 19/3.'),
('parallelogram-properties','intermediate','A parallelogram angle is 3x and adjacent angle is 5x. Find x.','45 degrees','Adjacent angles sum to 180.','Using 22.5.'),
('diagonal-reasoning','intermediate','Diagonals of a parallelogram meet at O. If AC=26, find AO.','13','O bisects diagonal AC.','Using 26.'),
('rectangle-properties','intermediate','A rectangle has perimeter 30 and width 6. Find diagonal.','$3\sqrt5$','Length is 9; use Pythagoras.','Using 15.'),
('square-properties','intermediate','A square has area 98. Find its diagonal.','14','Diagonal squared is twice area.','Using $7\sqrt2$.'),
('rhombus-properties','intermediate','A rhombus has area 96 and one diagonal 12. Find other diagonal.','16','96=half times 12 times d.','Using 8.'),
('trapezoid-midsegment','intermediate','Trapezoid midsegment is 17 and one base 9. Find other base.','25','Midsegment equals half sum.','Using 8.'),
('isosceles-trapezoid','intermediate','An isosceles trapezoid has one base angle 55. Find all angles.','55,55,125,125','Base angles match and same-leg angles supplement.','Four 55-degree angles.'),
('kite-properties','intermediate','A kite has diagonal lengths 16 and 25. Find area.','200','Use half product.','Using 400.'),
('coordinate-quadrilateral','intermediate','Classify points (0,0),(4,0),(4,3),(0,3).','Rectangle','Opposite sides are parallel and adjacent slopes are perpendicular.','Square.'),
('coordinate-quadrilateral','intermediate','Classify points (0,0),(3,0),(4,2),(1,2).','Parallelogram','Opposite side vectors match.','Rectangle.'),
('parallelogram-test','advanced','Prove that both pairs of opposite sides equal implies parallelogram.','Draw a diagonal; SSS gives alternate interior angles equal, hence both parallel pairs.','Assuming equal lengths imply parallel.'),
('quadrilateral-converses','advanced','Give counterexample to “perpendicular diagonals imply rhombus.”','A non-square kite with perpendicular diagonals.','Perpendicularity alone does not give diagonal bisection.','Using a rhombus.'),
('quadrilateral-converses','advanced','Give counterexample to “a quadrilateral with one pair parallel is a parallelogram.”','A non-parallelogram trapezoid.','Need both pairs parallel or a valid converse.','Using a rectangle.'),
('rectangle-proof','advanced','Prove diagonals of a rectangle are equal.','Each diagonal is hypotenuse of congruent right triangles with the same two side lengths.','Assuming it from the drawing.'),
('rhombus-proof','advanced','Prove each diagonal of a rhombus bisects opposite angles.','Use SSS congruence of the two triangles cut by a diagonal.','Using only equal diagonals.'),
('trapezoid-proof','advanced','Prove base angles of an isosceles trapezoid are equal.','Drop altitudes to create congruent right triangles using equal legs and equal heights.','Claiming all trapezoids have equal base angles.'),
('quadrilateral-area','advanced','A kite has sides 5,5,8,8 with equal-side vertices opposite. Explain an area strategy.','Draw the diagonal joining equal-side vertices; it is a symmetry axis and creates two congruent triangles.','Using one-half product without knowing diagonals.'),
('coordinate-quadrilateral','advanced','Show points (0,0),(2,1),(5,7),(3,6) form a parallelogram.','Compare vectors: first-to-second equals fourth-to-third and second-to-third equals first-to-fourth.','Using only two equal distances.'),
('orthodiagonal','advanced','Why does half diagonal product give area only for perpendicular diagonals?','The four triangle areas combine as one-half d1 d2 sine theta; sine theta must be 1.','Assuming any crossing diagonals work.'),
('quadrilateral-proof-strategy','advanced','What must be checked before using a trapezoid midsegment formula?','That the segment joins midpoints of the legs and is parallel to bases.','Only that it looks centered.'),
('mixed-quadrilateral-reasoning','advanced','A parallelogram has side lengths 10,14 and included angle 30. Find its diagonal lengths.','$\sqrt{296}$ and $\sqrt{576}=24$','Use cosine law on the two triangles formed by a diagonal.','Assuming both diagonals equal.'),
('area-decomposition','advanced','Prove a diagonal of a parallelogram divides its area equally.','It forms congruent triangles with equal opposite sides and shared diagonal, or equal base-height products.','Assuming equal-looking halves.'),
('square-classification','advanced','A quadrilateral is a rhombus with a right angle. Prove it is a square.','A rhombus is a parallelogram; one right angle forces all right angles.','Treating a kite as a parallelogram.'),
('parallelogram-test','advanced','If diagonals of a quadrilateral bisect each other, why are opposite sides parallel?','The diagonal-created triangles are congruent by SAS, yielding alternate interior angles.','Using equal diagonal lengths instead of equal halves.'),
('trapezoid-area','advanced','A trapezoid bases differ by 8 and legs are 5, height 3. Find bases if perimeter is 30.','7 and 15','Horizontal offsets are 4 each; legs confirm, then use perimeter.','Treating both bases as 11.'),
('diagram-assumption-check','advanced','Why does a slanted drawing not prove a quadrilateral is a trapezoid?','Parallelism requires markings, coordinates, or proof.','Measuring the screen angle.'),
('classification','advanced','State one property that separates a rhombus from a general parallelogram.','All four sides equal, or perpendicular diagonals.','Equal opposite sides only.'),
('quadrilateral-angle-sum','foundational','Find fourth angle if three angles are 90,90,120 degrees.','60 degrees','Subtract 300 from 360.','Using 180.'),
('parallelogram-properties','foundational','In a parallelogram, if one side is 17, what is opposite side?','17','Opposite sides are congruent.','34.'),
('rectangle-properties','foundational','A rectangle has width 4 and length 3. Find diagonal.','5','Use Pythagoras.','7.'),
('square-properties','foundational','A square has perimeter 36. Find side.','9','Divide perimeter by 4.','18.'),
('rhombus-properties','foundational','A rhombus has all angles equal only when it is what?','A square','A rhombus with right angles is a square.','Any rhombus.'),
('trapezoid-area','foundational','Trapezoid bases 12,20 height 4: area?','64','Average bases is 16.','Using 128.'),
('parallelogram-test','foundational','If both pairs of opposite sides are parallel, classify quadrilateral.','Parallelogram','This is the definition.','Kite.'),
('diagonal-reasoning','foundational','Diagonals of a parallelogram bisect what?','Each other','Their intersection is each midpoint.','The angles in every case.'),
('kite-properties','foundational','Does a kite require all four sides equal?','No','It needs two adjacent equal-side pairs.','Yes.'),
('trapezoid-properties','foundational','If trapezoid bases are parallel, what is its height?','Perpendicular distance between bases','Height is not a slanted leg.','The longer base.'),
('parallelogram-area','intermediate','A parallelogram area 72 has base 9. Find height.','8','Solve bh=72.','4.'),
('rectangle-properties','intermediate','Rectangle diagonal 25, length 24. Find width.','7','Use 7-24-25 Pythagorean triple.','1.'),
('square-properties','intermediate','A square diagonal is $8\sqrt2$. Find perimeter.','32','Side is 8, then multiply by 4.','$16\sqrt2$.'),
('rhombus-properties','intermediate','Rhombus diagonals 6 and 8. Find perimeter.','20','Half-diagonals 3,4 give side 5.','10.'),
('trapezoid-midsegment','intermediate','Bases are x and x+10; midsegment is 18. Find x.','13','(2x+10)/2=18.','8.'),
('isosceles-trapezoid','intermediate','An isosceles trapezoid has legs 10, bases 12 and 28. Find height.','6','Each offset is 8; use 6-8-10.','8.'),
('coordinate-quadrilateral','intermediate','Find area of rectangle with vertices (1,2),(7,2),(7,6),(1,6).','24','Side lengths are 6 and 4.','12.'),
('coordinate-quadrilateral','intermediate','Do points (0,0),(2,0),(3,3),(1,3) form a parallelogram?','Yes','Opposite vectors are equal.','No because it is slanted.'),
('diagonal-reasoning','intermediate','A rhombus has diagonal intersection O. If AO=7 and BO=24, find side.','25','Use right triangle AOB.','31.'),
('quadrilateral-angle-sum','intermediate','Angles of a quadrilateral are x,x+20,2x,2x+10. Find x.','55 degrees','Six x plus 30 equals 360.','60.'),
('parallelogram-test','intermediate','A quadrilateral has opposite angles equal. Is it necessarily a parallelogram?','Yes, for a convex quadrilateral.','Then consecutive angles are supplementary, yielding parallel sides by converse.','No because a kite may have equal opposite angles.'),
('rectangle-test','intermediate','A quadrilateral has four right angles. Is it a rectangle?','Yes','This is the defining property.','Only if sides also equal.'),
('rhombus-test','intermediate','A quadrilateral has four equal sides. Is it a rhombus?','Yes','This is the defining property.','Only if diagonals perpendicular.'),
('quadrilateral-converses','advanced','Give counterexample to “equal opposite sides prove rectangle.”','A nonrectangular parallelogram.','Equal opposite sides prove parallelogram, not right angles.','A square.'),
('parallelogram-proof','advanced','Prove diagonals of a parallelogram bisect each other.','Use alternate interior angles and shared diagonal to prove opposite triangles congruent.','Using equal diagonals, which need not hold.'),
('rectangle-proof','advanced','Prove a parallelogram with equal diagonals is a rectangle.','Compare triangles with both sides shared/opposite equal and equal diagonals to show an angle is right.','Assuming diagonal equality always means square.'),
('rhombus-proof','advanced','Prove a parallelogram with adjacent equal sides is a rhombus.','Opposite sides of parallelogram are equal, so all four sides equal.','Using perpendicular diagonal claim.'),
('trapezoid-proof','advanced','Prove that a trapezoid with equal base angles is isosceles.','Drop equal-height altitudes; congruent right triangles yield equal legs.','Assuming bases equal.'),
('area-decomposition','advanced','A diagonal cuts a rectangle 8 by 15. Find each triangular area.','60','Diagonal halves rectangle area 120.','Using 120 each.'),
('coordinate-quadrilateral','advanced','Use slopes to prove (0,0),(4,2),(6,6),(2,4) is a rhombus.','All four consecutive distances are square root of 20 and opposite slopes match.','Using slopes alone for equal lengths.'),
('quadrilateral-optimization','advanced','Among rectangles with perimeter 40, which has largest area?','The 10 by 10 square.','For fixed sum of side lengths, product is maximized when equal.','A 1 by 19 rectangle.'),
('quadrilateral-optimization','advanced','A rhombus has fixed side length. Which angle maximizes area?','90 degrees','Area is side squared times sine theta, maximal at sine 1.','0 degrees.'),
('orthodiagonal','advanced','A convex quadrilateral has diagonals 10 and 14 meeting at 30 degrees. Find area.','35','Use half d1 d2 sine 30 degrees.','70.'),
('mixed-quadrilateral-reasoning','advanced','A square is inscribed in a circle of radius 5. Find square area.','50','Square diagonal is circle diameter 10; area is diagonal squared/2.','25.'),
('mixed-quadrilateral-reasoning','advanced','A rectangle has sides 5 and 12. Find circumradius.','13/2','Circumradius is half diagonal.','13.'),
('proof-obligation','advanced','Why does a quadrilateral with perpendicular diagonals need not be a kite?','Perpendicularity does not ensure the adjacent equal-side pairs.','Assuming a visual diamond shape.'),
('construction','advanced','How can you construct a rectangle from one side and an adjacent side length?','Construct perpendicular at endpoint, mark adjacent length, then draw parallels through new endpoints.','Drawing an arbitrary quadrilateral.'),
('diagram-assumption-check','advanced','Why can equal-looking diagonals not be used as a fact?','Length equality needs a mark, calculation, or proof.','Measuring pixels.'),
('classification','advanced','A parallelogram has perpendicular and congruent diagonals. Classify it.','Square','Perpendicular diagonals make rhombus; congruent diagonals make rectangle.','Rectangle only.'),
('area-invariant','advanced','Two parallelograms share base 12 and lie between same parallels. Compare areas.','They are equal.','Their bases and heights match.','Their slanted sides determine area.'),
('quadrilateral-angle-sum','foundational','A quadrilateral has angles 88,92,88 degrees. Find fourth.','92 degrees','Subtract 268 from 360.','Using 180.'),
('parallelogram-properties','foundational','If AB=CD and AD=BC in a parallelogram, what can be said?','Both opposite side pairs are equal.','Use opposite-side property.','All adjacent sides equal.'),
('rectangle-properties','foundational','Find rectangle area with sides 11 and 3.','33','Multiply side lengths.','Using perimeter 28.'),
('rhombus-properties','foundational','A rhombus has side 9. What is its perimeter?','36','All four sides equal.','18.'),
('square-properties','foundational','A square area is 64. Find side.','8','Take positive square root.','32.'),
('trapezoid-area','foundational','Bases 4 and 16, height 7: find area.','70','Half sum bases is 10.','140.'),
('parallelogram-test','foundational','One pair of opposite sides is both equal and parallel. What follows?','Parallelogram','This is a sufficient test.','Rhombus.'),
('diagonal-reasoning','foundational','A diagonal of rectangle divides it into what type of triangles?','Congruent right triangles','Opposite sides match and diagonal is shared.','Equilateral triangles.'),
('trapezoid-properties','foundational','An isosceles trapezoid has what relation between its legs?','They are equal.','This is the definition used here.','They are parallel.'),
('quadrilateral-angle-sum','intermediate','Angles are x, x+30, x+60, x+90. Find x.','45 degrees','Four x plus 180 equals 360.','90.'),
('parallelogram-area','intermediate','Area 180 and height 12: find base.','15','Divide area by height.','30.'),
('rectangle-properties','intermediate','Rectangle perimeter 50 and length 16: find width.','9','2(16+w)=50.','17.'),
('square-properties','intermediate','Square perimeter 20: find area.','25','Side is 5.','100.'),
('rhombus-properties','intermediate','Rhombus area 150 and one diagonal 15: find other.','20','Half times 15 times d equals 150.','10.'),
('trapezoid-midsegment','intermediate','Bases 14 and 26: find midsegment.','20','Take their average.','12.'),
('coordinate-quadrilateral','intermediate','Find area of parallelogram with base 9 and perpendicular height 6.','54','Use bh.','27.'),
('isosceles-trapezoid','intermediate','Bases 6 and 14, height 4: find area.','40','Average bases 10 times height.','80.'),
('diagonal-reasoning','intermediate','A square diagonal is 18. Find distance from center to vertex.','9','Center bisects diagonals.','18.'),
('kite-properties','intermediate','Kite diagonals 18 and 10: find area.','90','Use half product.','180.'),
('parallelogram-proof','advanced','Prove opposite angles of a parallelogram are equal.','Use each pair of parallel sides with a transversal and supplementary-angle equations.','Claiming they are visually symmetric.'),
('quadrilateral-converses','advanced','Give counterexample to “all equal sides means square.”','A non-square rhombus.','Right angles are still required.','An equilateral triangle.'),
('rectangle-proof','advanced','Why do equal diagonals not alone prove a parallelogram?','An isosceles trapezoid can have equal diagonals.','State a concrete counterexample class.','Using a square.'),
('rhombus-proof','advanced','Prove a rhombus diagonal bisects its endpoint angles.','The two triangles on that diagonal have three corresponding equal sides.','Using only perpendicularity.'),
('trapezoid-proof','advanced','Prove trapezoid area formula by duplication.','Rotate a congruent copy and join to make a parallelogram of base sum and same height.','Doubling only the height.'),
('quadrilateral-area','advanced','A quadrilateral has diagonals 12,16 meeting at 90 degrees. Find area.','96','Use half product.','192.'),
('coordinate-quadrilateral','advanced','Prove a quadrilateral is rectangle using vectors.','Show adjacent dot product zero and opposite vectors equal.','Showing only equal diagonals.'),
('area-decomposition','advanced','A diagonal divides parallelogram into two equal areas. If total is 130, find one.','65','Diagonal halves parallelogram area.','130.'),
('mixed-quadrilateral-reasoning','advanced','A rhombus has side 10 and acute angle 30. Find area.','50','Use s squared sine 30.','100.'),
('mixed-quadrilateral-reasoning','advanced','A square circumscribes a circle radius 4. Find square area.','64','Side equals diameter 8.','16 pi.'),
('construction','advanced','How can a rhombus be constructed from one side and an included angle?','Copy side length on both rays from the angle, then draw parallels to close it.','Drawing a general parallelogram with unequal sides.'),
('diagram-assumption-check','advanced','Why is a drawn diagonal not necessarily an angle bisector?','A diagonal needs a stated/proven angle equality.','All rhombus diagonals bisect all angles.'),
('classification','advanced','A parallelogram has equal adjacent sides and one right angle. Classify it.','Square','Equal sides make rhombus and right angle makes rectangle.','Rhombus only.'),
('quadrilateral-optimization','advanced','For fixed diagonal lengths and included diagonal angle, what formula controls area?','One-half d1 d2 sine theta.','Decompose into four triangles.','Base times height without defining them.'),
('proof-obligation','advanced','Why should a proof of square classification establish both rhombus and rectangle properties?','Neither condition alone supplies both equal sides and right angles.','One familiar-looking property is enough.'),
('quadrilateral-angle-sum','intermediate','A quadrilateral has angles 100,80,100 degrees. Find fourth.','80 degrees','Subtract 280 from 360.','Using 100.'),
('parallelogram-properties','intermediate','A parallelogram has perimeter 44 and one side 8. Find adjacent side.','14','Two times sum of adjacent sides equals 44.','18.'),
('rectangle-properties','intermediate','Rectangle area 72 and width 8: find length.','9','Divide area by width.','64.'),
('square-properties','intermediate','Square side 11: find area.','121','Square the side.','44.'),
('rhombus-properties','intermediate','Rhombus perimeter 52: find side.','13','Divide by four.','26.'),
('trapezoid-area','intermediate','Trapezoid area 90, bases 8 and 22: find height.','6','Half base sum is 15.','3.'),
('diagonal-reasoning','intermediate','Parallelogram diagonal AC=30. Find AO.','15','Diagonals bisect.','30.'),
('kite-properties','intermediate','Kite area 72 has one diagonal 9. Find other diagonal.','16','72=one-half times 9 times d.','8.')]
items=[]
for i,item in enumerate(Q,1):
    c,d,p,a,o,*trap=item
    items.append({'id':f'aops-v1-ch12-q{i:03d}','concept':c,'difficulty':d,'source':'original-authoring','prompt':p,'answer':a,'solutionOutline':o,'commonTrap':trap[0] if trap else ''})
doc={'metadata':{'id':'aops-v1-ch12-quadrilaterals-bank','chapter':12,'topicIds':['aops-quadrilaterals'],'status':'in-progress','minimumRequiredItems':150,'sourcePageRange':'pdf 132-140; printed 118-126'},'items':items}
Path('docs/assessment-reference/aops-volume-1/chapter-12-quadrilaterals-question-bank.yaml').write_text(yaml.safe_dump(doc,sort_keys=False,allow_unicode=True),encoding='utf8')
