"""Generate the authored core for the AoPS Circles and Angle Chasing expansion.

The prose and problems in this script are original.  Chapter 9 and Chapter 14
reference documents supply the theorem scope and progression, not copied text.
"""
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "assessments"


def write(name, data):
    (OUT / name).write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=1000), encoding="utf-8")


def check(i, prompt, correct, wrong, explanation):
    return {"id": f"{i}-check", "type": "multipleChoice", "prompt": prompt,
            "choices": [{"id": x, "text": t} for x, t in zip("abcd", [correct] + wrong)],
            "answer": {"choiceId": "a"}, "explanation": explanation}


def lesson(aid, title, topic, intro, skills, sections):
    return {"schemaVersion": 1, "id": aid, "title": title, "assessmentType": "conceptLesson",
            "categoryId": "art-of-problem-solving", "topicId": topic, "modeDefault": "learn",
            "randomizeQuestions": False,
            "navigation": {"learningGoal": "learn", "activityType": "conceptLesson",
                           "tags": ["art-of-problem-solving", topic, "aops-volume-1", "geometry", "proof"]},
            "skills": skills, "lesson": {"introduction": intro, "sections": sections}}


def section(i, title, content, image, alt, caption, q, correct, wrong, explanation):
    return {"id": i, "title": title, "required": True, "content": content,
            "media": [{"type": "image", "src": f"/assessments/aops/{image}", "alt": alt, "caption": caption}],
            "check": check(i, q, correct, wrong, explanation)}


circle2 = lesson(
    "aops-circles-introduction-arcs-tangents-concept-lesson",
    "Circles II: Chords, Tangents, and Structural Proofs", "aops-circles-introduction",
    "A center turns curved geometry into triangles. This lesson develops the chord and tangent facts that make that conversion reliable, then combines them in proof and length problems.",
    ["Use perpendicular center-to-chord relationships in both directions.", "Build right triangles from tangent-radius perpendicularity.", "Select and justify auxiliary radii in circle proofs."], [
    section("aops-circle2-equal-radii", "Equal radii create isosceles triangles",
            "If $A$ and $B$ lie on a circle centered at $O$, then $OA=OB$. Thus triangle $AOB$ is isosceles. Equal radii are often the first hidden equality in a circle proof: draw the relevant radii, mark them equal, and then transfer equality to the base angles. The conclusion requires both endpoints to lie on the same circle.",
            "aops-circles-structure.svg", "Circle centered at O with labeled radii and chords.", "Drawing radii exposes equal sides that the curved boundary hides.",
            "Why are the base angles of triangle $AOB$ equal?", "$OA=OB$ because both are radii of one circle.", ["Every chord is a diameter.", "All triangles in a circle are equilateral.", "The picture makes the angles look equal."], "Equal sides in a triangle imply equal opposite angles."),
    section("aops-circle2-chord-forward", "A perpendicular from the center bisects a chord",
            "Let $OM$ be perpendicular to chord $AB$. Right triangles $OMA$ and $OMB$ share $OM$, have equal hypotenuses $OA=OB$, and each has a right angle. Hypotenuse-leg congruence gives $AM=MB$. This is a theorem with a condition: a segment from the center does not automatically bisect a chord unless perpendicularity is known.",
            "aops-circles-chord.svg", "Radius OM perpendicular to chord AB at M, with AM and MB marked equal.", "The perpendicular condition permits the midpoint conclusion.",
            "In the diagram, $AB=18$. What is $AM$?", "9", ["18", "36", "It cannot be determined."], "The perpendicular from the center bisects the chord, so $AM=AB/2=9$."),
    section("aops-circle2-chord-converse", "The chord theorem works in reverse",
            "If $M$ is the midpoint of chord $AB$, then $OM$ is perpendicular to $AB$. Triangles $OMA$ and $OMB$ have $OA=OB$, $AM=MB$, and common side $OM$, so SSS congruence makes the adjacent angles at $M$ equal. Because they form a linear pair, each is $90^\circ$. This converse is useful when midpoint markings are supplied instead of a right-angle mark.",
            "aops-circles-chord.svg", "Center O joined to the marked midpoint M of chord AB.", "Midpoint data can establish the missing perpendicular.",
            "Which fact is sufficient to prove $OM\perp AB$?", "$M$ is the midpoint of chord $AB$.", ["$M$ lies somewhere on $AB$.", "$AB$ appears horizontal.", "$OM$ is shorter than $OA$."], "The center-to-midpoint converse supplies perpendicularity."),
    section("aops-circle2-tangent", "A tangent is perpendicular to the contact radius",
            "A tangent meets a circle at one point $T$. The radius $OT$ is perpendicular to the tangent there. This creates a right triangle whenever an external point $P$ is joined to $O$. Conversely, a line through $T$ perpendicular to $OT$ is tangent. State the contact point: a radius to some other circle point need not be perpendicular to the tangent.",
            "aops-circles-tangent.svg", "Circle with tangent PT at T and right angle between OT and PT.", "Tangency turns the radius and tangent segment into perpendicular legs.",
            "If $OT=7$ and $OP=25$, what is tangent length $PT$?", "24", ["18", "25", "32"], "Right triangle $OTP$ gives $PT=\sqrt{25^2-7^2}=24$."),
    section("aops-circle2-two-tangents", "Tangents from one external point are equal",
            "If tangents from $P$ touch at $T$ and $U$, then $PT=PU$. Draw $OP$, $OT$, and $OU$. The two right triangles have common hypotenuse $OP$ and equal radius legs $OT=OU$, so they are congruent. This proof also shows why the theorem fails if either segment is a secant rather than a tangent.",
            "aops-circles-tangent.svg", "Tangent-radius right triangle from an external point P.", "Duplicating the right-triangle construction proves equal tangent lengths.",
            "Tangents from $P$ have lengths $3x+2$ and $5x-8$. Find $x$.", "5", ["2", "3", "10"], "Set the tangent lengths equal: $3x+2=5x-8$, hence $x=5$."),
    section("aops-circle2-construction", "Choose auxiliary lines for a purpose",
            "Draw a radius to a tangency point to create a right angle; draw radii to chord endpoints to create an isosceles triangle; join the center to a chord midpoint to access perpendicularity. An auxiliary line is not decoration. Before drawing it, name the theorem it unlocks and verify that its endpoints are available from the givens.",
            "aops-circles-tangent.svg", "Radius drawn to a tangent contact point to create a right triangle.", "A useful construction creates a named relation needed by the target.",
            "A problem gives a tangent at $T$ and asks for a length. Which auxiliary segment is most useful first?", "Draw the radius from the center to $T$.", ["Draw an arbitrary chord.", "Extend the tangent through the circle.", "Assume the tangent bisects a radius."], "The contact radius creates the justified right angle."),
    section("aops-circle2-synthesis", "Reason ledger and failure checks",
            "A complete circle argument records a reason beside every equality or right angle: radius, shared side, midpoint, perpendicular, or tangent. Reject conclusions based only on appearance. For lengths, check positivity and the Pythagorean inequality; for proofs, check that each theorem is used in the direction supported by its hypotheses.",
            "aops-circles-chord.svg", "Chord theorem diagram with midpoint and right-angle markings.", "Marks represent hypotheses; the proof ledger explains how conclusions follow.",
            "Which claim is invalid without another condition?", "A segment from the center to a chord bisects the chord.", ["Two radii of one circle are equal.", "A radius to a tangency point is perpendicular to the tangent.", "A diameter has length twice the radius."], "The center-to-chord segment must be perpendicular, or must meet the chord at its midpoint, before the paired theorem applies.")])


angle1_sections = [
    section("aops-angle-ledger", "Angle chasing is a reason ledger", "Mark only stated givens, then attach a reason to every new angle. The atomic moves are vertical angles equal, a linear pair sums to $180^\circ$, angles around a point sum to $360^\circ$, and triangle angles sum to $180^\circ$. A chase is valid because of this chain, not because the drawing resembles a familiar configuration.", "aops-angle-triangle.svg", "Triangle with two known angles and a marked exterior target.", "Each transferred or computed angle needs a named reason.", "Which note belongs in a valid reason ledger?", "$x=48^\circ+67^\circ$ by the exterior-angle theorem.", ["$x$ looks obtuse.", "$x$ is about $120^\circ$ from the drawing.", "$x$ equals the longest side."], "The note states both the relation and its justification."),
    section("aops-angle-intersections", "Intersections: vertical angles and linear pairs", "Opposite angles formed by two intersecting lines are vertical and equal. Adjacent angles whose noncommon sides form a line are a linear pair and sum to $180^\circ$. Decide whether the target is opposite or adjacent before choosing equality or supplementation.", "aops-angle-lines.svg", "Two parallel lines crossed by a transversal with marked interior angles.", "At each intersection, location determines whether angles are equal or supplementary.", "One angle at an intersection is $73^\circ$. What is an adjacent angle?", "$107^\circ$", ["$73^\circ$", "$17^\circ$", "$287^\circ$"], "Adjacent linear-pair angles sum to $180^\circ$."),
    section("aops-angle-triangle-sum", "Triangles and exterior angles", "Triangle interior angles total $180^\circ$. An exterior angle formed by extending one side equals the sum of the two remote interior angles; this follows by combining triangle sum with a linear pair. The remote angles are the two not adjacent to the exterior angle.", "aops-angle-triangle.svg", "Triangle ABC with remote interior angles 48 and 67 degrees and exterior angle x at C.", "The exterior target equals the two marked remote interior angles.", "For the shown values, what is $x$?", "$115^\circ$", ["$65^\circ$", "$67^\circ$", "$180^\circ$"], "$x=48^\circ+67^\circ=115^\circ$."),
    section("aops-angle-parallels", "Parallel lines transfer angles", "When parallel lines are cut by a transversal, corresponding and alternate interior angles are equal, while same-side interior angles are supplementary. These conclusions require an explicit parallel marking or a proved parallel relationship. Position names are safer than memorized letter shapes when a diagram is rotated.", "aops-angle-lines.svg", "Parallel lines l and m with a 62 degree angle alternate interior to x.", "The arrow marks supply the parallel hypothesis.", "In the marked diagram, what is $x$?", "$62^\circ$", ["$118^\circ$", "$28^\circ$", "Not enough information"], "Alternate interior angles between parallel lines are equal."),
    section("aops-angle-isosceles", "Equal sides transfer to equal angles", "In an isosceles triangle, equal sides face equal angles. The converse also holds: equal angles face equal sides. Mark which sides or angles are given equal before using the theorem. If a segment bisects the vertex angle of an isosceles triangle, congruent subtriangles often make it also a median and altitude.", "aops-angle-isosceles.svg", "Isosceles triangle ABC with AB equal AC and the 40 degree vertex angle bisected by AD.", "Equal sides and a bisected vertex angle create congruent halves.", "If the vertex angle is $40^\circ$, what is each base angle?", "$70^\circ$", ["$40^\circ$", "$80^\circ$", "$140^\circ$"], "The equal base angles share the remaining $140^\circ$."),
    section("aops-angle-direction", "Work forward and backward", "Forward work propagates known values. Backward work asks which equality or sum would determine the target. Meet in the middle: if the target is an exterior angle, seek its remote interiors; if it lies on a transversal, seek a transferable mate. Avoid computing every visible angle when only a short route is relevant.", "aops-angle-lines.svg", "A target angle x positioned across a transversal from a known 62 degree angle.", "Backward analysis identifies the exact transferable mate of x.", "What is the best backward question for target $x$ on a transversal?", "Which corresponding or alternate angle is linked to $x$?", ["How many angles can I label?", "Does $x$ look acute?", "Can I ignore the parallel marks?"], "The target's position determines the useful relation."),
    section("aops-angle-validation", "Validate the chase", "Check that triangle totals are $180^\circ$, angles around a point total $360^\circ$, and every angle measure lies between $0^\circ$ and $180^\circ$ unless a reflex angle is explicitly requested. Most importantly, audit every use of a converse and every parallel-line transfer for its missing hypothesis.", "aops-angle-triangle.svg", "Triangle and exterior angle configuration used to check an angle sum.", "A final sum check catches arithmetic and orientation errors.", "A chase gives triangle angles $48^\circ$, $67^\circ$, and $75^\circ$. What does the check reveal?", "The result is invalid because the sum is $190^\circ$.", ["The triangle is isosceles.", "The result is valid.", "The exterior angle is $75^\circ$."], "Interior angles of a triangle must sum to $180^\circ$.")]

angle1 = lesson("aops-angle-chasing-concept-lesson", "Angle Chasing I: Lines, Triangles, and Parallels", "aops-angle-chasing", "Angle chasing is controlled information propagation. Build a short chain of justified equalities and sums, and never treat visual appearance as a theorem.", ["Maintain a reason ledger for angle relations.", "Combine intersection, triangle, parallel-line, and isosceles facts.", "Validate a multi-step chase without relying on scale."], angle1_sections)

angle2_sections = [
    section("aops-angle2-central", "Central angles match their intercepted arcs", "A central angle has its vertex at the center, so its degree measure equals the measure of its intercepted arc. Identify the vertex before using this one-to-one relation; an angle whose vertex lies on the circle follows a different rule.", "aops-angle-circle.svg", "Central angle AOB of 104 degrees and inscribed angle ACB intercepting arc AB.", "The central angle and minor arc AB both measure 104 degrees.", "What is the measure of minor arc $AB$?", "$104^\circ$", ["$52^\circ$", "$208^\circ$", "$256^\circ$"], "A central angle has the same measure as its intercepted arc."),
    section("aops-angle2-inscribed", "Inscribed angles are half their arcs", "An inscribed angle has vertex on the circle and sides that are chords. Its measure is half the intercepted arc. Thus inscribed angles intercepting the same arc are equal. Be precise about which arc lies inside the angle; using the other arc changes the result.", "aops-angle-circle.svg", "Inscribed angle ACB marked x intercepting the same 104 degree arc as central angle AOB.", "The inscribed angle is half the central angle over the same arc.", "What is $x$ in the diagram?", "$52^\circ$", ["$104^\circ$", "$156^\circ$", "$208^\circ$"], "$x=104^\circ/2=52^\circ$."),
    section("aops-angle2-cyclic", "Opposite angles in a cyclic quadrilateral", "If all four vertices lie on one circle, opposite angles of the quadrilateral are supplementary. Each opposite pair intercepts arcs that together make the full circle, so their half-arc measures total $180^\circ$. The converse can prove concyclicity when a pair of opposite angles is supplementary.", "aops-angle-cyclic-tangent.svg", "Quadrilateral ABCD inscribed in a circle with all vertices visibly on the circumference.", "Concyclicity, not the shape's appearance, permits the supplementary conclusion.", "If angle $A=112^\circ$, what is opposite angle $C$?", "$68^\circ$", ["$112^\circ$", "$78^\circ$", "$248^\circ$"], "Opposite angles of a cyclic quadrilateral sum to $180^\circ$."),
    section("aops-angle2-tangent-chord", "A tangent-chord angle matches an inscribed angle", "The angle between a tangent at $A$ and chord $AB$ equals any inscribed angle intercepting chord $AB$ on the opposite arc. A reliable proof draws radius $OA$, uses $OA$ perpendicular to the tangent, then relates the isosceles central triangle to the relevant arc. Do not use this theorem when the line is a secant.", "aops-angle-cyclic-tangent.svg", "Tangent at A, chord AB, and inscribed angle ADB of 38 degrees intercepting chord AB.", "Both marked angles are tied to the same chord AB.", "What is tangent-chord angle $y$?", "$38^\circ$", ["$52^\circ$", "$76^\circ$", "$142^\circ$"], "The tangent-chord theorem equates it to inscribed angle $ADB$."),
    section("aops-angle2-radius", "Draw a radius to unlock circle angles", "When a tangent or chord is present, a radius can expose a right angle or an isosceles triangle. Draw to a tangency point for perpendicularity; draw to chord endpoints for equal sides. State the intended result before adding the line, because an arbitrary radius may not connect to the target.", "aops-angle-cyclic-tangent.svg", "Circle configuration containing a tangent at A and chord AB.", "Radius OA would create a justified right angle with the tangent.", "Which construction directly uses the tangent at $A$?", "Draw radius $OA$.", ["Draw any diameter not through $A$.", "Assume $AB$ passes through the center.", "Reflect the tangent without justification."], "The contact radius is perpendicular to the tangent."),
    section("aops-angle2-mixed", "Combine line and circle moves", "A mixed chase often follows this order: use parallel or isosceles facts to obtain one inscribed angle, convert it to an arc, and transfer that arc to another inscribed or tangent-chord angle. Record the intermediate arc explicitly so the factor of two is not lost.", "aops-angle-circle.svg", "Central and inscribed angles sharing the marked arc AB.", "Writing the arc measure makes the central-versus-inscribed factor visible.", "An inscribed angle intercepting arc $AB$ is $37^\circ$. What central angle intercepts the same arc?", "$74^\circ$", ["$18.5^\circ$", "$37^\circ$", "$143^\circ$"], "The arc and central angle are twice the inscribed angle."),
    section("aops-angle2-proof", "Converse checks and proof closure", "Circle angle theorems are conditional. Confirm vertex location, intercepted arc, tangency, or concyclicity before applying one. To close a proof, restate the target relation and cite the final theorem. Numerical agreement alone does not prove that an unmarked quadrilateral is cyclic.", "aops-angle-cyclic-tangent.svg", "Marked cyclic quadrilateral and tangent configuration.", "The circle and contact markings carry hypotheses that the proof must name.", "Which condition can prove four points concyclic?", "A pair of opposite quadrilateral angles sums to $180^\circ$.", ["Two adjacent angles are unequal.", "One diagonal looks like a diameter.", "Two sides appear parallel."], "The converse of the cyclic-quadrilateral theorem establishes concyclicity.")]

angle2 = lesson("aops-angle-chasing-circle-mixed-concept-lesson", "Angle Chasing II: Circle and Mixed Proof Chases", "aops-angle-chasing", "Circle configurations add arc conversion, cyclic quadrilaterals, tangent-chord angles, and purposeful auxiliary radii to the reason ledger.", ["Relate central angles, arcs, and inscribed angles.", "Use cyclic and tangent-chord conditions in both calculation and proof.", "Plan mixed line-and-circle chases."], angle2_sections)


def worked(aid, title, topic, skills, problems):
    rows = []
    for pi, (ptitle, problem, image, alt, steps) in enumerate(problems, 1):
        outsteps = []
        for si, (stitle, instruction, prompt, correct, wrong, expl) in enumerate(steps, 1):
            row = {"id": f"{aid}-p{pi}-s{si}", "title": stitle, "instruction": instruction,
                   "type": "multipleChoice", "prompt": prompt,
                   "choices": [{"id": x, "text": t} for x, t in zip("abcd", [correct]+wrong)],
                   "answer": {"choiceId": "a"}, "explanation": expl}
            if si == 1:
                row["media"] = [{"type": "image", "src": f"/assessments/aops/{image}", "alt": alt,
                                  "caption": "Use only the labels and markings stated in the problem."}]
            outsteps.append(row)
        rows.append({"id": f"{aid}-problem-{pi}", "title": ptitle, "problem": problem, "steps": outsteps})
    return {"schemaVersion": 1, "id": aid, "title": title, "assessmentType": "workedExample",
            "categoryId": "art-of-problem-solving", "topicId": topic, "modeDefault": "practice",
            "randomizeQuestions": False, "navigation": {"learningGoal": "learn", "activityType": "guidedWorkedExample", "tags": ["art-of-problem-solving", topic, "aops-volume-1", "geometry", "worked-example"]},
            "skills": skills, "workedExamples": rows}


def s(title, instruction, prompt, correct, b, c, d, explanation): return (title, instruction, prompt, correct, [b,c,d], explanation)

circle1_problems = [
 ("From circumference to area", "A circular garden has circumference $18\pi$ meters. Find its area.", "aops-circles-structure.svg", "Circle centered at O with radius and diameter distinguished.", [
  s("Parse the target", "Separate the given boundary length from the requested two-dimensional area.", "Which formula should be used first?", "$C=2\pi r$", "$A=\pi r^2$", "$d=\pi r$", "$C=\pi r^2$", "Circumference determines the radius before area can be found."),
  s("Recover the radius", "Set $2\pi r=18\pi$ and divide by $2\pi$.", "What is $r$?", "9 meters", "6 meters", "18 meters", "$9\pi$ meters", "The factors of $\pi$ cancel, giving $r=9$."),
  s("Compute the area", "Substitute the recovered radius into $A=\pi r^2$.", "What area results?", "$81\pi$ square meters", "$18\pi$ square meters", "$36\pi$ square meters", "$162\pi$ square meters", "$A=\pi(9)^2=81\pi$."),
  s("Check units", "Area must use square units and should scale quadratically.", "Which unit is correct?", "square meters", "meters", "cubic meters", "degrees", "Area is two-dimensional."),
  s("State the conclusion", "Answer the requested quantity, not the intermediate radius.", "What is the final answer?", "$81\pi$ square meters", "9 meters", "$18\pi$ meters", "$81$ meters", "The garden's area is $81\pi$ square meters.")]),
 ("Scaling a circular display", "A circular display is enlarged so its radius becomes $3/2$ of the original. The original area is $80$ square centimeters. Find the new area.", "aops-circles-scaling.svg", "Two circles with radii r and three-halves r illustrating linear and area scaling.", [
  s("Identify the scale", "The linear scale factor is the ratio of the new radius to the old.", "What is the linear factor?", "$3/2$", "$2/3$", "$3$", "$9/4$", "All lengths scale by $3/2$."),
  s("Choose the area law", "Area scales by the square of a linear factor.", "What is the area factor?", "$9/4$", "$3/2$", "$3$", "$4/9$", "Square $3/2$ to get $9/4$."),
  s("Apply the factor", "Multiply the original area by $9/4$.", "What calculation is correct?", "$80\cdot 9/4$", "$80\cdot 3/2$", "$80+9/4$", "$80\div 9$", "A scale factor multiplies, rather than adds to, the measurement."),
  s("Evaluate", "Simplify $80\cdot9/4$.", "What is the new area?", "180 square centimeters", "120 square centimeters", "90 square centimeters", "320 square centimeters", "$80/4=20$ and $20\cdot9=180$."),
  s("Sanity-check", "The radius increased by 50 percent, so area must increase by more than 50 percent.", "Which observation supports the answer?", "$180>120$", "$180<80$", "Area should scale linearly.", "Units should be centimeters.", "Quadratic growth makes the area more than $120$." )]),
 ("Sector with a removed center angle", "A radius-12 disk has a $150^\circ$ sector removed. Find the area that remains.", "aops-circles-sector.svg", "Circle sector with a central angle and shaded region distinguishing sector area.", [
  s("Translate the region", "The remaining region corresponds to the rest of the full $360^\circ$ turn.", "What angle remains?", "$210^\circ$", "$150^\circ$", "$120^\circ$", "$510^\circ$", "$360-150=210$."),
  s("Write the fraction", "Convert the remaining central angle into a fraction of the disk.", "Which fraction is correct?", "$210/360=7/12$", "$5/12$", "$7/6$", "$12/7$", "Reduce $210/360$ by 30."),
  s("Find the disk area", "Use $A=\pi r^2$ with $r=12$.", "What is the whole area?", "$144\pi$", "$24\pi$", "$12\pi$", "$288\pi$", "$12^2=144$."),
  s("Find the remainder", "Multiply the full area by $7/12$.", "What remains?", "$84\pi$ square units", "$60\pi$ square units", "$72\pi$ square units", "$252\pi$ square units", "$144\pi\cdot7/12=84\pi$."),
  s("Bound the result", "The remaining angle exceeds half a turn but is less than a full turn.", "Which bound must hold?", "$72\pi<84\pi<144\pi$", "$84\pi<72\pi$", "$84\pi>144\pi$", "$84\pi$ is a length.", "The area must lie between half and all of the disk.")])]

circle2_problems = [
 ("Chord distance from the center", "A circle has radius 13. Chord $AB$ has length 10, and $OM$ is perpendicular to $AB$. Find $OM$.", "aops-circles-chord.svg", "Circle with radius OM perpendicular to chord AB and midpoint marks at M.", [
  s("Use the chord theorem", "Perpendicular $OM$ from the center bisects chord $AB$.", "What is $AM$?", "5", "10", "13", "26", "$AM=AB/2=5$."), s("Build a right triangle", "Triangle $OMA$ is right at $M$, with hypotenuse $OA=13$.", "Which equation applies?", "$OM^2+5^2=13^2$", "$OM+5=13$", "$OM^2+13^2=5^2$", "$2OM=13$", "The radius is the hypotenuse."), s("Solve", "Subtract $25$ and take the positive square root.", "What is $OM$?", "12", "8", "14", "144", "$OM^2=144$, so distance $OM=12$."), s("Check the geometry", "A center-to-chord distance must be shorter than the radius.", "Which comparison holds?", "$12<13$", "$12>13$", "$12=13$", "$12<5$", "The computed leg is shorter than the hypotenuse."), s("Conclude", "State the requested length.", "What is the final conclusion?", "$OM=12$", "$AB=12$", "$OA=12$", "$AM=12$", "The center is 12 units from the chord.")]),
 ("Tangent length", "From external point $P$, segment $PT$ is tangent to a radius-8 circle at $T$. If $OP=17$, find $PT$.", "aops-circles-tangent.svg", "Circle centered O with tangent PT and right angle at T.", [
  s("Name the right angle", "A contact radius is perpendicular to its tangent.", "Which angle is $90^\circ$?", "$\angle OTP$", "$\angle OPT$", "$\angle TOP$", "Every angle shown", "$OT\perp PT$."), s("Set the equation", "Use hypotenuse $OP=17$ and leg $OT=8$.", "Which equation is correct?", "$PT^2+8^2=17^2$", "$PT^2+17^2=8^2$", "$PT+8=17$", "$2PT=25$", "The side opposite the right angle is $OP$."), s("Evaluate", "Compute $17^2-8^2$.", "What is $PT^2$?", "225", "153", "289", "81", "$289-64=225$."), s("Choose the root", "A geometric length is positive.", "What is $PT$?", "15", "$-15$", "225", "9", "$\sqrt{225}=15$."), s("Verify", "Check the Pythagorean triple.", "Which equality verifies the result?", "$8^2+15^2=17^2$", "$8+15=17$", "$15^2+17^2=8^2$", "$8\cdot15=17^2$", "$64+225=289$." )]),
 ("Equal tangents and an angle", "Tangents $PA$ and $PB$ touch a circle centered at $O$. If $\angle APB=50^\circ$, find $\angle AOB$.", "aops-circles-tangent.svg", "Tangent-radius construction from an external point, used twice for two contact points.", [
  s("Add the radii", "Draw $OA$ and $OB$ to the two tangency points.", "What angles are created?", "$\angle OAP=\angle OBP=90^\circ$", "Both are $50^\circ$", "Both are $25^\circ$", "No fixed angles", "Each contact radius is perpendicular to its tangent."), s("Recognize the quadrilateral", "Quadrilateral $OAPB$ has angle sum $360^\circ$.", "Which equation uses all four angles?", "$90+50+90+\angle AOB=360$", "$50+\angle AOB=180$", "$2\angle AOB=50$", "$90+90=\angle AOB$", "Use the two right angles and the given angle at P."), s("Solve", "Subtract the known angles from $360^\circ$.", "What is $\angle AOB$?", "$130^\circ$", "$50^\circ$", "$230^\circ$", "$310^\circ$", "$360-230=130$."), s("Relate arcs", "The central angle determines minor arc $AB$.", "What is the minor arc measure?", "$130^\circ$", "$65^\circ$", "$230^\circ$", "$50^\circ$", "A central angle equals its intercepted minor arc."), s("Check", "For two tangents, the external angle and minor central angle are supplementary.", "Which check holds?", "$50+130=180$", "$50=130$", "$2(50)=130$", "$360-50=130$", "The known tangent-angle relation confirms the result." )])]

angle1_problems = [
 ("Parallel-line transfer", "Parallel lines $l$ and $m$ are cut by transversal $t$. A marked alternate interior angle is $62^\circ$. Find $x$.", "aops-angle-lines.svg", "Parallel lines l and m with alternate interior angles 62 degrees and x.", [s("Read the markings", "Arrow marks, not appearance, establish $l\parallel m$.", "What hypothesis is available?", "$l\parallel m$", "$l\perp m$", "$t\parallel l$", "No line relation", "Matching arrow marks denote parallel lines."), s("Classify the pair", "The two marked angles lie between the parallels on opposite sides of the transversal.", "What kind of pair is this?", "alternate interior", "same-side interior", "vertical", "linear pair", "Their locations define alternate interior angles."), s("Apply the theorem", "Alternate interior angles between parallel lines are equal.", "Which equation follows?", "$x=62^\circ$", "$x+62=90$", "$x+62=360$", "$x=2(62)$", "The theorem gives equality."), s("Check range", "Both marked angles are acute.", "Which value is consistent?", "$62^\circ$", "$118^\circ$", "$242^\circ$", "$298^\circ$", "The transferred angle is acute."), s("Conclude", "State the target with units.", "What is $x$?", "$62^\circ$", "62 units", "$118^\circ$", "undetermined", "The parallel hypothesis determines $x$." )]),
 ("Exterior-angle chain", "In triangle $ABC$, $\angle A=48^\circ$ and $\angle B=67^\circ$. Side $AC$ is extended through $C$, forming exterior angle $x$. Find $x$.", "aops-angle-triangle.svg", "Triangle with remote interior angles 48 and 67 degrees and exterior target x.", [s("Locate remote angles", "The remote interior angles are the two triangle angles not adjacent to $x$.", "Which are remote?", "$\angle A$ and $\angle B$", "$\angle B$ and $\angle C$", "$x$ and $\angle C$", "Only $\angle C$", "Angles A and B do not share the exterior vertex."), s("Choose a theorem", "The exterior angle equals the sum of its remote interiors.", "Which equation applies?", "$x=48+67$", "$x=180-48-67$", "$x=48-67$", "$x=360-48-67$", "Use the exterior-angle theorem."), s("Calculate", "Add the two remote angles.", "What is $x$?", "$115^\circ$", "$65^\circ$", "$19^\circ$", "$245^\circ$", "$48+67=115$."), s("Independent check", "First find interior angle C, then use its linear pair.", "What is $\angle C$?", "$65^\circ$", "$115^\circ$", "$67^\circ$", "$48^\circ$", "$180-48-67=65$."), s("Verify", "Interior C and exterior x must be supplementary.", "Which check holds?", "$65+115=180$", "$65=115$", "$115-65=180$", "$2(65)=115$", "The linear pair verifies the chase." )]),
 ("Isosceles bisector synthesis", "In isosceles triangle $ABC$, $AB=AC$ and $\angle A=40^\circ$. Segment $AD$ bisects $\angle A$. Find $\angle ADB$.", "aops-angle-isosceles.svg", "Isosceles triangle with equal sides, 40 degree vertex angle, and angle bisector AD.", [s("Use equal sides", "Equal sides $AB$ and $AC$ make the base angles at B and C equal.", "What is each base angle?", "$70^\circ$", "$40^\circ$", "$20^\circ$", "$140^\circ$", "The remaining $140^\circ$ splits equally."), s("Use the bisector", "$AD$ divides the $40^\circ$ vertex angle equally.", "What is $\angle BAD$?", "$20^\circ$", "$40^\circ$", "$70^\circ$", "$80^\circ$", "An angle bisector makes two equal 20 degree angles."), s("Focus on a subtriangle", "Triangle $ABD$ has angles 20 degrees at A and 70 degrees at B.", "Which sum finds $\angle ADB$?", "$180-20-70$", "$20+70$", "$180-40-70$", "$360-20-70$", "Use the triangle sum in ABD."), s("Calculate", "Evaluate the remaining angle.", "What is $\angle ADB$?", "$90^\circ$", "$70^\circ$", "$110^\circ$", "$270^\circ$", "$180-90=90$."), s("Interpret", "A right angle at D proves a further relation.", "What follows?", "$AD\perp BC$", "$AD\parallel BC$", "$AB\perp AC$", "$D$ is the circle center", "A 90 degree intersection means perpendicular lines." )])]

angle2_problems = [
 ("Central to inscribed", "Central angle $\angle AOB=104^\circ$. Point $C$ lies on the opposite arc. Find inscribed angle $\angle ACB$.", "aops-angle-circle.svg", "Central angle 104 degrees and inscribed target x intercepting the same arc AB.", [s("Identify the shared arc", "Both angles intercept minor arc $AB$.", "What is arc $AB$?", "$104^\circ$", "$52^\circ$", "$208^\circ$", "$256^\circ$", "The central angle equals its arc."), s("Classify the target", "The vertex C lies on the circle.", "What kind of angle is ACB?", "inscribed", "central", "exterior", "reflex", "Its vertex is on the circumference and sides are chords."), s("Apply the half-arc rule", "An inscribed angle is half its intercepted arc.", "Which expression gives the target?", "$104/2$", "$2(104)$", "$360-104$", "$180-104/2$", "Use half the shared arc."), s("Calculate", "Divide by two.", "What is $\angle ACB$?", "$52^\circ$", "$104^\circ$", "$156^\circ$", "$208^\circ$", "$104/2=52$."), s("Check", "The inscribed angle must be half the central angle.", "Which relation verifies it?", "$2(52)=104$", "$52+104=180$", "$104-52=104$", "$52=104$", "Doubling the result recovers the central angle." )]),
 ("Cyclic quadrilateral converse", "In quadrilateral $ABCD$, $\angle A=73^\circ$ and $\angle C=107^\circ$. Prove that $A,B,C,D$ are concyclic.", "aops-angle-cyclic-tangent.svg", "Four points on a circle illustrating a cyclic quadrilateral; proof uses the given opposite angles.", [s("Identify the target theorem", "A converse can establish concyclicity from opposite angles.", "What must be shown?", "$\angle A+\angle C=180^\circ$", "$\angle A=\angle C$", "$AB=CD$", "$AB\parallel CD$", "Supplementary opposite angles imply a cyclic quadrilateral."), s("Substitute", "Use the two given angle measures.", "What sum is obtained?", "$73+107=180$", "$73+107=170$", "$107-73=180$", "$2(73)=107$", "The given values are supplementary."), s("Check opposition", "Angles A and C are at opposite vertices.", "Why does adjacency matter?", "The converse requires an opposite pair.", "Any two angles suffice.", "Only equal angles suffice.", "It does not matter.", "Supplementary adjacent angles occur in many noncyclic quadrilaterals."), s("Invoke the converse", "State the theorem after its condition is verified.", "What conclusion follows?", "$A,B,C,D$ are concyclic.", "$ABCD$ is a square.", "$AC$ is a diameter.", "$AB=BC$.", "The cyclic-quadrilateral converse gives exactly concyclicity."), s("Close the proof", "Connect the conclusion to the target without adding visual assumptions.", "Which final sentence is valid?", "Therefore one circle passes through all four vertices.", "Therefore every side is equal.", "Therefore the diagonals are perpendicular.", "Therefore the drawing is to scale.", "Concyclic means lying on one circle." )]),
 ("Tangent, chord, and arc transfer", "A tangent at $A$ forms angle $y$ with chord $AB$. Inscribed angle $\angle ADB=38^\circ$ intercepts chord $AB$. Find $y$ and minor arc $AB$.", "aops-angle-cyclic-tangent.svg", "Tangent at A and inscribed angle ADB of 38 degrees both associated with chord AB.", [s("Match the chord", "The tangent-chord angle and ADB both correspond to chord AB.", "Which theorem finds $y$?", "tangent-chord theorem", "linear-pair theorem", "triangle inequality", "parallel-lines converse", "The theorem equates the two angles intercepting the same chord."), s("Find the tangent angle", "Transfer the inscribed angle measure.", "What is $y$?", "$38^\circ$", "$52^\circ$", "$76^\circ$", "$142^\circ$", "$y=\angle ADB=38^\circ$."), s("Convert to an arc", "An inscribed angle is half its intercepted arc.", "Which equation gives arc $AB$?", "$m\widehat{AB}=2(38)$", "$m\widehat{AB}=38/2$", "$m\widehat{AB}=180-38$", "$m\widehat{AB}=360-38$", "Double the inscribed angle."), s("Calculate the arc", "Evaluate the doubled measure.", "What is minor arc $AB$?", "$76^\circ$", "$38^\circ$", "$142^\circ$", "$322^\circ$", "$2\cdot38=76$."), s("Audit conditions", "Check the vertex and tangency hypotheses.", "Which facts were essential?", "D lies on the circle and the line at A is tangent.", "The picture is symmetric.", "AB is a diameter.", "AD is parallel to the tangent.", "Those locations activate the two circle-angle theorems." )])]

write("aops-circles-introduction-arcs-tangents-concept-lesson.yaml", circle2)
write("aops-angle-chasing-concept-lesson.yaml", angle1)
write("aops-angle-chasing-circle-mixed-concept-lesson.yaml", angle2)
write("aops-circles-introduction-worked-example.yaml", worked("aops-circles-introduction-worked-example", "Circles I Worked Examples: Measurement and Scaling", "aops-circles-introduction", ["Solve circle measurement, scaling, and sector problems."], circle1_problems))
write("aops-circles-introduction-arcs-tangents-worked-example.yaml", worked("aops-circles-introduction-arcs-tangents-worked-example", "Circles II Worked Examples: Chords and Tangents", "aops-circles-introduction", ["Solve chord, tangent, and structural circle problems."], circle2_problems))
write("aops-angle-chasing-worked-example.yaml", worked("aops-angle-chasing-worked-example", "Angle Chasing I Worked Examples: Lines and Triangles", "aops-angle-chasing", ["Solve justified line, triangle, and parallel angle chases."], angle1_problems))
write("aops-angle-chasing-circle-mixed-worked-example.yaml", worked("aops-angle-chasing-circle-mixed-worked-example", "Angle Chasing II Worked Examples: Circle and Mixed Chases", "aops-angle-chasing", ["Solve and prove circle-angle and mixed configurations."], angle2_problems))


def glossary(aid, title, topic, entries):
    made=[]
    for term_id, term, definition, notation, example, aliases in entries:
        made.append({"id": term_id, "term": term, "definition": definition, "notation": notation,
                     "examples": [example], "aliases": aliases, "media": [], "tags": [term_id, topic],
                     "drills": [{"id": f"{term_id}-definition-drill", "type": "typed",
                                 "prompt": f"Name the term: {definition}",
                                 "answer": {"expected": term, "aliases": aliases},
                                 "explanation": f"The defining feature identifies {term}.", "tags": [term_id, topic]}]})
    return {"schemaVersion":1,"id":aid,"title":title,"assessmentType":"glossary","categoryId":"art-of-problem-solving","topicId":topic,"modeDefault":"practice","randomizeQuestions":True,"navigation":{"learningGoal":"learn","activityType":"glossary","tags":["art-of-problem-solving",topic,"aops-volume-1","geometry","terminology"]},"skills":["Recognize and use the topic's geometric vocabulary precisely."],"glossary":{"introduction":"Definitions include the condition that permits each theorem; use the drills to distinguish easily confused objects.","sections":[{"id":f"{topic}-terms","title":"Terms, conditions, and recognition cues","required":True,"content":"Name an object from its defining incidence or measurement facts, not from how a drawing looks.","entries":made}]}}

circle_terms=[
 ("circle","Circle","The set of points in a plane at one fixed positive distance from a center.","$OP=r$","Every boundary point P satisfies OP=r.",[]),("disk","Disk","A circle together with all points in its interior.","", "Area refers to the disk, while circumference refers to its boundary.",[]),("radius","Radius","A segment from the center to a point on the circle, or its length.","$r$","OA is a radius when A lies on the circle.",["radii"]),("diameter","Diameter","A chord that passes through the center; its length is twice the radius.","$d=2r$","A diameter divides the circle into two semicircles.",[]),("chord","Chord","A segment whose two endpoints lie on the circle.","", "Every diameter is a chord, but not every chord is a diameter.",[]),("secant","Secant","A line that intersects a circle at two points.","", "A secant continues beyond both endpoints of its chord.",[]),("tangent","Tangent","A line that meets a circle at exactly one point.","", "The tangent at T is perpendicular to radius OT.",[]),("point-of-tangency","Point of tangency","The unique point where a tangent meets its circle.","$T$","A radius to T makes the tangent-radius right angle.",["contact point"]),("circumference","Circumference","The length of a circle's boundary.","$C=2\pi r$","A radius-5 circle has circumference 10pi.",[]),("arc","Arc","A connected portion of a circle's circumference between two endpoints.","$\widehat{AB}$","An arc is one-dimensional; it is not a sector.",[]),("minor-arc","Minor arc","The arc between two points measuring less than 180 degrees.","", "Two-letter arc notation usually names a minor arc.",[]),("major-arc","Major arc","The arc between two points measuring more than 180 degrees.","", "A third point often identifies which major arc is intended.",[]),("central-angle","Central angle","An angle whose vertex is the center of a circle.","$\angle AOB$","Its degree measure equals that of its intercepted arc.",[]),("sector","Sector","The region bounded by two radii and their intercepted arc.","", "A 90-degree sector is one quarter of a disk.",[]),("concentric-circles","Concentric circles","Circles that share the same center but have different radii.","", "A washer-shaped region lies between concentric circles.",[]),("intercepted-arc","Intercepted arc","The arc lying between the points where an angle's sides meet a circle.","", "Circle-angle formulas require the correct intercepted arc.",[]) ]
angle_terms=[
 ("vertex","Vertex","The common endpoint of the rays that form an angle.","", "Vertex location distinguishes central from inscribed angles.",[]),("vertical-angles","Vertical angles","Opposite angles formed by two intersecting lines.","", "Vertical angles are equal.",[]),("linear-pair","Linear pair","Adjacent angles whose noncommon sides form a straight line.","", "A linear pair sums to 180 degrees.",[]),("complementary-angles","Complementary angles","Two angles whose measures sum to 90 degrees.","", "Complementary does not require adjacency.",[]),("supplementary-angles","Supplementary angles","Two angles whose measures sum to 180 degrees.","", "Opposite angles of a cyclic quadrilateral are supplementary.",[]),("transversal","Transversal","A line that intersects two or more other lines at distinct points.","", "A transversal creates corresponding and alternate angle pairs.",[]),("corresponding-angles","Corresponding angles","Angles in matching relative positions at two intersections of a transversal.","", "They are equal when the crossed lines are parallel.",[]),("alternate-interior-angles","Alternate interior angles","Interior angles on opposite sides of a transversal.","", "They are equal when the crossed lines are parallel.",[]),("same-side-interior-angles","Same-side interior angles","Interior angles on the same side of a transversal.","", "They are supplementary when the crossed lines are parallel.",["consecutive interior angles"]),("exterior-angle","Exterior angle","An angle formed by one side of a polygon and an extension of an adjacent side.","", "A triangle exterior angle equals its remote interior angles' sum.",[]),("remote-interior-angles","Remote interior angles","The two triangle interior angles not adjacent to a chosen exterior angle.","", "Their sum equals that exterior angle.",[]),("inscribed-angle","Inscribed angle","An angle with vertex on a circle and sides that are chords.","", "It measures half its intercepted arc.",[]),("cyclic-quadrilateral","Cyclic quadrilateral","A quadrilateral whose four vertices lie on one circle.","", "Its opposite angles are supplementary.",["inscribed quadrilateral"]),("tangent-chord-angle","Tangent-chord angle","An angle formed by a tangent and a chord at their shared endpoint.","", "It equals an inscribed angle intercepting the same chord.",[]),("auxiliary-line","Auxiliary line","A deliberately added line that creates a theorem-ready relationship.","", "A radius to tangency creates a right angle.",["construction line"]),("reason-ledger","Reason ledger","A record pairing each derived angle relation with the theorem or given that justifies it.","", "Write x=62 because alternate interior angles are equal.",[]) ]
write("aops-circles-introduction-glossary.yaml", glossary("aops-circles-introduction-glossary","Circles Glossary","aops-circles-introduction",circle_terms))
write("aops-angle-chasing-glossary.yaml", glossary("aops-angle-chasing-glossary","Angle Chasing Glossary","aops-angle-chasing",angle_terms))


def recall(aid,title,topic,entries):
    items=[]
    for term_id,term,definition,notation,example,aliases in entries:
        items.append({"id":f"{term_id}-flashcard","type":"flashcard","prompt":f"Define {term} and state its recognition cue.","answer":{"expected":definition},"explanation":example,"tags":[term_id,topic]})
    return {"schemaVersion":1,"id":aid,"title":title,"assessmentType":"recallDrill","categoryId":"art-of-problem-solving","topicId":topic,"modeDefault":"practice","randomizeQuestions":True,"navigation":{"learningGoal":"recall","activityType":"mixedRecallSet","tags":["art-of-problem-solving",topic,"aops-volume-1","geometry","terminology"]},"skills":["Recall precise definitions and theorem triggers."],"items":items}
write("aops-circles-introduction-recall.yaml", recall("aops-circles-introduction-recall","Circles Terminology Recall Drill","aops-circles-introduction",circle_terms))
write("aops-angle-chasing-recall.yaml", recall("aops-angle-chasing-recall","Angle Chasing Terminology Recall Drill","aops-angle-chasing",angle_terms))
print("generated core AoPS Circles and Angle Chasing content")
