"""Generate the Calc 3 Multiple Integration and Coordinate Systems assessment set."""
from pathlib import Path
import json
from generate_calc3_spatial_vectors_motion import ASSESSMENTS, PACKETS, BLUEPRINTS, MEDIA, write_yaml, lesson, recall, worked, quiz, packet, blueprint, svg

def T(id,slug,title,obj,a,b,sig,rem,vis,sec,rec,problem,steps,qs):
 return {"id":id,"slug":slug,"title":title,"objective":obj,"chunks":list(range(a,b+1)),"signal":sig,"remediation":rem,"visual":vis,"sections":sec,"recall":rec,"worked":problem,"worked_steps":steps,"questions":qs}

TOPICS=[
T("calc3-double-integrals","double-integrals","Double Integrals","calc3-double-integral-models",2675,2720,"integration-bounds-error","Calculus 1 → Riemann Integration","double-integrals",
[("Accumulate over a region","A double integral adds values across area elements in a planar region."),("Iterated integrals encode bounds","Inner bounds describe a slice; outer bounds move that slice across the region."),("Geometry guides setup","Sketching a region before integrating prevents reversed or missing bounds.")],
[("What differential represents area in rectangular coordinates?","dA"),("What does a double integral of 1 over D give?","area of D"),("What do inner bounds describe?","a slice"),("What does changing order require?","a new region description"),("What can a double integral represent under a surface?","volume"),("What must be sketched before setting bounds?","the region")],
"Evaluate $\int_0^2\int_0^3(x+y)\,dy\,dx$.",[("Integrate the inner variable","What is $\int_0^3(x+y)dy$?","$3x+9/2$"),("Integrate the outer variable","What is the final value?","15"),("Interpret","What does the rectangle provide?","Fixed x and y bounds.")],
[("Evaluate $\int_0^1\int_0^2 1\,dy\,dx$.",["2","1","3","0"],"2","The integrand 1 accumulates the rectangle's area."),("Which bounds describe $0\le x\le1$, $0\le y\le x$?",["$\int_0^1\int_0^x f(x,y)dy dx$","$\int_0^x\int_0^1 f dy dx$","$\int_0^1\int_x^0 f dy dx$","$\int_0^1 f dx$"],"$\int_0^1\int_0^x f(x,y)dy dx$","For each x, y runs from zero to the line y=x."),("What does $\iint_D1\,dA$ equal?",["Area of D","Volume above D","Perimeter of D","Maximum of f"],"Area of D","Each area element contributes one unit."),("Why sketch a general region first?",["To identify valid slice bounds","To avoid all integration","To make f constant","To remove one variable"],"To identify valid slice bounds","The sketch reveals where each slice starts and ends.")]),
T("calc3-double-integrals-polar","double-integrals-polar","Double Integrals in Polar Coordinates","calc3-polar-double-integrals",2721,2735,"polar-rectangular-conversion-error","Trigonometry → Polar Coordinates","polar-double-integrals",
[("Polar coordinates fit circular regions","Use radius and angle when a region has circular symmetry."),("Area scales with radius","The polar area element is $r\,dr\,d\theta$, not merely $dr\,d\theta$."),("Bounds trace a sweep","Choose theta for direction and r for distance along that direction.")],
[("What is dA in polar coordinates?","r dr dtheta"),("What does r measure?","distance from origin"),("What does theta measure?","angle"),("What is x in polar form?","r cos theta"),("What is y in polar form?","r sin theta"),("What coordinate system fits a disk?","polar")],
"Set up the area of the disk $x^2+y^2\le4$ in polar coordinates.",[("Convert boundary","What is the radial bound?","$0\le r\le2$"),("Choose angular sweep","What theta interval covers the disk?","$0\le\theta\le2\pi$"),("Include area factor","What integrand gives area?","$r$")],
[("Which factor must appear in a polar double integral?",["r","r squared","theta","1/r"],"r","Polar rectangles have area approximately r times dr times dtheta."),("What bounds describe the unit disk in polar form?",["$0\le r\le1$, $0\le\theta\le2\pi$","$-1\le x,y\le1$","$0\le r\le2\pi$, $0\le\theta\le1$","$r=1$ only"],"$0\le r\le1$, $0\le\theta\le2\pi$","Radius sweeps from center to boundary through all angles."),("What is $x^2+y^2$ in polar coordinates?",["$r^2$","r","theta squared","$r\cos\theta$"],"$r^2$","The radius satisfies r squared equals x squared plus y squared."),("Why can polar coordinates simplify a disk?",["The boundary has constant radius","They remove area","The angle is always zero","They make r negative"],"The boundary has constant radius","Circular boundaries become simple radial bounds.")]),
T("calc3-triple-integrals","triple-integrals","Triple Integrals","calc3-triple-integral-models",2762,2792,"integration-bounds-error","Calculus 1 → Riemann Integration","triple-integrals",
[("Accumulate through volume","A triple integral adds quantities across small volume elements."),("Nested bounds describe solids","Three bound pairs encode slices, sheets, and the full solid."),("Density creates mass","Integrating density over a solid yields total mass.")],
[("What does $\iiint_E1dV$ give?","volume of E"),("What does a triple integral of density give?","mass"),("What differential represents volume?","dV"),("How many variables occur in a triple integral?","three"),("What should bounds describe?","a solid region"),("What is a rectangular box bound by?","constant coordinate planes")],
"Evaluate $\int_0^1\int_0^2\int_0^3 1\,dz\,dy\,dx$.",[("Integrate z","What is the inner result?","3"),("Integrate y","What is the next result?","6"),("Integrate x","What is the volume?","6")],
[("What is $\iiint_{[0,1]\times[0,2]\times[0,3]}1dV$?",["6","3","5","0"],"6","It is the product of the box side lengths."),("What does $\iiint_E\rho dV$ represent?",["Mass","Area","Surface area","Density at one point"],"Mass","Density times volume elements accumulates mass."),("Which description is needed before setting triple bounds?",["The solid E","Only its boundary curve","A level curve","A tangent line"],"The solid E","Bounds must cover the three-dimensional region."),("How many integrations appear in a triple integral?",["Three","One","Two","Four"],"Three","One integral is used for each coordinate dimension.")]),
T("calc3-triple-integrals-cylindrical-spherical","triple-integrals-cylindrical-spherical","Triple Integrals in Cylindrical and Spherical Coordinates","calc3-3d-coordinate-integrals",2793,2825,"polar-rectangular-conversion-error","Trigonometry → Polar Coordinates","cylindrical-spherical",
[("Cylindrical extends polar","Use $(r,\theta,z)$ when a solid has circular symmetry around the z-axis."),("Spherical uses distance and angles","Use $(\rho,\theta,\phi)$ for spheres and cones centered at the origin."),("Jacobians scale volume","Cylindrical volume uses r; spherical volume uses $\rho^2\sin\phi$.")],
[("What coordinates are cylindrical?","r theta z"),("What is cylindrical dV?","r dr dtheta dz"),("What is spherical dV?","rho squared sin phi drho dphi dtheta"),("What solid fits spherical coordinates?","a sphere"),("What does rho measure?","distance from origin"),("What does cylindrical r measure?","distance from z-axis")],
"Set up the volume of the cylinder $x^2+y^2\le4$, $0\le z\le3$ in cylindrical coordinates.",[("Convert radial boundary","What is the r interval?","$0\le r\le2$"),("Set angle and height","What are theta and z bounds?","$0\le\theta\le2\pi$, $0\le z\le3$"),("Include the Jacobian","What factor is required?","r")],
[("Which Jacobian factor belongs to cylindrical coordinates?",["r","rho squared sin phi","1/r","theta"],"r","A polar cross-section contributes the radius factor."),("Which system is most natural for a sphere centered at the origin?",["Spherical","Rectangular only","Polar two-dimensional","Parametric only"],"Spherical","Constant rho describes a sphere."),("In cylindrical coordinates, what remains unchanged from rectangular coordinates?",["z","r","theta","rho"],"z","Cylindrical coordinates replace x and y but retain height."),("What does rho represent?",["Distance from origin","Angle in xy-plane","Height","Distance from z-axis"],"Distance from origin","Spherical radial distance is measured from the origin.")]),
T("calc3-change-of-variables","change-of-variables","Change of Variables in Multiple Integrals","calc3-jacobian-transformations",2826,2855,"algebraic-simplification-error","Calculus 2 → Integration Techniques","change-of-variables",
[("Transform a difficult region","A coordinate map can turn a slanted or curved region into a simpler uv-region."),("The Jacobian rescales area","The absolute determinant measures local area scaling under a transformation."),("Map both region and integrand","A valid setup changes bounds, variables, and the differential consistently.")],
[("What does the Jacobian determinant measure?","local area scaling"),("Why use absolute value of a Jacobian?","area is nonnegative"),("What must change with variables?","region bounds and differential"),("What variables commonly replace x and y?","u and v"),("What maps a region?","a transformation"),("What should a useful map simplify?","the region or integrand")],
r"Use $x=u+v$, $y=u-v$ to find $|\partial(x,y)/\partial(u,v)|$.",[("Build derivative matrix","What is the matrix?",r"$\begin{pmatrix}1&1\\1&-1\end{pmatrix}$"),("Take determinant","What is the determinant?","$-2$"),("Use magnitude","What is the Jacobian magnitude?","2")],
[("What factor replaces dA under a change of variables?",["$|\partial(x,y)/\partial(u,v)|du\,dv$","$du+dv$","$dx\,dy$ unchanged","$1/J$ always"],"$|\partial(x,y)/\partial(u,v)|du\,dv$","The determinant provides the local area scale."),("Why take an absolute value of the determinant?",["Area scale must be nonnegative","To make variables vanish","To reverse the region","To avoid bounds"],"Area scale must be nonnegative","Orientation may be negative but area is not."),("What should be transformed besides the integrand?",["The region and differential","Only x","Only y","Nothing else"],"The region and differential","All parts of the integral must use the new variables."),("What is a useful goal of a transformation?",["Simplify the region or integrand","Create more variables","Remove the Jacobian","Make every bound infinite"],"Simplify the region or integrand","The map is selected to reduce setup or computation complexity.")])
]
def main():
 for t in TOPICS:
  for name,build in [("concept-lesson",lesson),("recall",recall),("worked-example",worked)]:write_yaml(ASSESSMENTS/f"{t['slug']}-{name}-s2c.yaml",build(t))
  for kind in ["focused-practice","mastery-check"]:
   write_yaml(ASSESSMENTS/f"{t['slug']}-{kind}-s2c.yaml",quiz(t,kind));write_yaml(BLUEPRINTS/f"{t['slug']}-{kind}-blueprints-s2c.yaml",blueprint(t,kind))
  (PACKETS/f"packet-calc3-{t['slug']}-v1.json").write_text(json.dumps(packet(t),indent=2)+"\n",encoding="utf8")
  MEDIA.mkdir(parents=True,exist_ok=True);(MEDIA/f"{t['visual']}.svg").write_text(svg(t),encoding="utf8")
if __name__=='__main__':main()
