"""Generate the Calc 3 Vector Calculus and Integral Theorems assessment set."""
from pathlib import Path
import json

from generate_calc3_spatial_vectors_motion import (
    ASSESSMENTS, BLUEPRINTS, MEDIA, PACKETS, SOURCE, blueprint as _unused_blueprint,
    lesson, packet, recall, signal, svg, worked, write_yaml, expl,
)


def topic(id, slug, title, objective, start, end, issue, remediation, visual, sections, recall_items, worked_problem, worked_steps, focused, mastery):
    return {
        "id": id, "slug": slug, "title": title, "objective": objective,
        "chunks": list(range(start, end + 1)), "signal": issue,
        "remediation": remediation, "visual": visual, "sections": sections,
        "recall": recall_items, "worked": worked_problem, "worked_steps": worked_steps,
        "focused": focused, "mastery": mastery,
    }


TOPICS = [
topic("calc3-vector-fields", "vector-fields", "Vector Fields", "calc3-vector-field-interpretation", 2856, 2868,
      "vector-field-interpretation-error", "Calculus 3 -> Vectors", "vector-fields",
      [("A vector at every point", "A vector field assigns a vector to each point in a plane or space."),
       ("Arrows encode direction and size", "Arrow direction shows the local direction; arrow length represents relative magnitude."),
       ("Gradient fields point uphill", "A gradient is perpendicular to a level curve and points toward greatest increase.")],
      [("What does a vector field assign to each point?", "a vector"), ("What does arrow length represent?", "relative magnitude"), ("What does arrow direction represent?", "local direction"), ("What does a gradient point toward?", "greatest increase"), ("What is a gradient field built from?", "a scalar function"), ("What are level curves perpendicular to?", "the gradient")],
      "For F(x,y)=<y,-x>, find F(2,1).", [("Substitute the point", "What replaces x and y?", "x=2 and y=1"), ("Evaluate components", "What is F(2,1)?", "<1,-2>"), ("Interpret the arrow", "What does the result represent?", "The field vector at (2,1).")],
      [("For F(x,y)=<y,-x>, what is F(2,1)?", ["<1,-2>", "<2,1>", "<-1,2>", "<2,-1>"], "<1,-2>", "Substitute x=2 and y=1 into the ordered components."), ("Which field pattern represents arrows pointing away from the origin?", ["A radial outward field", "A circular field", "A uniform horizontal field", "A zero field"], "A radial outward field", "Each arrow must align with the position vector and point away from the origin."), ("For f(x,y)=x^2+y^2, what is the gradient at (1,2)?", ["<2,4>", "<1,2>", "<2,2>", "<4,2>"], "<2,4>", "Differentiate f by each variable, then evaluate at the point."), ("What does a gradient vector indicate?", ["The direction of greatest increase", "A direction tangent to a level curve", "The value of the function", "A closed path"], "The direction of greatest increase", "The gradient is normal to level curves and gives the maximum-rate direction.")],
      [("For F(x,y)=<x,-y>, what is F(3,-2)?", ["<3,2>", "<3,-2>", "<-3,2>", "<2,3>"], "<3,2>", "Evaluate both components at the stated point."), ("Which field is tangent to circles centered at the origin?", ["F(x,y)=<-y,x>", "F(x,y)=<x,y>", "F(x,y)=<1,0>", "F(x,y)=<0,0>"], "F(x,y)=<-y,x>", "This vector is perpendicular to the radial vector <x,y>."), ("At a point where level curves are close together, gradient arrows are usually", ["longer", "shorter", "always zero", "parallel to the level curve"], "longer", "A closer spacing signals a larger rate of change."), ("Which statement is true of a gradient and a level curve at the same point?", ["They are perpendicular", "They are always parallel", "They have equal magnitude", "They have opposite signs"], "They are perpendicular", "Moving along a level curve produces no first-order change in the function.")]),
topic("calc3-line-integrals", "line-integrals", "Line Integrals", "calc3-line-integral-evaluation", 2869, 2896,
      "line-integral-parameterization-error", "Calculus 3 -> Vector-Valued Functions", "line-integrals",
      [("Accumulate along a curve", "A scalar line integral adds scalar values weighted by small arc lengths."), ("Parameterization supplies motion", "A vector line integral uses a curve parameterization and its derivative."), ("Orientation can matter", "Reversing a vector line integral reverses its sign, while scalar mass integrals do not.")],
      [("What geometric object is integrated over in a line integral?", "a curve"), ("What does ds represent?", "arc length element"), ("What is dr for r(t)?", "r prime of t dt"), ("What can a vector line integral represent?", "work"), ("What happens when vector-line orientation reverses?", "the sign reverses"), ("What does a scalar line integral of density represent?", "mass of a wire")],
      "Find the scalar line integral of f=1 along the segment from (0,0) to (3,4).", [("Find the curve length", "What is the segment length?", "5"), ("Use the constant integrand", "What is 1 times the length?", "5"), ("Interpret", "What does the result measure?", "Accumulated unit density along the segment.")],
      [("What is the scalar line integral of f=1 along a segment of length 5?", ["5", "1", "10", "0"], "5", "Integrating one with respect to arc length gives the curve length."), ("For r(t)=<t,t^2>, what is r prime(t)?", ["<1,2t>", "<t,2t>", "<1,t>", "<2t,1>"], "<1,2t>", "Differentiate each coordinate with respect to t."), ("A force F=<2,0> moves from (0,0) to (3,0). What is the work?", ["6", "3", "2", "0"], "6", "The displacement is <3,0>, whose dot product with F is 6."), ("What changes sign if a vector line integral is traversed in reverse?", ["The integral", "The curve length", "A scalar density", "The endpoints as a set"], "The integral", "The differential displacement dr reverses direction.")],
      [("A wire has constant density 2 and length 5. What is its mass?", ["10", "7", "5", "2"], "10", "Mass is density times arc length for a constant density."), ("For F=<1,1> and r(t)=<t,t>, 0<=t<=2, what is the vector line integral?", ["4", "2", "0", "8"], "4", "F dot r prime is 2, and integrating 2 from 0 to 2 gives 4."), ("Which ingredient is required to evaluate a vector line integral from a parameterization?", ["The derivative r prime(t)", "Only the endpoints", "Only curve length", "A tangent plane"], "The derivative r prime(t)", "The differential displacement is obtained from the parameterization."), ("Which line integral is independent of orientation?", ["A scalar mass integral", "A work integral", "A circulation integral", "A vector integral with dr"], "A scalar mass integral", "Arc length ds stays positive when traversal is reversed.")]),
topic("calc3-conservative-vector-fields", "conservative-vector-fields", "Conservative Vector Fields and the Fundamental Theorem", "calc3-potential-path-independence", 2897, 2932,
      "conservative-field-test-error", "Calculus 3 -> Directional Derivatives and Gradients", "conservative-fields",
      [("Potentials generate fields", "A conservative field is the gradient of a potential function."), ("Endpoint values replace a path", "The Fundamental Theorem for Line Integrals evaluates a conservative-field integral by endpoint potential change."), ("Domain conditions matter", "Matching partial derivatives is a reliable test only on an appropriate simply connected domain.")],
      [("What is a conservative vector field?", "a gradient field"), ("What does path independent mean?", "only endpoints matter"), ("What does a closed-curve integral of a conservative field equal?", "zero"), ("What function is used in the Fundamental Theorem?", "a potential function"), ("What does grad f mean?", "the gradient of f"), ("What domain feature supports the curl test?", "simply connected")],
      "For F=<2x,2y>, use f=x^2+y^2 to evaluate the line integral from (0,0) to (1,2).", [("Recognize the potential", "What is f(1,2)?", "5"), ("Evaluate the start", "What is f(0,0)?", "0"), ("Subtract endpoint values", "What is the integral?", "5")],
      [("Which potential has gradient <2x,2y>?", ["x^2+y^2", "2xy", "x+y", "x^2-y^2"], "x^2+y^2", "Differentiate the candidate with respect to x and y."), ("If F is conservative, what is its line integral around a closed curve?", ["0", "Always positive", "Always one", "The curve length"], "0", "The initial and terminal points agree, so the potential change is zero."), ("For F=<y,x>, which potential works?", ["xy", "x+y", "x^2+y^2", "x-y"], "xy", "The partial derivatives of xy are y and x."), ("What feature makes a line integral path independent?", ["A conservative field", "A long curve", "A closed curve", "A constant parameter"], "A conservative field", "A potential function reduces the integral to endpoint values.")],
      [("For f=x^2+y^2, what is f(1,2)-f(0,0)?", ["5", "3", "1", "0"], "5", "Evaluate the potential at both endpoints and subtract."), ("Is F=<-y,x> conservative on the whole plane?", ["No", "Yes, its components are linear", "Yes, it has two components", "Only on a closed curve"], "No", "Its two-dimensional curl is 2 rather than zero."), ("Which check is necessary before using matching mixed partials as a conservative-field test?", ["Check the domain assumptions", "Measure the curve length", "Find a unit tangent", "Convert to polar coordinates"], "Check the domain assumptions", "A domain with a hole can invalidate the converse test."), ("A potential f has f(A)=7 and f(B)=3. What is the integral of grad f from A to B?", ["-4", "4", "10", "0"], "-4", "The Fundamental Theorem gives f(B)-f(A).")]),
topic("calc3-greens-theorem", "greens-theorem", "Green's Theorem", "calc3-greens-theorem", 2933, 2957,
      "greens-theorem-orientation-error", "Calculus 3 -> Double Integrals", "greens-theorem",
      [("Boundary becomes region", "Green's Theorem relates a planar closed-curve integral to a double integral over its interior."), ("Positive orientation is counterclockwise", "Traverse a positively oriented boundary so the region remains on the left."), ("Choose the correct form", "Use circulation or flux form according to the vector quantity requested.")],
      [("What kind of curve is used in Green's Theorem?", "a closed plane curve"), ("What is positive orientation?", "counterclockwise"), ("What region is used on the right side?", "the interior region"), ("What theorem connects a boundary and a double integral?", "Green's Theorem"), ("What should remain on the left during positive traversal?", "the region"), ("What coordinate dimension is Green's Theorem about?", "two")],
      "Use Green's Theorem to evaluate the circulation of F=<-y,x> around the counterclockwise unit circle.", [("Find the scalar curl", "What is Qx-Py?", "2"), ("Use the region", "What is the unit-disk area?", "pi"), ("Accumulate", "What is the circulation?", "2pi")],
      [("For F=<-y,x>, what is Qx-Py?", ["2", "0", "-2", "x+y"], "2", "Differentiate Q=x by x and P=-y by y, then subtract."), ("What direction is positive orientation in Green's Theorem?", ["Counterclockwise", "Clockwise", "Radially outward", "Along the gradient"], "Counterclockwise", "The positive convention keeps the region on the left."), ("What is the circulation of F=<-y,x> around the unit circle counterclockwise?", ["2pi", "pi", "-2pi", "0"], "2pi", "The scalar curl is 2 over a region of area pi."), ("When is Green's Theorem especially useful?", ["A closed planar curve bounds a simple region", "A space curve has endpoints", "A solid is closed", "A scalar function has one variable"], "A closed planar curve bounds a simple region", "It trades the boundary calculation for a planar double integral.")],
      [("For P=0 and Q=x around the counterclockwise unit square, what is the circulation?", ["1", "0", "2", "-1"], "1", "Qx-Py equals 1 and the square has area 1."), ("If a positively oriented boundary is reversed, what happens to its circulation integral?", ["Its sign reverses", "It is unchanged", "It becomes area", "It becomes zero"], "Its sign reverses", "Reversing traversal reverses the differential displacement."), ("Which quantity is integrated over the region in circulation form?", ["Qx-Py", "P+Q", "P dot Q", "curve length"], "Qx-Py", "This is the two-dimensional scalar curl in Green's Theorem."), ("Which prerequisite supports Green's Theorem setup?", ["Double-integral region description", "One-variable limits only", "Matrix inversion", "Series convergence"], "Double-integral region description", "The theorem's right side is a double integral over the enclosed region.")]),
topic("calc3-curl-divergence", "curl-divergence", "Curl and Divergence", "calc3-curl-divergence", 2958, 2975,
      "curl-divergence-component-error", "Calculus 3 -> Partial Derivatives", "curl-divergence",
      [("Curl measures local rotation", "Curl is a vector in three dimensions and detects local spinning tendencies."), ("Divergence measures net outflow", "Positive divergence indicates source-like local behavior; negative divergence indicates sink-like behavior."), ("Derivatives are component-specific", "Keep each partial derivative aligned with its field component and coordinate.")],
      [("What does curl measure?", "local rotation"), ("What does divergence measure?", "net outflow"), ("What is curl of a gradient?", "zero"), ("What is divergence of a constant field?", "zero"), ("What type is three-dimensional curl?", "a vector"), ("What type is divergence?", "a scalar")],
      "For F=<-y,x,0>, find curl F.", [("Identify components", "What are P, Q, and R?", "P=-y, Q=x, R=0"), ("Compute the nonzero component", "What is Qx-Py?", "2"), ("State the vector", "What is curl F?", "<0,0,2>")],
      [("What is curl of F=<-y,x,0>?", ["<0,0,2>", "<0,0,-2>", "<1,1,0>", "0"], "<0,0,2>", "The k-component is Qx-Py=1-(-1)=2."), ("What is div F for F=<x,y,z>?", ["3", "<1,1,1>", "0", "x+y+z"], "3", "Add Px, Qy, and Rz: 1+1+1."), ("What is curl(grad f)?", ["0", "grad f", "div f", "always 1"], "0", "Mixed partial derivatives cancel under the regularity assumptions."), ("Positive divergence most closely describes a", ["source", "sink", "closed curve", "tangent plane"], "source", "More leaves a small region than enters it.")],
      [("What is div F for F=<x^2,0,z>?", ["2x+1", "2x+z", "<2x,0,1>", "0"], "2x+1", "Take Px=2x, Qy=0, and Rz=1."), ("Which result has the correct type for divergence?", ["A scalar", "A vector normal", "A curve", "A surface"], "A scalar", "Divergence combines component derivatives into one scalar."), ("Which result has the correct type for curl in R3?", ["A vector", "A scalar", "A plane", "A parameter interval"], "A vector", "Curl has three components in three-dimensional vector calculus."), ("What can nonzero curl indicate for a velocity field?", ["Local rotation", "Constant speed", "Zero flux", "A conservative potential"], "Local rotation", "Curl captures infinitesimal spinning behavior.")]),
topic("calc3-parametric-surfaces-surface-integrals", "parametric-surfaces-surface-integrals", "Parametric Surfaces and Surface Integrals", "calc3-surface-integrals", 2976, 3026,
      "surface-orientation-parameterization-error", "Calculus 3 -> Vector-Valued Functions", "surface-integrals",
      [("Two parameters sweep a surface", "A parametric surface maps a parameter domain into three-dimensional points."), ("Cross products build area vectors", "The cross product of parameter tangent vectors supplies a normal direction and surface-area scaling."), ("Orientation selects a side", "Reversing the normal reverses a vector flux integral but not scalar surface area.")],
      [("How many parameters define a parametric surface?", "two"), ("What vectors are tangent to r(u,v)?", "ru and rv"), ("What produces a normal direction?", "ru cross rv"), ("What does dS represent?", "surface area element"), ("What does a scalar surface integral accumulate?", "a scalar density over area"), ("What does orientation affect?", "vector flux")],
      "For r(u,v)=<u,v,u+v>, find a normal vector.", [("Differentiate by u", "What is ru?", "<1,0,1>"), ("Differentiate by v", "What is rv?", "<0,1,1>"), ("Cross tangent vectors", "What normal can be used?", "<-1,-1,1>")],
      [("For r(u,v)=<u,v,u+v>, which vector is normal to the surface?", ["<-1,-1,1>", "<1,0,1>", "<0,1,1>", "<u,v,u+v>"], "<-1,-1,1>", "Compute ru cross rv from the two tangent vectors."), ("What does |ru cross rv| provide?", ["Surface-area scaling", "A potential function", "A curve length only", "A scalar curl"], "Surface-area scaling", "The cross-product magnitude is the area of a parameter-parallelogram."), ("What happens to a vector flux integral if the chosen normal reverses?", ["Its sign reverses", "It is unchanged", "It becomes scalar area", "It doubles"], "Its sign reverses", "The normal vector appears through a dot product with the field."), ("Which surface fits r(u,v)=<u,v,0>?", ["The xy-plane", "A sphere", "A helix", "The z-axis"], "The xy-plane", "Every point has z=0 while u and v freely supply x and y.")],
      [("What is a normal direction to r(u,v)=<u,v,0>?", ["<0,0,1>", "<1,0,0>", "<0,1,0>", "<u,v,0>"], "<0,0,1>", "The parameter tangent vectors are <1,0,0> and <0,1,0>."), ("What remains unchanged when surface orientation reverses?", ["Scalar surface area", "Vector flux", "The normal vector", "The sign of a flux integral"], "Scalar surface area", "Surface area uses the magnitude of the cross product, not its direction."), ("A uniform surface density of 3 over area 4 gives mass", ["12", "7", "3", "4"], "12", "A constant density factors out of the scalar surface integral."), ("Which data are essential for a vector surface integral?", ["A field and an oriented surface", "Only a boundary curve", "Only a scalar density", "A potential difference"], "A field and an oriented surface", "Flux pairs a vector field with a chosen normal direction.")]),
topic("calc3-stokes-theorem", "stokes-theorem", "Stokes' Theorem", "calc3-stokes-theorem", 3027, 3041,
      "stokes-orientation-theorem-selection-error", "Calculus 3 -> Parametric Surfaces and Surface Integrals", "stokes-theorem",
      [("Boundary circulation equals curl flux", "Stokes' Theorem connects a line integral around an oriented boundary to curl through any compatible surface."), ("Orientations must agree", "The right-hand rule links the chosen surface normal to the positive direction around its boundary."), ("Choose the simplest spanning surface", "A complicated boundary may be easier to evaluate using a simple surface with the same boundary.")],
      [("What theorem links boundary circulation and curl flux?", "Stokes' Theorem"), ("What does the boundary curve need?", "compatible orientation"), ("What rule links normal and boundary direction?", "right-hand rule"), ("What field operation appears in Stokes' Theorem?", "curl"), ("What may replace a difficult spanning surface?", "a simpler compatible surface"), ("What type of integral is on the boundary?", "a vector line integral")],
      "Use Stokes' Theorem for F=<-y/2,x/2,0> around the counterclockwise unit circle in the xy-plane.", [("Find curl", "What is curl F?", "<0,0,1>"), ("Choose the disk", "What is the unit disk area?", "pi"), ("Match orientation", "What is the circulation?", "pi")],
      [("What field operation appears in Stokes' Theorem?", ["Curl", "Divergence", "Gradient magnitude", "Laplacian only"], "Curl", "Stokes' Theorem integrates curl across an oriented surface."), ("For an upward normal, which boundary direction is positive when viewed from above?", ["Counterclockwise", "Clockwise", "Radially inward", "Either direction"], "Counterclockwise", "The right-hand rule gives the compatible orientation."), ("For F=<-y/2,x/2,0>, what is curl F?", ["<0,0,1>", "<0,0,-1>", "<1,1,0>", "0"], "<0,0,1>", "The k-component is Qx-Py=1/2-(-1/2)=1."), ("Why may a disk replace another surface with the same oriented boundary?", ["Stokes' Theorem equates their curl fluxes", "All surfaces have equal area", "Every field is conservative", "The boundary disappears"], "Stokes' Theorem equates their curl fluxes", "The theorem depends on the compatible boundary and field hypotheses.")],
      [("If a Stokes boundary orientation reverses while the surface normal stays fixed, what happens to the line integral?", ["Its sign reverses", "It is unchanged", "It becomes divergence", "It doubles"], "Its sign reverses", "Traversal reversal changes dr to its negative."), ("Which theorem is appropriate for circulation around a space-curve boundary?", ["Stokes' Theorem", "The Divergence Theorem", "A scalar surface-area formula", "A one-variable FTC statement"], "Stokes' Theorem", "It connects a boundary line integral to a curl surface integral."), ("For curl F=<0,0,2> through the upward unit disk, what is the flux?", ["2pi", "pi", "-2pi", "0"], "2pi", "The constant normal component 2 integrates over area pi."), ("Which condition is required for a Stokes surface?", ["Its boundary orientation matches its normal", "It is closed", "It has no boundary", "It is a solid"], "Its boundary orientation matches its normal", "Stokes' Theorem uses an oriented surface and its induced boundary orientation.")]),
topic("calc3-divergence-theorem", "divergence-theorem", "The Divergence Theorem", "calc3-divergence-theorem", 3042, 3055,
      "divergence-theorem-flux-error", "Calculus 3 -> Triple Integrals", "divergence-theorem",
      [("Closed-surface flux becomes volume accumulation", "The Divergence Theorem relates outward flux through a closed surface to a triple integral of divergence."), ("Outward is the positive convention", "The theorem requires the boundary surface of a solid with its outward orientation."), ("Divergence simplifies flux", "A difficult flux computation can become easy when divergence and the solid's volume are simple.")],
      [("What theorem relates closed-surface flux and divergence?", "The Divergence Theorem"), ("What orientation is positive?", "outward"), ("What kind of surface is required?", "closed"), ("What kind of integral appears on the right?", "a triple integral"), ("What field operation appears?", "divergence"), ("What solid is enclosed by a closed surface?", "a volume region")],
      "Use the Divergence Theorem for F=<x,y,z> over the outward unit sphere.", [("Compute divergence", "What is div F?", "3"), ("Find enclosed volume", "What is the unit-ball volume?", "4pi/3"), ("Accumulate", "What is the outward flux?", "4pi")],
      [("What operation appears inside the volume integral in the Divergence Theorem?", ["Divergence", "Curl", "Gradient only", "Arc length"], "Divergence", "The theorem accumulates div F over the enclosed volume."), ("What orientation is required for the Divergence Theorem?", ["Outward", "Counterclockwise", "Upward only", "Inward"], "Outward", "The theorem uses the outward normal convention on a closed surface."), ("What is div F for F=<x,y,z>?", ["3", "<1,1,1>", "x+y+z", "0"], "3", "Each component contributes one partial derivative."), ("What is the outward flux of a constant vector field through any closed surface?", ["0", "Always positive", "The surface area", "The enclosed volume"], "0", "A constant field has zero divergence, so its total closed flux is zero.")],
      [("For F=<2x,2y,2z>, what is div F?", ["6", "2", "<2,2,2>", "0"], "6", "Differentiate each component with respect to its matching coordinate."), ("The Divergence Theorem applies directly to which surface?", ["The closed boundary of a solid", "An open disk", "A line segment", "A level curve"], "The closed boundary of a solid", "The surface must enclose a three-dimensional region."), ("If div F=0 throughout a solid, what is the net outward flux?", ["0", "The volume", "Always positive", "The surface area"], "0", "The triple integral of zero is zero."), ("Which prerequisite supports the right side of the Divergence Theorem?", ["Triple-integral setup", "Only line-integral setup", "One-variable limits", "Series tests"], "Triple-integral setup", "The right side integrates divergence over a volume region.")]),
]


def quiz(topic_data, kind):
    questions = []
    tier = "easy" if kind == "focused-practice" else "hard"
    dimensions = ["representationTransfer", "auxiliaryTechnique"] if tier == "easy" else ["representationTransfer", "modelOrDerivation", "methodSelection"]
    for i, (prompt, choices, answer, solution) in enumerate(topic_data["focused" if kind == "focused-practice" else "mastery"], 1):
        options = [{"id": "a", "text": choices[0]}]
        for j, choice in enumerate(choices[1:], 1):
            options.append({"id": chr(97 + j), "text": choice, "issueSignals": signal(topic_data["signal"] if j < 3 else "sign-error")})
        questions.append({"id": f"q{i:03d}", "type": "multipleChoice", "prompt": prompt, "choices": options,
                          "answer": {"choiceId": "a"}, "issueSignals": signal(topic_data["signal"]),
                          "difficultyDimensions": dimensions, "difficultyEvidence": "Requires matching a vector-calculus representation to the governing relation and orientation.",
                          "explanation": expl(solution, topic_data["remediation"], prompt, answer,
                                              [(option["id"], option["text"]) for option in options[1:]])})
    goal, activity = ("practice", "focusedPractice") if kind == "focused-practice" else ("evaluate", "masteryCheck")
    return {"schemaVersion": 1, "id": f"{topic_data['slug']}-{kind}-s2c", "title": f"{topic_data['title']}: {'Focused Practice' if kind == 'focused-practice' else 'Mastery Check'}", "assessmentType": "quiz", "categoryId": "calculus-3", "topicId": topic_data["id"], "modeDefault": "practice", "randomizeQuestions": True, "skills": [topic_data["slug"]], "navigation": {"learningGoal": goal, "activityType": activity, "tags": ["calculus-3", topic_data["id"], topic_data["slug"], kind]}, "authoring": {"sourcePacketId": f"packet-calc3-{topic_data['slug']}-v1", "difficultyTier": tier, "visualRequirement": "required", "visualRationale": "Questions reinforce the topic's original vector-calculus representation.", "exceptionReason": "Four distinct source-grounded items form this focused bank."}, "questions": questions}


def blueprint(topic_data, kind):
    tier = "easy" if kind == "focused-practice" else "hard"
    dimensions = ["representationTransfer", "auxiliaryTechnique"] if tier == "easy" else ["representationTransfer", "modelOrDerivation", "methodSelection"]
    bank = topic_data["focused" if kind == "focused-practice" else "mastery"]
    return {"schemaVersion": 1, "assessmentId": f"{topic_data['slug']}-{kind}-s2c", "categoryId": "calculus-3", "topicId": topic_data["id"], "sourceId": SOURCE, "packetId": f"packet-calc3-{topic_data['slug']}-v1", "reviewState": "approved", "blueprints": [{"questionId": f"q{i:03d}", "objectiveId": topic_data["objective"], "sourceChunks": [f"chunk-{topic_data['chunks'][0]:04d}"], "questionType": "multipleChoice", "givens": question[0], "unknown": "Select the mathematically valid conclusion.", "representationRequirement": f"Original {topic_data['visual']} visual when spatial orientation is relevant.", "governingPrinciple": topic_data["sections"][0][0], "methodSteps": ["Identify the field, curve, surface, or region.", "Apply the governing relation.", "Check direction, orientation, and result type."], "likelyMisconception": "Using a familiar theorem or orientation with the wrong geometric object.", "issueSignal": topic_data["signal"], "verificationMethod": "Independent component calculation, integral evaluation, or orientation check.", "difficultyTier": tier, "difficultyDimensions": dimensions, "subjectDifficultyTags": ["representation", "orientation"], "difficultyEvidence": "Requires selecting the correct vector-calculus relation and checking its geometry.", "prerequisiteObjectives": ["calc3-ready-prior-skills"], "extensionObjectives": [topic_data["objective"]], "semanticVariationAxes": ["representation", "unknown", "governing relation"], "reasoningSignature": f"{topic_data['slug']}-{kind}-{i}", "reviewState": "approved"} for i, question in enumerate(bank, 1)]}


def main():
    for data in TOPICS:
        for name, builder in [("concept-lesson", lesson), ("recall", recall), ("worked-example", worked)]:
            write_yaml(ASSESSMENTS / f"{data['slug']}-{name}-s2c.yaml", builder(data))
        for kind in ("focused-practice", "mastery-check"):
            write_yaml(ASSESSMENTS / f"{data['slug']}-{kind}-s2c.yaml", quiz(data, kind))
            write_yaml(BLUEPRINTS / f"{data['slug']}-{kind}-blueprints-s2c.yaml", blueprint(data, kind))
        (PACKETS / f"packet-calc3-{data['slug']}-v1.json").write_text(json.dumps(packet(data), indent=2) + "\n", encoding="utf-8")
        MEDIA.mkdir(parents=True, exist_ok=True)
        (MEDIA / f"{data['visual']}.svg").write_text(svg(data), encoding="utf-8")


if __name__ == "__main__":
    main()
