"""Generate the Calc 3 Multivariable Derivatives and Optimization assessment set."""
from pathlib import Path
import json
from generate_calc3_spatial_vectors_motion import ASSESSMENTS, PACKETS, BLUEPRINTS, MEDIA, SOURCE, write_yaml, lesson, recall, worked, quiz, packet, blueprint, svg

def topic(id, slug, title, objective, first, last, signal, remediation, visual, sections, rec, problem, steps, questions):
    return {"id":id,"slug":slug,"title":title,"objective":objective,"chunks":list(range(first,last+1)),"signal":signal,"remediation":remediation,"visual":visual,"sections":sections,"recall":rec,"worked":problem,"worked_steps":steps,"questions":questions}

TOPICS=[
topic("calc3-functions-of-several-variables","functions-of-several-variables","Functions of Several Variables","calc3-multivariable-representations",2430,2455,"domain-range-misidentified","Calculus 1 → Sets, Sequences, and Functions","multivariable-functions",
[("Inputs form ordered pairs","A function of two variables assigns one output to each permitted pair $(x,y)$."),("Domains are regions","Restrictions on square roots, denominators, and logarithms produce regions rather than intervals."),("Level curves organize a surface","A level curve keeps $f(x,y)$ fixed while x and y vary.")],
[("For $f(x,y)=x+y$, find $f(2,3).","5"),("What does a level curve keep fixed?","the function value"),("What is the graph of $z=f(x,y)$?","a surface"),("What is the domain condition for $\sqrt{4-x-y}$?","x+y<=4"),("What is a contour map?","a plot of level curves"),("How many inputs does $f(x,y)$ use?","two")],
"Find the domain of $f(x,y)=\sqrt{9-x^2-y^2}$.",[("Set the radicand condition","What inequality is required?","$x^2+y^2\le9$"),("Name the region","What planar region satisfies it?","The disk of radius 3 centered at the origin."),("Interpret the graph","What part of a sphere is represented?","The upper hemisphere.")],
[("What is the domain of $f(x,y)=\ln(x-y)$?",["$x>y$","$x\ge y$","all pairs","$x<y$"],"$x>y$","A real logarithm needs a strictly positive argument."),("What does $f(x,y)=4$ describe on a graph?",["A horizontal plane","A vertical line","A circle","A single point"],"A horizontal plane","The output z is fixed while x and y vary."),("Which is a level curve of $f(x,y)=x^2+y^2$ at value 4?",["$x^2+y^2=4$","$x+y=4$","$z=4$","$x^2-y^2=4$"],"$x^2+y^2=4$","Set the function equal to the specified constant."),("Find $f(1,-2)$ for $f(x,y)=x^2+3y$.",["$-5$","$7$","$1$","$-1$"],"$-5$","Substitute both coordinates into the same function.")]),
topic("calc3-multivariable-limits-continuity","multivariable-limits-continuity","Multivariable Limits and Continuity","calc3-multivariable-limits",2456,2508,"mathematical-translation-error","Calculus 1 → The Derivative","multivariable-limits",
[("Approach from every direction","A two-variable limit exists only if every path approaching the point produces one common value."),("One path can disprove existence","Two valid paths with different limiting values prove the limit does not exist."),("Continuity combines three facts","The function value, limit, and limiting expression must agree.")],
[("What must agree for a multivariable limit to exist?","all approach paths"),("What can two paths with different limits prove?","the limit does not exist"),("What are level curves useful for near a point?","visualizing behavior"),("What is continuity at a point?","limit equals function value"),("Can one path prove a limit exists?","no"),("What point is approached in a limit?","the target point")],
"Determine whether $f(x,y)=\frac{x^2-y^2}{x^2+y^2}$ has a limit at $(0,0)$.",[("Test one path","What does $f(x,0)$ approach?","1"),("Test another path","What does $f(0,y)$ approach?","$-1$"),("Conclude","Does the full limit exist?","No; the paths disagree.")],
[("If two paths toward $(0,0)$ give 1 and -1, what follows?",["The limit does not exist","The limit is 0","The limit is 1","The limit is -1"],"The limit does not exist","A common limit cannot have two values."),("Which statement is required for continuity at $(a,b)$?",["$\lim_{(x,y)\to(a,b)}f(x,y)=f(a,b)$","Only $f(a,b)$ exists","Only one path has a limit","The graph is flat"],"$\lim_{(x,y)\to(a,b)}f(x,y)=f(a,b)$","Continuity matches the limit and the assigned value."),("Along $y=x$, what is $\frac{x^2-y^2}{x^2+y^2}$ for nonzero x?",["0","1","-1","undefined"],"0","The numerator becomes zero on this path."),("What is the main limitation of checking one path?",["It cannot establish all-path agreement","It always proves nonexistence","It changes the target point","It removes denominators"],"It cannot establish all-path agreement","Existence requires checking the full approach, not a sample.")]),
topic("calc3-partial-derivatives","partial-derivatives","Partial Derivatives","calc3-partial-rates",2509,2532,"product-rule-misapplied","Calculus 1 → Classical Theorems of Differential Calculus","partial-derivatives",
[("Hold the other input fixed","$f_x$ differentiates in x while treating y as a constant; $f_y$ reverses the roles."),("Partials are rates","Each first partial gives a slice slope of the surface."),("Higher partials measure change","Second partials differentiate a first partial and support later local classification.")],
[("What is held constant in $f_x$?","y"),("Find $f_x$ for $x^2y$.","2xy"),("Find $f_y$ for $x^2y$.","x^2"),("What does $f_{xy}$ mean?","differentiate fx with respect to y"),("What kind of quantity is $f_x$?","a rate of change"),("How many first partial derivatives does f(x,y) have?","two")],
"For $f(x,y)=x^2y+3y^2$, find $f_x$ and $f_y$.",[("Differentiate in x","What is $f_x$?","$2xy$"),("Differentiate in y","What is $f_y$?","$x^2+6y$"),("Interpret the difference","What changes between these calculations?","Which variable is held constant.")],
[("Find $f_x$ for $f(x,y)=x^3y+2y$.",["$3x^2y$","$x^3+2$","$3x^2y+2$","$x^2y$"],"$3x^2y$","Treat y and the $2y$ term as constants."),("Find $f_y$ for $f(x,y)=x^2y^3$.",["$3x^2y^2$","$2xy^3$","$x^2y^2$","$3xy^2$"],"$3x^2y^2$","Treat x squared as a constant coefficient."),("What does $f_y(a,b)$ describe?",["The y-direction slice slope at $(a,b)$","The function value only","A vector normal","An x-intercept"],"The y-direction slice slope at $(a,b)$","It measures rate as y changes while x is fixed."),("If $f=x^2+y^2$, what is $f_{xy}$?",["0","2","$2x$","$2y$"],"0","$f_x=2x$, which has no y dependence.")]),
topic("calc3-tangent-planes-linearization","tangent-planes-linearization","Tangent Planes and Linearization","calc3-linear-approximation",2533,2552,"algebraic-simplification-error","Calculus 1 → The Derivative","tangent-planes",
[("A surface has a local plane","Differentiability lets a tangent plane model a surface near a chosen point."),("Partials determine tilt","The x and y partial derivatives are the plane's directional slopes."),("Linearization is local","A linear approximation is reliable near its base point, not necessarily far away.")],
[("What object approximates a differentiable surface locally?","tangent plane"),("What is L(a,b)?","f(a,b)"),("What appears with x-a in a linearization?","fx(a,b)"),("What appears with y-b?","fy(a,b)"),("Where is linearization most accurate?","near the base point"),("What does dz approximate?","the local change in z")],
"Find the tangent plane to $z=x^2+y^2$ at $(1,2,5)$.",[("Find partials","What are $f_x$ and $f_y$?","$2x$ and $2y$"),("Evaluate slopes","What are the slopes at $(1,2)$?","2 and 4"),("Assemble plane","Which equation is correct?","$z-5=2(x-1)+4(y-2)$")],
[("What is the tangent plane form at $(a,b,f(a,b))$?",["$z-f(a,b)=f_x(a,b)(x-a)+f_y(a,b)(y-b)$","$z=f_xx+f_yy$","$z=f(a,b)$ only","$z=f_x+f_y$"],"$z-f(a,b)=f_x(a,b)(x-a)+f_y(a,b)(y-b)$","The plane matches the value and both slice slopes."),("For $f=x^2+y^2$, what is $f_x(1,2)$?",["2","4","5","1"],"2","Differentiate in x, then evaluate."),("Why is a linearization local?",["Curvature creates increasing error farther away","Planes have no equations","Partial derivatives vanish","Coordinates cannot change"],"Curvature creates increasing error farther away","The tangent plane matches first-order behavior only."),("For $f=x+y$, what is the tangent plane?",["$z=x+y$","$z=x^2+y^2$","$z=0$","$z=x-y$"],"$z=x+y$","A linear function equals its own tangent plane.")]),
topic("calc3-multivariable-chain-rule","multivariable-chain-rule","The Multivariable Chain Rule","calc3-chain-rule",2553,2575,"chain-rule-missed","Calculus 1 → Classical Theorems of Differential Calculus","multivariable-chain-rule",
[("Track dependencies","When x and y depend on t, a change in t reaches z through every dependency path."),("Add path contributions","The total derivative is the sum of each partial derivative times its corresponding input rate."),("Keep variables distinct","Evaluate partials and component rates at compatible input values.")],
[("If z=f(x,y), what does dz/dt combine?","fx dx/dt plus fy dy/dt"),("What diagram helps chain-rule setup?","dependency diagram"),("What rule handles a composition?","chain rule"),("What is an indirect dependency?","a variable changes through another variable"),("How are contributions combined?","added"),("What must match in evaluation?","the same input values")],
"If $z=x^2+y^2$, $x=t$, and $y=t^2$, find $dz/dt$ at $t=1$.",[("Find partials","What are $z_x$ and $z_y$?","$2x$ and $2y$"),("Find component rates","What are dx/dt and dy/dt?","1 and $2t$"),("Combine at t=1","What is dz/dt?","6")],
[("If $z=f(x,y)$ and x,y depend on t, which formula is correct?",["$dz/dt=f_x dx/dt+f_y dy/dt$","$dz/dt=f_x+f_y$","$dz/dt=dx/dt+dy/dt$","$dz/dt=f_{xy}$"],"$dz/dt=f_x dx/dt+f_y dy/dt$","Each dependency path contributes a rate product."),("For $z=x+y$ with x=t and y=t^2, what is dz/dt at t=2?",["5","3","4","6"],"5","Differentiate $t+t^2$ or use the chain rule."),("What mistake omits a chain-rule contribution?",["Ignoring one changing input","Adding partials","Using a dependency diagram","Evaluating at t"],"Ignoring one changing input","Every changing input creates a path contribution."),("If y is constant, what is dy/dt?",["0","1","y","undefined"],"0","A constant has zero rate of change.")]),
topic("calc3-directional-derivatives-gradients","directional-derivatives-gradients","Directional Derivatives and Gradients","calc3-gradient-geometry",2576,2601,"vector-component-resolution-error","Trigonometry → Unit Circle Trigonometry","gradients",
[("Directions must be unit vectors","A directional derivative uses a unit direction so its size is not distorted by the vector length."),("Gradient collects partials","$\nabla f=\langle f_x,f_y\rangle$ points toward steepest increase."),("Level curves reveal geometry","The gradient is perpendicular to a level curve where it is nonzero.")],
[("What is $\nabla f$ in two variables?","(fx,fy)"),("What length must a direction vector have?","1"),("What direction maximizes increase?","the gradient direction"),("What is the maximum rate?","magnitude of gradient"),("What is gradient relative to a level curve?","perpendicular"),("What operation gives directional derivative?","gradient dot unit vector")],
"For $f(x,y)=x^2+y^2$, find the directional derivative at $(1,2)$ toward $\langle3,4\rangle$.",[("Find the gradient","What is $\nabla f(1,2)$?","$\langle2,4\rangle$"),("Normalize direction","What unit vector points toward $\langle3,4\rangle$?","$\langle3/5,4/5\rangle$"),("Take dot product","What is the directional derivative?","$22/5$")],
[("What is $\nabla(x^2+y^2)$?",["$\langle2x,2y\rangle$","$\langle x,y\rangle$","$x^2+y^2$","$\langle2,2\rangle$"],"$\langle2x,2y\rangle$","Take each first partial derivative."),("Why normalize a direction vector?",["To measure change per unit distance","To make the gradient zero","To remove coordinates","To avoid partial derivatives"],"To measure change per unit distance","Directional derivatives are rates along unit distance."),("Which direction gives maximum increase?",["The gradient direction","The negative gradient","Any level-curve tangent","The zero vector"],"The gradient direction","The gradient points steepest uphill."),("What is $D_{\mathbf u}f$?",["$\nabla f\cdot\mathbf u$ for unit u","$f_x+f_y$","$|f|$","$\mathbf u\times\nabla f$"],"$\nabla f\cdot\mathbf u$ for unit u","The dot product extracts the component of gradient along u.")]),
topic("calc3-multivariable-optimization","multivariable-optimization","Multivariable Optimization and Lagrange Multipliers","calc3-constrained-extrema",2602,2674,"algebraic-simplification-error","Calculus 1 → Classical Theorems of Differential Calculus","multivariable-optimization",
[("Critical points start the search","Interior extrema occur where both first partial derivatives vanish or fail to exist."),("Second partials classify locally","The discriminant combines second partials to identify many local maxima, minima, and saddles."),("Constraints change the condition","Lagrange multipliers seek points where the objective gradient is parallel to the constraint gradient.")],
[("What equations identify an interior critical point?","fx=0 and fy=0"),("What does D=fxx fyy-fxy^2 classify?","local behavior at a critical point"),("What does D<0 indicate?","saddle point"),("What condition is used for Lagrange multipliers?","gradient f equals lambda gradient g"),("What is a constraint?","a required relationship among inputs"),("What must be compared after candidates?","objective values")],
"Find the constrained extrema of $f(x,y)=x+y$ subject to $x^2+y^2=1$.",[("Set gradient relation","What equation is required?","$\langle1,1\rangle=\lambda\langle2x,2y\rangle$"),("Use symmetry","What candidate directions result?","$x=y=\pm1/\sqrt2$"),("Compare values","What is the maximum?","$\sqrt2$")],
[("What is required at an interior differentiable critical point?",["$f_x=0$ and $f_y=0$","$f=0$","$f_{xy}=0$","$x=y$"],"$f_x=0$ and $f_y=0$","Both first-order directions must have zero rate."),("If D is negative at a critical point, what is it?",["A saddle point","A local minimum","A local maximum","An absolute maximum"],"A saddle point","Negative discriminant signals opposite curvature directions."),("What equation begins a Lagrange multiplier problem?",["$\nabla f=\lambda\nabla g$","$f=g$","$f_x=f_y$","$\nabla f=0$ only"],"$\nabla f=\lambda\nabla g$","At a constrained extremum the gradients are parallel."),("Why compare objective values at all candidates?",["To choose the requested extrema","To normalize a gradient","To make a path","To find a limit"],"To choose the requested extrema","Candidate equations alone do not identify largest or smallest values.")])
]

def main():
    for t in TOPICS:
        for name, build in [("concept-lesson",lesson),("recall",recall),("worked-example",worked)]: write_yaml(ASSESSMENTS/f"{t['slug']}-{name}-s2c.yaml",build(t))
        for kind in ["focused-practice","mastery-check"]:
            write_yaml(ASSESSMENTS/f"{t['slug']}-{kind}-s2c.yaml",quiz(t,kind))
            write_yaml(BLUEPRINTS/f"{t['slug']}-{kind}-blueprints-s2c.yaml",blueprint(t,kind))
        (PACKETS/f"packet-calc3-{t['slug']}-v1.json").write_text(json.dumps(packet(t),indent=2)+"\n",encoding="utf8")
        MEDIA.mkdir(parents=True,exist_ok=True); (MEDIA/f"{t['visual']}.svg").write_text(svg(t),encoding="utf8")
if __name__ == '__main__': main()
