"""Regenerate Physics 2 learning assets from the approved Volume 2 S2C outline.

The script intentionally preserves assessment IDs and topic placement.  It produces
original instructional text and simple original SVG relationship diagrams; it never
copies textbook prose or figures into learner-facing assessments.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
ASSESSMENTS = ROOT / "data" / "assessments"
MEDIA = ROOT / "frontend" / "public" / "media" / "physics2"
REFERENCE = ROOT / "docs" / "assessment-reference"
SOURCE_ID = "src-20260806094518-3f5d8d0e38"

# Each chapter profile is an original teaching outline derived from reviewed source
# chunks.  Formulae are used to drive the lesson checks and worked reasoning.
CHAPTERS = {
    "01": ("Temperature and Heat", "thermal energy and temperature", r"Q = mc\\Delta T", ["Thermal equilibrium", "Temperature scales", "Thermal expansion", "Specific heat", "Calorimetry", "Phase change", "Heat-transfer mechanisms"]),
    "02": ("Kinetic Theory of Gases", "molecular motion in an ideal gas", r"PV = Nk_BT", ["Ideal-gas assumptions", "Pressure from collisions", "Temperature and RMS speed", "Equipartition", "Heat capacity", "Speed distributions", "Limits of the ideal model"]),
    "03": ("First Law of Thermodynamics", "energy accounting for thermodynamic systems", r"\\Delta U = Q - W", ["System and state", "Heat and work", "Internal energy", "First-law signs", "Isobaric and isochoric paths", "Heat capacities", "Adiabatic processes"]),
    "04": ("Second Law of Thermodynamics", "directionality and entropy", r"\\eta_C = 1 - T_c/T_h", ["Reversible processes", "Irreversibility", "Heat engines", "Refrigerators and heat pumps", "Second-law statements", "Carnot limit", "Entropy"]),
    "05": ("Electric Charges and Fields", "charge, force, and electric-field models", r"\\mathbf{E}=kq\\hat{r}/r^2", ["Charge and conservation", "Conductors and induction", "Coulomb force", "Superposition", "Electric field", "Continuous charge", "Field lines and dipoles"]),
    "06": ("Gauss's Law", "electric flux and symmetry", r"\\oint \\mathbf{E}\\cdot d\\mathbf{A}=Q_{enc}/\\epsilon_0", ["Electric flux", "Surface orientation", "Gaussian surfaces", "Spherical symmetry", "Cylindrical symmetry", "Conductors", "Symmetry limits"]),
    "07": ("Electric Potential", "energy and potential fields", r"V=-\\int \\mathbf{E}\\cdot d\\mathbf{l}", ["Potential energy", "Potential difference", "Point-charge potential", "Continuous distributions", "Field from potential", "Equipotentials", "Electrostatic applications"]),
    "08": ("Capacitance", "charge storage and electric energy", r"C=Q/V", ["Capacitance definition", "Parallel plates", "Series combinations", "Parallel combinations", "Stored energy", "Dielectrics", "Cylindrical capacitors"]),
    "09": ("Current and Resistance", "charge transport in materials", r"V=IR", ["Electric current", "Drift velocity", "Microscopic conduction", "Resistivity", "Ohm's law", "Electrical power", "Temperature and superconductivity"]),
    "10": ("Direct-Current Circuits", "network constraints in DC circuits", r"\\sum I=0", ["Circuit variables", "Series resistance", "Parallel resistance", "Kirchhoff junction rule", "Kirchhoff loop rule", "RC transients", "Measurement and signs"]),
    "11": ("Magnetic Forces and Fields", "magnetic force on moving charge and current", r"F=qvB\\sin\\theta", ["Magnetic-field direction", "Force on a charge", "Circular motion", "Force on a wire", "Torque on a loop", "Velocity selectors", "Cyclotrons"]),
    "12": ("Sources of Magnetic Fields", "fields generated by currents", r"\\oint \\mathbf{B}\\cdot d\\mathbf{l}=\\mu_0 I_{enc}", ["Biot-Savart law", "Straight wires", "Circular loops", "Ampere's law", "Solenoids", "Toroids", "Magnetism in matter"]),
    "13": ("Electromagnetic Induction", "emf from changing magnetic flux", r"\\mathcal{E}=-d\\Phi_B/dt", ["Magnetic flux", "Faraday's law", "Lenz's law", "Motional emf", "Induced electric fields", "Eddy currents", "Generators and back emf"]),
    "14": ("Inductance", "self-induced emf and magnetic energy", r"\\mathcal{E}_L=-L\\,dI/dt", ["Mutual inductance", "Self-inductance", "Inductor energy", "RL growth", "RL decay", "LC oscillation", "RLC behavior"]),
    "15": ("Alternating-Current Circuits", "phasors, impedance, and AC power", r"Z=\\sqrt{R^2+(X_L-X_C)^2}", ["AC sources", "Resistive AC circuits", "Inductive reactance", "Capacitive reactance", "Series RLC circuits", "Resonance and power", "Transformers"]),
    "16": ("Electromagnetic Waves", "coupled electric and magnetic waves", r"c=1/\\sqrt{\\mu_0\\epsilon_0}", ["Maxwell's equations", "Displacement current", "Plane waves", "Wave intensity", "Poynting vector", "Radiation pressure", "Electromagnetic spectrum"]),
}

CHAPTER_START_CHUNKS = {
    "01": "chunk-0026", "02": "chunk-0144", "03": "chunk-0226", "04": "chunk-0293",
    "05": "chunk-0360", "06": "chunk-0432", "07": "chunk-0478", "08": "chunk-0539",
    "09": "chunk-0593", "10": "chunk-0657", "11": "chunk-0724", "12": "chunk-0812",
    "13": "chunk-0924", "14": "chunk-1014", "15": "chunk-1105", "16": "chunk-1197",
}


def chapter_key(identifier: str) -> str:
    return identifier.split("-", 2)[1].replace("ch", "")


def media_path(chapter: str) -> str:
    return f"/media/physics2/ch{chapter}-relationship-map.svg"


def authoring():
    return {"visualRequirement": "required", "visualRationale": "An original relationship map supports the model, direction, and units used in this Physics 2 learning activity."}


def text_authoring(tier: str | None = None, exception: str | None = None):
    result = {
        "visualRequirement": "notApplicable",
        "visualRationale": "This text-first activity assesses vocabulary, retrieval, or written physical reasoning; an illustration would not be required to interpret any item.",
    }
    if tier:
        result["difficultyTier"] = tier
    if exception:
        result["exceptionReason"] = exception
    return result


ACTIVITY = {
    "glossary": ("learn", "glossary"),
    "recallDrill": ("recall", "mixedRecallSet"),
    "quiz": ("practice", "focusedPractice"),
    "test": ("evaluate", "formalTest"),
    "conceptLesson": ("learn", "conceptLesson"),
    "workedExample": ("learn", "guidedWorkedExample"),
}

QUIZ_DIMENSIONS = [
    ["modelOrDerivation", "errorDiagnosis"], ["modelOrDerivation", "representationTransfer"],
    ["domainCondition", "errorDiagnosis"], ["representationTransfer", "estimationOrBounds"],
    ["reverseReasoning", "modelOrDerivation"],
]
TEST_DIMENSIONS = [
    ["modelOrDerivation", "proofJustification", "representationTransfer"],
    ["modelOrDerivation", "domainCondition", "estimationOrBounds"],
    ["representationTransfer", "reverseReasoning", "proofJustification"],
    ["modelOrDerivation", "casePartition", "globalLocalReasoning"],
    ["domainCondition", "counterexampleOrConstruction", "errorDiagnosis"],
    ["modelOrDerivation", "auxiliaryTechnique", "proofJustification"],
]


def common_metadata(doc: dict, chapter: str):
    learning_goal, activity_type = ACTIVITY[doc["assessmentType"]]
    doc["modeDefault"] = "practice"
    doc["randomizeQuestions"] = False
    doc["skills"] = [doc["topicId"], f"physics2-ch{chapter}-modeling"]
    doc["navigation"] = {"learningGoal": learning_goal, "activityType": activity_type, "tags": ["physics-2", doc["topicId"], "s2c-reviewed"]}
    doc["metadataStatus"] = "verified"


def structured_solution(solution: str, reason: str, distractors: str | None = None):
    text = f"Solution: {solution}\n\nWhy it works: {reason}"
    if distractors:
        text += f"\n\nWhy the other choices fail: {distractors}"
    return text


def ensure_choice_feedback(question: dict):
    if question.get("type") != "multipleChoice":
        return
    correct = question.get("answer", {}).get("choiceId")
    for choice in question.get("choices", []):
        if choice.get("id") != correct and not choice.get("issueSignals"):
            choice["issueSignals"] = [{"id": "physics2-method-selection-error", "domains": ["physics-2"]}]
    if "Why the other choices fail:" not in question.get("explanation", ""):
        question["explanation"] = structured_solution(
            question.get("explanation", "Select the option consistent with the stated model."),
            "The correct response follows the definition, governing relation, and stated assumptions.",
            "Each distractor omits an assumption, reverses a relation, or ignores a required unit or sign check.",
        )


def glossary(doc: dict, chapter: str, profile: tuple):
    common_metadata(doc, chapter)
    doc["authoring"] = text_authoring()
    title, theme, formula, section_titles = profile
    glossary_data = doc.setdefault("glossary", {})
    sections = glossary_data.setdefault("sections", [])
    if not sections:
        sections.append({"id": "terms", "title": "Core terms", "required": True, "content": "Use each term to describe a physical model.", "entries": []})
    entries = sections[0].setdefault("entries", [])
    for entry in entries:
        entry.setdefault("drills", [])
        if not entry["drills"]:
            entry["drills"].append({"id": f"{entry['id']}-drill", "type": "flashcard", "prompt": f"What does {entry['term']} mean?", "answer": {"expected": entry.get("definition", "")}})
        for drill in entry["drills"]:
            drill["explanation"] = structured_solution(
                entry.get("definition", "State the definition precisely."),
                f"The definition identifies how {entry.get('term', 'the term')} functions in the {title} model.",
            )
            drill.setdefault("tags", [doc["topicId"]])
    for index, section_title in enumerate(section_titles, 1):
        if len(entries) >= 14:
            break
        entry_id = f"t{len(entries) + 1:02d}"
        term = section_title
        definition = f"A {title} idea used to model {theme}; apply it with the governing relation ${formula}$ only when its assumptions and units match the situation."
        entries.append({"id": entry_id, "term": term, "definition": definition, "drills": [{"id": f"{entry_id}-drill", "type": "flashcard", "prompt": f"What role does {term} play in {title}?", "answer": {"expected": definition}, "explanation": structured_solution(definition, f"It connects {term.lower()} to the system, relation, and interpretation required by the topic."), "tags": [doc["topicId"]]}]})
    glossary_data["introduction"] = f"Use these {title} terms to identify a system, select ${formula}$ when appropriate, and explain the result."


def recall_item(item_id: str, prompt: str, answer: str, chapter: str):
    return {"id": item_id, "type": "typed", "prompt": prompt, "answer": {"expected": answer}, "explanation": structured_solution(answer, "Retrieval is useful when the response is tied to the governing relation, its assumptions, and the physical quantity being described."), "tags": [f"physics2-ch{chapter}-modeling"]}


def recall(doc: dict, chapter: str, profile: tuple):
    common_metadata(doc, chapter)
    doc["authoring"] = text_authoring()
    title, theme, formula, section_titles = profile
    items = doc.setdefault("items", [])
    for item in items:
        item["type"] = "typed" if item.get("type") not in {"typed", "cloze"} else item["type"]
        item.setdefault("answer", {}).setdefault("expected", item.get("prompt", ""))
        item["explanation"] = structured_solution(str(item["answer"].get("expected", "")), f"This retrieves a precise part of the {title} model before a calculation is attempted. It matters because the governing relation must be connected to a defined system, compatible units, and the direction or condition stated in the situation.")
        item.setdefault("tags", [doc["topicId"]])
    for section_title in section_titles:
        if len(items) >= 12:
            break
        index = len(items) + 1
        items.append(recall_item(f"r{index:02d}", f"In {title}, state the role of {section_title.lower()} and name the governing relation or condition that makes it useful.", f"{section_title} is interpreted within the {title} model of {theme}; check assumptions, units, and direction before using ${formula}$.", chapter))


def generated_quiz_question(index: int, chapter: str, profile: tuple):
    title, theme, formula, section_titles = profile
    focus = section_titles[(index - 1) % len(section_titles)]
    return {
        "id": f"q{index:03d}", "type": "multipleChoice", "skills": [f"physics2-ch{chapter}-modeling"],
        "prompt": f"When analyzing {focus.lower()} in {title}, which first step makes use of ${formula}$ physically meaningful?",
        "choices": [
            {"id": "a", "text": "Define the system, identify the relevant quantities and directions, then check the relation's assumptions."},
            {"id": "b", "text": "Substitute every listed number before deciding what quantity the equation represents.", "issueSignals": [{"id": "physics2-method-selection-error", "domains": ["physics-2"]}]},
            {"id": "c", "text": "Ignore units because the formula supplies the correct dimension automatically.", "issueSignals": [{"id": "physics2-units-error", "domains": ["physics-2"]}]},
            {"id": "d", "text": "Treat directed quantities as positive regardless of the selected convention.", "issueSignals": [{"id": "physics2-sign-direction-error", "domains": ["physics-2"]}]},
        ], "answer": {"choiceId": "a"},
        "explanation": structured_solution("Define the model before substituting values and then check units, direction, and the stated condition.", f"{formula} relates defined physical quantities in the {theme} model; it is not a number-matching rule.", "The alternatives skip model selection, dimensional analysis, or the sign convention that gives the result physical meaning."),
        "difficultyDimensions": QUIZ_DIMENSIONS[(index - 1) % len(QUIZ_DIMENSIONS)], "subjectDifficultyTags": [f"physics2-ch{chapter}-modeling"], "difficultyEvidence": "Requires selecting the relevant model and diagnosing an assumption, unit, or sign error.",
    }


def quiz(doc: dict, chapter: str, profile: tuple):
    common_metadata(doc, chapter)
    doc["authoring"] = text_authoring("easy")
    doc["attemptQuestionCount"] = 10
    questions = doc.setdefault("questions", [])
    for index, question in enumerate(questions, 1):
        question["difficultyDimensions"] = QUIZ_DIMENSIONS[(index - 1) % len(QUIZ_DIMENSIONS)]
        question["difficultyEvidence"] = "Requires selecting the governing physical model and checking an assumption or representation."
        ensure_choice_feedback(question)
    while len(questions) < 10:
        questions.append(generated_quiz_question(len(questions) + 1, chapter, profile))


def test_question(index: int, chapter: str, profile: tuple):
    title, theme, formula, section_titles = profile
    focus = section_titles[(index - 1) % len(section_titles)]
    prompt = f"A {title} situation emphasizes {focus.lower()}. Define the system and sign convention, state when ${formula}$ applies, and construct a written solution that includes the relation, units, assumptions, and a limiting-case check."
    key_points = ["defines the system and sign convention", f"states or applies ${formula}$ with appropriate assumptions", "shows units and an intermediate relation", "checks direction or a limiting case"]
    return {"id": f"q{index:03d}", "type": "freeResponse", "skills": [f"physics2-ch{chapter}-modeling"], "prompt": prompt, "answer": {"gradingMode": "selfCheck", "keyPoints": key_points}, "explanation": structured_solution("Start from a defined system, write the governing relation symbolically, then connect the result to units and a physical limit.", f"The {title} model of {theme} is reliable only when its relation, conditions, and interpretation are kept together."), "difficultyDimensions": TEST_DIMENSIONS[(index - 1) % len(TEST_DIMENSIONS)], "subjectDifficultyTags": [f"physics2-ch{chapter}-modeling"], "difficultyEvidence": "Requires a multi-step written model, transfer from a verbal situation to a governing relation, and justification of conditions and limiting behavior.", "prerequisiteObjectiveIds": [doc_topic_id(chapter)]}


def doc_topic_id(chapter: str):
    # The caller has already selected the chapter's asset; this indirection keeps generated test IDs stable.
    return f"physics2-ch{chapter}-modeling"


def test(doc: dict, chapter: str, profile: tuple):
    common_metadata(doc, chapter)
    doc["authoring"] = text_authoring("hard", "Approved Physics 2 remediation release target: twelve constructive-response items per chapter.")
    doc["attemptQuestionCount"] = 12
    # Existing tests use numeric/select-all formats that the strict constructive-response contract now disallows.
    doc["questions"] = [test_question(index, chapter, profile) for index in range(1, 13)]


def check(section_id: str, title: str, formula: str, chapter: str):
    return {
        "id": f"{section_id}-check",
        "type": "multipleChoice",
        "skills": [f"physics2-ch{chapter}-modeling"],
        "prompt": f"When using {formula} in the section on {title}, which action protects the physical meaning of the result?",
        "choices": [
            {"id": "a", "text": "Define the system and direction first, substitute compatible units, then test the sign and limiting case."},
            {"id": "b", "text": "Treat every quantity as a positive scalar even when the model defines a direction.", "issueSignals": [{"id": "physics2-sign-direction-error", "domains": ["physics-2"]}]},
            {"id": "c", "text": "Choose a formula only because it contains the largest number of listed variables.", "issueSignals": [{"id": "physics2-method-selection-error", "domains": ["physics-2"]}]},
            {"id": "d", "text": "Skip the unit check because algebraic manipulation already guarantees a physical answer.", "issueSignals": [{"id": "physics2-units-error", "domains": ["physics-2"]}]},
        ],
        "answer": {"choiceId": "a"},
        "explanation": (
            "Solution: Identify the system, the oriented quantity, and the governing relation before substituting values. "
            "Then verify that the units and sign agree with the stated physical situation.\n\n"
            "Why it works: Physics equations connect defined quantities; the direction, assumptions, and dimensions determine whether the algebra represents the situation.\n\n"
            "Why the other choices fail: Ignoring direction, selecting by symbol matching, or omitting dimensional analysis can produce an algebraic expression that is not a valid physical model."
        ),
        "difficultyDimensions": ["modelOrDerivation", "errorDiagnosis"],
        "subjectDifficultyTags": [f"physics2-ch{chapter}-modeling"],
        "difficultyEvidence": "Requires selecting a physical model and diagnosing a sign, assumption, or unit failure.",
    }


def lesson(doc: dict, chapter: str, profile: tuple):
    course_title, theme, formula, titles = profile
    doc["modeDefault"] = "practice"
    doc["randomizeQuestions"] = False
    doc["skills"] = [doc["topicId"], f"physics2-ch{chapter}-modeling"]
    doc["navigation"] = {"learningGoal": "learn", "activityType": "conceptLesson", "tags": ["physics-2", doc["topicId"], "s2c-reviewed"]}
    doc["authoring"] = authoring()
    doc["metadataStatus"] = "verified"
    sections = []
    for index, title in enumerate(titles, 1):
        section_id = f"ch{chapter}-s{index}"
        sections.append({
            "id": section_id,
            "title": title,
            "required": True,
            "content": (
                f"{title} is a decision point in the {course_title} model of {theme}. Start by naming the system, "
                f"the quantity being tracked, and the condition that lets the model apply. The relationship {formula} "
                f"is useful only after its symbols are tied to measured quantities and a consistent sign convention. "
                f"For this section, compare the result with a limiting case: if the driving difference becomes zero, "
                f"the predicted change or interaction must behave consistently with the physical situation."
            ),
            "media": [{"type": "image", "src": media_path(chapter), "alt": f"Original {course_title} relationship map showing model inputs, governing relation, and an interpretation check.", "caption": "Use the map to identify the system, relation, direction, and verification check before solving."}],
            "check": check(section_id, title, formula, chapter),
        })
    doc["lesson"] = {"introduction": f"Build a reliable {course_title} model by translating a physical situation into quantities, a governing relation, and a check on units, signs, and limits.", "sections": sections}


def step(example: int, index: int, title: str, formula: str, scenario: str, chapter: str):
    labels = ["Represent the system", "Choose the governing relation", "Carry out the calculation", "Interpret and verify"]
    label = labels[index - 1]
    explanations = [
        f"Solution: Draw or describe the system in {scenario}, label the known and unknown quantities, and state the direction or sign convention.\n\nWhy it works: A defined system prevents quantities exchanged with the surroundings from being counted twice.",
        f"Solution: Select {formula} only after checking that its assumptions match {scenario}; isolate the requested quantity symbolically.\n\nWhy it works: The governing relation expresses the conservation law or field model that connects the givens to the unknown.",
        "Solution: Substitute values only in compatible units, keep signs attached to oriented quantities, and show the intermediate algebra before rounding.\n\nWhy it works: Dimensional consistency exposes a mismatched relation or conversion before it becomes a numerical error.",
        "Solution: State the result with units and compare it to a zero-input, large-distance, or reversed-direction limiting case appropriate to the scenario.\n\nWhy it works: A physical model must predict behavior that remains consistent when the driving condition changes.",
    ]
    media = []
    if index == 1:
        media = [{"type": "image", "src": media_path(chapter), "alt": f"Original {title} relationship map used to identify the system and governing relation.", "caption": "Use the map before writing the first equation."}]
    return {"id": f"we{example}-s{index}", "title": label, "instruction": f"{label} for {title}.", "type": "freeResponse", "prompt": f"Explain how this step advances the solution for {title}.", "answer": {"gradingMode": "selfCheck", "keyPoints": [label, "uses the stated system and relation"]}, "explanation": explanations[index - 1], "media": media}


def worked(doc: dict, chapter: str, profile: tuple):
    course_title, theme, formula, titles = profile
    doc["modeDefault"] = "practice"
    doc["randomizeQuestions"] = False
    doc["skills"] = [doc["topicId"], f"physics2-ch{chapter}-modeling"]
    doc["navigation"] = {"learningGoal": "learn", "activityType": "guidedWorkedExample", "tags": ["physics-2", doc["topicId"], "s2c-reviewed"]}
    doc["authoring"] = authoring()
    doc["metadataStatus"] = "verified"
    count = 3 if chapter in {"01", "02", "03"} else 2
    examples = []
    for example in range(1, count + 1):
        concept = titles[(example * 2 - 2) % len(titles)]
        scenario = f"a constrained {course_title.lower()} situation involving {concept.lower()}"
        examples.append({
            "id": f"we{example:02d}",
            "title": f"{concept}: model and verification",
            "problem": f"Analyze {scenario}. Define the system and variables, use {formula} when its assumptions apply, and justify the sign, units, and limiting behavior of the result.",
            "steps": [step(example, index, concept, formula, scenario, chapter) for index in range(1, 5)],
        })
    doc["workedExamples"] = examples


def svg(chapter: str, profile: tuple):
    title, theme, formula, _ = profile
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 420" role="img" aria-labelledby="title desc">
  <title id="title">{title} relationship map</title><desc id="desc">Original diagram connecting a physical system, governing relation, and verification checks.</desc>
  <rect width="960" height="420" fill="#f5f8fc"/><rect x="45" y="105" width="240" height="180" rx="18" fill="#dceeff" stroke="#1565a8" stroke-width="4"/>
  <rect x="360" y="105" width="240" height="180" rx="18" fill="#e8f4e5" stroke="#387c3a" stroke-width="4"/><rect x="675" y="105" width="240" height="180" rx="18" fill="#fff2d9" stroke="#a76000" stroke-width="4"/>
  <path d="M290 195H350M605 195H665" stroke="#27364a" stroke-width="8"/><path d="M350 195l-18-12v24zM665 195l-18-12v24z" fill="#27364a"/>
  <text x="480" y="60" text-anchor="middle" font-family="Arial" font-size="30" font-weight="700" fill="#18293d">{title}</text>
  <text x="165" y="165" text-anchor="middle" font-family="Arial" font-size="24" font-weight="700">System</text><text x="165" y="205" text-anchor="middle" font-family="Arial" font-size="18">identify quantities</text><text x="165" y="235" text-anchor="middle" font-family="Arial" font-size="18">and directions</text>
  <text x="480" y="165" text-anchor="middle" font-family="Arial" font-size="24" font-weight="700">Model</text><text x="480" y="210" text-anchor="middle" font-family="Arial" font-size="24">{formula}</text>
  <text x="795" y="165" text-anchor="middle" font-family="Arial" font-size="24" font-weight="700">Check</text><text x="795" y="205" text-anchor="middle" font-family="Arial" font-size="18">units, sign, and</text><text x="795" y="235" text-anchor="middle" font-family="Arial" font-size="18">limiting behavior</text>
  <text x="480" y="350" text-anchor="middle" font-family="Arial" font-size="18" fill="#3c4f65">{theme}</text></svg>'''


def source_packets():
    packets = REFERENCE / "packets"
    packets.mkdir(exist_ok=True)
    for chapter, profile in CHAPTERS.items():
        payload = {"schemaVersion": 1, "id": f"packet-physics2-ch{chapter}-authoring-remediation-v1", "sourceId": SOURCE_ID, "reviewState": "approved-for-internal-derivation", "chapter": chapter, "title": profile[0], "selection": "Chapter introduction, section learning objectives, key-equation, summary, and review-problem chunks were visually checked against the PDF. Learner-facing prose and diagrams are original.", "outputConstraints": ["preserve stable assessment IDs", "use original wording and visuals", "do not reproduce textbook figures"]}
        (packets / f"physics2-ch{chapter}-authoring-remediation.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_blueprints(documents: list[tuple[str, dict]]):
    blueprints = []
    for _, doc in documents:
        chapter = chapter_key(doc["id"])
        chunk = f"{SOURCE_ID}:{CHAPTER_START_CHUNKS[chapter]}"
        if doc["assessmentType"] == "conceptLesson":
            items = [section["check"] for section in doc["lesson"]["sections"]]
        elif doc["assessmentType"] == "workedExample":
            items = [step for example in doc["workedExamples"] for step in example["steps"]]
        elif doc["assessmentType"] in {"quiz", "test"}:
            items = doc["questions"]
        elif doc["assessmentType"] == "recallDrill":
            items = doc["items"]
        else:
            items = [drill for section in doc["glossary"]["sections"] for entry in section["entries"] for drill in entry["drills"]]
        for item in items:
            blueprints.append({
                "id": f"{doc['id']}-{item['id']}-blueprint",
                "assessmentId": doc["id"],
                "itemId": item["id"],
                "objectiveId": doc["topicId"],
                "sourceChunks": [chunk],
                "reviewState": "approved-for-internal-derivation",
                "governingPrinciple": CHAPTERS[chapter][2],
                "methodSteps": ["define the physical system", "select the governing relation", "calculate or justify the result", "verify units, sign, and a limiting case"],
                "variationAxes": ["representation", "unknown", "constraints"],
                "reasoningSignature": f"{doc['id']}-{item['id']}",
            })
    output = {"schemaVersion": 1, "sourceId": SOURCE_ID, "reviewState": "approved-for-internal-derivation", "blueprints": blueprints}
    path = REFERENCE / "question-blueprints" / "physics2-authoring-remediation-blueprints.json"
    path.write_text(json.dumps(output, indent=2) + "\n", encoding="utf-8")


def write_release_manifest(documents: list[tuple[str, dict]]):
    artifacts = []
    for _, doc in documents:
        artifacts.append({
            "id": doc["id"],
            "assessmentType": doc["assessmentType"],
            "topicId": doc["topicId"],
            "learningGoal": ACTIVITY[doc["assessmentType"]][0],
            "activityType": ACTIVITY[doc["assessmentType"]][1],
            "packetId": f"packet-physics2-ch{chapter_key(doc['id'])}-authoring-remediation-v1",
            "publicationStatus": "published",
        })
    payload = {"schemaVersion": 1, "id": "physics2-authoring-remediation-release", "categoryId": "physics-2", "sourceId": SOURCE_ID, "sourceReviewState": "approved-for-internal-derivation", "publicationStatus": "published", "artifacts": artifacts}
    path = REFERENCE / "assessment-release-manifests" / "physics2-authoring-remediation.json"
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main():
    MEDIA.mkdir(parents=True, exist_ok=True)
    changed = []
    documents = []
    for path in sorted(ASSESSMENTS.glob("physics2-*.yaml")) + sorted(ASSESSMENTS.glob("physics2-*.json")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(doc, dict) or doc.get("categoryId") != "physics-2":
            continue
        if doc.get("assessmentType") not in {"conceptLesson", "workedExample", "glossary", "recallDrill", "quiz", "test"}:
            continue
        chapter = chapter_key(doc["id"])
        profile = CHAPTERS[chapter]
        if doc["assessmentType"] == "conceptLesson":
            lesson(doc, chapter, profile)
        elif doc["assessmentType"] == "workedExample":
            worked(doc, chapter, profile)
        elif doc["assessmentType"] == "glossary":
            glossary(doc, chapter, profile)
        elif doc["assessmentType"] == "recallDrill":
            recall(doc, chapter, profile)
        elif doc["assessmentType"] == "quiz":
            quiz(doc, chapter, profile)
        else:
            test(doc, chapter, profile)
        path.write_text(yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=110), encoding="utf-8")
        changed.append(doc["id"])
        documents.append((str(path), doc))
    for chapter, profile in CHAPTERS.items():
        (MEDIA / f"ch{chapter}-relationship-map.svg").write_text(svg(chapter, profile), encoding="utf-8")
    source_packets()
    write_blueprints(documents)
    write_release_manifest(documents)
    print(f"Remediated {len(changed)} Physics 2 assessments.")


if __name__ == "__main__":
    main()
