from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, white
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import Paragraph
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import os, math

ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),'..')); OUT=os.path.join(ROOT,'output','pdf'); os.makedirs(OUT,exist_ok=True)
TEST=os.path.join(OUT,'Physics 2 Comprehensive Conceptual Test - Dense Version.pdf'); KEY=os.path.join(OUT,'Physics 2 Comprehensive Conceptual Test - Dense Version Detailed Answer Key.pdf')
W,H=letter; NAVY=HexColor('#17324D'); TEAL=HexColor('#137C8B'); GOLD=HexColor('#D9942A'); INK=HexColor('#203040'); PALE=HexColor('#EAF3F5'); CREAM=HexColor('#F7F2E8'); MUTED=HexColor('#667786')
pdfmetrics.registerFont(TTFont('Arial',r'C:\Windows\Fonts\arial.ttf')); pdfmetrics.registerFont(TTFont('Arial-Bold',r'C:\Windows\Fonts\arialbd.ttf'))
body=ParagraphStyle('body',fontName='Arial',fontSize=9.0,leading=11.0,textColor=INK); small=ParagraphStyle('small',fontName='Arial',fontSize=8.0,leading=9.5,textColor=INK); eq=ParagraphStyle('eq',fontName='Arial-Bold',fontSize=10.5,leading=13,textColor=NAVY,alignment=1); key=ParagraphStyle('key',fontName='Arial',fontSize=8.1,leading=9.7,textColor=INK)
def clean(s):
    for a,b in {'⃗':'','∮':'∫','∇':'grad','∂':'d','Δ':'d','−':'-','–':'-','—':'-','⁺':'+','⁻':'-','²':'2','³':'3','⁰':'0','₀':'<sub>0</sub>','₁':'<sub>1</sub>','₂':'<sub>2</sub>','₃':'<sub>3</sub>','₄':'<sub>4</sub>','₅':'<sub>5</sub>','₆':'<sub>6</sub>','ₑ':'<sub>e</sub>','ᵣ':'<sub>r</sub>','ᵢ':'<sub>i</sub>','ₓ':'<sub>x</sub>','ₜ':'<sub>t</sub>'}.items(): s=s.replace(a,b)
    return s.replace('r<R','r &lt; R').replace('r>R','r &gt; R').replace('n2>n1','n2 &gt; n1').replace('n2<n1','n2 &lt; n1').replace('v2<c/n1','v2 &lt; c/n1')
def p(c,s,x,y,w,style=body):
    q=Paragraph(clean(s),style); _,h=q.wrap(w,1000); q.drawOn(c,x,y-h); return h
def header(c,title,n,total,answers=False):
    c.setFillColor(NAVY); c.rect(0,H-.34*inch,W,.34*inch,0,1); c.setFillColor(white); c.setFont('Arial-Bold',8); c.drawString(.58*inch,H-.23*inch,'COMPREHENSIVE CONCEPTUAL PHYSICS 2' + (' | ANSWERS' if answers else ''))
    c.setFillColor(NAVY); c.setFont('Arial-Bold',15); c.drawString(.58*inch,H-.72*inch,title); c.setFillColor(TEAL); c.rect(.58*inch,H-.84*inch,.52*inch,.035*inch,0,1)
    c.setStrokeColor(HexColor('#D7E0E4')); c.line(.58*inch,.43*inch,W-.58*inch,.43*inch); c.setFillColor(MUTED); c.setFont('Arial',7); c.drawString(.58*inch,.25*inch,'Physics 2 | Dense Version'); c.drawRightString(W-.58*inch,.25*inch,f'{n} / {total}')
def box(c,x,y,w,h,fill=PALE): c.setFillColor(fill); c.roundRect(x,y,w,h,7,0,1)
def axes(c,x,y,w,h,xlab,ylab):
    c.setStrokeColor(TEAL); c.line(x,y,x+w,y); c.line(x,y,x,y+h); c.setFillColor(INK); c.setFont('Arial',8); c.drawString(x+w-12,y-13,xlab); c.drawString(x-14,y+h-3,ylab)
def field(c,x,y,w,h):
    c.setStrokeColor(NAVY); c.circle(x+w*.5,y+h*.5,13,1,0); c.setFillColor(GOLD); c.circle(x+w*.5,y+h*.5,6,0,1)
    c.setStrokeColor(TEAL)
    for a in range(0,360,45): c.line(x+w*.5+16*math.cos(math.radians(a)),y+h*.5+16*math.sin(math.radians(a)),x+w*.5+(w*.4)*math.cos(math.radians(a)),y+h*.5+(h*.4)*math.sin(math.radians(a)))
    c.setFillColor(INK); c.setFont('Arial',8); c.drawString(x+5,y+5,'source charge')
def shm(c,x,y,w,h):
    axes(c,x,y,w,h,'t','x'); c.setStrokeColor(GOLD); pts=[]
    for i in range(100): pts.append((x+8+(w-16)*i/99,y+h*.5+h*.3*math.cos(2*math.pi*i/99)))
    c.lines([(pts[i][0],pts[i][1],pts[i+1][0],pts[i+1][1]) for i in range(99)])
def spectrum(c,x,y,w,h):
    axes(c,x,y,w,h,'f','amplitude'); c.setFillColor(GOLD)
    for xx,hh in [(0.18,.55),(0.43,.25),(0.66,.4),(0.85,.18)]: c.rect(x+w*xx,y,w*.035,h*hh,0,1)
def potential(c,x,y,w,h):
    axes(c,x,y,w,h,'r','U'); pts=[]
    for i in range(100):
        r=.5+2.5*i/99; u=1/(r**10)-1.7/(r**5); pts.append((x+8+(w-16)*i/99,max(y+8,min(y+h-8,y+h*.45+u*8))))
    c.setStrokeColor(GOLD); c.lines([(pts[i][0],pts[i][1],pts[i+1][0],pts[i+1][1]) for i in range(99)])
def wave(c,x,y,w,h):
    axes(c,x,y,w,h,'x','y'); pts=[]
    for i in range(100): pts.append((x+8+(w-16)*i/99,y+h*.5+h*.28*math.sin(4*math.pi*i/99)))
    c.setStrokeColor(GOLD); c.lines([(pts[i][0],pts[i][1],pts[i+1][0],pts[i+1][1]) for i in range(99)])
def gauss(c,x,y,r): c.setStrokeColor(TEAL); c.circle(x,y,r,1,0); c.setFillColor(GOLD); c.circle(x,y,6,0,1); c.setFillColor(INK); c.setFont('Arial',8); c.drawCentredString(x,y-r-14,'Gaussian surface')

def test_page(c,n,title,content,visual=None):
    header(c,title,n,12); y=H-1.03*inch; used=p(c,content,.75*inch,y,6.7*inch)
    if visual:
        # The drawing functions use a common 2-inch baseline; translate it upward
        # when the question block is short so the page does not have a dead zone.
        c.saveState(); c.translate(0, max(-0.25*inch, min(1.75*inch, 5.55*inch-used-3.05*inch)))
        visual(c); c.restoreState()
    c.showPage()
def wordbank_page(c):
    header(c,'1. Electric-field word bank',2,12); y=H-1.03*inch
    p(c,'Fill each blank using the word bank. Terms may be used more than once; several are distractors. Cross out each term as you use it.',.75*inch,y,6.7*inch); y-=.62*inch
    box(c,.82*inch,y-1.02*inch,6.35*inch,1.02*inch,CREAM)
    p(c,'<b>WORD BANK</b><br/>source &nbsp;&nbsp; test &nbsp;&nbsp; enclosed &nbsp;&nbsp; external &nbsp;&nbsp; scalar &nbsp;&nbsp; vector<br/>tangent &nbsp;&nbsp; perpendicular &nbsp;&nbsp; inverse-square &nbsp;&nbsp; conserved &nbsp;&nbsp; canceled<br/>reinforced &nbsp;&nbsp; zero &nbsp;&nbsp; nonzero &nbsp;&nbsp; frequency &nbsp;&nbsp; wavelength',1.03*inch,y-.16*inch,5.95*inch,small); y-=1.37*inch
    qs=['a. The electric field is force per unit ______ charge.','b. Field direction is defined using a positive ______ charge.','c. The net electric field from several charges is a ______ sum.','d. In a conductor at electrostatic equilibrium, E inside the metal is ______.','e. Gauss flux depends on ______ charge.','f. Field lines meet a conductor surface ______.','g. Coulomb magnitude has an ______ dependence on distance.','h. Charge is ______ in an isolated system.','i. At a midpoint, symmetric components may be ______ or ______.','j. A field-line arrow tells the force direction for a ______ test charge.','k. If the system is not isolated, charge can cross the boundary but the enlarged system still has ______ charge.']
    for q in qs: y-=p(c,q,.9*inch,y,6.25*inch,body)+.12*inch
    box(c,.9*inch,1.0*inch,6.25*inch,.72*inch,PALE); p(c,'Briefly explain one answer: identify the physical principle, not just the vocabulary word.',1.1*inch,1.5*inch,5.85*inch,small); c.showPage()

def draw_test():
    c=canvas.Canvas(TEST,pagesize=letter); c.setTitle('Physics 2 Comprehensive Conceptual Test - Dense Version')
    header(c,'Scope and Instructions',1,12); y=H-1.03*inch; p(c,'This version is conceptual-first and covers electric forces and fields, oscillations, waves, and sound. Explain direction, limiting behavior, symmetry, and physical meaning whenever asked. Use the word bank only for Questions 1 and 2; some words appear more than once and some do not belong.',.75*inch,y,6.7*inch); y-=.7*inch
    box(c,.8*inch,4.0*inch,6.35*inch,2.2*inch,CREAM); p(c,'Suggested constants and reminders:<br/>k=8.99 × 10<sup>9</sup> N·m<sup>2</sup>/C<sup>2</sup> &nbsp; ε<sub>0</sub>=8.85 × 10<sup>-12</sup> C<sup>2</sup>/(N·m<sup>2</sup>)<br/>v=fλ &nbsp; ω=2πf &nbsp; T=1/f &nbsp; F=-kx &nbsp; ∮E·dA=Q<sub>enc</sub>/ε<sub>0</sub>',1.05*inch,5.85*inch,5.85*inch,eq); p(c,'Answer in complete physics statements. A correct diagram must include axes, directions, and labels without relying on color alone.',.85*inch,3.45*inch,6.2*inch,body); c.showPage()
    wordbank_page(c)
    def v2(c): field(c,1.0*inch,3.05*inch,2.0*inch,2.0*inch); field(c,4.2*inch,3.05*inch,2.0*inch,2.0*inch)
    test_page(c,3,'2. Matching: visual behavior to equation','Match each visual/phenomenon (A–F) to one equation (1–6). Use each equation once.<br/><b>A.</b> Field lines radiate from an isolated positive charge. <b>B.</b> A closed surface counts net field-line excess. <b>C.</b> A mass oscillates about equilibrium. <b>D.</b> A shape translates right unchanged. <b>E.</b> A potential well has a horizontal minimum. <b>F.</b> A sound level compares a quantity to a reference logarithmically.<br/><br/><b>1.</b> F=-dU/dr &nbsp; <b>2.</b> β=10 log<sub>10</sub>(I/I<sub>0</sub>) &nbsp; <b>3.</b> E=kQ r̂/r<sup>2</sup> &nbsp; <b>4.</b> ∮E·dA=Q<sub>enc</sub>/ε<sub>0</sub> &nbsp; <b>5.</b> y=f(x-vt) &nbsp; <b>6.</b> x″+ω<sup>2</sup>x=0',lambda c:(field(c,1.0*inch,3.05*inch,2.0*inch,2.0*inch),shm(c,3.4*inch,3.15*inch,2.8*inch,1.6*inch)))
    test_page(c,4,'3. Explain electric-field phenomena','Answer in words and include a small labeled sketch for each.<br/>a. Why does a negative test charge accelerate opposite the direction of E?<br/>b. Why can two nonzero electric fields produce zero net field at a point?<br/>c. Why is the field inside conducting material zero at electrostatic equilibrium, and why is the surface field normal?<br/>d. Explain why an external charge can change field values on a Gaussian surface without changing the net flux through it. e. What is the difference between a field existing and a test charge experiencing a force? f. Why is E measured in N/C rather than newtons alone?')
    test_page(c,5,'4. Draw and interpret SHM graphs','For x(t)=A cos(ωt), draw on shared axes one cycle of x(t), v(t), and a(t), with relative phase and amplitudes labeled. Then draw U<sub>s</sub>(x) and K(x) for an ideal mass-spring oscillator. Also identify the sign of a and the direction of the restoring force at x<0. Explain why the period does not depend on amplitude in ideal SHM. Identify where x=0, x=±A, v is maximum, and acceleration is maximum in magnitude.',lambda c:shm(c,1.0*inch,3.1*inch,5.8*inch,2.2*inch))
    test_page(c,6,'5. Identify the best wave graph','A traveling-wave snapshot is described by y=A cos(kx-ωt). Choose which behavior is physically correct and explain why: <br/>I. Increasing A changes wave speed in every ideal linear medium. <br/>II. Increasing k decreases wavelength. <br/>III. Reversing the sign before ωt changes the propagation direction. <br/>IV. The medium’s particles travel with the same speed as the wave pattern. <br/><br/>Select all correct statements and draw a labeled snapshot showing λ and A. Then state what a fixed point on the medium does as the wave passes, and explain why a crest is not a material object moving through the medium.',lambda c:wave(c,1.0*inch,2.6*inch,5.8*inch,2.1*inch))
    test_page(c,7,'6. Oscillations: conceptual comparisons','For each pair, state which is larger or whether they are equal, and justify.<br/>a. Two identical springs: one has twice the mass. Compare periods.<br/>b. Same oscillator at x=0 and x=A. Compare speed and spring potential energy.<br/>c. Two oscillators have the same amplitude but different k. Compare total energy.<br/>d. A damped oscillator is driven at frequencies below, near, and above resonance. Describe the qualitative amplitude trend. Define resonance in terms of energy transfer, explain what damping changes, and state whether the natural frequency is set by the driving frequency or by the system.',lambda c:shm(c,1.0*inch,2.7*inch,5.8*inch,2.0*inch))
    test_page(c,8,'7. Sound and spectrum','a. Distinguish a pure tone, a periodic complex tone, and noise using a time trace and frequency spectrum. Draw one spectrum for each. b. Explain compression and rarefaction in air. c. If rms pressure doubles, what happens to intensity and sound-pressure level? d. Explain why changing source loudness does not necessarily change sound speed. Also distinguish amplitude, intensity, pitch, loudness, and timbre, and identify which of these a spectrum displays.',lambda c:spectrum(c,1.0*inch,2.65*inch,5.8*inch,2.1*inch))
    test_page(c,9,'8. Waves at boundaries','Explain and draw.<br/>a. At a boundary, what happens to frequency, speed, wavelength, and direction when a wave enters a slower medium?<br/>b. Use Huygens’ principle to explain refraction.<br/>c. State why the angle is measured from the normal and derive the qualitative direction of bending for n<sub>2</sub>>n<sub>1</sub>.<br/>d. Compare transverse and longitudinal waves, including the role of a medium. Explain why an electromagnetic wave can travel through vacuum while sound cannot, and state which quantities change and which stay continuous at a stationary boundary.',lambda c:wave(c,1.0*inch,2.8*inch,5.8*inch,1.9*inch))
    test_page(c,10,'9. Electric-field reasoning with symmetry','Without calculating a final number, rank the following field magnitudes at the marked point and justify using symmetry, distance, and superposition: (i) one point charge at distance r, (ii) the same charge at 2r, (iii) two equal like charges symmetrically placed with the point at the midpoint, (iv) two equal opposite charges symmetrically placed with the point at the midpoint. Draw vector contributions for (iii) and (iv). Then state what happens if the observation point is moved slightly off the midpoint, and explain why the inverse-square law alone cannot determine the answer for the two-charge cases.',lambda c:field(c,2.1*inch,2.8*inch,3.4*inch,2.0*inch))
    test_page(c,11,'10. Integrated concept check','Complete each statement and then explain one.<br/>a. Electric potential is a ______, while electric field is a ______.<br/>b. Moving along an equipotential requires ______ work by the electric field.<br/>c. The field points toward ______ potential.<br/>d. In a one-dimensional wave, phase difference depends on ______ and ______.<br/>e. For a sound wave, pitch is associated mainly with ______, while timbre depends on waveform and ______. f. Capacitance describes ______ per unit ______. g. A dipole in a uniform field can have zero net force but nonzero ______.',lambda c:potential(c,1.0*inch,2.8*inch,5.8*inch,2.0*inch))
    test_page(c,12,'11. Comprehensive explanation prompt','Choose two of the following and answer in 200–300 words each, using at least one diagram and one equation per response:<br/>A. Explain field lines, flux, Gaussian surfaces, and conductor shielding as one connected model.<br/>B. Explain how SHM, traveling waves, and sound connect local oscillation to energy transport.<br/>C. Explain how a sinusoidal wave’s mathematical form encodes amplitude, phase, wavelength, frequency, and direction. For every response, add one limiting-case prediction: far from a charge, at a conductor interior, at a turning point, or after entering a slower medium.')
    c.save()

def kp(c,n,title,concept,para_txt,steps,eqs,total=12):
    header(c,title,n,total,True); y=H-1.03*inch; c.setFillColor(TEAL); c.setFont('Arial-Bold',11); c.drawString(.68*inch,y,title.upper()); y-=.25*inch
    box(c,.65*inch,y-4.0*inch,7.0*inch,4.0*inch,PALE); p(c,'Concepts needed: <b>'+concept+'</b>',.85*inch,y-.18*inch,6.55*inch,key); p(c,para_txt,.85*inch,y-.52*inch,6.55*inch,key); yy=y-1.55*inch
    for i,s in enumerate(steps,1): yy-=p(c,f'<b>{i}.</b> {s}',.85*inch,yy,6.5*inch,key)+.05*inch
    ey=y-4.35*inch; box(c,.65*inch,ey-1.35*inch,7.0*inch,1.35*inch,CREAM); c.setFillColor(NAVY); c.setFont('Arial-Bold',8); c.drawString(.85*inch,ey-.18*inch,'ANSWER RELATIONS / CHECKS'); yy=ey-.35*inch
    for s in eqs: yy-=p(c,s,.85*inch,yy,6.5*inch,eq)+.02*inch
    if n<total: c.showPage()
def draw_key():
    c=canvas.Canvas(KEY,pagesize=letter); c.setTitle('Physics 2 Comprehensive Conceptual Test - Dense Version Detailed Answer Key')
    kp(c,1,'Scope and instructions','representation; explanation; equations; diagrams','This answer key treats a conceptual response as a chain of ideas rather than a single keyword. Full credit requires the physical object, the relationship, and the direction or limiting behavior. Diagrams should be judged by structure: axes and variables, arrows, phase, and labels matter more than artistic style.', ['Use the word bank only where requested; repeated terms are intentional.','For explanation prompts, name the governing principle before applying it.','For drawings, accept equivalent orientation if the relative geometry and labels are correct.'],['Conceptual proof = principle + interpretation + evidence','Prefer sign, direction, units, and limiting-case checks'])
    kp(c,2,'1  Electric-field word bank','field definition; test charge; vector addition; conductor equilibrium; Gauss law; inverse-square law; charge conservation','The correct words are determined by the mathematical type of each idea. Electric field is a vector because it has magnitude and direction, and it is defined using a positive test charge. “Source” identifies the charge arrangement creating the field; “test” identifies the small charge used to measure force. Coulomb’s law has inverse-square dependence because spherical spreading changes the field over an area proportional to r². In a conductor at equilibrium, mobile charges have rearranged until the interior field is zero. Gauss law selects enclosed charge for net flux, while an external charge can still alter local field. Symmetry can make contributions cancel or reinforce, and conservation says total charge is not created or destroyed.', ['a test; b source; c vector; d zero; e enclosed; f perpendicular; g inverse-square; h conserved; i canceled; reinforced.','The distractors “scalar,” “tangent,” “external,” “nonzero,” “frequency,” and “wavelength” do not fit these blanks.','The repeated use of “test” and the two symmetry outcomes are deliberate checks against guessing from word frequency. j. positive; k. conserved. A field is a source-created property of space; force is the interaction qE when a charge is placed there. N/C is force per charge, so newtons alone would omit the test-charge dependence.'],['E=F/q','F=k|q1q2|/r²','Qtotal(before)=Qtotal(after)'])
    kp(c,3,'2  Matching visuals to equations','field-line geometry; Gauss flux; SHM; traveling-wave translation; potential slope; logarithmic level','Each match follows from the feature emphasized by the visual. A radial field from a point charge is the inverse-square vector field. A closed surface with a net field-line excess represents flux and enclosed charge, not merely a local field value. Oscillation about equilibrium is represented by a second-time-derivative relation with a restoring sign. A translated shape must depend on x-vt for rightward motion. A potential well is interpreted through slope, so force is the negative derivative. Sound level is a logarithmic comparison with a reference, so the decibel expression is the only match that contains a logarithm and I0.', ['A-3: radial inverse-square field from a point charge.','B-4: closed-surface flux is set by enclosed charge.','C-6: SHM has x″ proportional to -x.','D-5: x-vt translates a shape in +x.','E-1: force is negative potential slope.','F-2: sound level is logarithmic relative to I0.'],['E=kQ rhat/r²','∮E·dA=Qenc/ε0','x″+ω²x=0','y=f(x-vt)','F=-dU/dr','β=10log10(I/I0)'])
    kp(c,4,'3  Explain electric-field phenomena','force direction; superposition; conductor equilibrium; flux','A negative test charge feels F=qE, so the negative scalar reverses the vector direction relative to E. Two nonzero fields can cancel because vectors add component-by-component; equal opposite vectors sum to zero at a symmetry point. Inside a conductor, a nonzero static field would accelerate mobile charges, contradicting equilibrium. Surface charges rearrange until the interior field cancels. The tangential component at the surface must vanish because otherwise charges would continue moving along the surface, so the remaining field is normal. Gauss law says external charge contributes as much inward and outward flux in aggregate. e. The field can exist with no test charge; the force is defined only after a charge is placed. f. Field is force divided by charge, so its unit must be N/C. as it crosses a closed surface, giving zero net contribution even though the local field is not zero.', ['a. State F=qE, then note q<0 reverses direction.','b. Draw equal arrows and add components; cancellation is vector addition, not absence of individual fields.','c. Use the contradiction with charge motion, then state normal surface field.','d. Distinguish local flux density from total closed-surface flux.'],['F=qE','Einside metal=0','Etangent=0','∮E·dA=Qenc/ε0'])
    kp(c,5,'4  SHM graphs','sinusoidal motion; phase; derivatives; energy conservation','For x=A cos(ωt), the displacement begins at +A. Differentiate once: v=-Aω sin(ωt), so velocity begins at zero and becomes negative. Differentiate again: a=-Aω² cos(ωt)=-ω²x, so acceleration is opposite displacement and has maximum magnitude at the turning points. The spring potential is Us=1/2kx²: an upward parabola with maximum at ±A. Total energy is 1/2kA², so K=E-Us is largest at x=0 and zero at ±A. This is why displacement, velocity, acceleration, and energy graphs are linked but not identical.', ['Draw x, v, and a with the same period; v is quarter-cycle shifted from x and a is opposite x.','At x=0: speed is maximum, Us=0, and acceleration is zero. For x<0, acceleration and restoring force point right, toward equilibrium. Ideal SHM has an amplitude-independent period because the linear equation has a fixed omega; amplitude changes energy, not omega.','At x=±A: speed is zero, Us is maximum, and |a| is maximum.','K is an inverted parabola relative to Us, and K+Us is constant.'],['x=A cos(ωt)','v=-Aω sin(ωt)','a=-ω²x','Us=1/2kx²; K=1/2k(A²-x²)'])
    kp(c,6,'5  Wave-graph statements','amplitude; wave number; direction; particle motion; linear medium','Statement II is correct because k=2π/λ, so larger k means shorter wavelength. Statement III is correct because a fixed phase point in cos(kx-ωt) moves toward increasing x, while cos(kx+ωt) moves toward decreasing x. Statement I is false for an ideal linear medium: amplitude controls disturbance size, while speed is set by medium properties. Statement IV is false because particles oscillate locally while the waveform transports energy at the propagation speed. The particle’s transverse velocity can be larger or smaller than the wave speed. A medium point oscillates about equilibrium while the pattern carries phase and energy; a crest is a location of the pattern, not a marked piece of matter. and is a different physical quantity.', ['Select II and III only.','Label one wavelength between matching phase points and amplitude from equilibrium to crest.','Explain that changing A changes energy carried, not necessarily v in a linear medium.','State transverse versus longitudinal motion separately from propagation direction.'],['y=A cos(kx-ωt)','k=2π/λ','vwave=ω/k=fλ'])
    kp(c,7,'6  Oscillation comparisons','period; mass-spring frequency; energy; resonance; damping','For a mass-spring oscillator, T=2π√(m/k), so doubling mass increases the period by √2. At equilibrium, all ideal energy is kinetic and speed is maximum; at a turning point, speed is zero and spring energy is maximum. Total energy is 1/2kA², so at fixed amplitude the stiffer spring has more energy. Damping removes mechanical energy, so a driven oscillator has a finite resonance peak rather than the indefinitely large ideal response. As driving frequency rises from low values, amplitude grows toward resonance and then falls above resonance; the exact peak depends on damping. Resonance is especially effective energy transfer when driving is near the system’s natural frequency. Damping lowers and broadens the response; natural frequency belongs to the system, not the driver.', ['a. T2/T1=√2 for twice the mass.','b. x=0 gives vmax; x=A gives v=0 and Us maximum.','c. Larger k means larger E when A is the same.','d. Amplitude rises, peaks near natural frequency, then falls; damping broadens and lowers the peak.'],['T=2π√(m/k)','ω=√(k/m)','E=1/2kA²'])
    kp(c,8,'7  Sound and spectrum','mechanical longitudinal waves; pressure; intensity; decibels; harmonics; timbre','A pure tone has one frequency component and a sinusoidal or nearly sinusoidal time trace. A periodic complex tone repeats in time but has a fundamental plus harmonics. Noise has irregular time behavior and a broad, non-discrete spectrum. In air, molecules oscillate parallel to propagation, forming compressions and rarefactions. For a sinusoidal sound, intensity is proportional to rms pressure squared, so doubling pressure makes intensity four times larger. Sound-pressure level changes by 20log10(2)=6.02 dB. Source loudness changes amplitude, not the medium’s stiffness. Amplitude is maximum displacement or pressure variation; intensity is power per area; pitch tracks frequency; loudness is perception; timbre tracks waveform and harmonic content. A spectrum displays amplitude versus frequency., density, or temperature, so it does not by itself determine sound speed.', ['Draw one spectral line for a pure tone, several harmonic lines for a complex tone, and a broad irregular spectrum for noise.','Mark compression as high pressure and rarefaction as low pressure.','Use the square relation before applying the logarithm.','Separate pitch, loudness, timbre, and propagation speed.'],['I∝p_rms²','dLp=20log10(p2/p1)','v_sound depends on medium properties'])
    kp(c,9,'8  Waves at boundaries','frequency continuity; wavelength; Huygens principle; refraction; normal angle','At a stationary boundary, the source fixes frequency, so frequency stays continuous across the interface. The new medium sets a new speed, and λ=v/f therefore changes. Huygens’ principle says each point on a wavefront emits secondary wavelets; when one side of a wavefront slows first, the wavefront pivots and the direction changes. Angles are measured from the normal because the normal is the direction in which the boundary crossing and phase matching are compared. If n2>n1, then v2<c/n1 is smaller, so the ray bends toward the normal. Transverse and longitudinal describe particle motion relative to propagation; sound in air is longitudinal and requires a material medium. Electromagnetic waves do not require matter. At a stationary boundary, frequency remains source-set while speed and wavelength can change.', ['a. In a slower medium: frequency unchanged, speed lower, wavelength shorter, ray toward normal.','b. Draw successive wavelets and their envelope; the unequal advance rotates the envelope.','c. Use n=c/v and the phase-matching sine relation.','d. State that mechanical waves require a medium; electromagnetic waves do not.'],['v=fλ','n=c/v','n1 sinθ1=n2 sinθ2'])
    kp(c,10,'9  Symmetry reasoning','inverse-square scaling; superposition; midpoint symmetry','For one point charge at r, E=k|Q|/r². At 2r, the field is one quarter as large. For two equal like charges at the midpoint, the two field vectors point in opposite directions and cancel, so the net field is zero. For equal opposite charges, the fields at the midpoint point in the same direction—from the positive charge toward the negative charge—so they reinforce. The comparison illustrates why vector direction must be drawn before magnitudes are combined. A zero result can arise from cancellation even though each individual contribution is nonzero. Off the midpoint, the exact symmetry cancellation is lost, so the geometry and component calculation are needed; inverse-square scaling alone is insufficient.', ['(ii) is one quarter of (i).','(iii) is zero by opposite-vector cancellation.','(iv) is nonzero and points from + toward -.','Do not rank (iv) against (i) numerically without a separation specification; state the direction and scaling instead.'],['Epoint=k|Q|/r²','Enet=ΣEi','E(r=2r)=E(r)/4'])
    kp(c,11,'10  Integrated concept check','scalar potential; vector field; work; phase; pitch; spectrum','Potential is a scalar because it has magnitude but no direction; electric field is a vector. Work along an equipotential is zero because ΔV=0, and E points toward decreasing potential. A wave’s phase changes with both position and time, through kx and ωt. In sound, pitch is primarily frequency. Timbre depends on waveform and harmonic spectrum. f. Capacitance describes charge per unit potential difference. g. A dipole can have nonzero torque even when its uniform-field net force is zero., which is why two instruments can have the same fundamental pitch but sound different.', ['a. scalar; vector. b. zero. c. lower. d. position; time. e. frequency; spectrum.','Explain one: E=-grad V means the field follows the steepest decrease in potential.','For phase, compare kx-ωt at two points or times.'],['ΔV=-∫E·dl','E=-grad V','phase=kx-ωt'])
    kp(c,12,'11  Comprehensive explanation prompt','synthesis; model selection; diagrams; physical interpretation','Answers vary, but a strong response must connect representations. For A, begin with the point-charge field and field-line rules, then define flux and explain why a Gaussian surface is useful only with symmetry, and finally connect conductor shielding to the zero interior field. For B, distinguish local oscillation from energy transport: SHM describes one oscillator, a traveling wave translates a disturbance, and sound is a mechanical longitudinal wave whose pressure variations carry energy. For C, decode each part of y=A cos(kx-ωt+φ): A is amplitude, k sets wavelength, ω sets frequency, φ sets phase, and the sign determines direction. A correct diagram must reinforce, not replace, the explanation.', ['A should include E=F/q, Φ=∮E·dA, Gauss law, and E=0 in metal.','B should include x(t), y(x,t), compression/rarefaction, and v=fλ.','C should label A, λ, phase, and a right-moving crest.','Award full credit when the response states assumptions and checks direction or limiting behavior. Strong responses should also connect the requested limiting case to a concrete prediction rather than merely naming it.'],['Φ=∮E·dA=Qenc/ε0','x=A cos(ωt+φ)','y=A cos(kx-ωt+φ)','v=fλ'])
    c.setFillColor(MUTED); c.setFont('Arial',7); c.drawString(.65*inch,.58*inch,'References: Young and Freedman, University Physics; OpenStax University Physics Vol. 1, Chapters 15–17; Volume 2, Chapters 5–6.'); c.save()
draw_test(); draw_key(); print(TEST); print(KEY)
