from pathlib import Path
import json,difflib
ROOT=Path(__file__).parents[1]; sid='src-20260806094518-3f5d8d0e38'; base=ROOT/'data/source-library/sources'/sid
notes={191:'Coulomb law: charge signs determine attraction versus repulsion; force acts along the line joining point charges and obeys inverse-square dependence.',192:'Coulomb law uses point charges and separation r; equal and opposite forces lie on the line of centers. Vector form uses source-to-target displacement.',193:'Worked Coulomb setup converts microcoulombs, identifies line-of-centers direction, and evaluates k|q1 q2|/r^2 with unit and sign checks.',194:'Superposition resolves forces from several source charges into components before adding; symmetry can cancel one component and reinforce another.',195:'Component addition uses source-target coordinate differences; the inverse-square denominator uses the full separation distance.',196:'Coulomb examples emphasize consistent units, signed products for direction, and limiting behavior as separation changes.',197:'Electric field is force per positive test charge, E=F/q0; it is produced by source charges and independent of the chosen test charge.',198:'Field lines point away from positive charges and toward negative charges; point-source magnitude follows k|q|/r^2.',199:'Point-charge field uses source-to-observer displacement divided by r^3; a test charge then experiences F=q0 E and its sign can reverse force direction.',200:'Several point-charge fields are added as vectors; coordinate components and symmetry determine which cancel at the observation point.',201:'Electric-field checks include N/C units, inverse-square scaling, charge sign, and the far-field kQ/r^2 limit.'}
chunks=json.loads((base/'chunks.json').read_text()); assert not any(c['id']==f'{sid}:page-{p:04}' for c in chunks for p in notes)
new=[dict(id=f'{sid}:page-{p:04}',ordinal=100000+p,kind='page-image',locator=f'PDF page {p}',text=f'Visually reviewed PDF page {p}: {t}',tokenCount=len(t.split())+5,ocrConfidence=None,imagePath=f'page-images/page-{p:04}.png',pageNumber=p,transcriptionReviewState='approved') for p,t in notes.items()]
raw=(base/'chunks.json').read_text().splitlines(); pos=next(i for i,l in enumerate(raw) if f'{sid}:page-0202' in l)
updated=chunks+new
insert='\n'.join(json.dumps(x,ensure_ascii=False,indent=2) for x in new)
print('*** Begin Patch\n*** Update File: '+(base/'chunks.json').as_posix()); print('@@'); print('+'+insert.replace('\n','\n+')+','); print('*** End Patch')
manifest=json.loads((base/'manifest.json').read_text()); manifest['chunkCount']=len(updated); oldm=(base/'manifest.json').read_text().splitlines(True); newm=json.dumps(manifest,indent=2,ensure_ascii=False).splitlines(True)
print('*** Begin Patch\n*** Update File: '+(base/'manifest.json').as_posix()); print(''.join(difflib.unified_diff(oldm,newm,n=1,lineterm=''))); print('*** End Patch')
for objid,packet,pages in [('physics2-ch05-electric-charges-fields-coulomb-law','packet-physics2-coulombs-superposition-calculus-v1',range(191,197)),('physics2-ch05-electric-charges-fields-electric-field','packet-physics2-point-charge-fields-calculus-v1',range(197,202))]:
 obj={'schemaVersion':1,'id':packet,'sourceId':sid,'curriculumId':'physics-2-calculus-curriculum','categoryId':'physics-2','topicId':'physics2-electric-charges-fields','objectiveIds':[objid],'chunkIds':[f'{sid}:page-{p:04}' for p in pages],'reviewState':'approved','reviewNotes':'PDF pages visually reviewed; original.pdf SHA256 matches manifest. Private page-image summaries are approved source evidence.','outputConstraints':{'verbatimSourceTextExcluded':True,'requireOriginalVisuals':True,'requireStructuredExplanations':True}}
 path=ROOT/'docs/assessment-reference/packets'/f'{packet}.json'; print('*** Begin Patch\n*** Add File: '+path.as_posix()); print('\n'.join('+'+x for x in json.dumps(obj,indent=2).splitlines())); print('*** End Patch')
