from pathlib import Path
import runpy
src=Path(r'C:\Users\SeanS\Downloads\cir_app\scratch\build_comprehensive_physics_test.py')
text=src.read_text(encoding='utf-8')
text=text.replace("Physics 2 Comprehensive Mixed Test - Detailed Answer Key.pdf", "Physics 2 Mixed Conceptual and Procedural Test - Version 2 Detailed Answer Key.pdf")
text=text.replace("Physics 2 Comprehensive Mixed Test.pdf", "Physics 2 Mixed Conceptual and Procedural Test - Version 2.pdf")
text=text.replace("total=11", "total=13").replace("total=11;", "total=13;")
text=text.replace("header(c,'COMPREHENSIVE PHYSICS 2 TEST'", "header(c,'COMPREHENSIVE PHYSICS 2 TEST | VERSION 2'")

test_pages=r'''    # 12 Coulomb force and field in one and two dimensions
    header(c,'Point Charges: 1D and 2D Force and Field',12,total); y=H-1.03*inch
    para(c,'12. Use k=8.99×10^9 N·m²/C². (a) On the x-axis, q1=+3.0 μC is at x=0 and q2=−2.0 μC is at x=0.40 m. Find the magnitude and direction of the force on q2. (b) A test charge q0=+1.0 μC is at (0,0), q1=+4.0 μC at (0.30,0) m, and q2=+4.0 μC at (0,0.30) m. Find the x- and y-components of the net electric field at q0, then its magnitude and direction. (c) Explain how the force result differs from the field result conceptually.',.75*inch,y,6.7*inch)
    box(c,.8*inch,3.75*inch,6.45*inch,1.45*inch,PALE); para(c,'For full credit: draw displacement vectors, identify attraction/repulsion, write each vector contribution, resolve components, and report units. Leave the lower half of the page for work.',1.05*inch,4.9*inch,5.95*inch,body)
    para(c,'F=k|q1q2|/r²    ;    E=k|q|/r²    ;    Ex=ΣEi,x    ;    Ey=ΣEi,y',1.05*inch,4.15*inch,5.95*inch,eq); c.showPage()
    # 13 hallmark equation memory and applications
    header(c,'Hallmark Equations and Physical Meaning',13,total); y=H-1.03*inch
    para(c,'13. (a) Write the standard forms of Newton’s universal law of gravitation, Coulomb’s law, the electric-field definition, Gauss’s law, the potential-energy relation, the linear wave equation, and the Doppler relation for a stationary observer and moving source. (b) For each, name the physical quantity being predicted and one condition or interpretation that prevents misuse. (c) Applications: predict qualitatively whether perceived frequency increases or decreases when the observer moves toward a sound source; predict how the field of an infinite line changes when distance doubles; and explain why a conductor surface cannot support a tangential electrostatic field.',.75*inch,y,6.7*inch)
    box(c,.8*inch,3.55*inch,6.45*inch,1.8*inch,CREAM); para(c,'Memory bank to complete from understanding, not guessing:<br/>F_g = ______ &nbsp;&nbsp; F_C = ______ &nbsp;&nbsp; E = ______ &nbsp;&nbsp; Φ_E = ______<br/>U = ______ &nbsp;&nbsp; y_xx = ______ &nbsp;&nbsp; f_obs = ______',1.05*inch,4.95*inch,5.95*inch,body)
    para(c,'Use the bottom half to explain the three applications in complete sentences and include one direction sketch.',1.05*inch,3.25*inch,5.95*inch,body); c.showPage()
'''
text=text.replace("    finish(c)\n\ndef key_page", test_pages+"    finish(c)\n\ndef key_page")
text=text.replace("; finish(c)\n\ndef key_page", "; c.showPage()\n"+test_pages+"    finish(c)\n\ndef key_page")
key_pages=r'''    key_page(c,12,total,'12  Point charges in 1D and 2D','Coulomb law; electric-field definition; source/test roles; attraction and repulsion; vector components; superposition; inverse-square scaling','The one-dimensional part is a signed-direction problem: q1 and q2 have opposite signs, so the force is attractive and points from q2 toward q1. The two-dimensional part is a field problem: the test charge is not included when computing E, and the equal perpendicular source charges make the x and y components equal. Only after the vector components are found should magnitude and angle be calculated. This distinction is essential: force depends on the test charge, while electric field is a property of the source arrangement at the point.',''' + "['a. r=0.40 m. The magnitude is F=k|q1q2|/r²=(8.99×10^9)(3.0×10^-6)(2.0×10^-6)/(0.40)²=0.337 N. The force is attractive, so it points left.','b. For q1, E1=k(4.0×10^-6)/(0.30)²=3.996×10^5 N/C in the negative x direction. For q2, the same magnitude points in negative y. Thus Ex=−3.996×10^5 N/C and Ey=−3.996×10^5 N/C.','The net field magnitude is E=√(Ex²+Ey²)=5.65×10^5 N/C and points 45 degrees below the negative x-axis, or 225 degrees from +x.','c. If the test charge is q0=+1.0 μC, F=q0E, so the force magnitude would be 0.565 N in the same direction. A negative test charge would reverse the force direction.','The inverse-square factor applies separately to each source distance; vector addition is required because the sources are not collinear.']" + ''', ['F = k m1m2/r² toward the other mass.','F = k|q1q2|/r² with direction set by signs and geometry.','E = F/q_test, independent of the small test charge.','Φ_E = closed integral E dot dA = Q_enc/eps0.','U = qV or U = kq1q2/r for point charges.','y_xx = (1/v²)y_tt.','For a stationary observer and moving source: f_obs=f_s v/(v∓v_s), with approach using the denominator v-v_s and increasing the observed frequency.','Approaching source or observer means wavefront arrival rate increases. For a line charge, doubling r halves E. A tangential conductor field would move free charge, contradicting electrostatic equilibrium.'])
'''
text=text.replace("    c.setFillColor(MUTED); c.setFont('Arial',7); c.drawString(.65*inch,.58*inch,'Sources:", key_pages+"    c.setFillColor(MUTED); c.setFont('Arial',7); c.drawString(.65*inch,.58*inch,'Sources:")
tmp=Path(r'C:\Users\SeanS\Downloads\cir_app\scratch\_generated_mixed_test_v2.py'); tmp.write_text(text,encoding='utf-8'); runpy.run_path(str(tmp))
