from pathlib import Path
import json
import yaml

ROOT = Path(r'C:\Users\SeanS\Downloads\cir_app')
OUT = ROOT / 'data' / 'assessments'
MEDIA = ROOT / 'data' / 'media' / 'chemistry'
BLUE = ROOT / 'docs' / 'assessment-reference' / 'question-blueprints'
for p in (OUT, MEDIA, BLUE): p.mkdir(parents=True, exist_ok=True)

TOPIC = 'chem-functional-group-introduction'
PACKET = 'packet-chem-functional-groups-v1'
SOURCE = 'src-20260720035703-91ea51b0d8'
chunks = [f'{SOURCE}:chunk-{i}' for i in list(range(2787, 2804)) + [11257, 11266, 11275, 11302, 11320]]

def expl(correct, options, principle):
    wrong = '; '.join(f"Choice {k} ({v}) fails because it {('confuses the connectivity or boundary' if k != correct else '') or 'does not match the stated structure'}" for k,v in options.items() if k != correct)
    return f'Solution: Choice {correct} ({options[correct]}).\n\nWhy it works: {principle}\n\nWhy the other choices fail: {wrong}.'

def q(qid, prompt, options, correct, obj, hard=False, sig=None, principle='Trace the atom connectivity first, then apply the defining functional-group pattern.'):
    dims = ['representationTranslation','connectivityAnalysis'] if not hard else ['representationTranslation','connectivityAnalysis','propertyTransfer']
    return {
        'id': qid, 'type': 'multipleChoice', 'prompt': prompt,
        'choices': [{'id': k, 'text': v if k == correct else f'{v} — competing {obj} reading in {qid}', 'media': [], 'issueSignals': ([] if k == correct else [{'id': f'fg-{obj}-misread', 'domains':['chemistry']}])} for k,v in options.items()],
        'answer': {'choiceId': correct, 'choiceIds': [], 'expected': None, 'gradingMode': None, 'expectedLatex': None, 'equivalenceMode': None, 'variables': [], 'value': None, 'tolerance': None, 'media': [], 'keyPoints': [], 'circuitAnswer': None, 'graphingAnswer': None},
        'explanation': expl(correct, options, principle), 'media': [], 'language': None, 'functionName': None, 'executionMode': 'unspecified', 'starterCode': None, 'tests': [], 'circuitQuestion': None, 'graphingQuestion': None,
        'skills': [obj], 'difficultyDimensions': dims, 'subjectDifficultyTags': [obj], 'difficultyEvidence': ('Requires transfer to a new connected structure and a property comparison.' if hard else 'Requires two distinct steps: translate representation and classify the connected atoms.'),
        'prerequisiteObjectiveIds': ['fg-read-structures','fg-connectivity'], 'extensionObjectiveIds': ['fg-property-reasoning'] if hard else [], 'parts': [], 'issueSignals': [],
        '_blueprint': {'objectiveId': obj, 'hard': hard, 'sig': sig or qid, 'variation': ['representation','unknown'] if not hard else ['representation','unknown','constraint']}
    }

def item(i, prompt, answer, obj):
    return {'id': f'dr-{i:02d}', 'type':'flashcard', 'prompt':prompt, 'answer':{'expected':answer}, 'explanation':f'Solution: {answer}. Why it works: Connect the defining atoms and bonds in the prompt to the vocabulary term.'}

def base(id_, title, typ, learning, activity):
    return {'schemaVersion':1,'id':id_,'title':title,'assessmentType':typ,'categoryId':'chemistry','topicId':TOPIC,'modeDefault':'practice','randomizeQuestions': typ in ('quiz','test'),'navigation':{'learningGoal':learning,'activityType':activity,'tags':['chemistry','functional-groups','molecular-structure']},'authoring':{'visualRequirement':'original-svg-structures','sourceId':SOURCE,'sourcePacketId':PACKET}}

# Original, compact SVGs with visible bonds and explanatory labels.
svgs = {
 'chem-functional-groups-map.svg': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 260" role="img" aria-labelledby="t d"><title id="t">Functional group connectivity map</title><desc id="d">A carbonyl carbon branches to oxygen patterns that distinguish aldehyde, ketone, carboxylic acid, ester, and amide.</desc><rect width="760" height="260" fill="#f8fafc"/><g stroke="#1e293b" stroke-width="4" fill="none"><path d="M80 130h70m30 0h70"/><path d="M165 120V55m0 80v70"/><path d="M165 55h55m-55 130h55"/><path d="M380 130h70m30 0h70"/><path d="M465 120V55m0 80v70"/><path d="M465 55h55m-55 130h55"/></g><g font-family="system-ui" font-size="22" fill="#0f172a"><text x="75" y="118">R</text><text x="155" y="45">O</text><text x="220" y="45">H</text><text x="220" y="205">OH</text><text x="375" y="118">R</text><text x="455" y="45">O</text><text x="520" y="45">R</text><text x="520" y="205">N</text><text x="98" y="245">acid: C(=O)OH</text><text x="402" y="245">amide: C(=O)N</text></g></svg>',
 'chem-functional-groups-rnotation.svg': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 260" role="img" aria-labelledby="t d"><title id="t">R notation and representation ladder</title><desc id="d">The same ethoxy fragment is shown as expanded, condensed, and skeletal-style endpoint labels.</desc><rect width="760" height="260" fill="#fff7ed"/><g font-family="system-ui" fill="#431407" font-size="22"><text x="30" y="40">expanded</text><text x="30" y="105">H₃C—CH₂—O—H</text><text x="30" y="170">condensed</text><text x="220" y="170">CH₃CH₂OH</text><text x="30" y="235">R means a carbon-containing remainder</text><text x="515" y="170">R—OH</text></g><g stroke="#c2410c" stroke-width="4"><path d="M36 120h300"/><path d="M530 120h120"/></g></svg>',
 'chem-functional-groups-properties.svg': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 260" role="img" aria-labelledby="t d"><title id="t">Polarity and hydrogen-bonding checklist</title><desc id="d">A nonpolar hydrocarbon and a polar alcohol are compared by their carbon skeleton and oxygen hydrogen bond.</desc><rect width="760" height="260" fill="#eff6ff"/><g font-family="system-ui" font-size="24" fill="#172554"><text x="42" y="45">hydrocarbon: R—R</text><text x="42" y="105">mostly dispersion; size matters</text><text x="420" y="45">alcohol: R—O—H</text><text x="420" y="105">polar O—H; donor + acceptor</text><text x="42" y="190">larger hydrocarbon tail can reduce water solubility</text></g><g stroke="#2563eb" stroke-width="5"><path d="M80 140h230"/><path d="M455 140h230"/><path d="M565 140v45"/></g></svg>',
 'chem-functional-groups-boundaries.svg': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 260" role="img" aria-labelledby="t d"><title id="t">Boundary checks for similar groups</title><desc id="d">Four paired patterns show oxygen or nitrogen connectivity that separates alcohol from phenol, ether from ester, aldehyde from ketone, and amine from amide.</desc><rect width="760" height="260" fill="#f0fdf4"/><g font-family="system-ui" font-size="22" fill="#14532d"><text x="25" y="50">R—OH ≠ Ar—OH</text><text x="25" y="105">R—O—R ≠ R—C(=O)—O—R</text><text x="25" y="160">—C(=O)H ≠ —C(=O)—R</text><text x="25" y="215">R—NH₂ ≠ R—C(=O)—NH₂</text></g></svg>',
 'chem-functional-groups-molecule.svg': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 260" role="img" aria-labelledby="t d"><title id="t">Reading multiple functional groups</title><desc id="d">A chain contains an alkene, an alcohol, and an ether; highlighted local neighborhoods are analyzed independently.</desc><rect width="760" height="260" fill="#faf5ff"/><g stroke="#6b21a8" stroke-width="5" fill="none"><path d="M70 150h100l60-70 100 70 100-70 100 70h130"/><path d="M230 80v-45m200 45v-45"/></g><g font-family="system-ui" font-size="22" fill="#581c87"><text x="180" y="30">OH</text><text x="405" y="30">O</text><text x="100" y="220">classify each connected neighborhood; do not count atoms twice</text></g></svg>'
}
for name, content in svgs.items(): (MEDIA/name).write_text(content, encoding='utf-8')

lesson = base(TOPIC+'-concept-lesson','Functional Group Introduction: Concept Lesson','conceptLesson','learn','conceptLesson')
lesson['randomizeQuestions']=False
objs=[('Representations and R notation','fg-read-structures','Read expanded, condensed, and simple skeletal structures by following bonds and treating R as a carbon-containing remainder.','chem-functional-groups-rnotation.svg','Which shorthand preserves the same alcohol connectivity as CH₃CH₂OH?','CH₃CH₂OH and R—OH when R is CH₃CH₂'),('Hydrocarbon and halogen groups','fg-recognize-hydrocarbon-halogen','Recognize C=C, C≡C, and C—X neighborhoods as alkene, alkyne, and haloalkane.','chem-functional-groups-map.svg','Which local pattern is an alkyne?','R—C≡C—R'),('Oxygen and nitrogen groups','fg-recognize-oxygen-nitrogen','Recognize alcohol, ether, aldehyde, ketone, carboxylic acid, ester, amine, and amide from connectivity.','chem-functional-groups-boundaries.svg','Which pattern is an ester rather than an ether?','R—C(=O)—O—R'),('Boundary checks','fg-distinguish-boundaries','Distinguish look-alike groups and do not count a carboxylic-acid OH as a separate alcohol.','chem-functional-groups-boundaries.svg','Why is R—C(=O)—OH classified as a carboxylic acid rather than acid plus alcohol?','The OH is directly attached to the carbonyl carbon as part of one group.'),('Properties and size','fg-property-reasoning','Use polar bonds, hydrogen-bond donors/acceptors, and hydrocarbon size to make qualitative property predictions.','chem-functional-groups-properties.svg','Which change generally lowers water solubility for a homologous alcohol series?','Increasing the hydrocarbon portion while retaining one OH')]
lesson['lesson']={'introduction':'Use local connectivity to recognize functional groups, then connect the same structure to polarity, hydrogen bonding, and qualitative solubility.','sections':[]}
for i,(title,obj,content,svg,prompt,answer) in enumerate(objs,1):
    concept_choices=[answer, ['Count only the total atoms','Ignore the C—X bond and use formula mass','Assume every oxygen is an alcohol','Treat every oxygen as an alcohol','Compare only hydrocarbon size'][i-1], ['Use the molecular formula alone','Treat every nitrogen as an amide','Ignore attached carbonyls','Call every carbonyl a ketone','Assume polarity replaces connectivity'][i-1], ['Name the largest fragment','Count the acid OH as another group','Use polarity without connectivity','Count every heteroatom as a group','Ignore the hydrocarbon remainder'][i-1]]
    lesson['lesson']['sections'].append({'id':f'sec-{i}','title':title,'required':True,'content':content,'media':[{'type':'image','src':'/media/chemistry/'+svg,'alt':title+' diagram with visible bonds.','caption':None}],'check':{'id':f'chk-{i}','type':'multipleChoice','prompt':prompt,'choices':[{'id':'a','text':concept_choices[0],'media':[],'issueSignals':[]},{'id':'b','text':concept_choices[1],'media':[],'issueSignals':[{'id':'fg-connectivity-misread','domains':['chemistry']}]},{'id':'c','text':concept_choices[2],'media':[],'issueSignals':[{'id':'fg-connectivity-misread','domains':['chemistry']}]},{'id':'d','text':concept_choices[3],'media':[],'issueSignals':[{'id':'fg-boundary-confusion','domains':['chemistry']}]}],'answer':{'choiceId':'a','choiceIds':[]},'explanation':f'Solution: Choice A ({answer}).\n\nWhy it works: The check uses the {obj} objective by tracing the local connectivity and then applying the defining pattern.\n\nWhy the other choices fail: Choice B ignores the representation; choice C discards a bond or attached atom; choice D substitutes an unrelated shortcut.'},'difficultyDimensions':['connectivityAnalysis','representationTranslation'],'subjectDifficultyTags':[obj],'difficultyEvidence':'The learner must translate a displayed or described structure and check a local bonding pattern.','prerequisiteObjectiveIds':['fg-read-structures'],'extensionObjectiveIds':['fg-property-reasoning'],'parts':[],'issueSignals':[]})

gloss = base(TOPIC+'-glossary','Functional Group Introduction Glossary','glossary','learn','glossary'); gloss['randomizeQuestions']=False
terms=[('functional group','A connected atom-and-bond pattern that gives an organic molecule characteristic recognition and properties.'),('R notation','R represents a carbon-containing remainder of a molecule.'),('skeletal structure','A line representation in which carbon atoms at vertices and endpoints are implied.'),('alkene','A group containing a carbon-carbon double bond, C=C.'),('alkyne','A group containing a carbon-carbon triple bond, C≡C.'),('haloalkane','An alkyl group bonded to a halogen, C—X.'),('alcohol','A hydroxyl group, R—OH, with oxygen bonded to carbon and hydrogen.'),('phenol','An OH group directly bonded to an aromatic ring; it is not classified as an ordinary aliphatic alcohol.'),('ether','An oxygen bonded to two carbon-containing groups, R—O—R.'),('aldehyde','A carbonyl group whose carbon is bonded to at least one hydrogen, R—C(=O)H.'),('ketone','A carbonyl group whose carbon is bonded to two carbon-containing groups, R—C(=O)—R.'),('carboxylic acid','R—C(=O)—OH; the OH is part of the acid group, not a second alcohol group.'),('ester','R—C(=O)—O—R; it contains a carbonyl and an adjacent single-bond oxygen.'),('amine','A nitrogen-containing group not directly attached to a carbonyl carbon, such as R—NH₂.'),('amide','A carbonyl group directly attached to nitrogen, R—C(=O)—N.'),('carbonyl','The C=O unit found in aldehydes, ketones, acids, esters, and amides.'),('hydrogen-bond donor','A molecule with H covalently bonded to electronegative N, O, or F.'),('hydrogen-bond acceptor','An electronegative atom with an available lone pair that can attract donor H.'),('dispersion force','An attraction present in all substances that generally grows with polarizability and contact area.')]
gloss['glossary']={'introduction':'Use these 18 terms to name structure patterns before reasoning about properties.','sections':[{'id':'sec-1','title':'Structure and properties','entries':[]} ]}
for i,(term,definition) in enumerate(terms,1): gloss['glossary']['sections'][0]['entries'].append({'id':f'ent-{i:02d}','term':term,'definition':definition,'drills':[item(i,f'What does {term} mean in a structure?',term,'fg-vocabulary')]})

worked = base(TOPIC+'-guided-worked-examples','Functional Group Introduction Guided Worked Examples','workedExample','learn','guidedWorkedExample'); worked['randomizeQuestions']=False; worked['workedExamples']=[]
examples=[('Identify from condensed notation','CH₃CH₂OCH₃','ether','The oxygen is single-bonded to two carbon-containing groups.'),('Separate aldehyde from ketone','CH₃C(=O)H','aldehyde','The carbonyl carbon has a hydrogen attached.'),('Find the boundary in an ester','CH₃C(=O)OCH₂CH₃','ester','The carbonyl carbon is directly bonded to an oxygen that is bonded to another carbon group.'),('Avoid double counting an acid','CH₃C(=O)OH','carboxylic acid','The OH is part of the single carboxylic-acid neighborhood.'),('Recognize multiple groups','CH₂=CHCH₂OH','alkene and alcohol','The chain has both C=C and C—OH neighborhoods.'),('Compare properties','ethanol versus hexanol in water','ethanol is generally more soluble','Both have one OH, but the larger hydrocarbon portion in hexanol makes the nonpolar contribution larger.')]
for i,(title,given,answer,why) in enumerate(examples,1): worked['workedExamples'].append({'id':f'example-{i:02d}','title':title,'problem':f'Analyze {given}.','steps':[{'id':'step-1','title':'Trace connectivity','instruction':'Mark the directly connected atoms and bond orders.','type':'freeResponse','prompt':'What local bonds should be marked first?','answer':{'gradingMode':'selfCheck','keyPoints':['Mark the connected atoms and bond order named in the prompt.']},'explanation':'Solution: Mark the local bonds. Why it works: Connectivity determines the classification.'},{'id':'step-2','title':'Classify','instruction':'Name the matching group.','type':'freeResponse','prompt':'What group is supported by that pattern?','answer':{'gradingMode':'selfCheck','keyPoints':[answer]},'explanation':f'Solution: {answer}. Why it works: {why}'},{'id':'step-3','title':'Verify boundary','instruction':'Check competing groups and property assumptions.','type':'freeResponse','prompt':'What boundary check prevents a competing classification?','answer':{'gradingMode':'selfCheck','keyPoints':['Check the neighboring atom and carbonyl boundary.']},'explanation':'Solution: Check the neighboring atom and carbonyl boundary. Why it works: This catches look-alike classifications.'}],'media':[{'type':'image','src':'/media/chemistry/chem-functional-groups-map.svg','alt':'Original connectivity reference with visible bonds.','caption':None}]})

specs=[
('read','Which representation explicitly shows every hydrogen in CH₃CH₂OH?',['expanded formula','condensed formula','R notation only','molecular formula'],'a'),('read','In R—O—R, what does each R stand for?',['a carbon-containing remainder','an oxygen atom','a required ring','a hydrogen only'],'a'),('alkyne','Which pattern identifies an alkyne?',['C≡C','C=C','C—O—C','C=O'],'a'),('haloalkane','Which pattern identifies a haloalkane?',['C—Cl','C—O—H','C(=O)—H','C—N—C'],'a'),('alcohol','Which is an alcohol?',['CH₃CH₂OH','CH₃OCH₃','CH₃COOH','CH₃COOCH₃'],'a'),('ether','Which is an ether?',['CH₃OCH₃','CH₃CH₂OH','CH₃CHO','CH₃CONH₂'],'a'),('aldehyde','Which is an aldehyde?',['CH₃CHO','CH₃COCH₃','CH₃COOH','CH₃COOCH₃'],'a'),('ketone','Which is a ketone?',['CH₃COCH₃','CH₃CHO','CH₃CH₂OH','CH₃NH₂'],'a'),('acid','Which is a carboxylic acid?',['CH₃COOH','CH₃OCH₃','CH₃CHO','CH₃CONH₂'],'a'),('ester','Which is an ester?',['CH₃COOCH₃','CH₃COOH','CH₃OCH₃','CH₃CONH₂'],'a'),('amine','Which is an amine rather than an amide?',['CH₃CH₂NH₂','CH₃CONH₂','CH₃COOH','CH₃CHO'],'a'),('amide','Which connectivity marks an amide?',['C(=O)—N','C—O—C','C(=O)—H','C—N without carbonyl'],'a'),('boundary','Why is phenol not classified as an ordinary alcohol in this lesson?',['OH is directly attached to an aromatic ring','it contains no oxygen','it always contains a carbonyl','it is an ether'],'a'),('boundary','What is the decisive difference between ether and ester?',['ester has a carbonyl adjacent to its oxygen','ether has a nitrogen','ester has no oxygen','ether has a C≡C'],'a'),('boundary','What distinguishes aldehyde from ketone?',['aldehyde carbonyl carbon has at least one H','ketone has no carbonyl','aldehyde must contain N','ketone must contain O—H'],'a'),('property','Which molecule can donate a hydrogen bond?',['CH₃CH₂OH','CH₃OCH₃','CH₃CH₃','CH₃Cl'],'a'),
]
practice=base(TOPIC+'-focused-practice','Functional Group Introduction Focused Practice','quiz','practice','focusedPractice'); practice['questions']=[]; practice['attemptQuestionCount']=24
for i,(obj,prompt,opts,ans) in enumerate(specs,1): practice['questions'].append(q(f'{TOPIC}-focused-practice-q{i:03d}',prompt,dict(zip('abcd',opts)),ans,'fg-'+obj,False,f'practice-{i}'))
hard_specs=[('property','Which is likely least soluble in water?',['methanol','ethanol','1-propanol','1-hexanol'],'d'),('multi','A molecule contains C=C, C—OH, and C—O—C. How many named groups from this lesson are present?',['one','two','three','four'],'c'),('multi','In R—C(=O)—O—R, which two local features must be seen before calling it an ester?',['carbonyl plus adjacent single-bond oxygen','C≡C plus N','OH plus aromatic ring','C=O plus N'],'a'),('property','Two same-sized molecules are compared: one has an alcohol and one is a hydrocarbon. Which explanation is best?',['alcohol is more polar and can hydrogen bond','hydrocarbon always has stronger H bonds','alcohol is nonpolar','size alone proves equal solubility'],'a'),('boundary','A structure has R—C(=O)—OH. Which count is correct?',['one carboxylic acid and zero separate alcohol groups','one acid and one alcohol','one ether and one alcohol','one ketone and one alcohol'],'a'),('multi','Which molecule contains both an amide and an alkene?',['CH₂=CHCONH₂','CH₃COOCH₃','CH₃CH₂NH₂','CH₃CHO'],'a'),('property','Why can a longer-chain alcohol become less water-soluble despite retaining O—H?',['the growing hydrocarbon region contributes more nonpolar character','the O—H bond disappears','dispersion forces vanish','the molecule loses all polarity'],'a'),('multi','Which sequence correctly classifies CH₃CH₂C(=O)OCH₃?',['ester, because C=O is attached to O—CH₃','ether, because it has oxygen','acid, because it has C=O','amide, because it has a heteroatom'],'a')]
for j,(obj,prompt,opts,ans) in enumerate(hard_specs,17): practice['questions'].append(q(f'{TOPIC}-focused-practice-q{j:03d}',prompt,dict(zip('abcd',opts)),ans,'fg-'+obj,True,f'practice-{j}'))

recall=base(TOPIC+'-mixed-recall','Functional Group Introduction Mixed Recall','recallDrill','recall','mixedRecallSet'); recall['randomizeQuestions']=False; recall['items']=[]
recall_prompts=[('Name the group containing C=C.','alkene'),('Name the group containing C≡C.','alkyne'),('Name C—X where X is a halogen.','haloalkane'),('Name R—OH.','alcohol'),('Name R—O—R.','ether'),('Name R—C(=O)H.','aldehyde'),('Name R—C(=O)—R.','ketone'),('Name R—C(=O)—OH.','carboxylic acid'),('Name R—C(=O)—O—R.','ester'),('Name R—C(=O)—N.','amide'),('Name R—NH₂ when no carbonyl is adjacent.','amine'),('What does R denote?','carbon-containing remainder'),('What atom pattern enables hydrogen donation?','H bonded to N, O, or F'),('What force exists in all molecules?','dispersion force'),('What local unit is shared by acid, ester, and amide?','carbonyl'),('Does an acid OH count as a separate alcohol here?','no'),('Which is more polar: hydrocarbon or alcohol?','alcohol'),('What happens to solubility as a hydrocarbon tail grows?','often decreases'),('What distinguishes an ester from an ether?','ester has adjacent carbonyl'),('What distinguishes an amide from an amine?','amide has carbonyl attached to N')]
for i,(p,a) in enumerate(recall_prompts,1): recall['items'].append(item(i,p,a,'fg-recall'))

master=base(TOPIC+'-mastery-check','Functional Group Introduction Mastery Check','test','evaluate','masteryCheck'); master['attemptQuestionCount']=12; master['questions']=[]
master_specs=[('representation','Which shorthand is equivalent to CH₃CH₂CH₂OH?',['R—OH with R=C₃H₇','R—O—R','R—C(=O)—OH','R—C≡C—R'],'a'),('recognition','Which structure is an aldehyde?',['CH₃C(=O)H','CH₃C(=O)CH₃','CH₃C(=O)OH','CH₃C(=O)OCH₃'],'a'),('recognition','Which structure is an amide?',['CH₃C(=O)NH₂','CH₃CH₂NH₂','CH₃OCH₃','CH₃CHO'],'a'),('boundary','Which statement is correct?',['An ester has a carbonyl directly adjacent to an oxygen linked to carbon','Every C—O bond is an alcohol','A ketone carbonyl must have H attached','An acid OH is a separate alcohol group'],'a'),('property','Which has the strongest direct evidence for hydrogen-bond donation?',['R—OH','R—O—R','R—Cl','R—C(=O)—R'],'a'),('multi','Which molecule contains an alkene and an alcohol?',['CH₂=CHCH₂OH','CH₃COOH','CH₃COOCH₃','CH₃CONH₂'],'a'),('multi','Which local patterns are present in CH₃COOCH₂CH₃?',['carbonyl and ester','alkene and alcohol','amine and ketone','alkyne and ether'],'a'),('property','Which trend is most defensible for equal-sized molecules?',['a polar OH-containing molecule is often more water-compatible than a hydrocarbon','nonpolar hydrocarbons hydrogen-bond best','size is irrelevant to solubility','all oxygen groups have identical properties'],'a')]
for i,(obj,prompt,opts,ans) in enumerate(master_specs,1): master['questions'].append(q(f'{TOPIC}-mastery-check-q{i:03d}',prompt,dict(zip('abcd',opts)),ans,'fg-'+obj,False,f'mastery-{i}'))
hard_master=[('transfer','A molecule has a carbonyl bonded to O—CH₃ and also C=C elsewhere. Which groups are present?',['ester and alkene','acid and alcohol','amide and alkyne','ketone only'],'a'),('transfer','Which molecule should generally have the lowest water solubility?',['CH₃OH','CH₃CH₂OH','CH₃CH₂CH₂OH','CH₃(CH₂)₅OH'],'d'),('transfer','A learner calls R—C(=O)—OH “a ketone plus an alcohol.” What correction is best?',['It is one carboxylic-acid group; the OH is part of that group','It is an ether','It has no carbonyl','It is an amide'],'a'),('transfer','Which comparison uses both connectivity and property reasoning?',['An amide has C=O—N, while an amine lacks that adjacent carbonyl','An ether is any molecule with oxygen','An alkene is polar because it has two carbons','A hydrocarbon always dissolves in water'],'a')]
for j,(obj,prompt,opts,ans) in enumerate(hard_master,9): master['questions'].append(q(f'{TOPIC}-mastery-check-q{j:03d}',prompt,dict(zip('abcd',opts)),ans,'fg-'+obj,True,f'mastery-{j}'))

for data in [lesson,gloss,worked,recall,practice,master]:
    path=OUT/(data['id']+'.yaml'); path.write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=120), encoding='utf-8')

# Tracked S2C packet and blueprints.
packet={'id':PACKET,'title':'Functional group introduction minimal source packet','sourceId':SOURCE,'categoryId':'chemistry','topicId':TOPIC,'sourceChunks':chunks,'constraints':['recognition and basic properties only','exclude mechanisms, synthesis, comprehensive nomenclature, spectroscopy, stereochemistry'],'pageImageReview':{'state':'approved','pages':[1049,1050,1051,1053,1054],'method':'Rendered private PDF pages at 120 dpi; human-reviewed the connectivity diagrams/Table 24.6 and recorded original paraphrase patterns before drafting.'}}
(ROOT/'docs/assessment-reference/packets'/f'{PACKET}.json').parent.mkdir(parents=True,exist_ok=True); (ROOT/'docs/assessment-reference/packets'/f'{PACKET}.json').write_text(json.dumps(packet,indent=2),encoding='utf-8')
manifest={'schemaVersion':1,'id':TOPIC+'-curriculum-manifest','sourceId':SOURCE,'sourceHash':'91ea51b0d87198f48679412a77bb9010f3296279b00b92b4a9e01ebcb37e6d0e','extractionGate':{'status':'passed','extractor':'pypdf-v1','chunkCount':5112,'actualChunkCount':5112,'diagramReview':'approved'},'categoryId':'chemistry','areaId':'chemistry-chemical-bonds-compounds','topicId':TOPIC,'prerequisites':['chem-covalent-bonds','chem-lewis-dot-structures','chem-polar-bonds-molecules'],'objectives':[{'id':'fg-read-structures','title':'Read representations and R notation'},{'id':'fg-recognize-hydrocarbon-halogen','title':'Recognize alkene, alkyne, and haloalkane'},{'id':'fg-recognize-oxygen-nitrogen','title':'Recognize oxygen and nitrogen groups'},{'id':'fg-distinguish-boundaries','title':'Distinguish competing classifications'},{'id':'fg-property-reasoning','title':'Explain polarity, hydrogen bonding, and size effects'}],'requiredActivities':[x['id'] for x in [lesson,gloss,worked,recall,practice,master]],'reviewState':'approved-for-internal-derivation'}
manifest={'schemaVersion':1,'id':TOPIC+'-curriculum-manifest','sourceId':SOURCE,'sourceHash':'91ea51b0d87198f48679412a77bb9010f3296279b00b92b4a9e01ebcb37e6d0e','extractionGate':{'status':'passed','extractor':'pypdf-v1','chunkCount':5112,'actualChunkCount':5112,'diagramReview':'approved'},'categoryId':'chemistry','areaId':'chemistry-chemical-bonds-compounds','topicId':TOPIC,'prerequisites':['chem-covalent-bonds','chem-lewis-dot-structures','chem-polar-bonds-molecules'],'objectives':[{'id':'fg-read-structures','title':'Read representations and R notation'},{'id':'fg-recognize-hydrocarbon-halogen','title':'Recognize alkene, alkyne, and haloalkane'},{'id':'fg-recognize-oxygen-nitrogen','title':'Recognize oxygen and nitrogen groups'},{'id':'fg-distinguish-boundaries','title':'Distinguish competing classifications'},{'id':'fg-property-reasoning','title':'Explain polarity, hydrogen bonding, and size effects'}],'requiredActivities':[x['id'] for x in [lesson,gloss,worked,recall,practice,master]],'blueprintIds':[practice['id']+'-blueprints',master['id']+'-blueprints',recall['id']+'-blueprints'],'reviewState':'approved-for-internal-derivation'}
(ROOT/'docs/assessment-reference/curriculum-manifests'/f'{TOPIC}.yaml').parent.mkdir(parents=True,exist_ok=True); (ROOT/'docs/assessment-reference/curriculum-manifests'/f'{TOPIC}.yaml').write_text(yaml.safe_dump(manifest,sort_keys=False,allow_unicode=True,width=120),encoding='utf-8')

def blueprint_for(data):
    records=[]
    for qq in data.get('questions',[]):
        b=qq.pop('_blueprint',None)
        if not b: continue
        records.append({'id':f"{data['id']}-{qq['id']}-bp",'assessmentId':data['id'],'questionId':qq['id'],'objectiveId':b['objectiveId'],'sourceChunks':chunks[:3] if b['objectiveId'] != 'fg-property' else chunks[-3:],'reviewState':'approved','questionType':qq['type'],'givens':qq['prompt'],'unknown':'functional-group classification or qualitative property relation','representationRequirement':'Trace every explicitly shown bond and local neighborhood.','governingPrinciple':'Classify by the directly connected atoms and bond orders; then compare polar and nonpolar contributions when properties are asked.','methodSteps':['translate the representation','isolate the local connectivity','name the matching group','check competing boundaries and property assumptions'],'likelyMisconception':'confusing an oxygen or nitrogen atom label with the complete connected functional group','difficultyEvidence':qq['difficultyEvidence'],'answerVerificationMethod':'Independent connectivity redraw and group-boundary check; property items checked against donor/acceptor and hydrocarbon-size reasoning.','variationAxes':b['variation'],'reasoningSignature':b['sig'],'difficultyDimensions':qq['difficultyDimensions'],'prerequisiteObjectiveIds':qq['prerequisiteObjectiveIds'],'extensionObjectiveIds':qq['extensionObjectiveIds']})
    return {'schemaVersion':1,'id':data['id']+'-blueprints','categoryId':'chemistry','topicId':TOPIC,'assessmentId':data['id'],'packetId':PACKET,'blueprints':records}
for data in [practice,master]: (BLUE/(data['id']+'-blueprints.yaml')).write_text(yaml.safe_dump(blueprint_for(data),sort_keys=False,allow_unicode=True,width=120),encoding='utf-8')

recall_records=[]
for i,(prompt,answer) in enumerate(recall_prompts,1):
    recall_records.append({'id':f'{recall["id"]}-dr-{i:02d}-bp','assessmentId':recall['id'],'questionId':f'dr-{i:02d}','objectiveId':'fg-recall','sourceChunks':chunks[:3],'reviewState':'approved','questionType':'flashcard','givens':prompt,'unknown':answer,'representationRequirement':'Name the local atom-and-bond pattern or property vocabulary.','governingPrinciple':'Use the defining connectivity pattern and distinguish whole groups from component atoms.','methodSteps':['locate the named atoms or bond','compare the pattern with the vocabulary definition'],'likelyMisconception':'naming an atom or bond without checking its connected neighbors','difficultyEvidence':'Recall is checked against a distinct structural or property definition.','answerVerificationMethod':'Independent definition and connectivity review.','variationAxes':['group boundary','prompt form'],'reasoningSignature':f'recall-{i}'})
(BLUE/(recall['id']+'-blueprints.yaml')).write_text(yaml.safe_dump({'schemaVersion':1,'id':recall['id']+'-blueprints','categoryId':'chemistry','topicId':TOPIC,'assessmentId':recall['id'],'packetId':PACKET,'blueprints':recall_records},sort_keys=False,allow_unicode=True,width=120),encoding='utf-8')
