// Numbered reference and companion use-guide share one equation inventory.
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(__dirname,'build_two_page_reference.cjs'),'utf8');
const {sections,css,M}=new Function('require','__dirname',source.slice(0,source.indexOf('const html='))+';return {sections,css,M};')(require,__dirname);
const {chromium}=require('C:/Users/SeanS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
// One identifier per printed equation row; linked equalities share the identifier.
const guide=[
[
['Electrostatic constants','Use kₑ in Coulomb force, field, and potential; use ε₀ in Gauss law and vacuum capacitance. They encode the same interaction strength because kₑ = 1/(4πε₀).','Do not substitute G for kₑ. Convert charges to coulombs and lengths to metres first.'],
['Elementary charge, gravity, and charge counting','Use e to convert an electron count into net charge: N extra electrons gives q = −Ne when N is a positive count. The sheet instead defines N as a signed integer. Use G for gravitational attraction.','Neutral means equal positive and negative charge. It does not mean the object contains no charged particles.'],
['Conservation and vector reconstruction','Use charge conservation for transfer between objects in an isolated system. After adding electric-field components, use the square root to find magnitude and atan2 to find the correct direction quadrant.','A zero vector total may result from cancellation of nonzero contributions. atan2(Ey,Ex) is not simply arctan(Ey/Ex) in every quadrant.']
],
[
['Point-charge fields and test-charge force','Given charges at coordinates, form each displacement Rᵢ from its source to the observation point. Evaluate each vector contribution, add them, and multiply by q₀ if force is requested. This handles both 1D and 2D.','Rᵢ/|Rᵢ|³ includes direction and inverse-square magnitude. A negative source reverses its field; a negative test charge reverses its force relative to the total field.'],
['Two-body electric force and gravity','Use FC for the magnitude between two point charges. Use Fg for gravitational attraction between masses and Ug for their gravitational potential energy with zero at infinity.','The absolute value in FC discards direction, so supply attraction or repulsion separately. Ug is negative for positive masses; force and energy have different powers of distance.']
],
[
['Choose a charge element','Use λq dl for a wire, σ dA for a sheet, or ρq dV for a volume. Integrate dq for total charge, or integrate the vector dE for the field at a specified point.','These are alternative descriptions of the source, not three densities to multiply together. Distance R and direction generally vary over the source.'],
['Field of a finite rod on its perpendicular bisector','Use this integral/result for a uniform rod from −L to L, observed at (0,a). Equal elements cancel horizontal components and reinforce vertical components; the projection supplies the extra factor a/R.','Do not use this result at an arbitrary off-axis point. The denominator power 3/2 includes both inverse-square distance and the component projection.'],
['Trigonometric substitution','When a²+x² occurs under a root, put x = a tanθ. Transform both dx and R, then replace the x bounds with angular bounds. This reduces the rod integral to a cosine integral.','θ is the angle from the perpendicular through the rod midpoint. Forgetting the sec²θ factor in dx gives the wrong integral.'],
['Evaluate and check the rod integral','The endpoint angle is θ₀ = arctan(L/a). Integrating cosine between ±θ₀ gives twice sinθ₀; sinθ₀ = L/√(a²+L²) restores the finite-rod result.','For L much larger than a, recover an infinite line. For a much larger than L, recover a point charge with Q = 2Lλq.']
],
[
['Flux integral and Gauss law','Use the open-surface integral for flux through any surface and EA cosθ only when the field and angle are uniform. Use the closed integral to relate total outward flux to net enclosed charge.','θ is measured from the surface normal. Zero net flux does not imply zero local field. An external charge contributes zero net closed-surface flux.'],
['Line, sheet, and spherical symmetry','Choose the line formula for an effectively infinite uniform line, the sheet formula for an infinite nonconducting sheet, and the spherical formula when the charge distribution is spherically symmetric.','Gauss law always holds, but these direct field formulas require symmetry. A conducting surface has σ/ε₀ just outside, not σ/(2ε₀).'],
['Enclosed charge and uniform solid sphere','For a radially varying density, integrate concentric shells of volume 4πs² ds to the Gaussian radius. For constant density, use the linear interior field and inverse-square exterior field.','Inside use only charge within r; outside use the whole sphere of radius R. The two uniform-sphere formulas agree at r = R.'],
['Uniform solid cylinder','Use the interior/exterior expressions for an infinitely long uniformly volume-charged cylinder of radius R. Cylindrical Gaussian area grows with r while enclosed interior charge grows with r².','A conducting cylinder is different: the field inside its metal is zero. For coaxial shells, compute the signed enclosed charge separately in each radial region.']
],
[
['Conductor equilibrium','Use Emetal = 0 inside conducting material at electrostatic equilibrium. At its surface the tangential component is zero and the outward normal field just outside in vacuum is σ/ε₀.','A cavity containing charge can have a field even though the surrounding metal does not. The surface field sign follows the signed surface density.'],
['Potential from sources or a field','For point charges or a continuous source, sum/integrate scalar potentials with zero at infinity where that reference is valid. If E is known instead, integrate −E·dl between two locations.','Potential contributions add with charge signs but without vector components. For an infinite line, use a finite reference potential difference rather than zero at infinity.'],
['Potential slope, energy, and charge pairs','Use E = −∇V to get a field from a spatial potential function; use the partial derivative for one component. U = qV uses the external potential at a test charge; U12 is pair interaction energy.','Do not include a charge’s own potential in qV. If summing pair energies for many charges, count each pair once. Field points toward decreasing V.'],
['Work and particle speed','Use WE = −qΔV for electric work. If only electric work changes kinetic energy, set ΔK = −qΔV and use K = ½mv² to find a speed or turning point.','Work-energy gives speed, not the full velocity direction. If another force does work, include its contribution rather than using ΔK = −qΔV alone.']
],
[
['Uniform ring on its axis','Use these expressions for a ring of radius R and total charge Q, observed a signed axial distance z from its center. Transverse fields cancel; the axial field changes sign with z.','At the center the field is zero but the potential is generally nonzero. Far from the ring both reduce to point-charge behavior.'],
['Uniform disk on its axis','Use the disk field on the positive axis for uniform surface density σ. One derivation adds rings of charge, each contributing its axial field.','This formula states z > 0. On the other side reverse the direction appropriately. A disk much wider than z approaches the infinite-sheet result.'],
['Force from an interaction-energy curve','Differentiate U with respect to outward separation r and change the sign. In the Lennard–Jones model, the short-range r⁻¹² energy term creates repulsion while the negative r⁻⁶ term creates attraction farther out.','Equilibrium is a zero slope, not zero energy. A local minimum is stable. C12 and C6 are material-specific constants, not electric charges.'],
['Arc center and solid-sphere potential','For a uniform arc of total angle 2α, use the arc result at its center; symmetry leaves a field along the bisector. For a uniform solid sphere, use the potential result at r < R with zero at infinity.','The arc expression gives a signed bisector component for a chosen orientation; use an absolute value for magnitude. The solid-sphere result joins kₑQ/R at the surface.']
],
[
['Capacitance definition, plates, and combinations','Use C = Q/ΔV for charge storage, εA/d for large parallel plates, and the combination rules to simplify networks. Parallel elements share voltage; a simple isolated series chain has equal charge magnitude.','C is geometry/material dependent, not proportional to Q when voltage changes on the same ideal capacitor. Use Q as the magnitude on either plate.'],
['Spherical and coaxial capacitors','Use the spherical result for concentric conducting shells of radii a and b; use the coaxial result for long coaxial cylinders of length L. Both assume the intervening dielectric is uniform.','a is the smaller radius. Fringing must be negligible for the coaxial expression. Let b tend to infinity to get the capacitance 4πεa of an isolated sphere.'],
['Stored energy and energy density','Integrate q/C as a capacitor is charged to Q to obtain its stored energy. Use the equivalent Q²/(2C) or C(ΔV)²/2 form depending on what is known; uE is energy per unit volume.','Decide what stays fixed: with a battery attached ΔV is fixed; disconnected Q is fixed. uE = εE²/2 assumes a linear, nondispersive dielectric in this electrostatic model.'],
['Polarization and electric displacement','Use P to describe dipole moment per volume and D to separate free charge from bound material charge. In a linear isotropic dielectric P is parallel to E, allowing D = εE.','D = εE is a material relation, not a universal law. χe = κ−1 is dimensionless; E has units V/m, while D and P have units C/m².']
],
[
['Dipole rotation and orientation energy','Use p = qd for separated equal and opposite charges, τ = p×E for torque, and U = −p·E for orientation energy. A uniform field can give zero net force but a nonzero turning effect.','d points from negative to positive charge. Parallel alignment minimizes energy; torque magnitude is pE sinθ and is zero for parallel or antiparallel orientations.'],
['Distant dipole fields and potential','Use the axial or equatorial field magnitude far from a small dipole, and the potential expression at polar angle θ measured from p. These approximate the difference between two nearly canceling point-charge sources.','Require r much larger than the charge separation. The equatorial field points opposite p; the axial field points along p. At the equator V = 0 does not imply E = 0.'],
['Newton law and derivative definitions','Start dynamics with the vector sum of forces equal to ma. Use a = dv/dt and v = dx/dt to move between acceleration, velocity, and position by differentiation or integration.','Net force, not just one force, determines acceleration. Initial values are needed when integrating; derivatives of position alone cannot recover those constants.'],
['Constant-acceleration motion','Use these kinematics formulas only when acceleration is constant along the chosen axis. Choose v = vi+at for time-to-speed, x(t) for displacement with time, and v² = vi²+2aΔx when time is absent.','Apply each component separately in 2D. The squared-speed relation loses the velocity sign, so direction must come from the physical motion.'],
['Deflection between parallel plates','For uniform transverse E, compute ay = qE/m. If no horizontal force acts, transit time is plate length ℓ divided by vx. With zero initial vertical speed and displacement, y = ½ayt².','This gives displacement while inside the plates. Beyond them, motion is straight at the exit velocity if no other forces act. Include gravity if it is not negligible.']
],
[
['Restoring force and natural period','Use Hooke law to obtain the SHM equation and ω₀ = √(ks/m). Period is 2π/ω₀. This identifies ideal mass-spring motion and supplies the starting point for a differential-equation derivation.','x is measured from equilibrium. ks is spring stiffness, not Coulomb’s constant or wave number. Greater mass increases period; greater stiffness decreases it.'],
['SHM position, velocity, and acceleration','Use the sinusoidal solution for an undamped oscillator; differentiate to get v and a. At a turning point speed is zero and restoring acceleration has its greatest magnitude.','φ sets the initial state. The velocity formula here corresponds to the displayed cosine displacement; do not change one phase convention without changing the derivatives.'],
['Energy at an oscillator position','Use Us for spring energy, K for kinetic energy at position x, and Etot for total energy fixed by amplitude A. This often gives speed without first solving for time.','These formulas assume ideal undamped SHM. x must lie between −A and A; K cannot be negative. At equilibrium energy is kinetic; at a turning point it is all spring energy.'],
['Pendulum period and driven-oscillator equation','Use the pendulum period for small angular oscillations of a simple pendulum. Use the driven differential equation when damping proportional to velocity and an external sinusoidal force are present.','Pendulum length ℓ runs from pivot to mass. Large-angle pendulum motion is not described by this amplitude-independent period. b is a damping coefficient, not a radius.'],
['Damped frequency and steady driven amplitude','Use ωd for free underdamped oscillations when b/(2m) < ω₀. Use Adrive for the steady-state amplitude at forcing frequency Ω, after startup transients have decayed.','Free damped motion and forced steady motion are different cases. With damping, the displacement-amplitude resonance is generally slightly below ω₀; at zero damping and exact resonance no finite steady amplitude exists.']
],
[
['Decode a sinusoidal traveling wave','Compare a supplied wave to A cos(kwx−ωt+φ). Read A, kw, ω, and φ directly; convert kw to wavelength and ω to frequency using 2π. Constant phase identifies direction.','For positive kw and ω, minus ωt travels toward +x. A plus sign travels toward −x. Do not confuse angular frequency ω with cycles per second f.'],
['Period and propagation speed','Use T = 1/f for period and vw = ω/kw = fλ for waveform speed. For an ideal stretched string use √(𝒯/μ) to connect speed to tension and mass per unit length.','The speed relation √(𝒯/μ) is string-specific. Source frequency can change while medium speed remains fixed; wavelength then adjusts.'],
['Motion of one point on the string','Hold x fixed and differentiate with respect to time to get transverse particle velocity and acceleration. Substitute the requested x and t only after taking the derivative.','vy is not wave speed vw. The positive sine in vy results from two minus signs: derivative of cosine and derivative of −ωt.'],
['Verify the linear wave equation','Differentiate twice in space and time. The same y appears with factors −kw² and −ω², yielding ∂t²y = vw²∂x²y when vw = ω/kw.','This verifies the harmonic solution. General traveling shapes f(x−vwt) also satisfy the constant-speed wave equation; the PDE does not require a sinusoidal source.'],
['Derive the string PDE and calculate mean power','For a short string element dx, small-slope tension forces give net transverse force 𝒯 yxx dx and mass μdx times acceleration. Cancel dx to derive the PDE. Use mean power for a sinusoidal traveling string wave.','Assume uniform tension and density, small slopes, negligible loss. Doubling amplitude quadruples mean power at fixed frequency and medium.']
],
[
['Phase difference and interference amplitude','Use the phase-difference expression to compare positions, times, or initial phases. For two equal-amplitude, same-frequency coherent waves, the cosine factor gives resultant amplitude.','Constructive interference has phase difference 2πm; destructive has (2m+1)π. The amplitude expression is not valid for arbitrary unequal amplitudes.'],
['Standing waves and two matching ends','Add equal opposite-traveling waves to get stationary nodes and antinodes. Use fn = nvw/(2L) for a string fixed at both ends or a pipe open at both ends, neglecting end corrections.','String fixed ends are displacement nodes. Open pipe ends are displacement antinodes and pressure nodes. Node spacing is λ/2; adjacent node-to-antinode distance is λ/4.'],
['One closed pipe end and beats','Use odd-n quarter-wave modes for an open-closed pipe. Use the absolute frequency difference for the slow loudness modulation produced by nearby frequencies.','The third harmonic of an open-closed pipe is n = 3; n = 2 is absent in the ideal model. Beat frequency is not the carrier pitch.'],
['Refraction and critical angle','Use Snell law for refraction at a stationary interface. With n = c/v, entering a higher-index medium bends toward the normal. Critical angle applies when crossing from higher to lower index.','Measure both angles from the normal. Frequency stays continuous. For sound, use sinθ₁/v₁ = sinθ₂/v₂ rather than assuming optical indices; total internal reflection requires a valid critical-angle geometry.'],
['String-junction reflection and transmission','Use these signed displacement-amplitude ratios at a junction of two ideal strings under the same tension. Incident motion travels from medium 1 toward medium 2; Z = 𝒯/v is the string impedance.','A negative rA means inversion. Amplitude ratios are not energy fractions: reflected power fraction is rA² and transmitted is (Z₂/Z₁)tA². A transmission amplitude greater than one need not violate energy conservation.']
],
[
['Sound speed and intensity','Use √(B/ρm) for longitudinal sound in a fluid. Use P/(4πr²) for an isotropic source without absorption; use the pressure or displacement forms for a progressive sinusoidal sound wave.','B here is bulk modulus, not magnetic field. The equality between pressure intensity and displacement intensity assumes the same medium and a traveling wave.'],
['Pressure amplitude, RMS, and level','Convert sinusoidal pressure amplitude to RMS by dividing by √2. Relate pressure amplitude to particle displacement through ρmvsωsm. Use β to express intensity relative to I₀.','Do not substitute peak pressure where RMS is required. I₀ is the conventional 10⁻¹² W/m² reference; a negative dB level simply means below that reference.'],
['Compare two sound levels','For intensity ratios use 10 log10; for pressure ratios in the same acoustic impedance use 20 log10 because intensity is proportional to pressure squared.','Pressure tripled means intensity multiplied by nine, and both calculations give +9.54 dB. The pressure-ratio equality needs the same medium/impedance.'],
['Doppler shift and induction reminder','Use Doppler for source/observer motion relative to the sound medium: positive vo points toward the source, positive vsrc toward the observer. The other two expressions describe magnetic flux and induced emf when flux changes.','Approach raises observed frequency. The sound formula assumes classical, subsonic motion along the line of propagation. Faraday’s minus sign expresses opposition to flux change; the displayed emf is for one loop (multiply by turns for identical linked flux).']
]
];
sections.forEach((s,i)=>{s.rows=s.formula.split('\\\\').map((formula,j)=>({id:`${i+1}.${j+1}`,formula,help:guide[i][j]}));if(s.rows.length!==guide[i].length)throw Error('Mapping mismatch '+s.title);});
const count=sections.reduce((n,s)=>n+s.rows.length,0);
const base=`<!doctype html><meta charset="utf-8"><style>${css}*{box-sizing:border-box}body{margin:0;color:#172e3e;font-family:Arial}@page{size:letter;margin:0}article{width:8.5in;height:11in;padding:.28in .32in;break-after:page}header{display:flex;justify-content:space-between;border-bottom:2px solid #216c74;padding-bottom:5px;font-weight:bold;font-size:13px;margin-bottom:6px}h2{background:#e8f1f3;font-size:12px;padding:4px 5px;margin:0 0 5px}p{font-size:11.3px;line-height:1.26;margin:5px 0}footer{border-top:1px solid #b9cbd0;padding-top:4px;margin-top:8px;font-size:8px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:13px}.col{min-width:0}section{margin-bottom:10px}.row{display:flex;align-items:center;gap:5px;min-width:0;line-height:1.85;font-size:12px}.eid{font:bold 9px Arial;color:#216c74;width:24px;flex-shrink:0}.math{min-width:0;flex:1}.katex{font-size:1em}.intro{font-size:10px;color:#425767}</style>`;
const numbered=base+[0,1].map(p=>{const ss=sections.filter(s=>s.page===p);return `<article><header><span>PHYSICS 2 · NUMBERED TEST REFERENCE</span><span>${p+1} / 2</span></header><p class="intro">Equation IDs: section.row (10.3 = Section 10, row 3). Linked equations on one row share an ID.</p><div class="cols">`+[ss.slice(0,3),ss.slice(3)].map(col=>'<div class="col">'+col.map(s=>`<section><h2>${s.title}</h2>${s.rows.map(r=>`<div class="row"><span class="eid">${r.id}</span><span class="math">${M(r.formula)}</span></div>`).join('')}<p>${s.legend}</p><p>${s.note}</p></section>`).join('')+'</div>').join('')+`</div><footer>Use the companion equation key to mark unfamiliar IDs. Bold = vector. kₑ: Coulomb constant; kₛ: spring stiffness; k𝑤: wave number. Print at 100%.</footer></article>`;}).join('');
const key=base+`<style>.entry{margin:6px 0 10px;border-bottom:1px solid #dbe4e8;padding-bottom:7px}.entry h3{font-size:12px;margin:0 0 3px}.tick{display:inline-block;width:10px;height:10px;border:1px solid #566e7b;margin-right:6px}.entry .row{font-size:13px;line-height:1.9}.entry p{font-size:11.5px;line-height:1.29;margin:4px 0}.mark{font-size:9px;color:#51636e}section{margin-bottom:13px}</style>`+sections.map((s,p)=>`<article><header><span>PHYSICS 2 · EQUATION USE KEY</span><span>${p+1} / ${sections.length}</span></header><p class="intro">Check the box beside an unfamiliar row; copy its ID onto your test reference. Each entry explains all equations on that row. The two-page reference retains the variable definitions.</p><section><h2>${s.title}</h2>`+s.rows.map(r=>`<div class="entry"><h3><span class="tick"></span>${r.id} · ${r.help[0]}</h3><div class="row"><span class="math">${M(r.formula)}</span></div><p><b>When and how:</b> ${r.help[1]}</p><p><b>Watch for:</b> ${r.help[2]}</p></div>`).join('')+'</section>'+`<footer>My priority IDs: ____________________________________________ &nbsp; Short reminder: ____________________________________________</footer></article>`).join('');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const [name,html,file]of [['numbered-reference',numbered,'Physics 2 - Two-Page Test Reference.pdf'],['equation-use-key',key,'Physics 2 - Equation Use Key.pdf']]){const location=path.join(__dirname,name+'.html');fs.writeFileSync(location,html);const pg=await browser.newPage();await pg.goto('file:///'+location.replace(/\\/g,'/'));await pg.evaluate(()=>document.fonts.ready);await pg.evaluate(()=>document.querySelectorAll('.math').forEach(e=>{const k=e.querySelector('.katex'),w=k.getBoundingClientRect().width;if(w>e.clientWidth)k.style.fontSize=e.clientWidth/w+'em';}));const audit=await pg.evaluate(()=>[...document.querySelectorAll('article')].map(a=>({bottom:a.querySelector('footer').getBoundingClientRect().bottom-a.getBoundingClientRect().top,limit:a.clientHeight,width:a.scrollWidth})));console.log(name,JSON.stringify(audit));if(audit.some(x=>x.bottom>x.limit-12||x.width>817))throw Error('Page overflow');await pg.pdf({path:path.join(root,'output/pdf',file),printBackground:true,preferCSSPageSize:true});await pg.close();}console.log('Mapped equation rows:',count);}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
