from pathlib import Path
import json, re, runpy, shutil
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.graphics.shapes import Drawing, Line, Circle, Rect, String, Polygon
from pypdf import PdfReader, PdfWriter

ROOT=Path(r'C:\Users\SeanS\Downloads\cir_app'); CANVAS=ROOT/'docs/reference/canvas_pages'; SCANS=ROOT/'docs/reference/reference-texts/Physics 2 scans Test 1'; OUT=ROOT/'output/pdf'; OUT.mkdir(parents=True,exist_ok=True)
old=OUT/'Conceptual Notes.pdf'; final=OUT/'Physics 2 Comprehensive Review Package.pdf'; supplement=ROOT/'scratch'/'review_supplement.pdf'

titles=[]
for p in CANVAS.glob('*.html'):
    if p.name.lower()!='pages list.html': titles.append(re.sub(r'\s+',' ',p.stem.split('：')[0]).strip())

topics=[
('01','Charge and conservation','Charge types, quantization, conservation, friction, contact, induction, conductors/insulators, electrostatics versus electrodynamics.','Q_total = constant','Choose the isolated system; electron transfer changes local charges by equal and opposite amounts; therefore the algebraic total is unchanged.','A neutral object can polarize without becoming net charged.','fill-in explain-phenomenon qualitative-prediction'),
('02','Coulomb force and electric fields','Inverse-square force, source/test charge roles, field direction, units, gravity analogy, and force from a field.','F = (1/(4 pi eps0)) (q1 q2/r^2) r_hat ; E = F/q_test','Start from the measured force; divide by a small test charge; the test charge disappears, leaving a field determined by the sources.','A negative test charge feels force opposite the electric field vector.','fill-in explain-phenomenon derivation'),
('03','Field lines, superposition, and vectors','Vector addition, components, symmetry cancellation, field-line density and direction, point-charge limits, dipole far-field behavior.','E_net = sum_i E_i','Write every source contribution at the same observation point; resolve x/y components; add components; check symmetry and limiting cases.','Field-line sketches encode direction and relative magnitude, not literal trajectories.','diagram-matching draw-phenomenon graph-interpretation'),
('04','Continuous charge distributions and integration','lambda, sigma, rho, dq elements, total charge, line/arc/ring/disk/sheet/cylinder geometry, trigonometric substitutions, differential reasoning.','dq = lambda dl = sigma dA = rho dV ; E = (1/(4 pi eps0)) integral dq r_hat/r^2','Partition into dq; express distance and direction geometrically; cancel symmetric components; integrate the surviving component over physical bounds.','Units are C/m, C/m^2, C/m^3 and N/C.','derivation draw-phenomenon fill-in'),
('05','Electric flux and Gauss law','Flux, area vectors, enclosed charge, closed surfaces, spherical/cylindrical/planar symmetry, and external-charge cancellation.','closed integral E dot dA = Q_enclosed/eps0','Orient dA outward; evaluate the dot product; choose a symmetry-matched surface so E is constant on useful parts; solve for E.','Zero net flux does not mean zero field at every point.','diagram-matching explain-phenomenon derivation'),
('06','Applications of Gauss law','Infinite line, sheet, sphere, nonuniform spherical charge, conductor surface, inside/outside field graphs.','E_line = lambda/(2 pi eps0 r) ; E_sheet = sigma/(2 eps0) ; E_sphere = Q_enclosed/(4 pi eps0 r^2)','Find Q_enclosed from the density and geometry, then divide by the flux-carrying area; test continuity and inside/outside limits.','A uniformly charged solid sphere has E proportional to r inside, but 1/r^2 outside.','derivation graph-interpretation qualitative-prediction'),
('07','Conductors, shielding, and induced charge','Electrostatic equilibrium, zero interior field, surface charge, cavities, shielding, pointed conductors, molecular induction.','E_inside metal = 0 ; E_just outside = sigma/eps0','Assume equilibrium; any interior or tangential field would move free charge. Surface rearrangement cancels it in the metal and fixes induced-charge constraints.','Do not mistake zero field in metal for zero field in a cavity containing charge.','draw-phenomenon explain-phenomenon fill-in'),
('08','Electric potential, energy, and equipotentials','V=U/q, work, potential differences, point and continuous sources, equipotential surfaces, E=-grad V.','V = (1/(4 pi eps0)) q/r ; E = -grad V ; delta U = q delta V','Use dU=-dW and dW=q E dot dl; cancel q to obtain dV=-E dot dl; component forms combine into the gradient relation.','E points toward decreasing potential; motion along an equipotential requires zero electric work.','fill-in diagram-matching qualitative-prediction derivation'),
('09','Capacitance and dielectrics','Capacitor geometry, series/parallel combinations, energy, battery-connected versus isolated cases, polarization and permittivity.','C = Q/V ; C_parallel = sum C_i ; 1/C_series = sum(1/C_i) ; U = 1/2 CV^2','For plates, Gauss law gives E=sigma/eps and geometry gives V=Ed; with Q=sigma A, C=eps A/d. Integrate dU=Vdq for stored energy.','A dielectric increases capacitance by polarizing and reducing the internal field for fixed free charge.','matching fill-in qualitative-prediction'),
('10','Dipoles, torque, polarization, and displacement','Dipole moment direction, torque, potential energy, polar/nonpolar molecules, P, D, susceptibility, free versus bound charge.','p = qd ; tau = p E sin(theta) ; U = -p dot E ; D = eps0 E + P','Opposite forces form a couple; the lever arm gives torque. Integrating torque gives energy; summing microscopic dipoles per volume gives P and D.','Parallel alignment is stable because it minimizes U.','diagram-matching explain-phenomenon derivation'),
('11','Oscillations and simple harmonic motion','Hooke law, SHM differential equation, amplitude, phase, period, x/v/a phase, energy, phasors, resonance background.','m x_ddot = -kx ; x = A cos(omega t+phi) ; omega=sqrt(k/m) ; E=1/2 kA^2','Insert Hooke law into Newton law; recognize that a sinusoid has second derivative -omega^2 times itself; identify omega^2=k/m.','At maximum displacement v=0 and acceleration points toward equilibrium.','graph-interpretation draw-phenomenon derivation'),
('12','Mechanical waves, interactions, and standing waves','Pulses, traveling wave translation, transverse/longitudinal motion, wave speed, linear wave equation, reflection, transmission, interference, standing waves.','y=A cos(kx-omega t+phi) ; v=f lambda ; y_xx=(1/v^2)y_tt ; L=n lambda/2','For x-vt, constant phase moves right. Differentiate twice to obtain the wave equation; apply endpoint conditions to select standing-wave wavelengths.','Frequency stays source-set across a boundary; speed and wavelength can change.','fill-in diagram-matching derivation draw-phenomenon'),
('13','Sound, intensity, spectra, hearing, and Doppler effect','Sound production/detection, compression and rarefaction, pressure amplitude, intensity, decibels, harmonics, noise, hearing, Doppler shift.','I=P/(4 pi r^2) ; beta=10 log10(I/I0)','Spread fixed power over spherical area; define a logarithmic ratio for level; compare wavefront arrival rate for approaching and receding motion.','Doubling distance quarters isotropic intensity; approach raises observed frequency.','fill-in graph-interpretation explain-phenomenon')]

def fig(i):
    d=Drawing(460,135); navy=colors.HexColor('#15324b'); teal=colors.HexColor('#287271'); red=colors.HexColor('#b64c4c'); gold=colors.HexColor('#d9942a'); gray=colors.HexColor('#778899'); d.add(Rect(0,0,460,135,fillColor=colors.HexColor('#f7fafc'),strokeColor=colors.HexColor('#d4e0e8')))
    labels=['Electron transfer and conservation','Point-charge force and field','Vector superposition and dipole','Element dq and integration','Closed Gaussian surface','Line, sheet, and sphere symmetry','Conductor shielding and induced charge','Equipotential map and field direction','Parallel-plate capacitor','Dipole torque and polarization','SHM phase and energy','Traveling wave and standing-wave modes','Sound pressure, spectrum, and Doppler']
    d.add(String(16,116,labels[i],fillColor=navy,fontSize=9))
    if i==0:
        d.add(Circle(120,65,20,fillColor=teal,strokeColor=navy)); d.add(Circle(340,65,20,fillColor=red,strokeColor=navy)); d.add(String(114,60,'-',fillColor=colors.white,fontSize=14)); d.add(String(334,60,'+',fillColor=colors.white,fontSize=14)); d.add(Line(145,65,315,65,strokeColor=gold,strokeWidth=2)); d.add(Polygon([315,65,305,70,305,60],fillColor=gold,strokeColor=gold)); d.add(String(190,42,'electron transfer',fillColor=navy,fontSize=8))
    elif i==1:
        d.add(Circle(120,65,16,fillColor=gold,strokeColor=navy)); d.add(Circle(340,65,16,fillColor=red,strokeColor=navy)); d.add(Line(137,65,323,65,strokeColor=navy,strokeWidth=1.5)); d.add(Polygon([323,65,313,70,313,60],fillColor=navy,strokeColor=navy)); d.add(String(166,83,'r',fillColor=navy,fontSize=10)); d.add(String(182,42,'attraction / repulsion follows sign',fillColor=navy,fontSize=8))
    elif i==2:
        d.add(Circle(150,65,14,fillColor=gold,strokeColor=navy)); d.add(Circle(310,65,14,fillColor=red,strokeColor=navy)); d.add(String(146,60,'+',fillColor=colors.white,fontSize=11)); d.add(String(306,60,'-',fillColor=colors.white,fontSize=11)); d.add(Line(166,65,294,65,strokeColor=teal)); d.add(Polygon([294,65,284,70,284,60],fillColor=teal,strokeColor=teal)); d.add(String(195,87,'p points from - to +',fillColor=navy,fontSize=8))
    elif i==3:
        d.add(Line(55,45,395,45,strokeColor=navy,strokeWidth=2)); d.add(Circle(185,45,5,fillColor=gold,strokeColor=gold)); d.add(Line(185,45,300,100,strokeColor=gray)); d.add(Circle(300,100,5,fillColor=red,strokeColor=red)); d.add(String(174,28,'dq',fillColor=navy,fontSize=8)); d.add(String(305,103,'P',fillColor=navy,fontSize=8)); d.add(String(200,120,'resolve dE before integrating',fillColor=navy,fontSize=8))
    elif i==4:
        d.add(Circle(230,65,42,fillColor=None,strokeColor=teal,strokeWidth=2)); d.add(Circle(230,65,6,fillColor=gold,strokeColor=gold));
        for x,y in [(230,107),(230,23),(188,65),(272,65)]: d.add(Line(230,65,x,y,strokeColor=gray)); d.add(Polygon([x,y,x-4,y-8,x+4,y-8],fillColor=gray,strokeColor=gray))
        d.add(String(140,15,'flux uses the outward area vector',fillColor=navy,fontSize=8))
    elif i==5:
        d.add(Rect(80,35,110,60,fillColor=None,strokeColor=teal)); d.add(Circle(135,65,6,fillColor=gold,strokeColor=gold)); d.add(String(88,103,'cylinder',fillColor=navy,fontSize=8)); d.add(Circle(325,65,30,fillColor=None,strokeColor=teal)); d.add(Circle(325,65,6,fillColor=gold,strokeColor=gold)); d.add(String(292,20,'sphere',fillColor=navy,fontSize=8)); d.add(Line(190,65,290,65,strokeColor=gray)); d.add(String(125,112,'match Gaussian surface to symmetry',fillColor=navy,fontSize=8))
    elif i==6:
        d.add(Rect(185,25,90,80,fillColor=colors.HexColor('#d8dde2'),strokeColor=navy)); d.add(Circle(230,65,5,fillColor=gold,strokeColor=gold)); d.add(Line(40,65,175,65,strokeColor=teal)); d.add(Polygon([175,65,165,70,165,60],fillColor=teal,strokeColor=teal)); d.add(Line(285,65,420,65,strokeColor=teal)); d.add(Polygon([420,65,410,70,410,60],fillColor=teal,strokeColor=teal)); d.add(String(196,57,'E=0 in metal',fillColor=navy,fontSize=8))
    elif i==7:
        for x in [110,165,220,275,330]: d.add(Circle(x,65,18,fillColor=None,strokeColor=teal)); d.add(Line(75,65,365,65,strokeColor=gold,strokeWidth=1.5)); d.add(Polygon([365,65,355,70,355,60],fillColor=gold,strokeColor=gold)); d.add(String(170,22,'E is perpendicular to equipotentials',fillColor=navy,fontSize=8))
    elif i==8:
        d.add(Line(190,28,190,105,strokeColor=navy,strokeWidth=5)); d.add(Line(270,28,270,105,strokeColor=navy,strokeWidth=5));
        for y in [42,58,74,90]: d.add(Line(200,y,260,y,strokeColor=teal)); d.add(Polygon([260,y,252,y+4,252,y-4],fillColor=teal,strokeColor=teal)); d.add(String(183,113,'+ plate',fillColor=navy,fontSize=8)); d.add(String(265,113,'- plate',fillColor=navy,fontSize=8))
    elif i==9:
        d.add(Circle(180,65,12,fillColor=teal,strokeColor=navy)); d.add(Circle(280,65,12,fillColor=red,strokeColor=navy)); d.add(Line(195,65,265,65,strokeColor=gold)); d.add(Polygon([265,65,255,70,255,60],fillColor=gold,strokeColor=gold)); d.add(Line(230,65,230,105,strokeColor=navy)); d.add(Polygon([230,105,225,95,235,95],fillColor=navy,strokeColor=navy)); d.add(String(180,24,'torque rotates p toward E',fillColor=navy,fontSize=8))
    elif i==10:
        d.add(Line(35,65,420,65,strokeColor=gray)); import math; prev=None
        for n in range(101):
            x=35+n*3.8; y=65+35*math.cos(n*2*math.pi/50)
            if prev:d.add(Line(prev[0],prev[1],x,y,strokeColor=teal,strokeWidth=2))
            prev=(x,y)
        d.add(String(190,18,'x, v, and a share a period but differ in phase',fillColor=navy,fontSize=8))
    elif i==11:
        d.add(Line(35,65,420,65,strokeColor=gray)); import math; prev=None
        for n in range(101):
            x=35+n*3.8; y=65+35*math.sin(n*2*math.pi/50)
            if prev:d.add(Line(prev[0],prev[1],x,y,strokeColor=teal,strokeWidth=2))
            prev=(x,y)
        d.add(String(174,18,'phase translates; boundary conditions create nodes',fillColor=navy,fontSize=8))
    else:
        for x in [95,125,155,265,295,325,355]: d.add(Line(x,35,x,100,strokeColor=teal,strokeWidth=3)); d.add(Line(55,25,400,25,strokeColor=gray)); d.add(String(175,110,'compression / rarefaction',fillColor=navy,fontSize=8))
    return d

def page_num(c,doc):
    c.setFont('Helvetica',7); c.setFillColor(colors.HexColor('#536575')); c.drawString(.55*inch,.35*inch,'Physics 2 Comprehensive Review Package'); c.drawRightString(7.95*inch,.35*inch,str(doc.page))

explain={
'Charge and conservation':['Charge is a signed, quantized property carried mainly by protons and electrons. A neutral object has equal positive and negative charge, not an absence of charge.','Charging by friction or contact transfers electrons; charging by induction separates charge inside an object and requires grounding to leave a net charge.','Conservation applies to the complete isolated system: one object gaining electrons means another loses the same electrons. Electrostatics describes settled charges; electrodynamics describes charge in motion or changing fields.'],
'Coulomb force and electric fields':['Coulomb law gives the force between point charges. The force acts along the line joining the charges, attracts unlike signs, repels like signs, and falls as 1/r^2.','Electric field is force per unit positive test charge. It belongs to the source arrangement, while the actual force on a charge is F=qE and reverses direction for q<0.','The gravity analogy is useful for the inverse-square geometry, but electric charge has two signs and can produce either attraction or repulsion.'],
'Field lines, superposition, and vectors':['Superposition means calculate each source field at the observation point and add the vectors. Components cancel or reinforce according to geometry; magnitudes alone are not enough.','Field lines are a drawing convention: the tangent gives the direction for a positive test charge, and line density represents relative strength. Lines never cross.','Dipole fields show cancellation clearly: far away, the fields of +q and -q nearly cancel, so the remaining field decreases faster with distance than a single-charge field.'],
'Continuous charge distributions and integration':['A continuous charge distribution is handled by dividing the source into elements dq. Use dq=lambda dl, sigma dA, or rho dV according to whether charge lies on a line, surface, or volume.','For each element, write its distance and direction to the field point, resolve the vector into components, and integrate over the actual source limits.','Symmetry is part of the solution: paired elements can cancel one component before integration. Trigonometric substitutions simplify the distance factor, but never replace the geometry or bounds.'],
'Electric flux and Gauss law':['Flux is the field component normal to a surface multiplied by area, summed over the surface. The area vector points outward on a closed surface.','Gauss law says net closed-surface flux measures enclosed charge. External charges can change the field at individual patches but add zero net flux because their field enters and leaves the surface.','Gauss law becomes a practical field solver only when symmetry makes E constant on a chosen Gaussian surface or makes parts of the flux zero.'],
'Applications of Gauss law':['For an infinite line, cylindrical area grows as r, giving E proportional to 1/r. For a sphere, area grows as r^2, giving the familiar inverse-square outside field.','Inside a uniformly charged solid sphere, enclosed charge grows as r^3 while Gaussian area grows as r^2, so E grows linearly with r.','The same procedure works for sheets, shells, and conductors: determine enclosed charge first, then use the surface on which symmetry controls the flux.'],
'Conductors, shielding, and induced charge':['Free charges in a conductor move until the electric field inside the metal is zero. Any remaining tangential field would continue driving surface charge, so the equilibrium field is normal to the surface.','Excess charge resides on surfaces. A charge in a cavity induces opposite charge on the inner wall; a neutral conductor then places compensating charge on its outer surface.','A closed conductor shields its cavity from external static fields. Sharp points have high surface-charge density and therefore unusually large nearby fields.'],
'Electric potential, energy, and equipotentials':['Potential V is scalar energy per charge, so point-charge potentials add algebraically. Potential differences are physical even though the zero of V is chosen by convention.','The field does work when a charge moves through a potential difference: delta U=q delta V. Equipotential motion has delta V=0 and therefore zero electric work.','E=-grad V means the field points in the direction of steepest decrease of potential. Closely spaced equipotentials indicate a stronger field.'],
'Capacitance and dielectrics':['Capacitance is the charge stored per potential difference, determined by geometry and dielectric material. Parallel plates have C=epsilon A/d when edge fringing is negligible.','Parallel capacitors share voltage and add capacitance; series capacitors share charge magnitude and add reciprocals. The battery-connected or isolated condition determines what changes when a dielectric is inserted.','A dielectric polarizes: bound charges reduce the internal field for fixed free charge and allow more charge to be stored at the same voltage. Stored energy is energy in the electric field.'],
'Dipoles, torque, polarization, and displacement':['A dipole has equal and opposite charges separated by d, with p=qd directed from negative to positive. In a uniform field, opposite forces can cancel while their separated lines of action create torque.','Torque aligns p with E, and U=-p dot E makes parallel alignment stable. In a nonuniform field, a dipole can also translate toward stronger field.','Polarization P is dipole moment per volume. D=epsilon0 E+P separates the free-charge bookkeeping from the material response; P and bound charge are not additional free charge.'],
'Oscillations and simple harmonic motion':['SHM requires a restoring acceleration proportional to displacement: x double-dot=-omega^2 x. A mass-spring system has omega=sqrt(k/m), so stiffness speeds oscillation and mass slows it.','The phase of x, v, and a matters: v is a quarter-cycle shifted from x, while a is opposite x. Turning points have zero speed and maximum restoring acceleration.','Energy moves between kinetic and spring potential while the total remains constant in ideal SHM. Damping removes energy; driving near the natural frequency produces resonance.'],
'Mechanical waves, interactions, and standing waves':['A traveling wave carries energy while each medium element oscillates locally. In y=f(x-vt), constant phase moves right; the pattern speed is not the same as the particle speed.','The harmonic form identifies A, k, omega, phase, wavelength, frequency, and direction. The linear wave equation relates spatial curvature to temporal acceleration when the medium has constant wave speed.','Reflection depends on the boundary, interference adds displacements, and two opposite waves form standing nodes and antinodes. Fixed-end conditions select lambda_n=2L/n.'],
'Sound, intensity, spectra, hearing, and Doppler effect':['Sound is a longitudinal pressure disturbance: compressions are high-pressure regions and rarefactions are low-pressure regions. Sound needs a material medium.','Intensity is power per area and falls as 1/r^2 for an isotropic source. Decibels describe ratios logarithmically, so equal dB changes represent multiplicative intensity changes.','Frequency sets pitch, amplitude and pressure relate to loudness, and harmonic content sets timbre. Relative motion changes wavefront arrival rate: approach raises perceived frequency and recession lowers it.']}

check_answers={
'Charge and conservation':'An isolated object that gains electrons becomes more negative. The charge of the object changes, but the charge of the complete isolated system does not: electrons have moved from one part of the system to another. Induction is therefore a redistribution of existing charge, not creation of new charge.',
'Coulomb force and electric fields':'The force is opposite the field because F=qE and q is negative. The field direction is defined using a positive test charge, so a negative charge reverses that direction. This is why field and force must not be treated as interchangeable vectors.',
'Field lines, superposition, and vectors':'Nonzero contributions can sum to zero when equal vectors point in opposite directions. Field-line density represents relative magnitude, while the tangent gives the direction a positive test charge would move. Dipole cancellation is why its distant field falls faster than a single-charge field.',
'Continuous charge distributions and integration':'For a uniform rod, dq=lambda dx. In a symmetric ring or rod arrangement, each element has a partner whose transverse component cancels. The remaining component is integrated after expressing r and the angle in terms of the chosen coordinate.',
'Electric flux and Gauss law':'The net flux is zero when the enclosed net charge is zero, even if the field is nonzero at individual points. External field lines enter and leave the closed surface, so their inward and outward contributions cancel in the total flux.',
'Applications of Gauss law':'Doubling distance from an infinite line halves the field because cylindrical area grows in proportion to r. Inside a charged spherical shell, a Gaussian sphere encloses no net charge, so Gauss law gives E=0.',
'Conductors, shielding, and induced charge':'A tangential field would exert a force along the conductor and keep free charges moving, contradicting electrostatic equilibrium. A +Q charge in a cavity induces -Q on the cavity wall so that the conducting material itself encloses zero net charge.',
'Electric potential, energy, and equipotentials':'If V decreases as x increases, dV/dx is negative and E_x=-dV/dx is positive. Motion along an equipotential has delta V=0, so delta U=q delta V=0 and the electric field does no work.',
'Capacitance and dielectrics':'In parallel, every capacitor has the same voltage and the stored charges add, so capacitances add. A dielectric polarizes: bound charge reduces the internal field for fixed free charge and increases the capacitance.',
'Dipoles, torque, polarization, and displacement':'The stable orientation is p parallel to E because U=-pE cos(theta) is then smallest. Polarization P is the net dipole moment per unit volume, not the total free charge density.',
'Oscillations and simple harmonic motion':'At maximum positive displacement, velocity is zero and acceleration is maximum negative, pointing toward equilibrium. Increasing mass increases the period because T=2 pi sqrt(m/k).',
'Mechanical waves, interactions, and standing waves':'The form f(x-vt) moves right because constant phase requires x to increase with t. At a boundary the source-set frequency remains continuous, while speed and wavelength adjust to the new medium.',
'Sound, intensity, spectra, hearing, and Doppler effect':'Doubling the distance quarters intensity because the same power spreads over four times the spherical area. An approaching source or observer increases wavefront arrival rate, so perceived frequency rises.'}

eq_html={
'Charge and conservation':'<i>Q</i><sub>total</sub> = constant',
'Coulomb force and electric fields':'<i>F</i> = <font size="13"><b>q</b><sub>1</sub><b>q</b><sub>2</sub></font> / (4&pi;&epsilon;<sub>0</sub><i>r</i><sup>2</sup>) &nbsp;&nbsp;&nbsp; <i>E</i> = <i>F</i>/<i>q</i><sub>test</sub>',
'Field lines, superposition, and vectors':'<b>E</b><sub>net</sub> = &Sigma;<sub>i</sub> <b>E</b><sub>i</sub>',
'Continuous charge distributions and integration':'d<i>q</i> = &lambda;d<i>l</i> = &sigma;d<i>A</i> = &rho;d<i>V</i> &nbsp;&nbsp;&nbsp; d<b>E</b> = (1/4&pi;&epsilon;<sub>0</sub>) d<i>q</i>/<i>r</i><sup>2</sup> <b>r</b><sub>hat</sub>',
'Electric flux and Gauss law':'&Phi;<sub>E</sub> = &oint; <b>E</b> &middot; d<b>A</b> = <i>Q</i><sub>enc</sub>/&epsilon;<sub>0</sub>',
'Applications of Gauss law':'<i>E</i><sub>line</sub> = &lambda;/(2&pi;&epsilon;<sub>0</sub><i>r</i>) &nbsp;&nbsp;&nbsp; <i>E</i><sub>sheet</sub> = &sigma;/(2&epsilon;<sub>0</sub>)',
'Conductors, shielding, and induced charge':'<i>E</i><sub>metal</sub> = 0 &nbsp;&nbsp;&nbsp; <i>E</i><sub>outside</sub> = &sigma;/&epsilon;<sub>0</sub>',
'Electric potential, energy, and equipotentials':'<b>E</b> = - grad <i>V</i> &nbsp;&nbsp;&nbsp; delta <i>U</i> = <i>q</i> delta <i>V</i>',
'Capacitance and dielectrics':'<i>C</i> = <i>Q</i>/<i>V</i> &nbsp;&nbsp;&nbsp; <i>U</i> = 1/2 <i>C V</i><sup>2</sup>',
'Dipoles, torque, polarization, and displacement':'<b>p</b> = <i>q d</i> &nbsp;&nbsp;&nbsp; &tau; = <i>p E</i> sin&theta; &nbsp;&nbsp;&nbsp; <b>D</b> = &epsilon;<sub>0</sub><b>E</b> + <b>P</b>',
'Oscillations and simple harmonic motion':'<i>x</i> = <i>A</i> cos(&omega;<i>t</i> + &phi;) &nbsp;&nbsp;&nbsp; &omega; = &radic;(<i>k</i>/<i>m</i>)',
'Mechanical waves, interactions, and standing waves':'<i>y</i> = <i>A</i> cos(<i>kx</i> - &omega;<i>t</i> + &phi;) &nbsp;&nbsp;&nbsp; <i>v</i> = <i>f</i>&lambda;',
'Sound, intensity, spectra, hearing, and Doppler effect':'<i>I</i> = <i>P</i>/(4&pi;<i>r</i><sup>2</sup>) &nbsp;&nbsp;&nbsp; &beta; = 10 log<sub>10</sub>(<i>I</i>/<i>I</i><sub>0</sub>)'}

check_questions={
'Charge and conservation':'An initially neutral object gains electrons from a second object. Describe the final signs of both objects and explain how the total charge of the complete system changes.',
'Coulomb force and electric fields':'A negative test charge is placed at a point where the electric field points east. Predict the force direction and explain why field direction is defined with a positive test charge.',
'Field lines, superposition, and vectors':'Two equal positive charges are placed symmetrically about a point. Explain which field components cancel at the midpoint, and describe what changes if the charges have opposite signs.',
'Continuous charge distributions and integration':'For a uniformly charged rod observed from its perpendicular bisector, explain how you would choose dq, which field component cancels, and why the remaining component must be integrated.',
'Electric flux and Gauss law':'A closed Gaussian surface encloses zero net charge but passes through a nonzero electric field. Explain how the net flux can still be zero.',
'Applications of Gauss law':'Compare the field-distance dependence for an infinite line charge and a uniformly charged spherical shell outside the shell. Explain why their powers of r differ.',
'Conductors, shielding, and induced charge':'Explain why a static electric field cannot remain inside conducting material, and describe the induced charge on the inner wall when a positive charge is placed in a neutral cavity.',
'Electric potential, energy, and equipotentials':'Explain what it means physically for electric potential to decrease in a direction, and why the electric field is perpendicular to an equipotential surface.',
'Capacitance and dielectrics':'Explain what capacitance measures, how parallel and series connections differ physically, and why inserting a dielectric changes the stored charge or voltage depending on whether a battery remains connected.',
'Dipoles, torque, polarization, and displacement':'Explain how a dipole can have zero net force but nonzero torque in a uniform electric field, and identify the stable orientation of its dipole moment.',
'Oscillations and simple harmonic motion':'At the positive turning point of an ideal mass-spring oscillator, describe the velocity, acceleration, spring energy, and direction of the restoring force.',
'Mechanical waves, interactions, and standing waves':'For y=f(x-vt), explain how you know the wave moves right, and distinguish the speed of the waveform from the velocity of a point in the medium.',
'Sound, intensity, spectra, hearing, and Doppler effect':'An observer moves toward a stationary sound source. Predict the change in perceived frequency and explain it using wavefront arrival rate rather than source loudness.'}

eq_explain={
'Charge and conservation':'<b>Symbols:</b> Q<sub>total</sub> is the algebraic sum of all positive and negative charge in the chosen isolated system. <b>Physical meaning:</b> the equation says electrons may move between objects, but the system cannot gain or lose net charge. A local charge change is balanced by an equal and opposite change elsewhere.',
'Coulomb force and electric fields':'<b>Symbols:</b> q<sub>1</sub>, q<sub>2</sub> are source charges, r is their separation, &epsilon;<sub>0</sub> is the vacuum permittivity, and <b>r</b><sub>hat</sub> gives direction. E is force per unit positive test charge. <b>Physical meaning:</b> inverse-square spreading weakens interaction with distance; the signs determine attraction or repulsion, while E describes the source before a test charge is added.',
'Field lines, superposition, and vectors':'<b>Symbols:</b> E<sub>i</sub> is the field from source i and E<sub>net</sub> is the vector total. <b>Physical meaning:</b> each source acts independently, then the components combine. This equation explains cancellation on symmetry axes and reinforcement between opposite charges.',
'Continuous charge distributions and integration':'<b>Symbols:</b> &lambda;, &sigma;, and &rho; are line, surface, and volume charge densities; dl, dA, and dV are source elements; dq is the charge in one element. <b>Physical meaning:</b> integration is a limit of adding many small Coulomb contributions whose distances and directions vary across an extended source.',
'Electric flux and Gauss law':'<b>Symbols:</b> dA is an outward area vector, E is the local field, Q<sub>enc</sub> is net enclosed charge, and &epsilon;<sub>0</sub> is vacuum permittivity. <b>Physical meaning:</b> the total excess of field passing outward through any closed surface is set only by charge inside it.',
'Applications of Gauss law':'<b>Symbols:</b> &lambda; is line charge density, &sigma; is sheet density, r is distance from the symmetry axis or center, and &rho; is volume density. <b>Physical meaning:</b> the field falloff follows how the available flux area grows: cylindrical area gives 1/r, spherical area gives 1/r<sup>2</sup>, and a plane gives constant area per unit length.',
'Conductors, shielding, and induced charge':'<b>Symbols:</b> E<sub>metal</sub> is the field inside conducting material and &sigma; is surface charge density. <b>Physical meaning:</b> free charges rearrange until no force remains in the metal; the normal surface field is the field produced by the accumulated surface charge just outside.',
'Electric potential, energy, and equipotentials':'<b>Symbols:</b> V is potential energy per charge, U is potential energy, q is the charge being moved, and &nabla;V describes spatial change in potential. <b>Physical meaning:</b> the field points in the direction where a positive charge loses potential energy most rapidly; equipotential motion has no potential-energy change.',
'Capacitance and dielectrics':'<b>Symbols:</b> C is capacitance, Q is stored free charge, V is the potential difference, and U is stored field energy. <b>Physical meaning:</b> geometry and material determine how much charge a capacitor can hold for a given voltage; a dielectric polarizes and changes that charge-voltage relationship.',
'Dipoles, torque, polarization, and displacement':'<b>Symbols:</b> p is dipole moment, d is charge separation, &tau; is torque, E is external field, P is dipole moment per volume, and D combines free-charge field with polarization. <b>Physical meaning:</b> separated opposite forces form a turning couple, while microscopic dipole alignment produces a macroscopic material response.',
'Oscillations and simple harmonic motion':'<b>Symbols:</b> A is amplitude, &omega; is angular frequency, t is time, &phi; is initial phase, k is spring stiffness, and m is mass. <b>Physical meaning:</b> the sinusoid is the motion whose acceleration always points toward equilibrium and whose restoring strength grows with displacement.',
'Mechanical waves, interactions, and standing waves':'<b>Symbols:</b> A is displacement amplitude, k is wave number, &omega; is angular frequency, &phi; is phase, &lambda; is wavelength, f is frequency, and v is waveform speed. <b>Physical meaning:</b> the phase argument tracks a repeating pattern in both space and time; the sign before &omega;t selects travel direction and v=f&lambda; links spatial and temporal repetition.',
'Sound, intensity, spectra, hearing, and Doppler effect':'<b>Symbols:</b> I is intensity, P is acoustic power, r is distance, &beta; is sound level, and I<sub>0</sub> is the reference intensity. <b>Physical meaning:</b> spherical spreading lowers intensity with distance, while the logarithm expresses how hearing compares multiplicative intensity ratios. Doppler shifts arise from arrival rate, not from a change in source power.'}

ss=getSampleStyleSheet(); ss.add(ParagraphStyle(name='T',parent=ss['Title'],fontSize=25,leading=30,alignment=TA_CENTER,textColor=colors.HexColor('#15324b'))); ss.add(ParagraphStyle(name='H',parent=ss['Heading1'],fontSize=16,leading=20,textColor=colors.HexColor('#15324b'))); ss.add(ParagraphStyle(name='B',parent=ss['BodyText'],fontSize=8.8,leading=11.5,textColor=colors.HexColor('#243342'),spaceAfter=3)); ss.add(ParagraphStyle(name='S',parent=ss['BodyText'],fontSize=7.2,leading=9,textColor=colors.HexColor('#536575')))
def P(x,s='B'): return Paragraph(x,ss[s])
story=[Spacer(1,1.1*inch),P('Physics 2<br/>Comprehensive Review Package','T'),Spacer(1,.2*inch),P('Professor-first master review and reusable knowledge base','S'),Spacer(1,.35*inch),fig(1),Spacer(1,.25*inch),P('This package consolidates the saved Canvas pages and worksheet scans into a conceptual progression. Each section gives the main ideas, a hallmark equation, the physical reasoning behind its derivation, misconceptions, and an immediate conceptual check with answer. Textbook supplements are labeled in the source map.','B'),PageBreak(),P('Contents and coverage map','H')]
for n,t,_,_,_,_,_ in topics: story.append(P(n+'. '+t,'B'))
story += [Spacer(1,.2*inch),P('The companion YAML records source pages, equations in normalized LaTeX, assumptions, limiting cases, diagrams, checks, and question-generation tags. The page-list-only gaps identified during inventory are covered as supplemental sections where a saved capture was absent.','S'),PageBreak()]
for idx,(n,t,scope,formula,reason,check,tags) in enumerate(topics):
    story += [P(n+'. '+t,'H'),P('<b>Scope and source status:</b> '+scope+' <br/><b>Question-generation tags:</b> '+tags,'S'),Spacer(1,4),fig(idx),Spacer(1,5),P('<b>Core understanding</b>','B')]
    bits=explain[t]
    for b in bits: story.append(P('&bull; '+b,'B'))
    story += [Table([[P('<b>Hallmark equation</b><br/><font size="12">'+eq_html[t]+'</font><br/>'+eq_explain[t],'B')]],colWidths=[6.65*inch],style=TableStyle([('BACKGROUND',(0,0),(-1,-1),colors.HexColor('#eaf4f3')),('BOX',(0,0),(-1,-1),.7,colors.HexColor('#287271')),('PADDING',(0,0),(-1,-1),8)])),P('<b>Concept check:</b> '+check_questions[t],'B'),P('<b>Answer and explanation:</b> '+check_answers[t],'B')]
    if idx<len(topics)-1: story.append(PageBreak())
story += [PageBreak(),P('References and provenance','H'),P('Primary: saved SingleFile Canvas pages in docs/reference/canvas_pages and worksheet scans in docs/reference/reference-texts/Physics 2 scans Test 1. Supplemental: OpenStax University Physics Volume 1, Chapters 15-17; OpenStax University Physics Volume 2, Chapters 5-7; Young and Freedman, University Physics, relevant electrostatics, oscillations, waves, and sound chapters.','B'),P('Original captures and scans were preserved unchanged. Repeated page titles were normalized in the knowledge base. Figures in this package are clean instructional redraws; the source inventory records where professor visuals are available for later extraction and reuse.','B')]
SimpleDocTemplate(str(supplement),pagesize=letter,leftMargin=.55*inch,rightMargin=.55*inch,topMargin=.55*inch,bottomMargin=.6*inch).build(story,onFirstPage=page_num,onLaterPages=page_num)

# Rebuild the existing 13-page notes in place, then prepend the new supplement and merge.
runpy.run_path(str(ROOT/'scratch/build_conceptual_notes.py'))
writer=PdfWriter()
for path in (supplement,old):
    for pg in PdfReader(str(path)).pages: writer.add_page(pg)
writer.add_metadata({'/Title':'Physics 2 Comprehensive Review Package','/Subject':'Electricity, oscillations, waves, and sound'})
with open(final,'wb') as f: writer.write(f)

kb={'title':'Physics 2 Comprehensive Review Package Knowledge Base','version':'1.0','source_priority':['Professor Canvas captures and worksheet scans','OpenStax University Physics Volumes 1-2','Young and Freedman University Physics'],'source_inventory':{'canvas_capture_count':len(titles),'worksheet_scan_count':len(list(SCANS.glob('*.pdf'))),'page_list':'docs/reference/canvas_pages/pages list.html','canvas_source_titles':sorted(titles)},'topics':[]}
for n,t,scope,formula,reason,check,tags in topics:
    key=' '.join(t.lower().split())
    matches=[x for x in titles if any(w in x.lower() for w in key.split() if len(w)>4)]
    kb['topics'].append({'id':re.sub('[^a-z0-9]+','-',t.lower()).strip('-'),'canonical_title':t,'scope':scope,'professor_source_pages':matches[:12],'worksheet_source_references':[p.stem for p in SCANS.glob('*.pdf') if any(w in p.stem.lower() for w in key.split() if len(w)>5)][:12],'supplemental_textbook_references':['OpenStax University Physics Volumes 1-2','Young and Freedman, University Physics'],'core_concepts':explain[t],'equations_latex':[formula],'equation_explanation':eq_explain[t],'derivation_steps':[reason],'assumptions':['Use only the stated source geometry and material model','Check symmetry and boundary conditions','Use SI units and signed/vector quantities'],'limiting_cases':['zero source','large distance','symmetry cancellation','inside/outside or boundary limit'],'common_misconceptions':['Do not add vector magnitudes when directions differ','Do not confuse field with force or potential','Do not use a symmetry shortcut unless the source geometry supports it'],'diagram_reference':'clean instructional diagram in the review package','conceptual_checks':[{'prompt':check_questions[t],'answer':check_answers[t]}],'question_generation_tags':tags.split()})
(ROOT/'docs/reference/physics2_review_knowledge_base.yaml').write_text(json.dumps(kb,indent=2),encoding='utf-8')
print(final); print(ROOT/'docs/reference/physics2_review_knowledge_base.yaml'); print('pages',len(PdfReader(str(final)).pages),'canvas',len(titles),'scans',len(list(SCANS.glob('*.pdf'))))
