const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const katex=require(path.join(root,'frontend/node_modules/katex'));
const {chromium}=require('C:/Users/SeanS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const M=s=>katex.renderToString(s,{throwOnError:true,displayMode:false});
const sections=[];let page=0;
function S(title,formula,legend,note=''){sections.push({page,title,formula,legend,note});}
S('1 · Constants, charge, vectors',String.raw`k_e=\frac1{4\pi\epsilon_0}=8.99\times10^9,\quad \epsilon_0=8.85\times10^{-12}\\ e=1.602\times10^{-19}\,\mathrm C,\quad G=6.674\times10^{-11},\quad q=Ne\\ Q_{\rm before}=Q_{\rm after},\quad |\mathbf E|=\sqrt{E_x^2+E_y^2},\quad \theta=\operatorname{atan2}(E_y,E_x)`,
'kₑ: Coulomb constant [N m²/C²]; ε₀: vacuum permittivity [F/m]; G: gravity constant [N m²/kg²]; e: elementary charge; N: signed integer. E: field [N/C = V/m]. μ = 10⁻⁶, n = 10⁻⁹, p = 10⁻¹².',
'An isolated system conserves net charge. Gaining electrons makes an object more negative. Bold symbols are vectors; hats are unit vectors. Angles in calculus are radians.');
S('2 · Coulomb force, gravity & superposition',String.raw`\mathbf R_i=\mathbf r-\mathbf r_i,\quad \mathbf E(\mathbf r)=k_e\sum_i\frac{q_i\mathbf R_i}{|\mathbf R_i|^3},\quad \mathbf F=q_0\mathbf E\\ F_C=k_e\frac{|q_1q_2|}{r^2},\quad F_g=G\frac{m_1m_2}{r^2},\quad U_g=-\frac{Gm_1m_2}{r}`,
'r, rᵢ: observation/source positions [m]; Rᵢ: source-to-observer displacement; qᵢ: source charges [C]; q₀: test charge; m: mass [kg]; F: force [N]; U: energy [J].',
'Add signed x/y components first. Like charges repel, unlike attract; gravity attracts. Positive charge follows E, negative charge feels opposite force. Point charges or spherically symmetric exterior fields only.');
S('3 · Continuous charge & trig substitution',String.raw`Q=\int dq,\quad dq=\lambda_q\,dl=\sigma\,dA=\rho_q\,dV,\quad \mathbf E=k_e\int\frac{\hat{\mathbf R}}{R^2}dq\\ E_y=k_e\lambda_q a\int_{-L}^{L}\frac{dx}{(a^2+x^2)^{3/2}}=\frac{2k_e\lambda_q L}{a\sqrt{a^2+L^2}}\\ x=a\tan\theta,\quad dx=a\sec^2\theta\,d\theta,\quad R=a\sec\theta\\ E_y=\frac{k_e\lambda_q}{a}\int_{-\theta_0}^{\theta_0}\cos\theta\,d\theta,\quad \theta_0=\tan^{-1}(L/a)`,
'λq: line density [C/m]; σ: surface density [C/m²]; ρq: volume density [C/m³]; l: source length; A: area; V here: volume. Rod spans −L…L; observer (0,a), a > 0.',
'Cancel odd components by symmetry. Rod: L ≫ a gives E = 2kₑλq/a; a ≫ L gives point-charge field with Q = 2Lλq. Use dV = 4πr²dr for spherical density.');
S('4 · Flux, Gauss law & standard geometries',String.raw`\Phi_E=\int_S\mathbf E\cdot d\mathbf A,\quad \Phi_E=EA\cos\theta\ (\mathrm{uniform}),\quad \oint\mathbf E\cdot d\mathbf A=\frac{Q_{\rm enc}}{\epsilon_0}\\ E_{\rm line}=\frac{\lambda_q}{2\pi\epsilon_0r},\quad E_{\rm sheet}=\frac{\sigma}{2\epsilon_0},\quad E_{\rm sphere}=\frac{Q_{\rm enc}(r)}{4\pi\epsilon_0r^2}\\ Q_{\rm enc}=4\pi\int_0^r\rho_q(s)s^2ds;\quad \rho_q=\mathrm{const}:\ E_{\rm in}=\frac{\rho_q r}{3\epsilon_0},\ E_{\rm out}=\frac{\rho_q R^3}{3\epsilon_0r^2}`,
'ΦE: flux [N m²/C]; θ: angle between E and outward area normal; Qenc: signed enclosed charge; R: solid-sphere radius; r: distance from center/axis; s: integration radius.',
'Line: infinite, cylindrical area 2πrL. Sheet: infinite nonconductor, two pillbox faces 2A. Sphere: 4πr²; uniform shell has E = 0 inside. External charges affect local E but not net flux.');
S('5 · Conductors, potential & work',String.raw`E_{\rm metal}=0,\quad E_t=0,\quad E_{n,\rm out}=\sigma/\epsilon_0\\ V=k_e\sum_i\frac{q_i}{R_i}=k_e\int\frac{dq}{R},\quad \Delta V=-\int_a^b\mathbf E\cdot d\mathbf l\\ \mathbf E=-\nabla V,\quad E_x=-\frac{\partial V}{\partial x},\quad U=qV,\quad U_{12}=\frac{k_eq_1q_2}{r}\\ W_E=-\Delta U=-q\Delta V,\quad K=\tfrac12mv^2,\quad \Delta K=-q\Delta V`,
'V: electric potential [volt = J/C]; U: potential energy; t,n: tangential/normal components; dl: path displacement. K: kinetic energy; WΕ: work done by electric field.',
'Last relation: electric force only. Equipotential ⇒ no electric work, E normal. Conducting cavity with +q induces −q on inner wall. Sphere shell V inside = kₑQ/R; V outside = kₑQ/r (zero at infinity).');
S('6 · Useful axial fields & potential shapes',String.raw`E_{\rm ring}(z)=\frac{k_eQz}{(z^2+R^2)^{3/2}},\quad V_{\rm ring}(z)=\frac{k_eQ}{\sqrt{z^2+R^2}}\\ E_{\rm disk}(z)=\frac{\sigma}{2\epsilon_0}\left(1-\frac{z}{\sqrt{z^2+R^2}}\right)\quad(z>0)\\ F_r=-\frac{dU}{dr};\quad U=\frac{C_{12}}{r^{12}}-\frac{C_6}{r^6}\Rightarrow F_r=\frac{12C_{12}}{r^{13}}-\frac{6C_6}{r^7}`,
'Uniform ring/disk: R radius, z axial distance. C₁₂,C₆: positive interaction constants [J m¹², J m⁶]. Equilibrium: U′ = 0; stable minimum: U″ > 0. Lennard–Jones rₑq = (2C₁₂/C₆)¹⁄⁶.',
'Positive radial force is outward. Like-charge U > 0, opposite-charge U < 0 with infinity as zero. A negative potential alone does not determine force: slope does.');
page=1;
S('7 · Capacitors & dielectric response',String.raw`C=\frac{Q}{\Delta V},\ C_{\rm plate}=\frac{\epsilon A}{d},\ C_{\parallel}=\sum C_i,\ \frac1{C_{\rm series}}=\sum\frac1{C_i}\\ C_{\rm sphere}=4\pi\epsilon\frac{ab}{b-a},\quad C_{\rm coax}=\frac{2\pi\epsilon L}{\ln(b/a)}\\ U_C=\int_0^Q\frac{q}{C}dq=\frac{Q^2}{2C}=\tfrac12C(\Delta V)^2,\quad u_E=\tfrac12\epsilon E^2\\ \mathbf D=\epsilon_0\mathbf E+\mathbf P=\epsilon\mathbf E,\quad \mathbf P=\epsilon_0\chi_e\mathbf E,\quad \epsilon=\kappa\epsilon_0=\epsilon_0(1+\chi_e)`,
'C: capacitance [F]; Q: plate-charge magnitude; d: gap; a,b: inner/outer radii; L: coax length; uΕ: energy/volume [J/m³]; P: polarization, D: displacement [C/m²]; κ, χe: dimensionless.',
'Linear isotropic dielectric fills gap; neglect edges. Parallel shares ΔV; series shares Q. Battery attached: ΔV fixed, Q rises with κ. Isolated: Q fixed, ΔV and U fall by κ. ∮D·dA = Qfree.');
S('8 · Dipoles, mechanics & calculus starts',String.raw`\mathbf p=q\mathbf d,\quad \boldsymbol\tau=\mathbf p\times\mathbf E,\quad U=-\mathbf p\cdot\mathbf E\\ E_{\rm axial}\simeq2k_ep/r^3,\ E_{\rm equator}\simeq k_ep/r^3,\ V\simeq k_ep\cos\theta/r^2\\ \sum\mathbf F=m\mathbf a,\quad a=\frac{dv}{dt},\quad v=\frac{dx}{dt}\\ a=\mathrm{const}:\ v=v_i+at,\ x=x_i+v_it+\tfrac12at^2,\ v^2=v_i^2+2a\Delta x\\ a_y=qE/m,\quad t=\ell/v_x,\quad y=\tfrac12a_yt^2\ (v_{y,i}=0)`,
'p: dipole moment [C m], d points − to +; τ: torque [N m]; θ between p and E (or r for V); far fields require r ≫ d. ℓ: deflection-plate length, vx constant.',
'Uniform E: dipole net force zero, torque aligns p; equatorial field opposite p. Integrate a dt with initial v, then v dt with initial x. For Bohr force balance only: kₑe²/r² = mₑv²/r (not quantization).');
S('9 · Oscillations, energy & damping',String.raw`F=-k_sx\Rightarrow \ddot x+\omega_0^2x=0,\quad \omega_0=\sqrt{k_s/m},\quad T=2\pi/\omega_0\\ x=A\cos(\omega_0t+\phi),\ v=-A\omega_0\sin(\omega_0t+\phi),\ a=-\omega_0^2x\\ U_s=\tfrac12k_sx^2,\quad K=\tfrac12k_s(A^2-x^2),\quad E_{\rm tot}=\tfrac12k_sA^2\\ T_{\rm pend}=2\pi\sqrt{\ell/g},\quad m\ddot x+b\dot x+k_sx=F_0\cos(\Omega t)\\ \omega_d=\sqrt{\omega_0^2-(b/2m)^2},\quad A_{\rm drive}=\frac{F_0}{\sqrt{(k_s-m\Omega^2)^2+(b\Omega)^2}}`,
'ks: stiffness [N/m]; A: amplitude [m]; ω: angular frequency [rad/s]; φ: initial phase; T: period [s]; b: damping [kg/s]; Ω,F₀: drive frequency/force; g ≈ 9.81 m/s².',
'Ideal SHM: vmax = Aω₀, amax = Aω₀²; x = 0 ⇒ max speed, ±A ⇒ v = 0. Pendulum small angles only. Underdamped amplitude decays as exp(−bt/2m); damping lowers resonance peak.');
S('10 · Traveling wave: decode & differentiate',String.raw`y=A\cos\psi,\quad \psi=k_wx-\omega t+\phi,\quad k_w=\frac{2\pi}{\lambda},\quad \omega=2\pi f\\ T=\frac1f=\frac{2\pi}{\omega},\quad v_w=\frac\omega{k_w}=f\lambda=\sqrt{\mathcal T/\mu}\\ v_y=\partial_ty=A\omega\sin\psi,\quad a_y=\partial_t^2y=-\omega^2y\\ \partial_x^2y=-k_w^2y\Rightarrow \boxed{\partial_t^2y=v_w^2\partial_x^2y}\\ \mathcal T\,\partial_x^2y\,dx=\mu\,dx\,\partial_t^2y,\quad \overline P=\tfrac12\mu\omega^2 A^2v_w`,
'y: transverse displacement; x: position; kw: wave number [rad/m]; λ: wavelength [m]; f: frequency [Hz]; μ: string mass/length [kg/m]; 𝒯: tension [N]; P̄: mean power [W].',
'Minus ωt travels +x; plus travels −x. Constant phase gives direction. Pattern speed vw differs from particle velocity vy. Small slopes and constant tension/density give the linear PDE.');
S('11 · Boundaries, interference & standing waves',String.raw`\Delta\psi=k_w\Delta x-\omega\Delta t+\Delta\phi,\quad A_{\rm sum}=2A|\cos(\Delta\psi/2)|\\ y_1+y_2=2A\sin(k_wx)\cos(\omega t),\quad f_n=\frac{nv_w}{2L}\ (n=1,2,\ldots)\\ f_n=\frac{nv_w}{4L}\ (n=1,3,5,\ldots),\quad f_{\rm beat}=|f_1-f_2|\\ n_1\sin\theta_1=n_2\sin\theta_2,\quad n=c/v,\quad \sin\theta_c=n_2/n_1`,
'L: vibrating length; n harmonic integer except in refraction, where n is index and c is vacuum light speed. θ measured from normal; total internal reflection needs n₁ > n₂.',
'Fixed string / open-open pipe: all harmonics; open-closed pipe: odd only. Nodes spaced λ/2. Fixed reflection inverts, free does not. Constructive phase 2πm; destructive (2m+1)π. Boundary f unchanged; Snell follows k₁sinθ₁ = k₂sinθ₂.');
S('12 · Sound, levels & Doppler',String.raw`v_s=\sqrt{B/\rho_m},\quad I=\frac{P}{4\pi r^2}=\frac{p_{\rm rms}^2}{\rho_mv_s}=\tfrac12\rho_mv_s\omega^2s_m^2\\ p_m=\rho_mv_s\omega s_m,\quad p_{\rm rms}=p_m/\sqrt2,\quad \beta=10\log_{10}(I/I_0)\\ \Delta\beta=10\log_{10}(I_2/I_1)=20\log_{10}(p_2/p_1)\\ f_o=f_s\frac{v_s+v_o}{v_s-v_{\rm src}},\quad \mathcal E_{\rm ind}=-\frac{d\Phi_B}{dt},\quad \Phi_B=\int\mathbf B\cdot d\mathbf A`,
'B: bulk modulus [Pa], ρm: medium density [kg/m³], sm: displacement amplitude; pm,prms: pressure [Pa]; I₀ = 10⁻¹² W/m²; air reference p₀ = 20 μPa. β: dB. Last two: scan induction reminder; magnetic B [T], ΦB [Wb], emf [V].',
'Doppler velocities relative to medium: vo positive toward source, vsrc positive toward observer (subsonic). Approach raises f, shortens observed period. Pressure ×3 ⇒ intensity ×9 ⇒ +9.54 dB. Pitch: f; timbre: spectrum; sound needs medium.');
sections[3].formula+=String.raw`\\ E_{\rm cyl,in}=\frac{\rho_q r}{2\epsilon_0},\quad E_{\rm cyl,out}=\frac{\rho_q R^2}{2\epsilon_0r}`;
sections[3].note+=' Cylinder: infinitely long, uniform solid, radius R. For concentric shells sum signed enclosed charges by region.';
sections[5].formula+=String.raw`\\ E_{\rm arc,center}=\frac{2k_e\lambda_q\sin\alpha}{R},\quad V_{\rm solid,in}=\frac{k_eQ}{2R}\left(3-\frac{r^2}{R^2}\right)`;
sections[5].note+=' Arc: total angle 2α, radius R, uniform λq; magnitude along bisector (away from positive arc). Solid sphere: uniform Q, r < R.';
sections[7].legend+=' v: particle speed [m/s]; a: acceleration [m/s²]; i: initial value; Δ: final minus initial; mₑ: electron mass.';
sections[11].legend+=' fo,fs: observed/source frequency [Hz]; vs: sound speed; vo,vsrc: observer/source velocity [m/s].';
sections[10].formula+=String.raw`\\ Z_j=\mathcal T/v_j,\quad r_A=\frac{Z_1-Z_2}{Z_1+Z_2},\quad t_A=\frac{2Z_1}{Z_1+Z_2}`;
sections[10].note+=' String junction, equal tension: Z impedance; rA,tA signed displacement-amplitude ratios. Power fractions rA² and (Z₂/Z₁)tA² sum to 1.';
const css=fs.readFileSync(path.join(root,'frontend/node_modules/katex/dist/katex.min.css'),'utf8').replace(/url\(fonts\//g,'url(file:///'+path.join(root,'frontend/node_modules/katex/dist/fonts/').replace(/\\/g,'/'));
const html=`<!doctype html><meta charset="utf-8"><style>${css}
@page{size:letter;margin:0}*{box-sizing:border-box}body{margin:0;color:#182c3b;font-family:Arial}article{width:8.5in;height:11in;padding:.28in .32in;page-break-after:always;overflow:hidden}header{display:flex;justify-content:space-between;border-bottom:2px solid #216c74;padding-bottom:5px;margin-bottom:6px;font-size:12px;font-weight:bold}.cols{display:grid;grid-template-columns:1fr 1fr;gap:0 13px}.col{min-width:0}section{margin-bottom:6px}h2{font-size:10px;margin:0 0 3px;background:#e8f1f3;padding:3px 5px}p{font-size:8.4px;line-height:1.22;margin:3px 0}.eq{font-size:9.4px;line-height:1.7;color:#071c30}.katex{font-size:1em}.note{color:#344854}footer{font-size:7px;border-top:1px solid #bdcbd1;margin-top:5px;padding-top:3px}</style>`+[0,1].map(p=>{const a=sections.filter(s=>s.page===p);return `<article><header><span>PHYSICS 2 · TEST REFERENCE</span><span>${p+1} / 2</span></header><div class="cols">`+[a.slice(0,3),a.slice(3)].map(col=>`<div class="col">`+col.map(s=>`<section><h2>${s.title}</h2><div class="eq">${s.formula.split('\\\\').map(x=>M(x)).join('<br>')}</div><p>${s.legend}</p><p class="note">${s.note}</p></section>`).join('')+'</div>').join('')+`</div><footer>Course review/worksheet scope; standard SI forms. Notation: kₑ Coulomb constant, kₛ stiffness, k𝑤 wave number; λq charge density versus λ wavelength. Print at 100%.</footer></article>`}).join('');
(async()=>{const target=path.join(root,'scratch/two-page-reference.html');fs.writeFileSync(target,html+'<style>p{font-size:11.3px;line-height:1.26;margin:5px 0}h2{font-size:12px;padding:4px 5px}.eq{font-size:12px;line-height:1.85}section{margin-bottom:10px}footer{font-size:8px}</style>');const browser=await chromium.launch({channel:'msedge',headless:true});const pg=await browser.newPage();await pg.goto('file:///'+target.replace(/\\/g,'/'));await pg.evaluate(()=>document.fonts.ready);await pg.evaluate(()=>document.querySelectorAll('.eq .katex').forEach(e=>{let w=e.getBoundingClientRect().width,available=e.closest('.col').clientWidth;if(w>available)e.style.fontSize=(available/w)+'em';}));console.log(await pg.evaluate(()=>[...document.querySelectorAll('article')].map(a=>({height:a.scrollHeight,limit:a.clientHeight,cols:[...a.querySelectorAll('.col')].map(c=>c.getBoundingClientRect().height)}))));await pg.pdf({path:path.join(root,'output/pdf/Physics 2 - Two-Page Test Reference.pdf'),printBackground:true,preferCSSPageSize:true});await browser.close();})();
