"""Replace generic Mathematical Literacy learning-asset content with packet-supported material."""
from pathlib import Path
import copy
import yaml

ROOT=Path(__file__).resolve().parents[1]
A=ROOT/'data/assessments'; B=ROOT/'docs/assessment-reference/question-blueprints'
SRC='src-20260813163657-e0e471ca79'
topics={
'notation':('mathematical-literacy-notation','mathematical-notation-and-structure','ml-notation','packet-mathematical-notation-and-structure-v2',[17,18,22,24],[
('Read set-builder notation','$E=\\{2n:n\\in\\mathbb Z\\}$ collects outputs $2n$ as $n$ ranges over integers; it is the set of even integers.','Which value belongs to $E=\\{2n:n\\in\\mathbb Z\\}$?','14'),
('Separate rule from output','In $\\{2n:n\\in\\mathbb Z\\}$, $2n$ is the output expression and $n\\in\\mathbb Z$ is the domain rule.','What role does $n\\in\\mathbb Z$ play in $\\{2n:n\\in\\mathbb Z\\}$?','It restricts n to integers'),
('Use context for vertical bars','$|X|$ means cardinality when $X$ is a set and absolute value when $X$ is a number.','When $X$ is a set, what does $|X|$ mean?','the number of elements in X'),
('Keep empty-set forms distinct','$\\varnothing$ has no elements, while $\\{\\varnothing\\}$ has one element: the empty set.','How many elements are in $\\{\\varnothing\\}$?','1'),
('Read grouped products','$\\mathbb R\\times(\\mathbb N\\times\\mathbb Z)$ has a real first coordinate and an ordered pair as its second coordinate.','What shape has an element of $\\mathbb R\\times(\\mathbb N\\times\\mathbb Z)$?','(real number, (natural number, integer))'),
('Distinguish membership from subset','$a\\in A$ names an element; $B\\subseteq A$ says every element of B belongs to A.','What does $B\\subseteq A$ assert?','Every element of B is an element of A'),
('Use the empty-set rule','Because it has no counterexample element, $\\varnothing$ is a subset of every set.','Is $\\varnothing\\subseteq A$ true for every set A?','yes')],[
('What does $x\\in\\mathbb Z$ say about x?','x is an integer'),('Complete: $A\\subseteq B$ means every element of A is an element of ___.','B'),('What does $|A|$ mean when A is a set?','the number of elements of A'),('Give the set-builder rule for even integers.','2n where n is an integer'),('How many elements does $\\{\\varnothing\\}$ have?','1'),('What is the second coordinate of an element of $\\mathbb R\\times(\\mathbb N\\times\\mathbb Z)$?','an ordered pair in N times Z'),('Can a set be an element of another set?','yes'),('What must be preserved when reading a nested Cartesian product?','parentheses')]),
'logic':('mathematical-literacy-logic','mathematical-statements-and-logic','ml-logic','packet-mathematical-statements-and-logic-v2',[47,48],[
('Identify statements','A statement has a definite truth value; commands, questions, and unresolved open sentences do not.','Is “$2+3=5$” a statement?','yes'),
('Recognize open sentences','A variable-containing sentence whose truth changes with the variable value is an open sentence until a value or quantifier is supplied.','Is “$x+1>0$” an open sentence without a stated domain or quantifier?','yes'),
('Use a stated domain','A sentence with a variable can still be a statement when a domain makes its truth definite.','Why can a variable-containing sentence be a statement?','Its truth is fixed by the stated domain'),
('Read a conditional','A conditional has a hypothesis and conclusion and is false only when its hypothesis is true and its conclusion is false.','When is “if P then Q” false?','when P is true and Q is false'),
('Do not reverse conditionals','The converse swaps hypothesis and conclusion; it is a different statement.','What is the converse of “if P then Q”?','if Q then P'),
('Name truth status','A complete mathematical statement is either true or false, even if it is difficult to determine which.','What two truth values can a statement have?','true or false'),
('Classify before calculating','Before evaluating symbols, decide whether the line is a statement, a command, a question, or an open sentence.','What should be identified before assigning a truth value?','whether the line is a statement')],[
('What is a statement?','a sentence that is definitely true or definitely false'),('What is an open sentence?','a sentence whose truth depends on an unspecified variable'),('Complete: a conditional is false only when its hypothesis is ___ and its conclusion is ___.','true; false'),('Name the two parts of “if P then Q.”','hypothesis and conclusion'),('What is the converse of “if P then Q”?','if Q then P'),('Is a command a statement?','no'),('Can a statement be false?','yes'),('What must a stated domain do for a variable sentence to have fixed truth?','fix the truth value')]),
'quantifiers':('mathematical-literacy-quantifiers-negation-and-mathematical-translation','quantifiers-negation-and-mathematical-translation','ml-quantifiers','packet-quantifiers-negation-and-mathematical-translation-v2',[65,69,71],[
('Read universal scope','$\\forall$ means every object in the declared domain must satisfy the predicate.','What does $\\forall$ mean?','for every'),('Read existential scope','$\\exists$ requires at least one witness in the stated domain.','What does $\\exists$ mean?','there exists'),('Preserve the domain','A quantifier only ranges over the domain supplied by the statement.','What must remain unchanged when translating a quantified claim?','the domain'),('Negate a universal','The negation of “every object has P” is “there exists an object that does not have P.”','How does the outer quantifier change when negating a universal claim?','from for every to there exists'),('Negate an existential','The negation of “there exists an object with P” says every object fails P.','How does the outer quantifier change when negating an existential claim?','from there exists to for every'),('Keep conditional direction','A conditional is false only in the true-hypothesis, false-conclusion case.','Which case makes “if P then Q” false?','P true and Q false'),('Apply De Morgan','Negating “P and Q” gives “not P or not Q”; negating “P or Q” gives “not P and not Q.”','What connective replaces and when its whole conjunction is negated?','or')],[
('What does $\\forall$ mean?','for every'),('What does $\\exists$ mean?','there exists'),('Negate: every integer is even.','there exists an integer that is not even'),('Negate: there exists an integer that is even.','every integer is not even'),('What domain must a translation preserve?','the stated domain'),('When is “if P then Q” false?','when P is true and Q is false'),('Complete: not (P and Q) is ___.','not P or not Q'),('Complete: not (P or Q) is ___.','not P and not Q')]),
'definitions':('mathematical-literacy-definitions','definitions-theorems-and-examples','ml-structures','packet-definitions-theorems-and-examples-v2',[127,128],[
('Definitions fix meaning','A definition supplies an exact criterion; it is not merely a typical example.','What does a mathematical definition provide?','an exact meaning'),('Unpack evenness','An integer is even exactly when it can be written $2k$ for an integer k.','What form proves that n is even?','n equals 2k for some integer k'),('Unpack oddness','An integer is odd exactly when it can be written $2k+1$ for an integer k.','What form proves that n is odd?','n equals 2k plus 1 for some integer k'),('Read divisibility','$a\\mid b$ means $b=ac$ for some integer c; it is not the fraction $a/b$.','What must exist for $a\\mid b$?','an integer c with b equals ac'),('Use prime and composite criteria','Prime and composite are definitions about positive integer factors, not simply about odd or even values.','Is every odd integer prime?','no'),('Separate example and definition','An example can illustrate a definition but cannot replace its necessary-and-sufficient condition.','Can one example serve as a definition?','no'),('Use definitions in proofs','A definition licenses substituting its exact form into a proof step.','What licenses replacing an even integer n by 2k?','the definition of even')],[
('Complete: n is even if n equals __ for an integer k.','2k'),('Complete: n is odd if n equals __ for an integer k.','2k plus 1'),('What does $a\\mid b$ mean?','b equals ac for some integer c'),('Is $a\\mid b$ the same notation as a divided by b?','no'),('What kind of meaning does a definition give?','an exact meaning'),('Can a single example prove a universal definition?','no'),('What factor property distinguishes a prime number?','it has exactly two positive divisors'),('What factor property distinguishes a composite number?','it has more than two positive divisors')]),
'theorems':('mathematical-literacy-theorem-reading-and-application','theorem-reading-and-application','ml-theorem-reading','packet-theorem-reading-and-application-v2',[125,126],[
('Theorem and proof','A theorem is a true mathematical statement with a proof; a proof is its written verification.','What is a proof?','a written verification of a theorem'),('Find hypotheses','In a conditional theorem, hypotheses are the conditions assumed before the conclusion can be used.','What must be checked before applying a conditional theorem?','its hypotheses'),('Read the conclusion','Once hypotheses hold, a conditional theorem yields its stated conclusion—not its converse.','What does a conditional theorem yield when its hypothesis holds?','its conclusion'),('Read setup notation','Some theorems begin with declarations that set the objects or domains before the conditional claim.','What can setup notation specify before a theorem claim?','the objects or domain'),('Read biconditionals','A biconditional asserts both directions and can be read as two conditionals.','How many conditional directions does a biconditional contain?','two'),('Name theorem roles','Proposition, lemma, and corollary name roles in exposition; a lemma often supports a larger result.','What is a lemma commonly used for?','as an intermediate result'),('Avoid overgeneralizing','Not every theorem is conditional; some directly state a proved fact.','Must every theorem have if-then form?','no')],[
('What is a theorem?','a true mathematical statement that has been proved'),('What is a proof?','a written verification'),('What must hold before a conditional theorem conclusion is used?','the hypotheses'),('What does a biconditional express?','two conditional directions'),('What is a lemma?','an intermediate result used to support a larger theorem'),('What can setup notation specify?','objects or domains'),('Does a theorem conclusion prove its converse?','no'),('Must every theorem be conditional?','no')]),
'proofs':('mathematical-literacy-proofs','reading-proofs-and-exposition','ml-proof-reading','packet-reading-proofs-and-exposition-v2',['0033'],[
('Read the proposition','A proposition states hypotheses and a conclusion; a proof must connect the former to the latter.','What two parts should a reader locate in a proposition?','hypotheses and conclusion'),('Track auxiliary quantities','An auxiliary quantity is introduced to make a needed relationship easier to express or bound.','Why might a proof define an auxiliary quantity?','to establish a needed relationship'),('Check inequalities','Displayed inequalities must actually be established before they can support a later theorem use.','What must be shown before using a bound in a proof?','the inequality'),('Apply a cited theorem','A cited theorem is warranted only after its relevant conditions have been verified.','What must be checked before invoking a theorem?','its conditions'),('Read squeeze structure','The squeeze theorem is used after the target quantity has been placed between appropriate bounds.','What kind of evidence supports a squeeze-theorem application?','bounds on the target quantity'),('Mark the conclusion','A proof-closing statement is justified only when the announced conclusion follows from earlier licensed steps.','What must precede “this proves the theorem”?','a derivation of the stated conclusion'),('Separate exposition roles','A definition fixes meaning, a theorem states a claim, and a proof supplies the justification.','What role supplies justification for a theorem?','a proof')],[
('What two parts should you locate in a proposition?','hypotheses and conclusion'),('Why introduce an auxiliary quantity?','to establish a needed relationship'),('What must be established before citing a theorem?','its conditions'),('What evidence is needed for a squeeze-theorem application?','appropriate bounds'),('What does a definition do in exposition?','fixes meaning'),('What does a proof do in exposition?','supplies justification'),('When may a proof be closed?','after the stated conclusion has been derived'),('What should every inference have?','a justification')]),
'diagnosis':('mathematical-literacy-proof-forms-and-argument-diagnosis','proof-forms-and-argument-diagnosis','ml-proof-diagnosis','packet-proof-forms-and-argument-diagnosis-v2',[140,141],[
('Start a direct proof','A direct proof of “if P then Q” assumes P and derives Q using definitions or algebra.','What does a direct proof of “if P then Q” assume?','P'),('Form the contrapositive','The contrapositive of “if P then Q” is “if not Q then not P.”','What is the contrapositive of “if P then Q”?','if not Q then not P'),('Use equivalence','A contrapositive proof works because the original conditional and its contrapositive are logically equivalent.','Why can a contrapositive proof prove the original conditional?','the statements are logically equivalent'),('Do not prove the converse','“If Q then P” is the converse and does not generally establish “if P then Q.”','What is “if Q then P” called?','the converse'),('Do not prove the inverse','“If not P then not Q” is the inverse, another different conditional.','What is “if not P then not Q” called?','the inverse'),('Track the contrapositive branch','A contrapositive proof assumes not Q and must derive not P.','What must a contrapositive branch derive from not Q?','not P'),('Demand warrants','In the parity example, each algebraic or definition-based step must justify the next conclusion.','What must each proof step have?','a justification')],[
('What does a direct proof of “if P then Q” assume?','P'),('What does a direct proof derive?','Q'),('What is the contrapositive of “if P then Q”?','if not Q then not P'),('What is the converse of “if P then Q”?','if Q then P'),('What is the inverse of “if P then Q”?','if not P then not Q'),('What does a contrapositive proof assume?','not Q'),('What must it derive?','not P'),('What must justify each proof step?','a definition or algebra')]),
'exposition':('mathematical-literacy-reading-mathematical-exposition','reading-mathematical-exposition','ml-exposition','packet-reading-mathematical-exposition-v2',['0033'],[
('Find the proposition','A proposition presents a mathematical claim with hypotheses and conclusion.','What does a proposition state?','a claim with hypotheses and conclusion'),('Read definitions','A definition supplies exact terminology used by subsequent statements and proofs.','What does a definition supply?','exact terminology'),('Read theorem statements','A theorem names the claim to be established; it is not itself the chain of reasons.','What does a theorem statement provide?','the claim to be established'),('Read proof steps','A proof turns definitions, hypotheses, and prior results into a warranted conclusion.','What turns hypotheses into a warranted conclusion?','a proof'),('Follow auxiliary notation','An auxiliary definition can organize the quantity that later inequalities discuss.','Why can an author introduce auxiliary notation?','to organize a needed relationship'),('Check theorem transitions','An invocation of the squeeze theorem must follow verified bounds, not merely precede them.','What must appear before a squeeze-theorem conclusion?','verified bounds'),('Read conclusion markers','A conclusion marker summarizes a completed chain; it does not supply a missing reason.','Does a conclusion marker replace a proof step?','no')],[
('What does a definition supply?','exact terminology'),('What does a theorem statement provide?','the claim to be established'),('What does a proof provide?','a warranted conclusion'),('What two parts can a proposition contain?','hypotheses and conclusion'),('Why introduce auxiliary notation?','to organize a needed relationship'),('What must precede a squeeze-theorem conclusion?','verified bounds'),('Does “this proves the theorem” supply a missing reason?','no'),('What should connect a conclusion to earlier text?','justified inference')])}

def pages(values):
 base='src-20260807082523-aa2084c404' if values==['0033'] else SRC
 return [f'{base}:page-{x:0>4}' for x in values]
def choice(id,text,wrong=False): return {'id':id,'text':text,'issueSignals':([{'id':'mathematical-structure-recognition-error','domains':[]}] if wrong else [])}
def check(i,title,prompt,answer):
 if answer == 'no': answer = f'No—{title.lower()} supplies the needed distinction.'
 if answer == 'yes': answer = f'Yes—{title.lower()} meets the stated criterion.'
 return {'id':f'check-{i:03d}','type':'multipleChoice','prompt':prompt,'choices':[choice('a',answer),choice('b',f'Confuse {title.lower()} with a different mathematical role.',True),choice('c',f'Drop a required condition from {title.lower()}.',True),choice('d',f'Assert a conclusion about {title.lower()} without a warrant.',True)],'answer':{'choiceId':'a'},'explanation':f'Solution: {answer}.\n\nWhy it works: The section on {title.lower()} supplies the exact definition, condition, or proof structure needed here.\n\nWhy the other choices fail: Each alternative specifically misreads {title.lower()} by changing its role, omitting its condition, or asserting a result without a warrant.','difficultyDimensions':['representationTransfer','conditionChecking'],'difficultyEvidence':f'Requires reading the specific structure in {title.lower()} and preserving its stated conditions.'}
def recall(i,prompt,answer):
 return {'id':f'r{i:03d}','type':'cloze' if i%2 else 'typed','prompt':prompt,'answer':{'expected':answer,'aliases':[answer]},'explanation':f'Solution: {answer}.\n\nWhy it works: The response follows from the approved topic definition or structure.','tags':[],'skills':[],'issueSignals':[],'choices':[]}
def blueprint(aid,qid,obj,packet,source,qtype,given):
 sig=f'{aid}::{qid}::'+''.join(c.lower() if c.isalnum() else '-' for c in given).strip('-')[:145]
 return {'id':f'{aid}-{qid}-blueprint','assessmentId':aid,'questionId':qid,'objectiveId':obj,'sourceChunks':source,'reviewState':'approved','questionType':qtype,'givens':given,'unknown':'The requested topic-specific reading or retrieval response.','representationRequirement':'Read the stated notation, condition, or proof role without changing its meaning.','governingPrinciple':'Apply the approved packet-supported definition or logical relation.','methodSteps':['Identify the declared object and its condition.','Apply the topic-specific definition or relation.','Check the response against every stated condition.'],'likelyMisconception':'Confusing a related notation, direction, condition, or exposition role.','difficultyEvidence':'Requires topic-specific interpretation rather than a generic reading strategy.','answerVerificationMethod':'Check directly against the packet-supported definition, condition, or proof relation.','variationAxes':['topic representation','governing relation','misconception branch'],'reasoningSignature':sig}

for key,(stem,topic,obj,packet,pageids,sections,recalls) in topics.items():
 source=pages(pageids); lesson_path=A/f'{stem}-concept-lesson.yaml'; recall_path=A/f'{stem}-recall.yaml'
 lesson=yaml.safe_load(lesson_path.read_text(encoding='utf-8')); drill=yaml.safe_load(recall_path.read_text(encoding='utf-8'))
 lesson['authoring']=lesson.get('authoring') or {}; lesson['authoring']['sourcePacketId']=packet; lesson['authoring']['blueprintId']=f'{stem}-concept-lesson-phase1-blueprints'
 lesson['lesson']={'introduction':f'This lesson develops {lesson["title"]} through the exact notation, definitions, and proof structures in the approved source packet. Read the stated condition before drawing a conclusion.','sections':[{'id':f's{i:02d}','title':title,'required':True,'content':content,'media':[],'check':check(i,title,prompt,answer)} for i,(title,content,prompt,answer) in enumerate(sections,1)]}
 drill['authoring']=drill.get('authoring') or {}; drill['authoring']['sourcePacketId']=packet; drill['authoring']['blueprintId']=f'{stem}-recall-phase1-blueprints'; drill['items']=[recall(i,p,a) for i,(p,a) in enumerate(recalls,1)]
 lesson_path.write_text(yaml.safe_dump(lesson,sort_keys=False,allow_unicode=True,width=110),encoding='utf-8'); recall_path.write_text(yaml.safe_dump(drill,sort_keys=False,allow_unicode=True,width=110),encoding='utf-8')
 for assessment,entries,suffix in [(lesson,lesson['lesson']['sections'],'concept-lesson'),(drill,drill['items'],'recall')]:
  bp_path=B/f'{stem}-{suffix}-phase1-blueprints.yaml'; bp=yaml.safe_load(bp_path.read_text(encoding='utf-8'))
  bp['packetId']=packet; bp['blueprints']=[blueprint(assessment['id'], (e['check']['id'] if suffix=='concept-lesson' else e['id']),obj,packet,source,(e['check']['type'] if suffix=='concept-lesson' else e['type']),(e['check']['prompt'] if suffix=='concept-lesson' else e['prompt'])) for e in entries]
  bp_path.write_text(yaml.safe_dump(bp,sort_keys=False,allow_unicode=True,width=110),encoding='utf-8')
