import re
import glob

def remove_duplicate_subcategoryIds(content):
    # Find all 'subcategoryIds:' lines
    lines = content.split('\n')
    out = []
    
    seen_subcat = False
    skip_mode = False
    
    for i, line in enumerate(lines):
        if line.startswith('subcategoryIds:'):
            if seen_subcat:
                # We already saw one. Oh wait, if the second one is the real one, we should keep the second one.
                # Actually, the FIRST one was generated by my bad regex replace.
                # Let's read the file as text and remove the FIRST block.
                pass
            seen_subcat = True

    # A better way: find 'subcategoryIds:\n  - <something>\nsubcategoryIds:'
    # and remove the first part
    content = re.sub(r'subcategoryIds:\n\s+-\s+[^\n]+\nsubcategoryIds:', 'subcategoryIds:', content)
    return content

for path in glob.glob('data/assessments/*.yaml'):
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    new_content = remove_duplicate_subcategoryIds(content)
    
    # Also fix "While parsing a block mapping, did not find expected key."
    # Wait, those 4 volumes-solids files had:
    #   learningGoal: ...
    #   activityType: ...
    #   tags: ...
    # That might have gotten moved into `navigation:` but I put `navigation:` before `subcategoryIds`?
    # Let's just fix the python script to properly format `navigation:` block.
    
    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)
