import os

def create_yaml(filename, content):
    path = os.path.join(r"c:\Users\SeanS\Downloads\cir_app\data\assessments", filename)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content.strip() + '\n')

volumes_method_selection = """
schemaVersion: 1
id: calc2-volumes-method-selection-quiz
title: Volumes - Method Selection & Tricky Axes
assessmentType: quiz
categoryId: calculus-2
subcategoryIds:
  - volumes-of-solids
  - cylindrical-shells
navigation:
  learningGoal: practice
  activityType: focusedPractice
  tags:
    - advanced
    - exam-prep
modeDefault: practice
randomizeQuestions: true
questions:
  - id: vols-method-1-y-axis-shell
    type: multipleChoice
    prompt: |
      You need to find the volume of the solid generated by revolving the region bounded by $y = \sin(x^2)$, the $x$-axis, $x = 0$, and $x = \sqrt{\pi}$ around the $y$-axis. Which method MUST be used, and what is the correct integral?
    choices:
      - id: a
        text: 'Disks: $\pi \int_0^{\sqrt{\pi}} \sin^2(x^2) \, dx$'
      - id: b
        text: 'Shells: $2\pi \int_0^{\sqrt{\pi}} x \sin(x^2) \, dx$'
      - id: c
        text: 'Washers: $\pi \int_0^1 (\pi - \arcsin(y)) \, dy$'
      - id: d
        text: 'Shells: $2\pi \int_0^{\sqrt{\pi}} x^2 \sin(x) \, dx$'
    answer:
      choiceId: b
    explanation: |
      Let's analyze the region. It's given in terms of $x$, and the bounds are $x=0$ to $x=\sqrt{\pi}$.
      
      We are revolving around the $y$-axis (a vertical line).
      - If we use **Disks/Washers**, our slices are horizontal ($\perp$ to the $y$-axis), so we must integrate with respect to $y$. This means we'd have to solve $y = \sin(x^2)$ for $x$. $x = \pm\sqrt{\arcsin(y)}$, which creates an extremely difficult or impossible integral to solve analytically.
      - If we use **Cylindrical Shells**, our slices are vertical ($\parallel$ to the $y$-axis), so we integrate with respect to $x$. This avoids solving for $x$.
      
      The Shell formula is $V = \int 2\pi r(x) h(x) \, dx$.
      Here, the radius is the distance from the slice at $x$ to the $y$-axis ($x=0$), so $r(x) = x$.
      The height is the top function minus the bottom function: $h(x) = \sin(x^2) - 0 = \sin(x^2)$.
      
      $$V = \int_0^{\sqrt{\pi}} 2\pi x \sin(x^2) \, dx$$
      
      Notice that this integral can be easily solved using $u$-substitution with $u = x^2, du = 2x \, dx$.

  - id: vols-method-2-shifted-axis-washer
    type: multipleChoice
    prompt: |
      Set up the integral for the volume of the solid obtained by rotating the region bounded by $y = x^2$ and $y = 2x$ about the line $y = 5$.
    choices:
      - id: a
        text: '$\pi \int_0^2 [(5 - x^2)^2 - (5 - 2x)^2] \, dx$'
      - id: b
        text: '$\pi \int_0^2 [(2x)^2 - (x^2)^2] \, dx$'
      - id: c
        text: '$\pi \int_0^2 [(5 - 2x)^2 - (5 - x^2)^2] \, dx$'
      - id: d
        text: '$2\pi \int_0^2 (5 - x)(2x - x^2) \, dx$'
    answer:
      choiceId: a
    explanation: |
      First, find the intersection points: $x^2 = 2x \implies x(x - 2) = 0 \implies x = 0, 2$.
      On $[0, 2]$, $2x \ge x^2$ (so $y=2x$ is the "top" curve and $y=x^2$ is the "bottom").
      
      We are revolving about the horizontal line $y=5$. Since the axis is horizontal and our functions are $y=f(x)$, we slice vertically ($\perp$ to axis). This means we use the **Washer Method** ($dx$).
      
      The formula is $V = \pi \int [R(x)^2 - r(x)^2] \, dx$.
      The axis of revolution is $y=5$. Both curves are below this axis.
      The **outer radius** $R(x)$ is the distance from the axis down to the *furthest* curve (the bottom curve $y=x^2$).
      $R(x) = 5 - x^2$.
      
      The **inner radius** $r(x)$ is the distance from the axis down to the *closest* curve (the top curve $y=2x$).
      $r(x) = 5 - 2x$.
      
      Therefore, the setup is:
      $$V = \pi \int_0^2 [(5 - x^2)^2 - (5 - 2x)^2] \, dx$$
      
      *Common Error Trap:* Choice C reverses the radii, which would result in a negative volume. Choice D attempts to use the Shell method but incorrectly uses $5-x$ for the radius (which would be for revolution around $x=5$).

  - id: vols-method-3-shifted-axis-shell
    type: multipleChoice
    prompt: |
      Set up the integral for the volume of the solid obtained by rotating the region bounded by $y = x^2$ and $y = 2x$ about the line $x = -1$.
    choices:
      - id: a
        text: '$2\pi \int_0^2 (x - 1)(2x - x^2) \, dx$'
      - id: b
        text: '$2\pi \int_0^2 (x + 1)(2x - x^2) \, dx$'
      - id: c
        text: '$2\pi \int_0^2 (x + 1)(x^2 - 2x) \, dx$'
      - id: d
        text: '$\pi \int_0^2 [(x + 1)(2x) - (x + 1)(x^2)] \, dx$'
    answer:
      choiceId: b
    explanation: |
      First, intersection points are $x=0$ and $x=2$. On $[0,2]$, $y=2x$ is above $y=x^2$.
      
      We are revolving about the vertical line $x = -1$. Because our functions are $y=f(x)$, vertical slices are parallel to the axis of revolution. This dictates the **Cylindrical Shells** method ($dx$).
      
      Formula: $V = \int 2\pi r(x) h(x) \, dx$.
      
      **Radius $r(x)$:** The distance from a slice at $x$ to the axis $x = -1$. Since $x \ge 0$, the slice is to the right of the axis.
      $r(x) = x - (-1) = x + 1$.
      
      **Height $h(x)$:** Top curve minus bottom curve.
      $h(x) = 2x - x^2$.
      
      Putting it together:
      $$V = 2\pi \int_0^2 (x + 1)(2x - x^2) \, dx$$
      
      *Common Error Trap:* Choice A uses $x-1$ which would be for an axis at $x=1$ if the region were $x>1$. Choice C reverses the height, yielding a negative volume. Choice D inappropriately mixes the disk/washer constant $\pi$ with the shell components.

  - id: vols-method-4-which-is-better
    type: multipleChoice
    prompt: |
      The region bounded by $x = y^3 - 4y^2 + 3y$ and the $y$-axis is revolved about the $x$-axis. Which method avoids the need to solve a cubic equation for $y$?
    choices:
      - id: a
        text: 'Cylindrical Shells'
      - id: b
        text: 'Disks/Washers'
      - id: c
        text: 'Both require solving the cubic.'
      - id: d
        text: 'Neither, integration by parts is required.'
    answer:
      choiceId: a
    explanation: |
      The boundary function is given as $x = f(y)$. 
      The axis of revolution is the $x$-axis (a horizontal line).
      
      - **Disks/Washers** slice $\perp$ to the axis. For a horizontal axis, this requires vertical slices, so we must integrate with respect to $x$. This would force us to solve $x = y^3 - 4y^2 + 3y$ for $y$ in terms of $x$, which is incredibly difficult for a cubic.
      - **Cylindrical Shells** slice $\parallel$ to the axis. For a horizontal axis, this requires horizontal slices, meaning we integrate with respect to $y$. This allows us to use the function exactly as given: $h(y) = y^3 - 4y^2 + 3y$.
      
      Thus, Cylindrical Shells is the superior method here.
"""

volumes_mixed = """
schemaVersion: 1
id: calc2-volumes-mixed-test
title: Volumes of Solids Cumulative Mastery
assessmentType: test
categoryId: calculus-2
subcategoryIds:
  - volumes-of-solids
  - cylindrical-shells
navigation:
  learningGoal: evaluate
  activityType: formalTest
  tags:
    - advanced
    - cumulative
modeDefault: evaluate
randomizeQuestions: true
attemptQuestionCount: 5
questions:
  - id: vol-mix-1
    type: multipleChoice
    prompt: |
      Find the volume of the solid generated by revolving the region bounded by $y = \sqrt{x}$, $y = 2$, and $x = 0$ about the $y$-axis.
    choices:
      - id: a
        text: '$\frac{32\pi}{5}$'
      - id: b
        text: '$\frac{16\pi}{3}$'
      - id: c
        text: '$\frac{8\pi}{3}$'
      - id: d
        text: '$\frac{32\pi}{3}$'
    answer:
      choiceId: a
    explanation: |
      **Method 1: Disks (dy)**
      The region is bounded on the left by $x=0$ and on the right by $x = y^2$. The limits are $y=0$ to $y=2$.
      Revolving around the $y$-axis, the slices are horizontal ($\perp$ to axis).
      $V = \pi \int_0^2 R(y)^2 \, dy = \pi \int_0^2 (y^2)^2 \, dy = \pi \int_0^2 y^4 \, dy$
      $V = \pi [\frac{1}{5}y^5]_0^2 = \frac{32\pi}{5}$.
      
      **Method 2: Shells (dx)**
      The region is bounded by top $y=2$, bottom $y=\sqrt{x}$, from $x=0$ to $x=4$.
      Revolving around $y$-axis, slices are vertical ($\parallel$ to axis).
      $V = 2\pi \int_0^4 r(x)h(x) \, dx = 2\pi \int_0^4 x(2 - \sqrt{x}) \, dx = 2\pi \int_0^4 (2x - x^{3/2}) \, dx$
      $V = 2\pi [x^2 - \frac{2}{5}x^{5/2}]_0^4 = 2\pi (16 - \frac{2}{5}(32)) = 2\pi (16 - \frac{64}{5}) = 2\pi (\frac{80-64}{5}) = \frac{32\pi}{5}$.
      
      Both methods yield $\frac{32\pi}{5}$.

  - id: vol-mix-2
    type: multipleChoice
    prompt: |
      Set up the integral for the volume of the solid whose base is the region bounded by $x^2 + y^2 = 4$, and whose cross sections perpendicular to the $x$-axis are equilateral triangles.
    choices:
      - id: a
        text: '$\sqrt{3} \int_{-2}^2 (4 - x^2) \, dx$'
      - id: b
        text: '$\frac{\sqrt{3}}{4} \int_{-2}^2 (4 - x^2) \, dx$'
      - id: c
        text: '$\frac{\sqrt{3}}{4} \int_{-2}^2 \sqrt{4 - x^2} \, dx$'
      - id: d
        text: '$\sqrt{3} \int_{-2}^2 (4 - x^2)^2 \, dx$'
    answer:
      choiceId: a
    explanation: |
      The base is a circle of radius 2.
      Cross sections are perpendicular to the $x$-axis, so we integrate with respect to $x$ from $x = -2$ to $x = 2$.
      
      The length of the base of each triangle $s$ stretches from the bottom of the circle $y = -\sqrt{4-x^2}$ to the top $y = \sqrt{4-x^2}$.
      $s = \sqrt{4-x^2} - (-\sqrt{4-x^2}) = 2\sqrt{4-x^2}$.
      
      The area of an equilateral triangle with side $s$ is $A = \frac{\sqrt{3}}{4} s^2$.
      $A(x) = \frac{\sqrt{3}}{4} (2\sqrt{4-x^2})^2 = \frac{\sqrt{3}}{4} (4(4 - x^2)) = \sqrt{3}(4 - x^2)$.
      
      The volume is $V = \int_{-2}^2 A(x) \, dx = \sqrt{3} \int_{-2}^2 (4 - x^2) \, dx$.
      
      *Common Error Trap:* Choice B incorrectly forgets to square the $2$ when squaring the side length, leaving the $1/4$ uncancelled.

  - id: vol-mix-3
    type: multipleChoice
    prompt: |
      The region bounded by $y = \sec(x)$, $y=0$, $x=0$, and $x=\pi/4$ is revolved about the $x$-axis. Find the volume.
    choices:
      - id: a
        text: '$\pi$'
      - id: b
        text: '$\frac{\pi}{4}$'
      - id: c
        text: '$\pi \sqrt{2}$'
      - id: d
        text: '$2\pi$'
    answer:
      choiceId: a
    explanation: |
      Revolving around the $x$-axis using vertical slices $\implies$ Disks.
      
      $V = \pi \int_0^{\pi/4} R(x)^2 \, dx$
      $V = \pi \int_0^{\pi/4} \sec^2(x) \, dx$
      
      The antiderivative of $\sec^2(x)$ is $\tan(x)$.
      $V = \pi [\tan(x)]_0^{\pi/4} = \pi (\tan(\pi/4) - \tan(0)) = \pi (1 - 0) = \pi$.

  - id: vol-mix-4
    type: multipleChoice
    prompt: |
      Set up the integral for the volume of the solid generated by revolving the region bounded by $y=e^x$, $x=0$, $y=3$ about the line $x=-2$.
    choices:
      - id: a
        text: '$2\pi \int_0^{\ln(3)} (x+2)(3-e^x) \, dx$'
      - id: b
        text: '$\pi \int_1^3 [(\ln(y) + 2)^2 - 2^2] \, dy$'
      - id: c
        text: '$2\pi \int_0^{\ln(3)} (x-2)(e^x-3) \, dx$'
      - id: d
        text: 'Both A and B are correct setups.'
    answer:
      choiceId: d
    explanation: |
      Let's analyze the region: bounded by $y=e^x$ (bottom), $y=3$ (top), $x=0$ (left boundary, $y=1$). Intersection of $y=e^x$ and $y=3$ is $x=\ln(3)$.
      
      **Method 1: Shells (dx)**
      Vertical slices, revolving around $x=-2$ (vertical).
      Radius $r(x) = x - (-2) = x + 2$.
      Height $h(x) = \text{Top} - \text{Bottom} = 3 - e^x$.
      Bounds: $x=0$ to $x=\ln(3)$.
      $V = 2\pi \int_0^{\ln(3)} (x+2)(3-e^x) \, dx$. This matches choice A.
      
      **Method 2: Washers (dy)**
      Horizontal slices, revolving around $x=-2$ (vertical).
      Rewrite equations: $x = \ln(y)$. Left boundary is $x=0$.
      Outer radius $R(y)$: Distance from $x=-2$ to furthest curve $x=\ln(y)$. $R(y) = \ln(y) - (-2) = \ln(y) + 2$.
      Inner radius $r(y)$: Distance from $x=-2$ to closest curve $x=0$. $r(y) = 0 - (-2) = 2$.
      Bounds: $y=1$ (since $e^0=1$) to $y=3$.
      $V = \pi \int_1^3 [(\ln(y) + 2)^2 - 2^2] \, dy$. This matches choice B.
      
      Therefore, both A and B are correct.

  - id: vol-mix-5
    type: multipleChoice
    prompt: |
      Find the volume of the solid whose base is the unit circle $x^2 + y^2 = 1$ and whose cross sections perpendicular to the $y$-axis are squares.
    choices:
      - id: a
        text: '$\frac{8}{3}$'
      - id: b
        text: '$\frac{16}{3}$'
      - id: c
        text: '$\frac{4\pi}{3}$'
      - id: d
        text: '$2$'
    answer:
      choiceId: b
    explanation: |
      The base is $x^2 + y^2 = 1$.
      Cross sections are perpendicular to the $y$-axis, so we integrate with respect to $y$ from $-1$ to $1$.
      
      The side of the square $s$ stretches from the left boundary $x = -\sqrt{1-y^2}$ to the right boundary $x = \sqrt{1-y^2}$.
      $s = \sqrt{1-y^2} - (-\sqrt{1-y^2}) = 2\sqrt{1-y^2}$.
      
      The area of a square is $A = s^2$.
      $A(y) = (2\sqrt{1-y^2})^2 = 4(1 - y^2)$.
      
      The volume is:
      $V = \int_{-1}^1 A(y) \, dy = 4 \int_{-1}^1 (1 - y^2) \, dy$.
      Using symmetry (even function):
      $V = 8 \int_0^1 (1 - y^2) \, dy = 8 [y - \frac{1}{3}y^3]_0^1 = 8(1 - \frac{1}{3}) = 8(\frac{2}{3}) = \frac{16}{3}$.
"""

create_yaml('calc2-volumes-method-selection-quiz.yaml', volumes_method_selection)
create_yaml('calc2-volumes-mixed-test.yaml', volumes_mixed)
print("Generated Volumes advanced files.")
