import yaml
from pathlib import Path
out=Path('docs/assessment-reference/question-blueprints')
assets=[]
for p in Path('data/assessments').glob('*.yaml'):
 n=p.name
 if not any(x in n for x in ['chem-acids-easy-quiz.yaml','chem-acids-hard-quiz.yaml','chem-acids-easy-test.yaml','chem-acids-hard-test.yaml','chemistry-acid-base-reactions-easy-quiz-s2c.yaml','chemistry-acid-base-reactions-hard-quiz-s2c.yaml','chemistry-acid-base-reactions-easy-test-s2c.yaml','chemistry-acid-base-reactions-hard-test-s2c.yaml','chemistry-acids-bases-easy-quiz-s2c.yaml','chemistry-acids-bases-hard-quiz-s2c.yaml','chemistry-acids-bases-easy-test-s2c.yaml','chemistry-acids-bases-hard-test-s2c.yaml','chemistry-ph-water-easy-quiz-s2c.yaml','chemistry-ph-water-hard-quiz-s2c.yaml','chemistry-ph-water-easy-test-s2c.yaml','chemistry-ph-water-hard-test-s2c.yaml','chemistry-titrations-easy-quiz-s2c.yaml','chemistry-titrations-hard-quiz-s2c.yaml','chemistry-titrations-easy-test-s2c.yaml','chemistry-titrations-hard-test-s2c.yaml']): continue
 a=yaml.safe_load(p.read_text(encoding='utf8')); aid=a['id']; topic=a['topicId']; tier='hard' if 'hard' in aid else 'easy'; packet={'chem-acids':'packet-chemistry-acids-foundations-v1','chemistry-acid-base-reactions':'packet-chemistry-acid-base-reactions-v1','chemistry-acids-bases':'packet-chemistry-acids-bases-equilibrium-v1','chemistry-ph-water':'packet-chemistry-ph-water-calculus-v1','chemistry-titrations':'packet-chemistry-titrations-analysis-v1'}[topic]; chunks={'chem-acids':['chunk-1824','chunk-1826','chunk-1836'],'chemistry-acid-base-reactions':['chunk-0419','chunk-0420','chunk-0433'],'chemistry-acids-bases':['chunk-1824','chunk-1826','chunk-1836'],'chemistry-ph-water':['chunk-1837','chunk-1842','chunk-1848'],'chemistry-titrations':['chunk-0455','chunk-0457','chunk-0458']}[topic]
 bs=[]
 for i,q in enumerate(a.get('questions',[]),1):
  bs.append({'id':f'{aid}-q{i:03d}-blueprint','assessmentId':aid,'questionId':q['id'],'objectiveId':f'{topic}-acid-base-objective','sourceChunks':[f'src-20260720035703-91ea51b0d8:{chunks[(i-1)%len(chunks)]}'],'reviewState':'approved-for-internal-derivation','questionType':q.get('type','multipleChoice'),'governingPrinciple':f'{topic} acid-base model','methodSteps':['Identify the species, region, or governing relation.','Apply proton bookkeeping, equilibrium, pH, or stoichiometry.','Verify charge, units, and stated assumptions.'],'likelyMisconception':'Confuses model scope, coefficients, strength, logarithmic direction, or titration region.','answerVerificationMethod':'Independently recompute from the cited relation and check units and limiting behavior.','variationAxes':['scenario','representation','unknown'],'difficultyDimensions':q.get('difficultyDimensions',['modelOrDerivation','errorDiagnosis'] if tier=='easy' else ['modelOrDerivation','errorDiagnosis','transfer']),'difficultyEvidence':q.get('difficultyEvidence','Applies the acid-base model to a new prompt and verifies assumptions.'),'transferObjective':f'{topic}-transfer' if tier=='hard' else None,'reasoningSignature':f'{aid}-reasoning-{i:03d}'})
 for b in bs:
  if b['transferObjective'] is None: del b['transferObjective']
 bp={'schemaVersion':1,'id':aid+'-blueprints','categoryId':'chemistry','topicId':topic,'packetId':packet,'reviewState':'approved-for-internal-derivation','blueprints':bs}
 out.joinpath(aid+'-blueprints.yaml').write_text(yaml.safe_dump(bp,sort_keys=False,allow_unicode=True,width=120),encoding='utf8')
