import os

def create_yaml(filename, content):
    path = os.path.join(r"c:\Users\SeanS\Downloads\cir_app\data\assessments", filename)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content.strip() + '\n')

arc_surface_mixed = """
schemaVersion: 1
id: calc2-arc-surface-mixed-quiz
title: Arc Length & Surface Area - Advanced Distinctions
assessmentType: quiz
categoryId: calculus-2
subcategoryIds:
  - arc-length-surface-area
navigation:
  learningGoal: practice
  activityType: focusedPractice
  tags:
    - advanced
    - exam-prep
modeDefault: practice
randomizeQuestions: true
questions:
  - id: arc-surf-1-distinction
    type: multipleChoice
    prompt: |
      You are given the curve $y = \frac{x^3}{3} + \frac{1}{4x}$ for $1 \le x \le 2$. 
      Which of the following integrals represents the **surface area** generated by revolving this curve about the **$x$-axis**?
    choices:
      - id: a
        text: '$\int_1^2 \sqrt{1 + (x^2 - \frac{1}{4x^2})^2} \, dx$'
      - id: b
        text: '$2\pi \int_1^2 x \sqrt{1 + (x^2 - \frac{1}{4x^2})^2} \, dx$'
      - id: c
        text: '$2\pi \int_1^2 (\frac{x^3}{3} + \frac{1}{4x}) \sqrt{1 + (x^2 - \frac{1}{4x^2})^2} \, dx$'
      - id: d
        text: '$\pi \int_1^2 (\frac{x^3}{3} + \frac{1}{4x})^2 \sqrt{1 + (x^2 - \frac{1}{4x^2})^2} \, dx$'
    answer:
      choiceId: c
    explanation: |
      First, distinguish between Arc Length, Surface Area, and Volume.
      - **Arc Length**: $L = \int \sqrt{1 + (f'(x))^2} \, dx$ (Choice A is just the arc length).
      - **Volume (Disk)**: $V = \pi \int (f(x))^2 \, dx$.
      - **Surface Area**: $SA = \int 2\pi r \cdot ds$, where $ds = \sqrt{1 + (f'(x))^2} \, dx$.
      
      Since we are revolving about the $x$-axis, the radius $r$ of the surface of revolution at a point $(x,y)$ is the distance from the point to the $x$-axis, which is $y$ (or $f(x)$).
      
      Therefore, $r = \frac{x^3}{3} + \frac{1}{4x}$.
      The derivative is $y' = x^2 - \frac{1}{4x^2}$.
      
      Plugging this into the Surface Area formula:
      $$SA = \int_1^2 2\pi y \sqrt{1 + (y')^2} \, dx = 2\pi \int_1^2 (\frac{x^3}{3} + \frac{1}{4x}) \sqrt{1 + (x^2 - \frac{1}{4x^2})^2} \, dx$$
      
      *Common Error Traps:* Choice B uses $r = x$, which would be correct if revolving about the $y$-axis. Choice D mixes the volume formula $\pi r^2$ with the arc length element $ds$.

  - id: arc-surf-2-simplification
    type: multipleChoice
    prompt: |
      Find the arc length of the curve $y = \frac{1}{8}x^2 - \ln(x)$ from $x = 1$ to $x = 2$. 
      *(Hint: Look for a perfect square after expanding $1 + (y')^2$.)*
    choices:
      - id: a
        text: '$\frac{3}{8} + \ln(2)$'
      - id: b
        text: '$\frac{3}{8} - \ln(2)$'
      - id: c
        text: '$\frac{15}{8} + \ln(2)$'
      - id: d
        text: '$\frac{15}{8} - \ln(2)$'
    answer:
      choiceId: a
    explanation: |
      The arc length formula is $L = \int_1^2 \sqrt{1 + (y')^2} \, dx$.
      
      First, find the derivative:
      $$y' = \frac{1}{4}x - \frac{1}{x}$$
      
      Square it:
      $$(y')^2 = (\frac{1}{4}x - \frac{1}{x})^2 = \frac{1}{16}x^2 - 2(\frac{1}{4}x)(\frac{1}{x}) + \frac{1}{x^2} = \frac{1}{16}x^2 - \frac{1}{2} + \frac{1}{x^2}$$
      
      Add 1:
      $$1 + (y')^2 = 1 + \frac{1}{16}x^2 - \frac{1}{2} + \frac{1}{x^2} = \frac{1}{16}x^2 + \frac{1}{2} + \frac{1}{x^2}$$
      
      Notice this is a perfect square! It is exactly $(y')^2$ but with a $+\frac{1}{2}$ instead of $-\frac{1}{2}$.
      $$1 + (y')^2 = (\frac{1}{4}x + \frac{1}{x})^2$$
      
      Now, take the square root for the integral:
      $$\sqrt{1 + (y')^2} = \frac{1}{4}x + \frac{1}{x}$$
      
      Integrate:
      $$L = \int_1^2 (\frac{1}{4}x + \frac{1}{x}) \, dx = [\frac{1}{8}x^2 + \ln|x|]_1^2$$
      $$= (\frac{1}{8}(4) + \ln(2)) - (\frac{1}{8}(1) + \ln(1))$$
      $$= (\frac{1}{2} + \ln(2)) - \frac{1}{8} = \frac{3}{8} + \ln(2)$$

  - id: arc-surf-3-y-axis-surface
    type: multipleChoice
    prompt: |
      Consider the curve $x = \sqrt{2y - y^2}$ for $0 \le y \le 1$. Which integral represents the surface area generated by revolving this curve around the **$y$-axis**?
    choices:
      - id: a
        text: '$2\pi \int_0^1 y \sqrt{1 + (\frac{1-y}{\sqrt{2y-y^2}})^2} \, dy$'
      - id: b
        text: '$2\pi \int_0^1 \sqrt{2y - y^2} \sqrt{1 + (\frac{1-y}{\sqrt{2y-y^2}})^2} \, dy$'
      - id: c
        text: '$2\pi \int_0^1 \sqrt{2y - y^2} \sqrt{1 + (\frac{1}{2\sqrt{2y-y^2}})^2} \, dy$'
      - id: d
        text: '$2\pi \int_0^1 (1-y) \sqrt{1 + (\frac{1-y}{\sqrt{2y-y^2}})^2} \, dy$'
    answer:
      choiceId: b
    explanation: |
      We are given $x = g(y)$ and revolving about the $y$-axis.
      The formula for surface area is $SA = \int 2\pi r \, ds$.
      
      When revolving about the $y$-axis, the radius $r$ is the distance to the $y$-axis, which is $x$.
      Therefore, $r = x = \sqrt{2y - y^2}$.
      
      The arc length element with respect to $y$ is $ds = \sqrt{1 + (dx/dy)^2} \, dy$.
      Let's find $dx/dy$:
      $$x = (2y - y^2)^{1/2}$$
      $$\frac{dx}{dy} = \frac{1}{2}(2y - y^2)^{-1/2} \cdot (2 - 2y) = \frac{1 - y}{\sqrt{2y - y^2}}$$
      
      Substitute $r$ and $dx/dy$ into the integral:
      $$SA = \int_0^1 2\pi \sqrt{2y - y^2} \sqrt{1 + \left(\frac{1-y}{\sqrt{2y-y^2}}\right)^2} \, dy$$
      
      Choice B exactly matches this. Choice A incorrectly uses $r = y$ (which would be for revolution about the $x$-axis).
"""

com_average_value = """
schemaVersion: 1
id: calc2-com-average-value-tricky-quiz
title: Center of Mass & Average Value - Advanced
assessmentType: quiz
categoryId: calculus-2
subcategoryIds:
  - average-value
  - moments-mass
navigation:
  learningGoal: practice
  activityType: focusedPractice
  tags:
    - advanced
    - exam-prep
modeDefault: practice
randomizeQuestions: true
questions:
  - id: avg-val-1-implicit-bounds
    type: multipleChoice
    prompt: |
      Find the average value of $f(x) = 3x^2 - 2x$ on the interval defined by the roots of $f(x)$.
    choices:
      - id: a
        text: '$-4/27$'
      - id: b
        text: '$-2/9$'
      - id: c
        text: '$4/27$'
      - id: d
        text: '$0$'
    answer:
      choiceId: b
    explanation: |
      First, find the roots of $f(x) = 3x^2 - 2x$:
      $$x(3x - 2) = 0 \implies x = 0, x = 2/3$$
      The interval is $[a, b] = [0, 2/3]$.
      
      The average value formula is $f_{avg} = \frac{1}{b-a} \int_a^b f(x) \, dx$.
      $$f_{avg} = \frac{1}{2/3 - 0} \int_0^{2/3} (3x^2 - 2x) \, dx$$
      $$= \frac{3}{2} [x^3 - x^2]_0^{2/3}$$
      $$= \frac{3}{2} \left( (2/3)^3 - (2/3)^2 \right)$$
      $$= \frac{3}{2} \left( \frac{8}{27} - \frac{4}{9} \right) = \frac{3}{2} \left( \frac{8}{27} - \frac{12}{27} \right) = \frac{3}{2} \left( -\frac{4}{27} \right) = -\frac{12}{54} = -\frac{2}{9}$$

  - id: com-1-symmetry
    type: multipleChoice
    prompt: |
      Find the centroid $(\bar{x}, \bar{y})$ of the region bounded by $y = 4 - x^2$ and $y = 0$.
    choices:
      - id: a
        text: '$(0, 8/5)$'
      - id: b
        text: '$(0, 2)$'
      - id: c
        text: '$(0, 4/3)$'
      - id: d
        text: '$(8/5, 0)$'
    answer:
      choiceId: a
    explanation: |
      The region is bounded by the parabola $y = 4 - x^2$ (opening downwards, vertex at $(0,4)$) and the $x$-axis. It intersects the $x$-axis at $x = \pm 2$.
      
      **Symmetry Shortcut**: The region is perfectly symmetric across the $y$-axis. Therefore, the centroid must lie on the $y$-axis, meaning $\bar{x} = 0$.
      
      To find $\bar{y}$, we need the Area $A$ and the moment $M_x$.
      $$A = \int_{-2}^2 (4 - x^2) \, dx = 2 \int_0^2 (4 - x^2) \, dx = 2[4x - x^3/3]_0^2 = 2(8 - 8/3) = 2(16/3) = 32/3$$
      
      The moment about the $x$-axis is $M_x = \frac{1}{2} \int_{-2}^2 [f(x)]^2 \, dx$:
      $$M_x = \frac{1}{2} \int_{-2}^2 (4 - x^2)^2 \, dx = \int_0^2 (16 - 8x^2 + x^4) \, dx$$
      $$= [16x - \frac{8}{3}x^3 + \frac{1}{5}x^5]_0^2 = 32 - \frac{64}{3} + \frac{32}{5}$$
      $$= 32(1 - \frac{2}{3} + \frac{1}{5}) = 32(\frac{15 - 10 + 3}{15}) = 32(\frac{8}{15}) = \frac{256}{15}$$
      
      Now find $\bar{y} = \frac{M_x}{A}$:
      $$\bar{y} = \frac{256/15}{32/3} = \frac{256}{15} \cdot \frac{3}{32} = \frac{256}{32} \cdot \frac{3}{15} = 8 \cdot \frac{1}{5} = \frac{8}{5}$$
      
      The centroid is $(0, 8/5)$. Choice B $(0,2)$ is the "midpoint" of the height, which is incorrect because the bottom of the parabola is wider and holds more area, pulling the centroid down below $y=2$.

  - id: com-2-setup-error
    type: multipleChoice
    prompt: |
      A student is setting up the integral for the moment about the $y$-axis ($M_y$) for the region bounded by $y=e^x$, $y=1$, and $x=2$ assuming constant density $\rho = 1$. The student writes:
      $$M_y = \int_0^2 x (e^x) \, dx$$
      What error did the student make?
    choices:
      - id: a
        text: 'The student forgot the $\frac{1}{2}$ multiplier in front of the integral.'
      - id: b
        text: 'The student used the wrong height; the height of the region is $(e^x - 1)$, not $e^x$.'
      - id: c
        text: 'The student should have integrated with respect to $y$.'
      - id: d
        text: 'There is no error; the setup is correct.'
    answer:
      choiceId: b
    explanation: |
      The moment about the $y$-axis is given by $M_y = \int \rho x [f(x) - g(x)] \, dx$.
      The "lever arm" distance from the $y$-axis is $x$.
      The "mass" of a vertical slice is $\rho \cdot (\text{Area}) = \rho \cdot (\text{top} - \text{bottom}) \cdot dx$.
      
      The top function is $y=e^x$ and the bottom function is $y=1$. 
      Therefore, the height of the slice is $(e^x - 1)$.
      
      The correct setup is $M_y = \int_0^2 x (e^x - 1) \, dx$.
      The student incorrectly used the distance from the $x$-axis ($e^x$) instead of the height of the bounded region.
      (Choice A refers to the $M_x$ formula which has the $\frac{1}{2}$. Choice C is incorrect because $M_y$ can absolutely be calculated with respect to $x$.)
"""

create_yaml('calc2-arc-surface-distinction-quiz.yaml', arc_surface_mixed)
create_yaml('calc2-com-average-value-tricky-quiz.yaml', com_average_value)
print("Generated Arc/Surface and COM advanced files.")
