from pathlib import Path
import yaml,json
ROOT=Path(__file__).parents[1]
SID='src-20260720035703-91ea51b0d8'
common={
'chem-acids':('Acids and Bases Foundations','packet-chemistry-acids-foundations-v1','chemistry-acids-foundations-v1','acid-base-models',[
('Identify acids and bases','An acid increases effective hydronium in water or donates a proton; a base increases hydroxide or accepts a proton. Always read the reaction context, not just the formula.','In NH3 + H2O ⇌ NH4+ + OH−, which reactant is the Brønsted–Lowry acid?',['NH3','H2O','NH4+','OH−'],'b','conjugate-acid-base-misidentified'),
('Arrhenius model','Arrhenius language is restricted to aqueous behavior: acids produce H+ (represented by H3O+ in water), and bases produce OH−. It is useful but narrower than proton-transfer language.','Which statement is specifically Arrhenius?',['HCl produces H3O+ in water','NH3 accepts H+','H2O donates H+','NH4+ is conjugate acid of NH3'],'a','acid-base-model-confusion'),
('Brønsted–Lowry transfer','A Brønsted–Lowry acid donates H+ and a base accepts H+. Compare each reactant with its product to locate the transferred proton.','In HCl + H2O → H3O+ + Cl−, water acts as',['the acid','the base','a spectator','a strong electrolyte only'],'b','acid-base-model-confusion'),
('Conjugate pairs','A conjugate base is the acid after losing one proton; a conjugate acid is the base after gaining one. Pair members differ by exactly one H+.','What is the conjugate base of H2CO3?',['H3CO3+','HCO3−','CO3^2−','OH−'],'b','conjugate-acid-base-misidentified'),
('Strength and dissociation','Strong acids and bases dissociate essentially completely; weak species establish an equilibrium. Strength is not the same thing as concentration.','Which description fits a weak acid?',['Every molecule ionizes','Ionization is partial and reversible','It cannot donate H+','Its concentration must be zero'],'b','strong-weak-acid-base-confusion'),
('Electrolytes and concentration','Strong electrolytes conduct well because they produce many ions, but conductivity also depends on concentration. Do not infer strength from dilute or concentrated alone.','Which comparison is valid?',['A dilute strong acid can conduct less than a concentrated weak acid','A weak acid always has lower concentration','A strong acid always has pH 7','Conductivity identifies the conjugate pair'],'a','strong-weak-acid-base-confusion'),
('Integrated classification','Classify with the governing model, track the proton, and then compare conjugate strength. This prevents reversing donor and acceptor roles.','For HSO4− + H2O → SO4^2− + H3O+, which is correct?',['HSO4− is acid and H2O is base','HSO4− is base and H2O is acid','SO4^2− is acid and H3O+ is base','Both reactants are bases'],'a','conjugate-acid-base-misidentified')]),
'chemistry-acid-base-reactions':('Acid–Base Reactions','packet-chemistry-acid-base-reactions-v1','chemistry-acid-base-reactions-v1','neutralization-equations',[
('Neutralization pattern','Neutralization transfers protons so acid and base form water plus a salt or dissolved ions. Balance atoms and charge before interpreting the products.','Which net ionic equation represents strong acid–strong hydroxide neutralization?',['H+ + OH− → H2O','H+ + Cl− → HCl','Na+ + OH− → NaOH','H2O → H+ + OH−'],'a','chemical-equation-balancing-error'),
('Molecular to ionic','Write the balanced molecular equation, dissociate strong aqueous electrolytes, and cancel unchanged spectators. Weak acids remain molecular in the complete ionic equation.','In CH3COOH + NaOH neutralization, which remains molecular?',['NaOH','Na+','CH3COOH','OH−'],'c','spectator-ion-analysis-error'),
('Spectator ions','Spectators appear unchanged on both sides and cancel. A net ionic equation keeps only species participating in the chemical change.','Which ion is a spectator in HCl(aq) + NaOH(aq)?',['H+','OH−','Na+','H2O'],'c','spectator-ion-analysis-error'),
('Acid plus metal','Active metals can displace hydrogen from acids, producing a salt and hydrogen gas. Balance atom and electron counts.','What gas forms when Mg reacts with excess HCl?',['O2','H2','Cl2','CO2'],'b','reaction-product-analysis-error'),
('Acid plus carbonate','Acid plus carbonate proceeds through carbonic acid, which decomposes into water and carbon dioxide.','What additional product distinguishes acid–carbonate reaction from hydroxide neutralization?',['H2 gas','CO2 gas','O2 gas','NH3 gas'],'b','reaction-product-analysis-error'),
('Stoichiometric mole map','Use coefficients from the balanced equation to map known moles to product or reactant moles. Volume and molarity enter after the ratio is correct.','How many moles of NaOH neutralize 0.020 mol H2SO4?',['0.010 mol','0.020 mol','0.040 mol','0.200 mol'],'c','stoichiometry-ratio-error'),
('Reaction direction','Proton transfer is favored toward the weaker acid and weaker base. Compare conjugate strengths rather than deciding from charge alone.','For a strong acid reacting with water, which direction is favored?',['Toward hydronium and the conjugate base','Toward undissociated strong acid only','No reaction is possible','Toward hydroxide formation'],'a','acid-base-equilibrium-direction-error')]),
'chemistry-acids-bases':('Acid–Base Models and Equilibrium','packet-chemistry-acids-bases-equilibrium-v1','chemistry-acids-bases-equilibrium-v1','strength-and-dissociation',[
('Model scope','Arrhenius describes aqueous H+/OH− production; Brønsted–Lowry describes proton transfer in broader settings. Use the broader model when water is absent.','Which reaction is best classified with Brønsted–Lowry language without water?',['NH3 + HCl → NH4+ + Cl−','NaOH → Na+ + OH− in water','HCl(aq) → H+ + Cl−','KOH(aq) → K+ + OH−'],'a','acid-base-model-confusion'),
('Amphiprotic species','An amphiprotic species can donate or accept H+. Bicarbonate can become carbonate by donation or carbonic acid by acceptance.','Which equation shows HCO3− acting as a base?',['HCO3− → CO3^2− + H+','HCO3− + H+ → H2CO3','HCO3− → H+ + CO3^2− only','HCO3− + OH− → H2O'],'b','amphiprotic-role-confusion'),
('Ka and acid strength','For HA ⇌ H+ + A−, Ka=[H+][A−]/[HA]. At comparable conditions, larger Ka means stronger acid and greater dissociation.','Which acid is stronger at comparable conditions?',['Ka=1.0×10−3','Ka=1.0×10−7','They are equal','Strength cannot be compared'],'a','ka-expression-error'),
('Kb and conjugates','For a conjugate pair KaKb=Kw. A stronger acid has a weaker conjugate base, so the constants vary inversely.','If Ka(HA)=1.0×10−5 at 25 °C, what is Kb(A−)?',['1.0×10−9','1.0×10−5','1.0×10−14','1.0×10^9'],'a','conjugate-constant-relation-error'),
('ICE setup','For a weak acid of initial concentration C and change x, equilibrium concentrations are C−x, x, and x. Insert these into Ka before approximating.','Which Ka expression matches a weak monoprotic acid?',['x^2/(C−x)','C^2/x','(C−x)^2/x^2','x/(C+x)'],'a','chemistry-equilibrium-ice-stoichiometry-error'),
('Approximation check','If x is much smaller than C, use C−x≈C and x≈sqrt(KaC), then check percent ionization. A large percentage invalidates the shortcut.','When is the weak-acid approximation least trustworthy?',['x/C=0.20','x/C=0.002','Ka is small and C moderate','The acid is monoprotic'],'a','chemistry-equilibrium-approximation-unchecked'),
('Conjugate equilibrium','A complete solution identifies the model, writes the equilibrium expression, applies conservation, and checks assumptions.','Which statement is correct for a conjugate pair at 25 °C?',['KaKb=1.0×10−14','Both members must be strong','Their concentrations are always equal','pKa and pKb are unrelated'],'a','conjugate-constant-relation-error')]),
'chemistry-ph-water':('Water, pH, and pOH','packet-chemistry-ph-water-v1','chemistry-ph-water-v1','ph-poh-calculation',[
('Autoionization','Water can transfer a proton between molecules: 2H2O ⇌ H3O+ + OH−. At equilibrium Kw=[H3O+][OH−].','In pure water at 25 °C, which relation is true?',['[H3O+]=[OH−]=1.0×10−7 M','[H3O+]=1 M','[OH−]=0','[H3O+][OH−]=1'],'a','water-autoionization-error'),
('pH definition','pH is −log[H3O+]. A tenfold increase in hydronium lowers pH by one unit, so pH is logarithmic.','What is pH when [H3O+]=1.0×10−3 M?',['3.00','−3.00','0.001','11.00'],'a','ph-poh-calculation-error'),
('pOH and Kw','At 25 °C, pH+pOH=14.00 and [H3O+][OH−]=1.0×10−14. Use the relation matching the known quantity.','A solution has pOH=3.00 at 25 °C. What is pH?',['3.00','7.00','11.00','14.00'],'c','ph-poh-calculation-error'),
('Strong-acid calculation','For a strong monoprotic acid, complete dissociation makes formal concentration approximately equal to hydronium concentration. Include coefficients for polyprotic acids.','What is [H3O+] in 0.020 M HCl?',['0.010 M','0.020 M','0.040 M','20 M'],'b','strong-acid-stoichiometry-error'),
('Weak-acid calculation','A weak acid requires Ka, an equilibrium unknown, and a justified approximation or quadratic solution. Do not set hydronium equal to formal concentration automatically.','What distinguishes a weak-acid calculation?',['Include Ka and an equilibrium unknown','Ignore acid concentration','Set dissociation to 100%','Use pOH without finding OH−'],'a','strong-weak-acid-base-confusion'),
('Log interpretation','Because pH is logarithmic, pH 3 has ten times the hydronium concentration of pH 4 and one hundred times that of pH 5.','Compared with pH 5, how much more hydronium is at pH 3?',['2 times','10 times','100 times','1000 times'],'c','ph-scale-interpretation-error'),
('Verification and transfer','Check pH/pOH sums, units, logarithm decimal places, and whether hydronium exceeds hydroxide.','What follows from pH=9.20 at 25 °C?',['Acidic and [H3O+]>[OH−]','Basic and [OH−]>[H3O+]','Neutral and equal concentrations','Impossible because pH cannot exceed 7'],'b','ph-scale-interpretation-error')]),
'chemistry-titrations':('Acid–Base Titrations and Indicators','packet-chemistry-titrations-v1','chemistry-titrations-v1','titration-stoichiometry',[
('Titration vocabulary','A titration uses a standard solution to determine an unknown analyte. Equivalence is stoichiometric completion; endpoint is the observed indicator signal.','Which distinction is correct?',['They are identical by definition','Equivalence is stoichiometric; endpoint is observed','Endpoint is calculated from moles only','Equivalence depends on indicator color'],'b','titration-equivalence-endpoint-confusion'),
('Mole ratio','At equivalence, use balanced coefficients. Titrant and analyte moles are not necessarily equal for polyprotic acids or bases.','For H2SO4 + 2NaOH at equivalence, moles NaOH are',['half the H2SO4 moles','equal to H2SO4 moles','twice the H2SO4 moles','four times the H2SO4 moles'],'c','stoichiometry-ratio-error'),
('Unknown concentration','Map standard-solution moles through the balanced equation, then divide unknown moles by its volume. Keep aliquot and titrant volumes distinct.','25.0 mL HCl is neutralized by 18.0 mL of 0.100 M NaOH. What is MHCl?',['0.0180 M','0.0720 M','0.100 M','0.139 M'],'b','titration-volume-concentration-error'),
('Indicator transition','An indicator changes color over a pH range. Choose a range within the steep pH change near equivalence, not merely a familiar color.','Which indicator property matters most?',['Its range overlaps the steep equivalence region','It is always colorless','Its molarity equals analyte','It reacts stoichiometrically'],'a','indicator-range-selection-error'),
('Curve regions','Before equivalence, limiting reagent and conjugate pair determine the solution. At half-equivalence for weak acid/strong base, pH=pKa.','At half-equivalence for weak acid/strong base, which equality holds?',['pH=pKa','pH=7 always','[HA]=0','pOH=pKa'],'a','titration-region-misidentified'),
('Weak/strong distinction','A weak-acid/strong-base titration has a buffer region and an equivalence point above 7 because the conjugate base hydrolyzes water.','Why is that equivalence solution basic?',['The conjugate base hydrolyzes water','Strong base remains unreacted','Indicator creates OH−','The acid becomes strong'],'a','titration-equivalence-chemistry-error'),
('Testing and error','Reliable endpoints use calibrated indicators or probes, controlled addition near endpoint, correct meniscus reading, and concordant trials. Overshooting adds excess titrant.','Which error makes recorded titrant volume too large?',['Adding titrant past the first persistent endpoint color','Rinsing buret with titrant','Reading meniscus at eye level','Running a blank trial'],'a','titration-experimental-error')])}

def dump(v):
 class D(yaml.SafeDumper): pass
 def rep(d,x): return d.represent_scalar('tag:yaml.org,2002:str',x,style='|' if '\n' in x else ("'" if any(ch in x for ch in '\\\n') else None))
 D.add_representer(str,rep); return yaml.dump(v,Dumper=D,sort_keys=False,allow_unicode=True,width=120)

for topic,(title,packet,bpid,obj,secs) in common.items():
 oldpath=ROOT/'data/assessments'/(({'chem-acids':'chemistry-acids-bases-concept-lesson-s2c'}.get(topic,f'{topic}-concept-lesson-s2c'))+'.yaml')
 old=yaml.safe_load(oldpath.read_text())
 aid=old['id']; a={'schemaVersion':1,'id':aid,'title':title,'assessmentType':'conceptLesson','categoryId':'chemistry','topicId':topic,'modeDefault':'practice','randomizeQuestions':False,'navigation':{'learningGoal':'learn','activityType':'conceptLesson','tags':['chemistry','acid-base','s2c-reviewed']},'authoring':{'visualRequirement':'required','visualRationale':'Original diagram supports the proton-transfer, equilibrium, pH, or titration reasoning taught here.','difficultyTier':'unspecified','exceptionReason':None,'physicsModel':None,'sourcePacketId':packet,'blueprintId':bpid},'lesson':{'introduction':'This lesson builds an acid-base model from definitions through equations, calculations, and verification.','sections':[]},'exploration':None,'directedProject':None,'sandbox':None,'skills':['chemistry-acid-base','proton-transfer','equilibrium-calculation','solution-stoichiometry','pH-analysis'],'glossary':None,'questions':[],'workedExamples':[],'guidedProject':None,'items':[]}
 for i,(st,content,prompt,*rest) in enumerate(secs):
  choices=rest[0]; ans=rest[1]; sig=rest[2]; sid='sec-1' if i==0 else f'sec-{i+1}'; cid='chk-1' if i==0 else f'chk-{i+1}'
  q={'id':cid,'type':'multipleChoice','prompt':prompt,'choices':[{'id':chr(97+j),'text':x,'issueSignals':([] if chr(97+j)==ans else [{'id':sig,'domains':['chemistry']}])} for j,x in enumerate(choices)],'answer':{'choiceId':ans},'explanation':f'Solution: Choice {ans.upper()} follows from {st.lower()} and the stated species or numerical condition.\n\nWhy it works: Apply the governing acid-base definition or equation while preserving proton bookkeeping, stoichiometry, units, and assumptions.\n\nWhy the other choices fail: Each alternative makes a prompt-specific error such as reversing donor and acceptor roles, using the wrong coefficient, treating a weak species as fully dissociated, or misreading pH or endpoint evidence.','difficultyDimensions':['modelOrDerivation','errorDiagnosis'],'difficultyEvidence':f'{st}: apply the governing acid-base relation and check the result against the stated condition.','prerequisiteObjectiveIds':[],'extensionObjectiveIds':[]}
  a['lesson']['sections'].append({'id':sid,'title':st,'required':True,'content':content,'media':[{'type':'image','src':f'/media/chemistry/{topic}-model.svg','alt':f'Original diagram supporting {st.lower()}.'}],'check':q})
 text=dump(a); print('*** Begin Patch'); print(f'*** Delete File: {oldpath.as_posix()}'); print('*** End Patch'); print('*** Begin Patch'); print(f'*** Add File: {oldpath.as_posix()}'); print('\n'.join('+'+l for l in text.splitlines())); print('*** End Patch')
